### ISSUE TITLE
Please update Translation from Transifex

### ISSUE THREAD

**Issue by BuSHari** [Razzeee/script.trakt#102]
Hello,

I`ve just finished to translate the add-on to Hebrew language in Transifex,
Can you please update it?

Thanks,
Idan

**Comment by Razzeee** [comment]
I'm updating regularly. As far as I know the translations only update when the kodi team syncs so even if I update them now it's likely your translation is not there yet

**Comment by BuSHari** [comment]
ok thanks.

**Comment by anaconda** [comment]
Translations from Transifex shouldn't need any manual intervention from Team-Kodi.
However, I'm here to ask the same, but for Italian. Someone who clearly has no experience with translations has f*ed up the Italian translation (they evidently though the various "`%i`" were optional...):
```
File "/home/xbian/.kodi/addons/script.trakt/sync.py", line 170, in __addEpisodesToTraktCollection
    self.__updateProgress(int(y), line2=utilities.getString(1436) % ((i)*chunksize if (i)*chunksize < x else x, x))
TypeError: not all arguments converted during string formatting
```
I have just fixed it by (temporarily) removing the translated string (so it'll show up in English, but it'll work).

**Comment by Razzeee** [comment]
@anaconda 
I would wish they didn't need to manually do it..
http://kodi.wiki/view/Translation_System#Sync_time_schedule

**Comment by anaconda** [comment]
I think that only applies to the xbmc repo (https://github.com/xbmc/xbmc), but I have to admit that I don't know how add-on translations are handled.
I can get an up to date po file from here though: https://www.transifex.com/projects/p/xbmc-addons/resource/script-trakt/l/it/download/for_use/ - I'm using this until it's fixed here.

**Comment by Razzeee** [comment]
Yep, I could possibly get all by hand, but with up to ~87 supported languages it would take me quiet some time.
As I'm using this http://forum.kodi.tv/showthread.php?tid=149658 to download, I have to wait for the syncs by attila

**Comment by Razzeee** [comment]
@anaconda 
btw here are the logs from the last sync 
https://github.com/xbmc/translations/blob/master/translations/xbmc-addons/txupdate-syntax.log#L365
