### ISSUE TITLE
Script failed: trakt!

### ISSUE THREAD

**Issue by gcleaves** [Razzeee/script.trakt#120]
I just installed the dev version and get the script failed message appear in XBMC as soon as it starts.  I'm using XBMC 13.2 on OpenElec.

I don't understand install step 3 which says "Make sure you have six and requests installed. Check under Settings > Add-ons > Get Add-ons > All Add-ons > Add-on libraries (restart if you had to install these)".  I don't see "Add-on libraries" under All Add-ons.  I see Add-on repository but there is nothing that says "six" or "requests"  

Here is what the log shows:

23:35:04 T:2867102800  NOTICE: ## OpenELEC Addon ## 0.3.20
23:35:05 T:2900657232  NOTICE: -->Python Interpreter Initialized<--
23:35:05 T:2892268624  NOTICE: RCB Service: Start
23:35:05 T:2892268624  NOTICE: RCB Service: launch RCB on startup =
23:35:05 T:2892268624  NOTICE: RCB Service: scrape games on startup = false
23:35:05 T:2892268624  NOTICE: RCB Service: Done
23:35:11 T:2909045840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named six
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/script.trakt/default.py", line 5, in <module>
                                                import kodilogging
                                              File "/storage/.xbmc/addons/script.trakt/kodilogging.py", line 19, in <module>
                                                from utilities import getSettingAsBool
                                              File "/storage/.xbmc/addons/script.trakt/utilities.py", line 11, in <module>
                                                from dateutil.tz import tzutc, tzlocal
                                              File "/storage/.xbmc/addons/script.trakt/dateutil/tz.py", line 16, in <module>
                                                from six import string_types, PY3
                                            ImportError: No module named six
                                            -->End of Python script error report<--
23:35:15 T:2858714192  NOTICE:  StorageServer Module loaded RUN
23:35:17 T:2858714192  NOTICE: StorageClient-2.5.4 Starting server
23:35:59 T:2850325584  NOTICE: Thread JobWorker start, auto delete: true
23:36:09 T:2774180944  NOTICE: Previous line repeats 2 times.
23:36:09 T:2774180944  NOTICE: Thread BackgroundLoader start, auto delete: false

Oh, I see that six is missing, going to try and find that now....

**Comment by Razzeee** [comment]
Check this https://github.com/Razzeee/script.trakt#installation

**Comment by gcleaves** [comment]
Adding module.six manually seems to have solved the problem.  Requests was already in my system.  I've scrobbled, now I will try syncing my entire library.  Oh, there is the notification that it has started!  Neet-o.  Amazing, it's already done.  Issue resolved!
