### ISSUE TITLE
Problem when using sync with italian language

### ISSUE THREAD

**Issue by tdragonite** [Razzeee/script.trakt#121]
Hi guys,
I've this issue during episode sync:

10:39:56 T:2802578464   DEBUG: [script.trakt] sync: [Episodes Sync] Episodes added: 2 Broke Girls [tvdb: 248741] - S04E01, S04E02, S04E03, S04E04
10:39:56 T:2802578464   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/home/osmc/.kodi/addons/script.trakt/service.py", line 281, in run
                                                sync.sync()
                                              File "/home/osmc/.kodi/addons/script.trakt/sync.py", line 792, in sync
                                                self.__syncEpisodes()
                                              File "/home/osmc/.kodi/addons/script.trakt/sync.py", line 459, in __syncEpisodes
                                                self.__addEpisodesToTraktCollection(kodiShowsCollected, traktShowsCollected)
                                              File "/home/osmc/.kodi/addons/script.trakt/sync.py", line 174, in __addEpisodesToTraktCollection
                                                self.__updateProgress(int(y), line2=utilities.getString(1436) % ((i)*chunksize if (i)*chunksize < x else x, x))
                                            TypeError: not all arguments converted during string formatting

Full debug log: http://pastebin.com/RJyDADAJ

**Comment by Razzeee** [comment]
Which language are you using?

**Comment by tdragonite** [comment]
On Kodi? Italian

**Comment by tdragonite** [comment]
Oh, ok! Switch back to english for now ;-)
Tnx Razzeee!

**Comment by Razzeee** [comment]
https://github.com/Razzeee/script.trakt/commit/fd485c0ca676e5270bf4e7264a8d88d9a13703e5

**Comment by tdragonite** [comment]
Still broken ;-)

**Comment by Razzeee** [comment]
The dev branch?

**Comment by tdragonite** [comment]
Ye, the string 1436 of the italian translation is still the same of the old version

**Comment by RavRob** [comment]
@tdrgonite
Just for safe measure, remove all traces of the previous addon on your STB then re-install the new Dev branch.  Don't just uninstall, physically remove all traces.  I've had to do that many times when @Razze was working on my issues.

**Comment by tdragonite** [comment]
Ye, but the problem is another here :-P the strings.po of the italian translation still have a broken string, like the previous one.

**Comment by Razzeee** [comment]
Sorry, it should have shown up here. https://github.com/xbmc/translations/blob/master/translations/xbmc-addons/txupdate-syntax.log seems like theres a bug in the kodi script. Will have them check that first.

**Comment by Razzeee** [comment]
@tdragonite 
please consider signing up for transiflex and doing the italian translation :)
check here for further instructions http://kodi.wiki/view/Translation_System

**Comment by tdragonite** [comment]
Ye, I'm signed in but I haven't understood how to subscribe to the Italian translation group :-\

**Comment by Razzeee** [comment]
:thumbsup:

**Comment by Jean85** [comment]
Same issue here, I was about to open an issue, and I stumbled on this one :D Didn't know that the language was the issue..

I'm already signed up on Transifex, and I've fixed it with:

    %i su %i serie TV hanno episodi che sono stati aggiunti alla collezione trakt

**Comment by Razzeee** [comment]
@Jean85 
can you please fix these too?

```
Addon: script.trakt, Lang: it, Warning: count missmatch of char "%"
msgctxt "#1436"
msgid "%i of %i show(s) have episodes added to trakt collection"
msgstr "Tag \"visto(i)\" della serie %i verrà aggionato su trakt"


Addon: script.trakt, Lang: it, Warning: count missmatch of char "%"
msgctxt "#1472"
msgid "Updating %i of %i movie playcount(s) in Kodi"
msgstr "Aggiornamento tag visto per il film(s) %i su Kodi"


Addon: script.trakt, Lang: it, Warning: count missmatch of char "%"
msgctxt "#1478"
msgid "Updating %i of %i movie playcount(s) on trakt"
msgstr "Aggiornamento tag visto per il film(s) %i su trakt"


Addon: script.trakt, Lang: it, Warning: count missmatch of char "%"
msgctxt "#1494"
msgid "Updating %i of %i episode playcount(s) in Kodi"
msgstr "Aggiornamento tag visto(i) per l'episodio %i su Kodi"
```

**Comment by anaconda** [comment]
All issues should be fixed now.
(I'm a bit unsatisfied by some strings, but I wanted to had these consistent with Kodi's translation.)

**Comment by Jean85** [comment]
Thanks @anaconda.. Now we just need to wait a merge on master ;)

**Comment by Razzeee** [comment]
Can somebody try with the newest? There is a new translation update, but I'm not really sure if that changed anything.

**Comment by anaconda** [comment]
No need to. Old messages are still there:
https://github.com/Razzeee/script.trakt/blob/dev/resources/language/Italian/strings.po#L296-L297

I think c4b34b6c4964675529f1cec7a8b56b0f0b8cbc5a has confused the sync script, as I can see these strings were also reverted on Transifex. I think the ID change has caused an inverse sync (from GitHub to Transifex) and only _after that_ a sync from Transifex to GitHub. I'm going through all messages again...

**Comment by Razzeee** [comment]
Thank you.
