### ISSUE TITLE
FYI: exception thrown in latest dev commit

### ISSUE THREAD

**Issue by mgonzales71** [Razzeee/script.trakt#122]
I was using the latest commit 8605abbd72 of script.trakt dev branch and had the following error

wanted to pass it along as an FYI 

thanks for all your hard work getting trakt v2 api's back into xbmc/kodi - much appreciated :)

05:04:45 T:6500   ERROR: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.NameError'>
Error Contents: name 'utilities' is not defined
Traceback (most recent call last):
File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.trakt\default.py", 
line 19, in <module>
message = utilities.createError(ex)
NameError: name 'utilities' is not defined
-->End of Python script error report<--

**Comment by Razzeee** [comment]
Sorry, I should not commit on the go. Should be fixed.

**Comment by mgonzales71** [comment]
awesome... thanks again for the great work

**Comment by Razzeee** [comment]
You're welcome! :)
