### ISSUE TITLE
Re-Rate with same value removes the Rate

### ISSUE THREAD

**Issue by bigmong** [Razzeee/script.trakt#129]
I have it enabled to re-rate things (like i'm re-watching a show)

I have spotted that if i re-rate a show with the same rating as it already had it will then have no rating on trakt, so it unrates the ep.

The notification from Kodi says it has been rated.

**Comment by s7eele** [comment]
i believe this is normal behavior and there may be a little misunderstanding, in the previous version of the add-on the allow re-rating setting was actually related to the context menu iirc, it allowed you to rate an already rated item via the context menu, it did not apply to the rating dialogue seen at the end of playback afaik, this rating dialogue will appear everytime at the end of playback regardless of the allow re-rating setting, the rating dialogue indicates that you are unrating a movie if you select its current rating

the context menu is disabled atm to focus on basic functionality as i understand it, im going to double check but i think this is correct

**Comment by Razzeee** [comment]
It is shown in the dialog that you will unrate and it even shows "trakt - Episode unrated" in the notification. Just tested it again, seems to work nicely.
You should just back out of the dialog if you want to use the same rating.

**Comment by bigmong** [comment]
Yeah my bad, I just looked at it closely and your right, i only every look at the stars not too much the text.
tonight i did read the text and it says unrate for the same star
