### ISSUE TITLE
trakt syncs exclusions

### ISSUE THREAD

**Issue by jenn9376** [Razzeee/script.trakt#13]
The trakt script syncs the entire kodi collection to trakt, skipping the path exclusions set in the settings:

![image](https://cloud.githubusercontent.com/assets/10712768/5905302/039eae36-a598-11e4-80d4-0edb9d623899.png)

After I ran the script it synced all of my anime even though I had it excluded. Note that there is a # in the folder name, maybe it matters.

**Comment by Razzeee** [comment]
@jenn9376 
can you try it again with the newest version? (I might be wrong)
but as of https://github.com/Razzeee/script.trakt/commit/455376bd63b50bb01f0697aea4642f37994d06c3 shows should also use the exclude paths when syncing

**Comment by jenn9376** [comment]
Thanks for the quick response!

Checking the log, it does take the exclusions into account but it hangs after a while (at around 10%):

23:05:37 T:1696  NOTICE: [trakt] checkExclusion(): Checking exclusion settings for 'I:\Backstrom\season 01\Backstrom - 101 - Dragon Slayer.mp4'.
23:05:37 T:1696  NOTICE: [trakt] [Episodes Sync] Getting episode collection from trakt.tv
23:05:38 T:1696   ERROR: WARNING:trakt.core.http:Continue retry since status is 520

23:05:43 T:1696   ERROR: WARNING:trakt.core.http:Retry # 1
23:06:43 T:1696   ERROR: WARNING:trakt.core.http:Continue retry since status is 504
23:06:48 T:1696   ERROR: WARNING:trakt.core.http:Retry # 2
23:07:48 T:1696   ERROR: WARNING:trakt.core.http:Continue retry since status is 504
23:07:53 T:1696   ERROR: WARNING:trakt.core.http:Retry # 3
23:08:53 T:1696   ERROR: WARNING:trakt.core.http:Continue retry since status is 504
23:08:58 T:1696   ERROR: WARNING:trakt.core.http:Retry # 4
23:09:58 T:1696   ERROR: WARNING:trakt.core.http:Continue retry since status is 504

23:10:03 T:1696   ERROR: WARNING:trakt.interfaces.base:request failed: Gateway Timeout - "server timeout" (code: 504)

**Comment by jenn9376** [comment]
Ah, never mind, after a bit it finished reading the collection from trakt website and it removed some episodes. Then I got this error:

23:10:54 T:1696   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\Eugenia\AppData\Roaming\Kodi\addons\script.trakt-dev\service.py", line 273, in run
                                                sync.sync()
                                              File "C:\Users\Eugenia\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 643, in sync
                                                self.__syncEpisodes()
                                              File "C:\Users\Eugenia\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 399, in __syncEpisodes
                                                traktShowsUpdate = self.__compareShows(kodiShows, traktShows, watched=True)
                                              File "C:\Users\Eugenia\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 246, in __compareShows
                                                if self.__countEpisodes([show_col1]) > 0:
                                              File "C:\Users\Eugenia\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 134, in __countEpisodes
                                                if episodeKey['number']:
                                            TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Razzeee** [comment]
Should be fixed by the newest commit

**Comment by jenn9376** [comment]
Now I get these errors:

http://pastebin.com/rkaMyuZW

**Comment by Razzeee** [comment]
@jenn9376 
can you try with the latest version and let me know if its still there? Did some work an that yesterday.
And for some reason your log is weird. Are that multiple errors? When do they occure?

**Comment by jenn9376** [comment]
They are logs from 2 different versions (I downloaded the .zip from a specific commit page and then the -dev fork). On both occasions the error occurs like this:
- Plugin reads the database from trakt website
- It checks the kodi collection (including exclusions) and compares
- It finds episodes that exist in trakt collection but not on kodi collection
- It starts cleaning trakt collection then it hangs and I get the messages I sent in the logs

I will check with latest version when I get home later tonight.

Thanks for all your help!

**Comment by Razzeee** [comment]
@jenn9376 
your version has to be pretty old, I changed the order so that cleanup is done first, some days ago.

**Comment by jenn9376** [comment]
I did a clean install of the plugin, this time it cleaned the collection first then I get this error:

http://pastebin.com/ZWazyywS

**Comment by Razzeee** [comment]
@jenn9376 
yes, thats an error that was fixed some minutes ago, check the newest version

**Comment by jenn9376** [comment]
I get the same error:

http://pastebin.com/qDtHM95u

**Comment by Razzeee** [comment]
Update and retry please. Might have been the problem if not, I will need more logging to adress this.

**Comment by jenn9376** [comment]
Unfortunately I get the same error. You can close this issue since the initial problem has been fixed. Besides, there are many open issues concerning syncing errors. Thank you so much for your work so far!
