### ISSUE TITLE
Multipart files handling

### ISSUE THREAD

**Issue by FluffMe** [razzeee/script.trakt#132]
Hi guys,

XBMC has stacking of multi-part files.

Current version of trakt plugin handles it almost as it should.
The only problem is - rate dialogue pops up each time the part ends starting from part 2 or 3, depending on your rate percentage option. I'm not sure but I think the same happens with scrobble - it's scrobbled each time file ends if stacked length is more then percent value in options. Gonna test that now.

More info on stacking: http://wiki.xbmc.org/index.php?title=File_stacking

**Comment by razzeee** [comment]
It's scrobbling at the calculated end of the episode now. And it will only show one rating dialog at the end of the last episode, which will be pretty hard to fix.

**Comment by razzeee** [comment]
The dev version is showing multiple rating dialogs  now for multipart files!
