### ISSUE TITLE
Sync duplicating watched?

### ISSUE THREAD

**Issue by tknorris** [Razzeee/script.trakt#134]
I don't have any logs for it, but I'm pretty sure that the current build is occasionally duplicating my watch history for movies. I just checked my watched history and I think almost every movie I've watched was marked watched again today @ 6PM

**Comment by tknorris** [comment]
IT also seems to have happened 2/24@11PM

**Comment by tknorris** [comment]
It seems like it's happening at, or shortly after, each time a new update is pushed from my repo...

**Comment by Razzeee** [comment]
@tknorris am I reading this right? It happend before I merged the playlist sync?

**Comment by Razzeee** [comment]
And how do you know the time it happened?

**Comment by Razzeee** [comment]
So how could this be related to new updates in your repo? I can't replicate it with the local version. We're talking about movies only? What else have you checked for movies?

**Comment by Razzeee** [comment]
@tknorris 
I just installed your repo and installed the beta from there. Did multiple syncs without getting a problem.
Can you bump the version, so that I get an update?

**Comment by tknorris** [comment]
I can tell the time it happened because all the watch history had the same times: 2/25 6:17 PM EST and 2/24 11:00 PM EST. I do think it happened before the merge of playlist sync.

I can't think of an obvious way that a zip update can trigger this. The only thing I can think of is if you are serializing some information to use as a local cache of watch history and that cache is getting removed during a zip update.

To force an update yourself, you could install my beta repo and then manually install one of the older betas from here: https://github.com/tknorris/tknorris-beta-repo/tree/master/zips/script.trakt. That should trigger the repo to update you.

**Comment by tknorris** [comment]
I took a glance at the userdata/script.trakt and I notice you are putting a queue.db in there. It might not be related, but I normally put files like that in special://database. I don't think that's related, but it might be.

**Comment by Razzeee** [comment]
@tknorris 
that queue is still from the "old" addon pretty much untouched.
Whats curious is that we send the watched times from kodi. In normal cases, so it should never be the time when the sync is running. It has to think trakt doesn't have these yet, and don't have a local watched at time...

**Comment by tknorris** [comment]
Hmm, that is odd. I cant explain it other than to say that it definitely happened because it took me nearly an hour last night to delete 20 pages of plays in my movie history. It was only movies thankfully. It also was very accurate in that it was just a pure duplications of my movie watched history.

**Comment by Razzeee** [comment]
@tknorris 
anything special about your setup? using mysql for e.g.?

**Comment by tknorris** [comment]
No, nothing particularly special. I have 4 machines running XBMC: My main htpc (Linux), an FTV running Android+Kodi, an rpi running OpenElec, and my dev machine (Linux).

I double checked my dev machine and none of those movies are marked watched on my dev machine because I always run the trakt addon in debug mode on my dev machine to avoid getting erronous scrobbled & watched history on trakt.

I also run plex on the main htpc w/ the trakt plugin installed to sync watched history, so it's technically possible the problem could have come from there, but I don't think it did because it's been running for about 2 weeks w/o a problem. I also went through it's logs and didn't see anything odd.

The only thing that I noticed that is odd is it seems like both times the problem happened w/i a couple hours of me pushing a new beta...I can't explain that though...

**Comment by Razzeee** [comment]
@tknorris 
Debug mode?
I removed the simulated scrobble etc for the time beeing.

**Comment by Razzeee** [comment]
Just installed beta1 did a few syncs, upgraded via repo to beta4. Did more syncs, no duplicates for me :(

**Comment by tknorris** [comment]
Hmm, I don't have a better explanation for you unfortuantely. I guess lets just leave this open for now and if it happens again I'll try to get some better info.

**Comment by tknorris** [comment]
So, I just checked the FTV and the OpenElec box and both were still running the old trakt addon to beta4 and so far no sync issues. I'll keep my fingers crossed.

**Comment by tknorris** [comment]
So, I updated to beta5, and then forced a sync from XBMC two or three times and haven't been able to reproduce this. Maybe all the more recent code changes made it go away.

I also made sure I was on the latest plex trakt channel and forced syncs from it. I can't reproduce it there either.

I'll close this and re-open it if it happens again.
