### ISSUE TITLE
Rating broken due to incorrect default skin directory

### ISSUE THREAD

**Issue by anaconda** [Razzeee/script.trakt#152]
After watching something, if rating is enabled:
```
04:04:31 123280.617188 T:1810887744   ERROR: GetDirectory - Error getting /home/xbian/.kodi/addons/script.trakt/resources/skins/Default
04:04:31 123280.617188 T:1810887744   ERROR: EXCEPTION: XML File for Window is missing
04:04:31 123280.617188 T:1810887744   FATAL: [script.trakt] service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'RuntimeError'>
                                            Error Contents: ('XML File for Window is missing',)
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/script.trakt/service.py", line 39, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/home/xbian/.kodi/addons/script.trakt/scrobbler.py", line 220, in playbackEnded
                                                ratingCheck(self.curVideo['type'], self.curVideoInfo, self.watchedTime, self.videoDuration, self.playlistLength)
                                              File "/home/xbian/.kodi/addons/script.trakt/rating.py", line 27, in ratingCheck
                                                rateMedia(media_type, summary_info)
                                              File "/home/xbian/.kodi/addons/script.trakt/rating.py", line 89, in rateMedia
                                                rerate=rerate
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--
```

So, it tries to load the rating window from `resources/skins/Default`, but we have `resources/skins/default`.
On case-sensitive filesystems `Default` and `default` are 2 different directories.
Seems broken since https://github.com/Razzeee/script.trakt/commit/e10a10e25ca9e97cb855093bb4118c54efd2be68

**Comment by Razzeee** [comment]
Yes, this is probably a repo problem. You'll have to deinstall it and reinstall it. Your preferences should be persisted.

**Comment by anaconda** [comment]
I have never installed this add-on from a repository.

The problem is indeed a case-sensitive filesystem.
The default value for the skin is `Default`:
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/WindowXML.h#L49
but that directory was renamed to `default` in e10a10e25ca9e97cb855093bb4118c54efd2be68.
You need to pass `defaultSkin='default'` in https://github.com/Razzeee/script.trakt/blob/master/rating.py#L84 or revert the directory renaming.

**Comment by Razzeee** [comment]
Well, funny. On my rpi2 a reinstall fixed it, had the same problem yesterday.
And if I understand the code correctly the part your refering to is reflected in our case: https://github.com/Razzeee/script.trakt/blob/master/rating.py#L86

**Comment by Razzeee** [comment]
Well the documentation at http://kodi.wiki/view/Add-on_Standards fooled me into thinking this should be lowercase. I'll revert that.

**Comment by anaconda** [comment]
Is it more clear now? I have added a note for this "Default" directory.

**Comment by Razzeee** [comment]
Yes, should prevent anyone from making the same mistake
