### ISSUE TITLE
unmet dependencies error

### ISSUE THREAD

**Issue by butcha** [Razzeee/script.trakt#155]
After the latest commits you made I get an "unmet dependencies" error when i try to install the add-on..
Same goes if I try to install the new module.trakt thing you made (I figured I might need to install that first).

**Comment by butcha** [comment]
Nevermind, I'm not sure what went wrong but after a reboot of the system if installed fine.
Sorry about that.

**Comment by Razzeee** [comment]
To install the trakt module you need the other two new modules. What probably happend is they showed up for you in the official kodi repo and were installed from there.
