### ISSUE TITLE
No autofocus on rating

### ISSUE THREAD

**Issue by Sup3rLativ3** [Razzeee/script.trakt#156]
When the prompt appears after a show it doesn't autofocus on the rating outsell which means I either need to back out and not give a rating (left and right buttons don't work) our use a muse to submit my score.

**Comment by Sup3rLativ3** [comment]
After removing the entire plugin and associated folders restarting then installing the new one and restarting it seems to have solved it.

**Comment by Sup3rLativ3** [comment]
After removing the entire plugin and associated I had uninstalled and reinstalled previously but that hasn't helped

folders restarting then installing the new one and restarting it seems to have solved it.

**Comment by s7eele** [comment]
what platform, ver, skin?
