### ISSUE TITLE
Rating popup not working

### ISSUE THREAD

**Issue by Svashta** [Razzeee/script.trakt#159]
Hi,

this weekend i got new trakt rating popup in kodi, which is nice and dandy, but can't actually do anything with it. Pressing left/right, doesn't actually do anything. All i can do is press back to close it.
I am using remote, no mouse.

I just on a side-note, rating doesn't actually show on trakt website since it was upgraded to new website version.

**Comment by Razzeee** [comment]
Most likely a problem with your upgrade try this:

Remove trakt, probably also the modules trakt,dateutil, six, requests and arrow (under librarys)
Exit Kodi. 
Remove addon_data folder from %APPDATA%/kodi/userdata/
Remove script.module.dateutil ,script.module.arrow, script.module.request, script.module.six, script.trakt and script.module.requests folders from %APPDATA%/kodi/addons/
Reboot kodi and wait for a moment (like 30sec) so it clean database and rebuild cache. (not really sure if this applys)
Force refresh the Kodi repo.
Install Trakt 3.0.0
It should have installed six and request and the others automatically. 
Configure trakt add-on and reboot kodi.

**Comment by Razzeee** [comment]
Had a user confirm it's fixed by deleting the settings.xml as stated in the faq at: http://forum.kodi.tv/showthread.php?tid=220547
