### ISSUE TITLE
Addon wont start: No module named parser

### ISSUE THREAD

**Issue by pschonmann** [Razzeee/script.trakt#160]
Hello, ive updated from git now from some version. But ive got error. I installed trakt.py and dateutils from repo as described in install. But still getting these lines in output log

23:37:04 T:6048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named parser
                                            Traceback (most recent call last):
                                              File "C:\Users\zzz\AppData\Roaming\Kodi\addons\script.trakt\script.py", line 2, in <module>
                                                import utilities as utils
                                              File "C:\Users\zzz\AppData\Roaming\Kodi\addons\script.trakt\utilities.py", line 11, in <module>
                                                import dateutil.parser
                                            ImportError: No module named parser
                                            -->End of Python script error report<--

**Comment by s7eele** [comment]
refer to issue 159, procedures outlined should correct

**Comment by Razzeee** [comment]
Parser is a part of dateutils so you might want to check after that. 

We also recommend the kodi repo version over the git version. Much simpler and nothing that can go wrong. If it does, check s7eeles link
