### ISSUE TITLE
scrobbling broken in beta4?

### ISSUE THREAD

**Issue by tknorris** [Razzeee/script.trakt#173]
My main htpc just updated to beta4 and it doesn't seem like anything is scrobbling....

**Comment by tknorris** [comment]
nevermind, issue cleared up on it's own after 2 xbmc restarts..weird...

**Comment by Razzeee** [comment]
Well that's not sounding great.

**Comment by tknorris** [comment]
It seems to be working now. I'm not sure what the problem was at first. I restarted XBMC after upgrading and the sync was running after each library update but nothing would scrobble.

**Comment by Razzeee** [comment]
Well sync and scrobble are two different things for me

**Comment by tknorris** [comment]
Yep, agreed, but they both run off the service was my point.

**Comment by tknorris** [comment]
Hmm, I'm still getting unreliable scrobbling since updating to beta4. I can't find anything particularly interesting in the log about it. I'll try to rollback to beta3 and see if things get better.

**Comment by tknorris** [comment]
Another thing I noticed (maybe related) is scrobbling doesn't seem to pause when I pause the video.

**Comment by Razzeee** [comment]
Hrm, that should have been fixed with this commit https://github.com/Razzeee/script.trakt/commit/07e9beaa3ccba6beb732fa7614a7482b39d9d6ca

**Comment by Razzeee** [comment]
So any news?

**Comment by tknorris** [comment]
I haven't rolled back yet. I'll get a better chance to test it tonight. I'll add some comments here if I find anything. The problem is it's so random it's hard to get a good debug log for it.

**Comment by tknorris** [comment]
So, i'm not positive yet, but I think the problem crops up every time I pause a stream. When I resume the stream, it seems like the scrobbling stops. Then as soon as the video stops playing, the stop is scrobbled to trakt. If I don't pause, then it seems like the show continues to show up as scrobbling until the very end (as it should). Can you try playing back something from SALTS and see if you can reproduce the issue w/ beta4?

**Comment by tknorris** [comment]
I just tested it and that's exactly what's happening. I start playback of a stream, it scrobbles but as soon as I pause it, the scrobbling stops and doesn't restart when I resume the stream.

**Comment by Razzeee** [comment]
Well, still on the road but I think it just clicked. The resume after pause may only work for multi part items

**Comment by Razzeee** [comment]
Should be fixed now. Let's hope I didn't break anything new :D
We might want to try some streaming movies/shows/multipart shows (freakazoid, invader zim, etc)

**Comment by tknorris** [comment]
Should I pull it into a new beta build?

**Comment by Razzeee** [comment]
Yes, go ahead. I will implement PIN auth soon, but not sure if I want it to ship with this release.

**Comment by tknorris** [comment]
Yeah, I don't know about you but adding PIN auth to SALTS is going to be quite a bit of work. I have to completely rework the token logic. I'll pull this into a beta right now.

**Comment by Razzeee** [comment]
It will be quiet simple for me. (due to fuzemans api wrapper) The only big thing is changing the settings, so the users will understand. I hoped to add a qr code to the settings, but it seems like that won't be possible.
Might have the same problem with a "long" description text.

**Comment by tknorris** [comment]
I was thinking about that QR code thing, and I think the easiest thing to do would be to create a window xml that has both the url and the qr code in it. The QR code would just be packaged with the addon since it's not available as a url from trakt. I'm not sure yet though as I haven't actually tried to make it work.

**Comment by tknorris** [comment]
Also, I just pushed beta5. I'll test it later tonight to let you know if the problem is resolved.

**Comment by tknorris** [comment]
You know if you wanted the QR code to show up in addon settings, you could do the window xml I was talking about and add an "action" item to the settings.xml that popped up the window: http://kodi.wiki/view/Add-on_settings#type_.3D_.22action.22

**Comment by Razzeee** [comment]
Yeah, I know, but that would mean I have to add a new window and I really hate frontends :D
I think I will hit Piers with this then.

**Comment by tknorris** [comment]
Hmm, I'm not sure things are still working correctly. The experience I just had was the movie I'm watching wasn't being scrobbled, and then when I paused & resumed, it suddenly started being scrobbled...

**Comment by tknorris** [comment]
Also, it doesn't seem like the scrobbling stops anymore when a video ends.

**Comment by Razzeee** [comment]
Your refereing to streams or local media?

**Comment by tknorris** [comment]
In the two most recent instances it was local media.

**Comment by Razzeee** [comment]
Yeah, seems like there was an start event storm :X

**Comment by tknorris** [comment]
Let me know when you want to do another beta.

**Comment by Razzeee** [comment]
Well I think we're ready. Piers might improve the new dialogues soon, but that shouldn't break functionality or keep us from testing.

**Comment by s7eele** [comment]
ive been watching this closely because i recognized some of it but i just noticed the above comment from @tknorris about scrobbling not stopping when playback stops, had to mention that it has been like this since i was testing the playlist-sync branch, at least, do you remember that discussion @Razzeee (it did sound odd at the time, something about them having to poll), im sure i can find it if its of any use, otherwise this is just fyi, as always appreciate your continued work

**Comment by Razzeee** [comment]
Please also update the mofule

**Comment by tknorris** [comment]
Are you sure you want to push the PIN Auth change into beta already? As far as I know PIN auth is only available on the trakt staging server right now. Anyone using the beta on their main systems will be broken...

**Comment by tknorris** [comment]
done. 3.0.1~beta6 and 2.3.0 of the module pushed.

**Comment by tknorris** [comment]
Hmm, I couldn't get beta6 to work properly at all. Ratings didn't work and scrobbling didn't work. I think the PIN auth was not working properly. I'm going to roll my main HTPC back to beta4 for now.

**Comment by Razzeee** [comment]
Any logs? My dev widows installation is having zero problems

**Comment by tknorris** [comment]
I'll give it another try and produce some debug logs later today.

**Comment by s7eele** [comment]
@Razzeee not sure if you saw my comment above about scrobbling problems, specifically what @tknorris mentioned wrt scrobbling not ending when playback stopped, if you look through the last few comments of closed issue #93 you will see all the details, at that time your response was:

<Just a quick FYI. 
<The website can't detect that the playback is over, without you refreshing it. 
<It would be technically possible for the trakt guys to detect it, but it would be quite a waste.
<
<So be sure to refresh the page after playback stops.

it didnt make sense to me at the time but neither did a lot of other things so i didnt bother you with it further, now im wondering if it is still accurate and whether it has anything to do with the comment tk left regarding scrobbling not stopping at playback end, appreciate any response

ive been following closely but decided i would keep quiet and allow you to focus on development, just want to say that as always im available to help where possible, just ask

**Comment by s7eele** [comment]
different issue than above so entering a new comment vs editing the message above, ive just installed beta 6 and as mentioned above (and on forum) it doesnt appear to be scrobbling, running helix 14.2 on android, i havent done any real testing yet but after doing so and if behavior continues i will open issue and post logs, if nobody has done so yet of course

**Comment by Razzeee** [comment]
Have you setup your pin?

**Comment by s7eele** [comment]
yes sir, im dealing with some medical issues but im hoping to test more thoroughly and capture logs shortly, i havent checked yet but if no issue has been opened do you want one created yet?

**Comment by Razzeee** [comment]
Absolutely or just post it here

**Comment by tknorris** [comment]
I can't seem to get beta6 to log anything meaningful. I'm not sure why yet. It's certainly not working though.

**Comment by tknorris** [comment]
OK, so the problem is a logic error in traktapi.py's init function.
Changing line 24 to this seems to fix it:
```
        self.authorization = getSetting('authorization')
```

I'm not sure what your original intent was though?

One other thing, I think it's weird to make the PIN value be hidden in the settings dialog. The PIN is a temporary thing so someone seeing it is no big deal. It makes entering it harder.

**Comment by tknorris** [comment]
Hmm, I see now that you are holding the whole json response in the authorization setting and using eval to interpret it? That seems really scary to me to run eval on strings stored in files...Wouldn't it be better to do a json.reads() on it?

**Comment by Razzeee** [comment]
Well eval was the first thing I found to create an object out of a string. Still learning python, so yeah it's probably scary.(but for me everything holding data in a file is)

About the pin, yeah I feel the same. I wasn't sure about it and just thought, let's see if we keep it this way.

**Comment by tknorris** [comment]
I just did a commit to change both; feel free to roll back the settings.xml change though. PR incoming.

**Comment by tknorris** [comment]
I'll do a beta build as soon as you are ready to get the beta working again.

**Comment by s7eele** [comment]
cool, i wasnt able to do it as quickly as i thought, like the pin change too, good catch, thx as always

**Comment by Razzeee** [comment]
@s7eele click the minutes on that post. that will give you a link you can use to refere to this post. This will also work on twitter and facebook ;)

about that error, I haven't seen it and don't think it is happening. Only case would be massive timeouts on the end of trakt when we send the stop scrobble.

**Comment by Razzeee** [comment]
Btw a basic feedback about the health of the new beta would be great. I would like to push it to the master branch so we can get some new translations and possibly go live.

**Comment by tknorris** [comment]
I will test it tonight for both the PIN auth and scrobbling.

**Comment by s7eele** [comment]
roger that, i know you mean overall feedback but just want to mention that wrt problems with beta 6, everything seems to be working again on android with beta 7

**Comment by tknorris** [comment]
PIN auth works in beta7, scrobbling and manual rating tested to work as well.

**Comment by tknorris** [comment]
Some of the edge cases that were causing problems in beta5 seem to be resolved as well. Pause/resume seems to work again properly.

**Comment by s7eele** [comment]
might be good to let it run for another two or three days just to make sure nothing pops up as a result of all the recent changes but im in agreement with @tknorris, it seems ready for release to me, you mentioned skinning changes being made by @VonH (Piers) somewhere a short while back, do you plan to include them in this next release

definitely not rushing or being pushy or anything, just curious @Razzeee

p.s. - PIN working fine for me as well, had to obtain and enter a new PIN after upgrade to beta 7 but obviously thats not an issue, just mentioning it
