### ISSUE TITLE
Startup exception

### ISSUE THREAD

**Issue by jgerhold** [Razzeee/script.trakt#179]
Starting up on 14.2 I get the following exception:

> 20:59:32 T:4893184000   FATAL: [script.trakt] __main__: EXCEPTION Thrown (PythonToCppException) : -->Python callback/> script returned the following error<--
>  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
> Error Type: <type 'AttributeError'>
> Error Contents: ("'TraktClient' object has no attribute 'on'",)
> Traceback (most recent call last):
>   File "/Users/tv/Library/Application Support/Kodi/addons/script.trakt/default.py", line 18, in <module>
>     traktService().run()
>   File "/Users/tv/Library/Application Support/Kodi/addons/script.trakt/service.py", line 94, in run
>     globals.traktapi = traktAPI()
>   File "/Users/tv/Library/Application Support/Kodi/addons/script.trakt/traktapi.py", line 36, in __init__
>     Trakt.on('oauth.token_refreshed', self.on_token_refreshed)
>   File "/Users/tv/Library/Application Support/Kodi/addons/script.trakt/trakt/__init__.py", line 24, in __getattr__
> AttributeError: 'TraktClient' object has no attribute 'on'
> -->End of Python script error report<--

Tried updating script.modules.trakt to the newest version (mine was still 2.1.1~beta), but no luck.

**Comment by Razzeee** [comment]
No luck updating? Or fixing it with that?

**Comment by jgerhold** [comment]
No luck fixing it with that – still the same exception.

**Comment by Razzeee** [comment]
So your on module 2.2.0 now?
What system are you using, anything special?

**Comment by jgerhold** [comment]
I had time to take a closer look.. It seemd to me that there were some directories (arrow, dateutil, trakt, tzlocal) with old .pyo laying around.. So I just deleted the whole plugin dir and did a fresh clone of the repo and it works now. :)
