### ISSUE TITLE
doesnt work if kodi uses proxy to access internet.

### ISSUE THREAD

**Issue by papampi** [Razzeee/script.trakt#181]
first of all thanks a lot for your awesome job on this script.
Trakt 3 seems not to work with proxy, I had no issue in Trakt 2 and earlier versions.
my kodi needs to access internet via proxy 
here is the schema : 
router (ip 192.168.1.1) > RPi ( ip: 192.168.1.2) + raspbian + privoxy (bypass for 192.168.1.x & locals) > all devices ( http proxy : 192.168.1.2 : 8118 )

Trakt log : 
>15:09:20 T:140518723725056   FATAL: [script.trakt] traktapi: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ConnectionError'>
                                            Error Contents: (MaxRetryError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /auth/login (Caused by ProtocolError('Connection aborted.', error(101, 'Network is unreachable')))",),)
                                            Traceback (most recent call last):
                                              File "/home/payam/.kodi/addons/script.trakt/traktapi.py", line 63, in getToken
                                                auth = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "/home/payam/.kodi/addons/script.module.trakt/lib/trakt/interfaces/auth.py", line 10, in login
                                                'password': password
                                              File "/home/payam/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 89, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/home/payam/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 66, in request
                                                response = self.session.send(prepared, timeout=timeout)
                                              File "/home/payam/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 576, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/payam/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 424, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /auth/login (Caused by ProtocolError('Connection aborted.', error(101, 'Network is unreachable')))
                                            -->End of Python script error report<--
15:09:20 T:140518723725056   DEBUG: [script.trakt] traktapi: Cannot connect to server>

weird thing is I can see all the access logs from kodi in my RPi privoxy log, but there is none to/from trakt.tv
will try to run kodi under proxychains from my ubuntu desktop to see how it goes and will post results.

**Comment by Razzeee** [comment]
Hey, I have already prepared some code to get the settings from kodi and transform it into a string like this: http://docs.python-requests.org/en/latest/user/advanced/#proxies

But we need to wait for @fuzeman to get back to me on this: https://github.com/fuzeman/trakt.py/issues/22

Does your proxy url start with "http://" or "https://"?

**Comment by papampi** [comment]
@Razzeee , Thanks a lot for your fast actions...
mine is http://192.168.1.x:8118
but kodi accepts other proxies as well from settings menu

![image of kodi proxy setting] 
(http://kodi.wiki/images/c/c3/Settings.network.internet_access.png)

**Comment by Razzeee** [comment]
I just added this to the code base, as I can't test it here it's pretty much untested. The best you could do is install the tknorris beta repo and your version of trakt should update to the latest beta. You might have to wait a little for beta 9 to be out, but if you restart kodi then trakt should start using the proxy settings.

**Comment by papampi** [comment]
can you please let me know where to find tknorris beta repo ?

**Comment by Razzeee** [comment]
https://github.com/tknorris/tknorris-beta-repo

Just download the zip and install it to kodi

**Comment by papampi** [comment]
Thnx, 
downloading repo,
will install and post the results

**Comment by papampi** [comment]
nope, 
it still does not show up in my proxy log
and here is kodi log :  
>
23:01:13 T:140165338937088   DEBUG: [script.trakt] service: Service thread starting.
23:01:13 T:140165338937088   DEBUG: [script.trakt] service: [traktPlayer] Initalized.
23:01:13 T:140165338937088   DEBUG: [script.trakt] service: [traktMonitor] Initalized.
23:01:13 T:140165338937088   DEBUG: [script.trakt] traktapi: Initializing.
23:01:13 T:140165338937088   DEBUG: [script.trakt] requests.packages.urllib3.util.retry: Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
23:01:13 T:140165338937088   DEBUG: Previous line repeats 1 times.
23:01:13 T:140165338937088   DEBUG: [script.trakt] trakt.core.emitter: [trakt.client.TraktClient          ]:on(events: ['oauth.token_refreshed'], func: <bound method traktAPI.on_token_refreshed of <traktapi.traktAPI object at 0x7f7adc354390>>)
23:01:13 T:140165338937088   DEBUG: [script.trakt] traktapi: Exchanging pin for access token
23:01:13 T:140165338937088    INFO: [script.trakt] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): api-v2launch.trakt.tv
23:01:25 T:140165338937088   DEBUG: [script.trakt] requests.packages.urllib3.util.retry: Incremented Retry for (url='/oauth/token'): Retry(total=2, connect=None, read=None, redirect=None)
23:01:25 T:140165338937088 WARNING: [script.trakt] requests.packages.urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /oauth/token
23:01:25 T:140165338937088    INFO: [script.trakt] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (2): api-v2launch.trakt.tv
23:01:29 T:140166771328960   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/ImageLib-x86_64-linux.so)
23:01:29 T:140166771328960   DEBUG: Unloading: /ImageLib-x86_64-linux.so
23:01:29 T:140166771328960    INFO: LIRC Initialize: using: /dev/lircd
23:01:29 T:140166771328960   DEBUG: Failed to connect to LIRC. Retry in 40s.
23:01:33 T:140164697302784   DEBUG: Thread JobWorker 140164697302784 terminating (autodelete)
23:01:33 T:140165712439040   DEBUG: Thread JobWorker 140165712439040 terminating (autodelete)
23:01:33 T:140165376894720   DEBUG: Thread JobWorker 140165376894720 terminating (autodelete)
23:01:36 T:140166771328960    INFO: CheckIdle - Closing session to http://feeds.xbmc.org (easy=0x7f7aa8005b10, multi=0x7f7aa8001270)
23:01:37 T:140165338937088   DEBUG: [script.trakt] requests.packages.urllib3.util.retry: Incremented Retry for (url='/oauth/token'): Retry(total=1, connect=None, read=None, redirect=None)
23:01:37 T:140165338937088 WARNING: [script.trakt] requests.packages.urllib3.connectionpool: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /oauth/token
23:01:37 T:140165338937088    INFO: [script.trakt] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (3): api-v2launch.trakt.tv
23:01:50 T:140165338937088   DEBUG: [script.trakt] requests.packages.urllib3.util.retry: Incremented Retry for (url='/oauth/token'): Retry(total=0, connect=None, read=None, redirect=None)
23:01:50 T:140165338937088 WARNING: [script.trakt] requests.packages.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', error(101, 'Network is unreachable'))': /oauth/token
23:01:50 T:140165338937088    INFO: [script.trakt] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (4): api-v2launch.trakt.tv
23:02:02 T:140165338937088   FATAL: [script.trakt] traktapi: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ConnectionError'>
                                            Error Contents: (MaxRetryError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /oauth/token (Caused by ProtocolError('Connection aborted.', error(101, 'Network is unreachable')))",),)
                                            Traceback (most recent call last):
                                              File "/home/payam/.kodi/addons/script.trakt/traktapi.py", line 73, in authenticate
                                                self.authorization = Trakt['oauth'].token_exchange(self.__pin, 'urn:ietf:wg:oauth:2.0:oob')
                                              File "/home/payam/.kodi/addons/script.module.trakt/lib/trakt/interfaces/oauth.py", line 59, in token_exchange
                                                authenticated=False
                                              File "/home/payam/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 105, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/home/payam/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 81, in request
                                                response = self.session.send(prepared, timeout=timeout)
                                              File "/home/payam/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 576, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/payam/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 424, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /oauth/token (Caused by ProtocolError('Connection aborted.', error(101, 'Network is unreachable')))
                                            -->End of Python script error report<--
23:02:02 T:140165338937088   DEBUG: [script.trakt] traktapi: Cannot connect to server
23:02:02 T:140165338937088   DEBUG: POParser: loaded 144 strings from file /home/payam/.kodi/addons/script.trakt/resources/language/English/strings.po
>

**Comment by Razzeee** [comment]
@papampi can you try with the new beta?

**Comment by papampi** [comment]
sorry, just saw the new beta 10.
at work now, will test as soon as I get home.

**Comment by papampi** [comment]
sorry, just saw the new beta 10.
at work now, will test as soon as I get home.

**Comment by papampi** [comment]
sorry, just saw the new beta 10.
at work now, will test as soon as I get home.

**Comment by papampi** [comment]
seems like its working just fine.
awesome work ...
Thanks a lot

P.S:  is it ok that change version  9 to 10 beta asked me for new pin ?

**Comment by Razzeee** [comment]
@papampi 
that shouln't happen

@tknorris @s7eele
can you guys confirm this?

**Comment by papampi** [comment]
each device need its own pin or once obtained a pin it can be used in all kodi devices ?

**Comment by Razzeee** [comment]
@papampi 
I'm not sure. It's changing every 15 min or so. You might be able to enter the same on both devices if you don't wait to long.

maybe @rectifyer can clear this up

**Comment by tknorris** [comment]
I believe each request for the PIN page generates a new PIN, and then as soon a that PIN is exchanged for a token, it is no longer valid. In other words, each machine needs to be authorized with a new PIN.

**Comment by rectifyer** [comment]
That is correct, each would need its own PIN. They are 1 time use.

**Comment by s7eele** [comment]
sorry, a little late to the party but glad i made it, good information, i feel smarter already lol

@Razzeee wrt your request above for verification, i realize it may not be needed anymore but id like to make sure im understanding things properly, if i understand the request correctly you wanted to know if we were asked for a new pin on upgrade, my answer:

no, i was not asked for a new pin after update from 9 to 10, i have never been asked for a new pin after an update, i have used the same pin across multiple updates/versions

believe it or not my understanding of how it worked was the same as tknorris described and, if i'm reading the comments above correctly, has been verified by rectifyer, so as i understand it:

1. each pin can only be used by one machine since it expires as soon as it has been exchanged for a token (probably just one of many reasons)

2. you should not be prompted for a new pin when the add-on updates unless a problem is encountered (e.g. userdata folder no longer available)

i would appreciate a quick reply from anyone when they have a moment to let me know if i understand correctly or not, thx

**Comment by Razzeee** [comment]
Well I should stop copy pasting the generatedauth urls then :D
Thanks for clearing that up

@s7eele 
we'll you got the gist.

**Comment by papampi** [comment]
visiting http://trakt.tv/pin/999
each time any kodi asks for new pin gives a new one.

**Comment by Razzeee** [comment]
That's how it's supposed to be

**Comment by papampi** [comment]
Yup, its simple and effective

**Comment by Razzeee** [comment]
Not sure what your suggesting

**Comment by papampi** [comment]
when we click how to get the pin it gives the code and tells that we can also visit the http://trakt.tv/pin/999 
I myself didnt have the scanner and had to install it ... not that its hard to install a small app ... lol

**Comment by Razzeee** [comment]
That should be already standing there. Unless your translator screwed up, what language are you using?

**Comment by papampi** [comment]
English, 
it wasnt showed up in beta, 
didnt check the stable, just visited the page and entered the code.
