### ISSUE TITLE
Question on rating only working w/ library items

### ISSUE THREAD

**Issue by tknorris** [razzeee/script.trakt#183]
There is a comment in the wiki that says manual rating only works with library items. I was looking through this code to see if I could at least reuse the ratings dialog in my addon and I started to notice that there seemed to be quite a bit of code already in the rating code dedicated to working with non-library items. There were only a very few minor issues preventing it from working. In particular:

If line 217 of service.py is changed to:

```
if 'dbid' in data and (utilities.isMovie(media_type) or utilities.isShow(media_type)):
```

and Line 203 of service.py a minor typo is corrected to:

```
elif 'remoteid' in data:
```

and lastly if line 164 of rating.py is changed to:

```
if 'xbmc_id' in media and tagging.isTaggingEnabled() and tagging.isRatingsEnabled():
```

 then everything seems to work just fine for rating non-library items. I tested movies, tvshows and episodes and they all rated no problem. I would much prefer to re-use the script's ratings dialog than write my own that is essentially the same. Any chance of getting these changes made?

**Comment by razzeee** [comment]
@tknorris 
this should also be fixed with 3.0.0 am I right?

**Comment by tknorris** [comment]
I haven't walked through the code to check. If you want to run a quick test on it, you can remove False from this line: https://github.com/tknorris/salts/blob/master/default.py#L1194 and try a rating from SALTS

**Comment by razzeee** [comment]
@tknorris 
why would I have to do that? are you doing anything yourself there?

Thought it was solved by https://github.com/Razzeee/script.trakt/issues/59

**Comment by razzeee** [comment]
pretty sure this is working, despite the False in your code
@s7eele ?

**Comment by tknorris** [comment]
I don't think that issue would fix the problem. This issue was calling the manual rating function using the runscript() command that script.trakt exposed. For pre-3.0.0 versions it only worked for library items and the changes above were to fix that. 

Note the automatic popup on playback ending always worked even on non-library items in the old version.

**Comment by razzeee** [comment]
Ahhh, so your talking about the manual rating via context menu not the rating that comes up after a movie/episode?
Should have read this more carefully

**Comment by tknorris** [comment]
yep, exactly

**Comment by razzeee** [comment]
I'll have to readd these completely. Don't know when I can or how to test it.

**Comment by tknorris** [comment]
It's on my list to look at, I just haven't gotten around to it yet. I wanted your code to stabilize before I strated trying to fix it again.

Oh. "readd" I see you mean you've removed those manual functions completely?

**Comment by razzeee** [comment]
No, they remain broken for now. Not really sure if they can be called for now, but the old code is still there. Probably needs some work.

**Comment by tknorris** [comment]
Here's the page that defines the manual functions: https://github.com/trakt/script.trakt/wiki

**Comment by tknorris** [comment]
> No, they remain broken for now. Not really sure if they can be called for now, but the old code is still there. Probably needs some work.

Yep, that was my assumption as well. Do you know off hand if the manual call to sync still works? The SALTS service does a silent sync call when playback stops to force watched statuses to be updated because sometimes the scrobble doesn't complete before the directory is re-rendered.

**Comment by tknorris** [comment]
As far as how to test it, you could use the rating function in SALTS to test it. I've disabled using script.trakt for ratings until a released version worked with non-library items. You can re-enable that though by just removing that False from that line I linked to above.

**Comment by razzeee** [comment]
From memory I would think the manual sync call should still work, but someone should test it.

**Comment by s7eele** [comment]
been busy i see @razzeee, anything for me to do here? perhaps trying to remove default as @tknorris mentioned? ill check back when im free in a couple hours and look more into manual sync (certainly not suggesting i can do anything with it but wanna check it out anyway lol)

**Comment by razzeee** [comment]
There's probably nothing to do as long as nobody has a look on the manual executions.

**Comment by s7eele** [comment]
roger that, ill look at it more thoroughly just for fun then, 'fun', how terribly sad ;-)

**Comment by tknorris** [comment]
I haven't fixed it yet, but I walked through the code and at least most of the problems that I reported above still exist in the 3.0.0 code base. If I get time this weekend, I'll get manual ratings working and submit a PR against your repo, Razzeee.

**Comment by razzeee** [comment]
That sounds great, thank you

**Comment by tknorris** [comment]
I started looking at this tonight, and I have a branch in my fork that kind of works. I could use some help with some of the dependencies though. The main issue is that manual ratings depend on several trakt API calls that are not implemented in 3.0.0 TraktAPI class right now. I have marked each one here that is missing: https://github.com/tknorris/script.trakt/blob/man_rating/service.py#L151 (Line 151, 157, 160, and 164)

It would make my life alot easier if you could add those, Razzeee. I looked at adding them but that whole TraktAPI class is pretty complex and it was going to take me a while to figure out how it worked.

The other issue is getEpisodeRatingForUser only accepts a tvdb_id right now but manual rating only works off imdb_id. Would it be possible to optionally allow an imdb_id to getEpisodeRatingForUser? Without it, the code iwll need to make an additional call to get the show summary just to get the tvdb_id. (Also, the tvdb_id returned for the episode won't work since it's the episode id and not the tv show id).

**Comment by razzeee** [comment]
My head is killing me today. Will try to have a look tomorrow.

**Comment by razzeee** [comment]
I really think we could skip the summary calls, as we already have the data in Kodi. Not really sure why they were there in the old version. getEpisodeRatingForUser  shouldn't be a problem to implement also, I think I had this implemented somewhere along the line, but moved it over to use one identifyer and simplify the code :/

**Comment by tknorris** [comment]
We don't have the data in Kodi if the episode/show/movie isn't a library item.

And also, it's getShowRatingForUser that's missing, not getEpisodeRatingForUser. The problem with getEpisodeRatingForUser is that it requires a tvdb but the script call for rating uses imdb_id.

**Comment by razzeee** [comment]
Correct, but we're matching the plays from non library items by name and year / name, year, season, episode.
So we should be okay doing the same here?

**Comment by tknorris** [comment]
But at this point you don't have that, you have only what was passed in to the script which is imdbnumber, season, and episode. you need the summary calls to map the imdbnum to title/year.

Note: This logic is only for non-library items because the code passed the dbid into the rating call to get the data for library items.

**Comment by razzeee** [comment]
I think the imdb number is even better than the title and year, at least for movies.
It should also work pretty well for episodes, tvdb has most set and trakt should have merged the data from tmdb and tvdb for this field.
If we're talking about the series imdb number.

**Comment by tknorris** [comment]
Yes, the imdb number is what gets passed to trakt, but you need the title and year for the window that pops up.

**Comment by razzeee** [comment]
Forgot about that. Any chance we can add this to the call? It seems pretty wasteful to me, doing a whole api call for this information.
It should even make this a little faster.

**Comment by razzeee** [comment]
Btw your working on ratings only?
Shall I have a look at set manual watched?

**Comment by tknorris** [comment]
IMHO, calling the summary calls is a better design. Passing both will ultimately allow the title/year to potentially not match the imdbnumber. One thing that wasn't clear to me is in the rating window is the "title" for an episode supposed to be the episode title or the show title?

Oh, one other thing you MUST get the episode summary because you need the various episode ids in order for the rating trakt call to work. when you pass "episodes" to trakt's rating call it requires episode ids and not show ids.

If you are interesting in looking at watched go ahead. I don't mind looking at it once ratings are working.

**Comment by razzeee** [comment]
Yes, but this also mean there is something wrong with your local database/the data the stream is providing. I know it's bad when this happens, but why shouldn't we trust other addons and assume that they are wrong by wasting a call and check on them?

Probably won't have the time to look at it until the mid of the week.

**Comment by tknorris** [comment]
I think an argument can be made both ways, but what sways it for me is 1) the potential for the mismatch and 2) conforming to the existing API that the addon offered prior to 3.0.0. 

Also, see my update to my last post that it's mandatory for episodes because you need the episode id's not the show ids for the rating call to work.

**Comment by razzeee** [comment]
Well then we should probably open an issue here: https://github.com/fuzeman/trakt.py/issues

**Comment by tknorris** [comment]
OK, I'll open an issue w/ fuzeman and if he adds the API calls I can add them to traktapi.py. TBH, it was his module that I found so confusing.

**Comment by razzeee** [comment]
@tknorris 
use this for your episode/show/movie searches

```
def findMovieMatchInList(id, list, idType = 'imdb'):
    return next((item.to_dict() for key, item in list.items() if any(idType in key for key, value in item.keys if str(value) == str(id))), {})

def findShowMatchInList(id, list, idType):
    return next((item for key, item in list.items() if  any(idType in key for key, value in item.keys if str(value) == str(id))), {})

def findEpisodeMatchInList(id, seasonNumber, episodeNumber, list, idType = 'tvdb'):

    show = findShowMatchInList(id,list, idType)

    logger.debug("findEpisodeMatchInList %s" % show)
    if not show:
        return {}
    else:
        if not seasonNumber in show.seasons:
            return {}
        else:   
            season = show.seasons[seasonNumber]
            if not episodeNumber in season.episodes:
                return {}
            else:   
                episode = season.episodes[episodeNumber]
                return episode.to_dict()
```

might have to test them some more, when you've added them, as I'm not sure if the cast to str has any negative effects

**Comment by tknorris** [comment]
Those are to replace the utilities methods that getRatingsXX calls use right? I need to update traktapi.py as well right to pass in the id type?

**Comment by razzeee** [comment]
Yes,  but only for the manual calls, if handy. The defaults should handle the old cases.

**Comment by tknorris** [comment]
OK, so I'll add kwargs for idtype to those as well and default idType to imdb and tv to tbdb as you did above. I opened the issue w/ fuzeman on the summary calls but he hasn't commented back yet.

**Comment by razzeee** [comment]
And we might have to check if the show level already implements ratings. From memory I think it does, but better check first.

**Comment by tknorris** [comment]
I'm 95% certain it works because I tested w/ my hard coded show, movie and episode values and they all worked correctly.

**Comment by razzeee** [comment]
Yeah, I think fuzeman is more of a weekend contributer. Might take some time. 
I maybe have a go at it, but I 'm not sure if I already understand his code.

**Comment by tknorris** [comment]
Lol, better you than me. I KNOW I didn't understand it.

**Comment by razzeee** [comment]
I mean if trakt.py is already returning them

**Comment by tknorris** [comment]
As soon as your change is merged into fuzeman's repo, I'll finish this off.

**Comment by tknorris** [comment]
Razzee, I see you made some suggestions on alternate implementations of the GetRatingForUser methods. Should I wait until that question is resolved before adding those methods to script.module.trakt and traktapi.py?

**Comment by razzeee** [comment]
No, don't wait. It's just a optimization if you ask me, so it should not break any of your code. The old implementation should work fine.
If we decide to go for the suggestions, it should be painless.

**Comment by tknorris** [comment]
OK, I've got everything working except the episode ratings which needs fixes from fuzeman first. Razzeee, I tried to avoid changing any code outside of the manual ratings code to prevent breaking any other area of script.trakt. The only exception is on the findEpisodeMatchInList code you gave me. To make the code consistent, I switched findShowInList to return a dict, but that mean findEpisode is now walking the dictionary version of shows instead of objects. Take a look at the code and let me know if you don't like it: https://github.com/tknorris/script.trakt/blob/man_rating/utilities.py#L293

**Comment by tknorris** [comment]
On a side note, we might want to consider doing a pep8 cleanup on this code at some point. The tabs in the files were giving me fits because they should really be spaces.

**Comment by razzeee** [comment]
Well consistent wise I like that change. Not sure about the default parameter for shows, but thats probably a preference of mine. Maybe we shouldn't use the default values at all, doesn't really matter. 

Regarding pep8,yeah I just keept going the way it was when I took it over. I actually looked into an automatic cleanup but probably got sidetracked on the way.

**Comment by tknorris** [comment]
I can pull the default values if you want. I think I only included them because I thought you wanted the id lookups to default to tvdb.

I suggest once the code base is otherwise stable, I can do a commit that is jsut a pep8 clean up. I can do an auto-cleanup using pydev pretty easily.

**Comment by razzeee** [comment]
That would be great!

**Comment by razzeee** [comment]
So this can probably be closed with the new dev version comming along nicely?

**Comment by tknorris** [comment]
yep, I think this is resolved now.
