### ISSUE TITLE
Incorrect last play date when syncing

### ISSUE THREAD

**Issue by moiseslorono** [razzeee/script.trakt#185]
The last play date registered to trakt website when syncing tv shows watched previously on XBMC is the current date and time. For example, I watched a certain tv show last month on XBMC but when I synced it with trakt it doesn't display the date accurately on the trakt website.

Syncing movies and tv shows registers the wrong last play date on XBMC as well. Instead of having the last play date registered on trakt, XBMC displays the current date and time as the last play date.

**Comment by razzeee** [comment]
This is fixed with the comming version 3.0.0
