### ISSUE TITLE
Better PIN Window

### ISSUE THREAD

**Issue by tknorris** [Razzeee/script.trakt#186]
Are you interested in integrating the better PIN window that I added to SALTS? You can see what it looks like in this github issue: https://github.com/marcelveldt/xbmc.skin.titan/issues/57

The code is written to be (mostly) drop in.

**Comment by Razzeee** [comment]
Yeah, totally. Have already seen it posted somewhere.

**Comment by tknorris** [comment]
Great, I'll add the code in tomorrow when I get time. 95% of it should just drop in.

**Comment by tknorris** [comment]
PR #188 submitted for this

**Comment by Razzeee** [comment]
Let's go for a new beta!
