### ISSUE TITLE
Trakt not syncing

### ISSUE THREAD

**Issue by pedrojvaz** [razzeee/script.trakt#187]
Hello,
\I'm using RASPBMC with Gotham and for the past month that the plugin is unable to sync the movies, checkin (scrobble), or provide with the option to rate movies.

My log file is here http://pastebin.com/miYeJqxJ

Could you assist me?

Thanks

**Comment by razzeee** [comment]
This will probably be fixed with the new 3.0.0 version. If anything comes up just create a new ticket.
