### ISSUE TITLE
incorrect episode length time

### ISSUE THREAD

**Issue by klyonrad** [razzeee/script.trakt#191]
I just watched a 50 minute long episode. But after the scrobble action the time in my weekly charts jumped up 60 minutes

The check-in feature in trakt 1.whatever also had these incorrect timings which is why I never used it. Please bring back the old behaviour asap

**Comment by disrupted** [comment]
i believe it's because you watched the episode without commercial breaks while they are usually aired on TV with interruptions.

**Comment by razzeee** [comment]
Might be wrong data on tvdb / tmdb. Care to share what show you were watching?

**Comment by klyonrad** [comment]
doesn't matter what I watched, the episode length data is wrong in tvdb for **all** episodes, because it doesn't substract the commercial breaks. I know that.

My point is that before trakt 2.0 the scrobbler sent to trakt the correct episode length time and this correct time was seen on the trakt website.

**Comment by flabbamann** [comment]
The scrobbling is more like a check-in now, as the trakt update broke this funktion.
You have to wait for the script to be updated for trakt 2.0, for this to work again.

**Comment by razzeee** [comment]
This won't be fixable as this is no longer posible in the api.
