### ISSUE TITLE
remote sync with json api?

### ISSUE THREAD

**Issue by nopoz** [razzeee/script.trakt#192]
Any way to remotely run a sync? This is what I've tried without any success. 

`curl -v -H "Accept: application/json" -H "Content-type: application/json" -u user:password -d '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.trakt":"action=sync"},"id":1}' http://10.0.0.111:80/jsonrpc`

I get the output:

```
> POST /jsonrpc HTTP/1.1
> Authorization: Basic ****
> User-Agent: curl/7.33.0
> Host: 10.0.0.111
> Accept: application/json
> Content-type: application/json
> Content-Length: 105
>
< HTTP/1.1 200 OK
< Content-Length: 76
< Content-Type: application/json
< Date: Sat, 17 Jan 2015 06:45:18 GMT
<
{"error":{"code":-32700,"message":"Parse error."},"id":null,"jsonrpc":"2.0"}
```

**Comment by nopoz** [comment]
Think I got it working, but would like to add the silent parameter - any ideas?

works by just calling script:
`curl -v -H "Accept: application/json" -H "Content-type: application/json" -u user:password -d '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.trakt"},"id":1}' http://10.0.0.111:80/jsonrpc`

Trying to add the slient parameter:
`curl -v -H "Accept: application/json" -H "Content-type: application/json" -u user:password -d '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.trakt","params":{"silent":"true"}},"id":1}' http://10.0.0.111:80/jsonrpc`

get an ok response from the command:

```
> POST /jsonrpc HTTP/1.1
> Authorization: Basic ****
> User-Agent: curl/7.33.0
> Host: 10.0.0.111
> Accept: application/json
> Content-type: application/json
> Content-Length: 118
>
< HTTP/1.1 200 OK
< Content-Length: 38
< Content-Type: application/json
< Date: Sat, 17 Jan 2015 07:44:23 GMT
<
{"id":1,"jsonrpc":"2.0","result":"OK"}
```

doesn't work on xbmc though - getting an error:

```
23:44:23 T:1476  NOTICE: Thread LanguageInvoker start, auto delete: false
23:44:23 T:1476  NOTICE: -->Python Interpreter Initialized<--
23:44:24 T:1476   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('action',)
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\script.trakt\script.py", line 427, in <module>
                                                Main()
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\script.trakt\script.py", line 47, in Main
                                                args = getArguments()
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\script.trakt\script.py", line 41, in getArguments
                                                data['action'] = data['action'].lower()
                                            KeyError: ('action',)
                                            -->End of Python script error report<--
```

**Comment by nopoz** [comment]
figured it out - for those that are interested:

`curl -v -H "Accept: application/json" -H "Content-type: application/json" -u user:password -d '{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.trakt","params":{"action":"sync","silent":"True"}},"id":1}' http://10.0.0.111:80/jsonrpc`

**Comment by glensc** [comment]
this should be added to some faq or readme i think

**Comment by razzeee** [comment]
feel free to send a PR adding that to the readme

**Comment by drinfernoo** [comment]
Is this any different from using Python to call `RunScript(script.trakt, action=sync[, silent=True])`?

**Comment by razzeee** [comment]
No, but it's available to non python clients via web sockets

**Comment by drinfernoo** [comment]
@Razzeee Exactly as I expected 🙏
