### ISSUE TITLE
Sync question

### ISSUE THREAD

**Issue by tknorris** [Razzeee/script.trakt#195]
I just discovered my trakt account has over 6000 pages of episode watched history. I watch a lot of TV, but not that much. So, the theory is I might have gotten a bad sync somehow. The question is: When the kodi addon syncs your wached history to trakt, does it include the "watched_at" field or does it just leave it out?

**Comment by Razzeee** [comment]
It does include it and chooses the last watched_at for an episode/movie if you have multiple

**Comment by tknorris** [comment]
Somehow the addon has gotten confused and updated some shows with 100's of watches. I know it's the Kodi addon because one of the shows that had duplicates is only in my Kodi library and not in my Plex library. I have no idea what happened though.

**Comment by Razzeee** [comment]
Thats a nightmare, but this shouldn't be possible unless its creating the duplicates on the server side or the server is vending wrong errorcodes?

**Comment by tknorris** [comment]
Yeah, I'm really perplexed w/ the whole thing. I can say for sure though it's not giving more current dates because many of the ones that have so many sitll only show really old last_watched_at values.

For example:
```
The Genius of Charles Darwin - 1x1 - 648 plays - 2013-03-31T20:54:09.000Z
The Genius of Charles Darwin - 1x2 - 648 plays - 2013-03-31T20:54:09.000Z
The Genius of Charles Darwin - 1x3 - 648 plays - 2013-03-31T20:54:09.000Z
```
(That last column is the last_watched_at value)

I'm writing code now to remove all plays for each one and then to add them back w/ just their most recent play.

**Comment by Razzeee** [comment]
Well when you remove them the kodi addon will know it on the next sync and it will do the readding for you

**Comment by tknorris** [comment]
Hmm, that's a good point..maybe I should just remove them and let it handle it.

**Comment by tknorris** [comment]
what I'll do is keep a copy of the watched history so that I can reprocess it in case it doesn't add them properly

**Comment by tknorris** [comment]
Something is going on because I went to each kodi install, made sure it was properly authorized and then reset all the watched status for each episode with mroe than 10 plays and now those same episodes have several watch history entries again...I'm not sure what's going on yet.

**Comment by tknorris** [comment]
Ok, here's the log of the sync: http://pastebin.com/9ceerKN9

Sync is definitely adding new playcounts to several shows on each sync.  The specific shows affected are: Survivorman, Dancing with the Stars, and The Three Stooges. None of my other many shows seem affected.

**Comment by tknorris** [comment]
also, The Genuis of Darwin and Nashville are affected.

**Comment by tknorris** [comment]
Also, not all episodes of these shows are impacted, just a small submit...very weird.

**Comment by tknorris** [comment]
After removing most of the junk, I was finally able to view some of my history. Here's the most recent duplication.  (It shows the time that was recorded for the extra plays)
![screenshot from 2015-06-01 21 51 07](https://cloud.githubusercontent.com/assets/1934551/7927031/81a072d8-08a8-11e5-979b-364ff13c4f84.png)

**Comment by tknorris** [comment]
@Razzeee Any ideas what the problem could be here? I don't know how the watched sync code works at all...

**Comment by Razzeee** [comment]
Not really, logfiles might help.

**Comment by tknorris** [comment]
I included a log file in this comment: https://github.com/Razzeee/script.trakt/issues/195#issuecomment-107750184

**Comment by Razzeee** [comment]
Can't find anything wrong in there.

**Comment by tknorris** [comment]
Well, the interesting thing is it says those episodes are updated, but they actually aren't. They are already in my history on trakt and I haven't changed them or watched them in months

**Comment by tknorris** [comment]
Since it's a simple show, We can stick with the Charles Darwin show. Those episode haven't been watched in like 2 years

**Comment by Razzeee** [comment]
Em,  wasnt the log from your first sync after you deleted everything? 
Then it's really an other context to work with. Sorry if I assumed false.

**Comment by tknorris** [comment]
Ah, ok, I'll generate another one then after a sync. I assume it's much the same though since every single sync adds another watched event for those episodes

**Comment by Razzeee** [comment]
Well that would essentially mean trakt isn't giving these episodes back as seen or we can't match them. Nashville for eg doesn't seem to have a tvdbID

**Comment by tknorris** [comment]
Here's a log of a manual sync. It has much the same results as my triggered ones. It still says 31 shows in the library are missing playcounts which must be wrong since the last time my library had new episodes was Sunday. http://pastebin.com/TnT5H9bL

**Comment by tknorris** [comment]
hmm, that's odd about Nashville, because I just did this json rpc request against the same box and it returns the tvdb number for the show.

```
curl -g 'http://htpc.local:8080/jsonrpc' -d '{"jsonrpc": "2.0", "method": "VideoLibrary.GetTVShowDetails", "params": {"tvshowid": 139, "properties": ["title", "imdbnumber"]}, "id": 1}' -H 'content-type: application/json'
{"id":1,"jsonrpc":"2.0","result":{"tvshowdetails {"imdbnumber":"259055","label":"Nashville","title":"Nashville","tvshowid":139}}}
````

**Comment by tknorris** [comment]
aha, I think the problem is here: https://github.com/tknorris/script.trakt/blob/dev/utilities.py#L354

I don't think that id dictionary reference is right any more.

**Comment by tknorris** [comment]
PR #196 submitted for this. As soon as you merge, I'll push another beta.

**Comment by tknorris** [comment]
Also, in case anyone else gets caught by this, I have a python script that removes all the history for any episode with more than X watches.
