### ISSUE TITLE
Trakt does not synch episodes which were manually set to "marked as watched"

### ISSUE THREAD

**Issue by GolexPrime** [razzeee/script.trakt#196]
When I manually mark episodes as watched (within the menu by clicking on "marked as watched"), the plugin does not recognize it. I have to start an episode to convince the plugin to tell trakt that it should be synchronized as a watched episode.

**Comment by CaTzil** [comment]
Here as well

**Comment by razzeee** [comment]
This will be fixed with the 3.0.0 version which should show up in the official Kodi repo shortly.
