### ISSUE TITLE
Trakt addon syncing incorrectly.

### ISSUE THREAD

**Issue by bukes007** [Razzeee/script.trakt#197]
I've been tearing my hair out slightly on this one. I am pretty defeated trying to figure this out. Here it is.

This started when I connected Series Guide (android app) to Trakt. It marked everything in my library as watched. -_-

So I finally get that resolved and my trakt.tv watched history is now where it should be. Here begins my problem. The trakt addon in Kodi is not syncing correctly. It appears to be working, but just incorrectly. I can unmark episodes as watched in Kodi but when I perform a manual trakt update it resets the episode to watched even though I am on the trakt.tv/shows/show/seasons/1/ page and it's clear that it is indeed unwatched (and nothing in my history obviously). This was performed on a clean install of Kodi. I added my sources and had no watched statuses up. They were all marked as watched by the trakt addon (incorrectly).

Some basic questions answered:

<li>Fresh install of Kodi</li>
<li>tried it with the trakt 3.0.1 and 3.0.2 beta 2. Same activity</li>
<li>Yes the account is attached correctly. I authorized with the pin. Not possible it's attaching to another account (I don't have two, and am only user on this PC)</li>

Has anyone else had this issue? I'm going mad trying to figure this out.

**Comment by bukes007** [comment]
log

https://gist.github.com/bukes007/a5fe16cbb2049dfa7bb9#file-gistfile1-txt

**Comment by Razzeee** [comment]
Can you name an show as an example? Best with episode and season numbers.
Also is your account public and would you share a link to it? (I can understand if you don't want to)

**Comment by bukes007** [comment]
The show I have been using as an example is "The 100". It consistently thinks I have seen all of season 2 (this happened when Series Guide exploded my watched history). In reality (and as you can see from trakt, I have only watched up to S02E07.

My account is public

http://trakt.tv/users/bukes
https://trakt.tv/shows/the-100

Thanks for the help with this.

**Comment by Razzeee** [comment]
Well your log doesn't show this happening.
See https://gist.github.com/bukes007/a5fe16cbb2049dfa7bb9#file-gistfile1-txt-L1497 there is no mention of the 100 in that part. The other parts where it's mentioned it's just saying it has found the show on your kodi.

**Comment by bukes007** [comment]
I dumbed everything down. Fresh install of Kodi and I only added one show, Castle (2009). This is the log.

13:42:51 T:174984   DEBUG: [script.trakt] sync: [Episodes Sync] Trakt.tv episode collection is up to date.
13:42:51 T:174984   DEBUG: [script.trakt] sync: [Episodes Sync] 1 show(s) shows are missing playcounts on Kodi
13:42:51 T:174984   DEBUG: [script.trakt] sync: [Episodes Sync] Episodes updated: Castle [tvdb: 83462] - S01E01, S01E03, S01E05, S01E06, S01E07, S01E08, S01E09, S01E10
13:42:51 T:174984   DEBUG: [script.trakt] sync: [Episodes Sync] chunk [{'params': {'playcount': 1, 'lastplayed': '2014-02-24 21:12:33', 'episodeid': 1}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 0}, {'params': {'playcount': 1, 'lastplayed': '2015-05-23 09:06:47', 'episodeid': 3}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 1}, {'params': {'playcount': 1, 'lastplayed': '2015-05-23 09:06:47', 'episodeid': 5}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 2}, {'params': {'playcount': 1, 'lastplayed': '2015-05-23 09:06:47', 'episodeid': 6}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 3}, {'params': {'playcount': 1, 'lastplayed': '2015-05-23 09:06:47', 'episodeid': 7}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 4}, {'params': {'playcount': 1, 'lastplayed': '2015-05-23 09:06:47', 'episodeid': 8}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 5}, {'params': {'playcount': 1, 'lastplayed': '2015-05-23 09:06:48', 'episodeid': 9}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 6}, {'params': {'playcount': 1, 'lastplayed': '2015-05-23 09:06:48', 'episodeid': 10}, 'jsonrpc': '2.0', 'method': 'VideoLibrary.SetEpisodeDetails', 'id': 7}]

I assume this means the issue is on Trakts end. It clearly doesn't state that I have watched those episodes in my cleaned up history (on trakt.tv) but it appears that the addon still sees that history. I wonder if trakt has more than one DB and synchronizes them or something. I'll open up a support ticket.

**Comment by Razzeee** [comment]
Yes, the addon receives that you have seen this already.
Have you reset your whole profile or do have you just deleted some episodes?
If you want to rest the whole profile, have a look at https://github.com/damienhaynes/TraktRater it has a maintendence tab where you can do this

**Comment by bukes007** [comment]
Essentially what I want to do is erase the cache. I want to keep my watched
history (very important). I have a very large library so what I did was go
back through the history on the website and delete the history of shows I
have not seen yet. I don't understand why it's so hard to erase the cache.

On Wed, Jun 3, 2015 at 6:29 PM, Razzeee <notifications@github.com> wrote:

> Yes, the addon receives that you have seen this already.
> Have you reset your whole profile or do have you just deleted some
> episodes?
> If you want to rest the whole profile, have a look at
> https://github.com/damienhaynes/TraktRater it has a maintendence tab
> where you can do this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Razzeee/script.trakt/issues/197#issuecomment-108620970>
> .
>



-- 
Thanks,

Scott Buchanan
http://scottbuchanan.ca

**Comment by Razzeee** [comment]
For starters try another browser or the incognito mode. If it is still wrong then, there's something fishy.

**Comment by bukes007** [comment]
It's not the browser. Everything is good when I navigate to trakt.tv and
check my history there. What the problem is is the master db caching my
history which is not seen on the website.

This is what I got from Justin.

"We have a master db that would contain your data. We do cache your
history, but that would expire as soon as you watch something new. One
thing you could test is marking an episode watched, then unwatched on the
website to force the cache to update. I'm not really sure how the history
would be gone on the website, but show up in the API. I've never had a
report of that before."

and

"Marking the one show should expire your full history that the Kodi plugin
uses."

The last one isn't true. It just erases the cache for that show.

It looks like I am SOL unless Justin can help erase the cache. It's just
annoying because it took me forever to get my history correct again on the
website thinking that Kodi would simply take that info. I wasn't
anticipating dealing with a hidden cache system that I can't erase.

On Wed, Jun 3, 2015 at 8:04 PM, Razzeee <notifications@github.com> wrote:

> For starters try another browser or the incognito mode. If it is still
> wrong then, there's something fishy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Razzeee/script.trakt/issues/197#issuecomment-108639765>
> .
>



-- 
Thanks,

Scott Buchanan
http://scottbuchanan.ca

**Comment by Razzeee** [comment]
Well, it's unfortunatly not up to this addon to fix it then

**Comment by bukes007** [comment]
Yeah that was my conclusion. The caching system is just flawed. I hope that
eventually we can manually erase our cache if needed... It took a pretty
long time to do it manually.

On Sun, Jun 7, 2015 at 11:42 AM, Razzeee <notifications@github.com> wrote:

> Well, it's unfortunatly not up to this addon to fix it then
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Razzeee/script.trakt/issues/197#issuecomment-109762455>
> .
>



-- 
Thanks,

Scott Buchanan
http://scottbuchanan.ca
