### ISSUE TITLE
Cannot validate SSL certificate when connecting to trakt

### ISSUE THREAD

**Issue by jacaru** [razzeee/script.trakt#198]
OpenElec 5.0.4
Kodi 14.2
Trakt 3.0.0 dev branch 

After some succesful runs, suddenly cannot connect to trakt server due to SSL certificate verification failed upon starup:

01:00:17 T:1815757888    INFO: [script.trakt] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): api-v2launch.trakt.tv

01:00:18 T:1815757888   FATAL: [script.trakt] traktapi: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!  
                                            Error Type: <type 'SSLError'>  
                                            Error Contents: (SSLError(SSLError(1, '_ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed'),),)
                                            Traceback (most recent call last):  
                                              File "/storage/.kodi/addons/script.trakt-dev/traktapi.py", line 63, in getToken
                                                auth = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "/storage/.kodi/addons/script.trakt-dev/trakt/interfaces/auth.py", line 10, in login  
                                                'password': password  
                                              File "/storage/.kodi/addons/script.trakt-dev/trakt/core/http.py", line 89, in post  
                                                return self.request('POST', path, params, data, *_kwargs)  
                                              File "/storage/.kodi/addons/script.trakt-dev/trakt/core/http.py", line 66, in request  
                                                response = self.session.send(prepared, timeout=timeout)  
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 569, in send  
                                                r = adapter.send(request, *_kwargs)  
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 420, in send  
                                                raise SSLError(e, request=request)  
                                            SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed  
                                            -->End of Python script error report<--  
01:00:18 T:1815757888   DEBUG: [script.trakt] traktapi: Cannot connect to server

**Comment by razzeee** [comment]
Read this topic https://github.com/Razzeee/script.trakt/issues/78

**Comment by jacaru** [comment]
Ok it is a timing issue. Embarrassed.

When openelec boots up it takes some time to setup the clock from the ntp servers. Trakt has a delay configuration option and by making use of this I can overcome the problem. I would say that the maximum allowed value of 30 seconds seems too tight to the eye, but so far so good.

By the way, I recall previous versions of trakt having a default non zero value for this option.

**Comment by razzeee** [comment]
If that setting is not working for you, you can activate "wait for lan" in the openelec setting.

I havent changed the default there and it seems like it was added with that default.
https://github.com/trakt/script.trakt/commit/d35cb35cccace8ab92983b6d55d60accdb6b774e#diff-af43a89be9d2f2f9592bb0e0fdeb2138R8

**Comment by jacaru** [comment]
Hmm, then I must be mistaken. I do have that other option enabled. 

Actually is kodi which is setting up the time and not openelec. So maybe enabling NTP service on openelec itself speeds things up.

**Comment by jacaru** [comment]
Yes, after setting NTP in openelec everything is better.

Secondary question: 
In a permanently running kodi setup, if initial trakt connection fails we will need to reboot kodi? 
If it does not, are we guaranteed connectivity for a i.e. month long session?
What I mean is that, how should we be aware that trakt is working or if a reboot is needed other than eventually noticing on trakt web that things are not being pushed? I usually have trakt notifications off but I guess this is a reason to have them on.

**Comment by razzeee** [comment]
If it fails you will have to reboot or go to the options and change your password to something wrong, then change it back. This should also trigger a new login. 
And as long as your token is valid it should work even after a month.

**Comment by jacaru** [comment]
Thanks for your answer!

As a final suggestion, maybe an option to "notify only on fail" for scrobbles would be nice to have.
