### ISSUE TITLE
six required to be installed on raspberrypi (raspbmc)

### ISSUE THREAD

**Issue by wintersandroid** [Razzeee/script.trakt#20]
I had a little trouble getting the dev branch to work on my raspbmc, Seems the six libarary was not installed by default..

Might be good to include a note in the readme, or include six in the tz library..

Good work!

**Comment by Razzeee** [comment]
How did you install it, if you copy it, it's your task to make sure it's there. (will add this to readme) 
If you install from zip or repository (when we push it) kodi should make sure it's there
