### ISSUE TITLE
3.0 Server Busy message & Exeception thread

### ISSUE THREAD

**Issue by dpons039** [razzeee/script.trakt#200]
Hello guys,

I'm getting this error with the 3.0 version, it seems like the Api connection is way too busy and the Script can't perform the Sync.

coud it be posible to.. Instead of failing give a message at Kodi saying: "The server is busy, try the sync again later..."

Thank you!!

Message log:
22:20:54 T:39376  NOTICE: [trakt] [traktAPI] __getData(): urllib2.urlopen()
22:20:55 T:39376  NOTICE: [trakt] [traktAPI] traktRequest(): (3) Server Busy ({"status":"failure","error":"server is over capacity"})
22:21:01 T:39376  NOTICE: [trakt] [traktAPI] traktRequest(): (4) Request URL 'https://api.trakt.tv/movie/library/b6135e0f7510a44021fac8c03c36c81a17be35d9'
22:21:01 T:39376  NOTICE: [trakt] [traktAPI] __getData(): urllib2.Request(https://api.trakt.tv/movie/library/b6135e0f7510a44021fac8c03c36c81a17be35d9)
22:21:01 T:39376  NOTICE: [trakt] [traktAPI] __getData(): urllib2.urlopen()
22:21:02 T:39376  NOTICE: [trakt] [traktAPI] traktRequest(): (4) Server Busy ({"status":"failure","error":"server is over capacity"})
22:21:08 T:39376  NOTICE: [trakt] [traktAPI] traktRequest(): JSON Request failed, data is still empty after retries.
22:21:08 T:39376   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\David\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 364, in run
                                                episode = xbmc.getInfoLabel('VideoPlayer.Episode')
                                              File "C:\Users\David\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 765, in sync
                                                titles = ", ".join(["%s" % (m['title']) for m in kodiMoviesToUpdate])
                                              File "C:\Users\David\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 729, in syncMovies
                                                chunked_movies = utilities.chunks([movie for movie in traktMoviesToUpdate], chunksize)
                                              File "C:\Users\David\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 634, in traktAddMovies
                                                y = ((i / x) \* 25) + 11
                                            TypeError: not all arguments converted during string formatting

**Comment by razzeee** [comment]
The logfile you posted is not from 3.0.0 can you delete your settings.xml located at Kodi\userdata\addon_data\script.trakt ?
Have you installed from the official repo?

**Comment by dpons039** [comment]
Hello,It did the auto-update and seems it went bad. I have re-installed it.
Btw, the debug mode seems not to be working, at my kodi.log I can't see what the plugin is doing like it was at the previous. // The option is enabled.

Saludos cordiales / Best regards,David Pons

Date: Fri, 6 Mar 2015 13:56:04 -0800

**Comment by razzeee** [comment]
@Dpons039 
you'll also have to activate the debugging in kodi itself. this is something that the kodi team expects from addons.
https://github.com/trakt/script.trakt#creating-logfiles

**Comment by dpons039** [comment]
Tried that, and yeah the messages does appear now.

It wouls be better to have some of that outputs at the regular log (Like When the Sync started/Stoped and the difference "on Trakt.tv (xxx), shows in Kodi (xxx).")

Thank you for everything!

**Comment by razzeee** [comment]
Yes, but the behavior right now is the recommended one from team kodi and there are some very good reasons.
