### ISSUE TITLE
Question: Get Trakt.TV rating of TV Show or Movie for Skin use?

### ISSUE THREAD

**Issue by mgonzales71** [Razzeee/script.trakt#201]
I have searched with no luck to see if it is possible to get the community rating of a show or movie from trakt.tv for use in a skin to display?

my end goal is in the skin to be able to support ratings from:
trakt.tv (reason for this Q)
imdb (already available)
and rotten tomatoes, meta critic, etc.

My hope is it's an easy thing like properties setting in skin or even a RunScript

Thanks and sorry if this answer is already out there - I just couldn't easily find it.

Mario

**Comment by Razzeee** [comment]
You're probably looking for this:
http://kodi.wiki/view/Add-on:Universal_Movie_Scraper

**Comment by mgonzales71** [comment]
ok - thanks - I need to find good documentation on that add-on - from what I have read it only supports one source for ratings - not many at once.  

I was thinking the trakt addon had support for grabbing ratings in addition to submitting them.

go ahead and close this and thanks for your time sir! :)

**Comment by Razzeee** [comment]
You want to merge the ratings from different sites into one?

You may have luck with this if you are a skinner https://github.com/phil65/script.extendedinfo#trakttv

**Comment by mgonzales71** [comment]
thanks - have been reading more about this last couple of days.
the code to get all the ratings is in the universal scraper but it's assumption is that you only want one source for them.

i am playing around with utilizing external script/python to get at the data easier using the existing code. 

thanks again

**Comment by freeman212** [comment]
let me know if you find a simple way to utilize the trakt rating in skins :)

**Comment by Razzeee** [comment]
Well, as the v1 api is dead now and there is no way to scrap the new one, it's very unlikely we'll get to see that.

**Comment by Razzeee** [comment]
If we're lucky this will be in J*******
https://github.com/xbmc/xbmc/pull/7561

**Comment by freeman212** [comment]
@Razzeee that's great news :+1:

**Comment by Razzeee** [comment]
I've finished userratings for movies here: https://github.com/Razzeee/script.trakt/tree/User-Ratings
You'll need jarvis to test it. If you do, please don't use your normal trakt login, as watched or collected also needs to be checked again. So far everything seems promissing.

**Comment by Razzeee** [comment]
I just added episode and tvshow ratings sync. I'll close this for now.
