### ISSUE TITLE
Script Error on startup

### ISSUE THREAD

**Issue by pogman-code** [razzeee/script.trakt#203]
Hi,
I'm running Kodi through RaspBMC and I used script.trakt so far. Recently I tried to update the script (git pull'ed the repository. Since then, I can't manage to make it work. I even tried to remove/re-install it using provided zip file and via git clone.

For information:

```
pi@raspbmc:~$ kodi --version
14.1 Git:2015-02-02-81c4046-dirty Media Center Kodi
Copyright (C) 2005-2013 Team Kodi - http://kodi.tv
```

Also I installed following modules:
https://github.com/Razzeee/script.module.trakt
&
https://github.com/Razzeee/script.module.dateutil

as advised in README.md

Am I missing something?

Thanks :)

**Comment by razzeee** [comment]
Yes, the logfile ;)

Is there a reason your installing it from git and not the official kodi repo?

**Comment by pogman-code** [comment]
I can provide logfile indeed, just let me know where it is supposed to be, I'm not very familiar with kodi's filesystem and I don't know where to look at.

I used to get script from git because I had the script from your fork at first and it wasn't available from Kodi repos. (And as far as I saw, the two modules are not on Kodi repos, am I right?)

Anyway, I tried also to install it through Settings and it didn't work either...

**Comment by razzeee** [comment]
As of last friday everything you need is on the Kodi repository. You might need to do a "force refresh" on the repo.
http://kodi.wiki/view/Add-on_manager#Force_refresh

Regarding the log location:
http://kodi.wiki/view/Log_file/Easy

You will also have to enabel debug logging in the addons options.

**Comment by pogman-code** [comment]
OK, I managed to make it work. I removed all "manually" installed addons:
- request
- six
- trakt.py
- dateutil. 

Then rebooted, force refreshed repos and installed script.trakt through XBMC. 
I noticed that it also installed _arrow_ module (that I did not had) though.

My bad.
Thanks you Razzeee

**Comment by razzeee** [comment]
No problem :)
