### ISSUE TITLE
Intempestiv seen status

### ISSUE THREAD

**Issue by ghost** [razzeee/script.trakt#204]
A lot of my last added episodes are marked as watched with something like twenty views...
Is this a known issue ?

**Comment by ghost** [comment]
I've never watched them ofc.

**Comment by razzeee** [comment]
No, your the first and only one I heard this from so far.

**Comment by s7eele** [comment]
i remember people reporting similar issues way back at the beginning of the upgrade but nothing since, might even have been something caused by 2.3.1, more than likely an update issue, log?

**Comment by ghost** [comment]
I don't have log right now.
I just noticed this yesterday. 5 episodes in 3 differents shows were marked as watched (never watched them)
I marked them as unwatched, make a sync, they come back...
After, I logged on trakt.tv, found the episode and clicked on "remove watch status". Pop up ask for all ?
Said Yes => Confirm message said something like "25 plays removed" :O

**Comment by ghost** [comment]
For exemple all this season is marked has watched... but I did watched all of it... Episodes arent aired now...
And when I'd removed one, got this message.
I suspect that this script send a "full season watched" to the web site....
![screen](https://cloud.githubusercontent.com/assets/3975358/6770518/14b46832-d0c2-11e4-9b38-14b06255cdeb.PNG)

**Comment by razzeee** [comment]
Well we can only confirm this off we have a log

**Comment by ghost** [comment]
Should I activate Debug Mode ?

**Comment by s7eele** [comment]
yes, enable debug first

**Comment by ghost** [comment]
ok now I need to wait for a new episode...

**Comment by razzeee** [comment]
So any news?

**Comment by ghost** [comment]
Not yet...

**Comment by razzeee** [comment]
Are you using any other apps/addons that connect to trakt?

**Comment by ghost** [comment]
No. Just this one.

**Comment by razzeee** [comment]
I'm going to close this, if we can't get a log or anything that confirms this.

**Comment by ghost** [comment]
Can't reproduce on the last version.
