### ISSUE TITLE
"OAuth must be provided" (code: 401)

### ISSUE THREAD

**Issue by gborri** [razzeee/script.trakt#209]
08:21:40 T:2370906944 WARNING: [script.trakt] trakt.interfaces.base: request failed: Unauthorized - "OAuth must be provided" (code: 401)

**Comment by razzeee** [comment]
This happens if your login wasn't accepted (the api is pretty busy these days, throwing some errors)  and you try to do some other commands.

**Comment by gborri** [comment]
it's almost 3 days that haven't update watched episode, is it correct?

**Comment by razzeee** [comment]
Yes, thats when the 520 errors started. Seems to be right.
You can get lucky if you restart kodi often enough, but it's probably not worth it.

**Comment by gborri** [comment]
thaks.

**Comment by gborri** [comment]
The problem persist, are you sure it really a problem of traktv site? SickRage has an integration with traktv and it work, there no problem of authentication. I started having problem after an update of script.trakt.

**Comment by razzeee** [comment]
So, you could delete the settings.xml and see if it solves anything. 

But we probably need a full log to say anything more.

**Comment by gborri** [comment]
tried but doesen't work.

**Comment by razzeee** [comment]
Read here https://github.com/trakt/script.trakt#creating-logfiles
And post a log

**Comment by razzeee** [comment]
So any news?
