### ISSUE TITLE
Movies with no IMDB id being added to collection as watched

### ISSUE THREAD

**Issue by botchla** [Razzeee/script.trakt#21]
I'm having an issue where movies that aren't on IMDB, like comedy DVDs, that are on TMDB, are being added to my collection during a sync, but the watched status is being added as 'watched' even though they are not watched.

**Comment by spencems** [comment]
i confirm i am also having this issue

**Comment by Razzeee** [comment]
Should be fixed, mea culpa ;)

**Comment by botchla** [comment]
Thanks!

**Comment by Jobespierre** [comment]
Fixed, tx @Razzeee  awesome day putting out fixes all over the place!
