### ISSUE TITLE
Very slow performance during sync on RPi

### ISSUE THREAD

**Issue by Jean85** [Razzeee/script.trakt#211]
I'm using XBian on my RPi B+, and during the sync I'm having some performance issues.

Basically, the RPi freezes for a few seconds when the sync starts, probably it goes 100% CPU.
Obviously it's very annoying if I'm viewing something at the same time, and this happens a lot because I launch the sync after lib refresh, and I have a lib refresh triggered every time transmission finishes something.

The obvious fix right now is to disable the automatic lib refresh... There's something else that I can do?

**Comment by Razzeee** [comment]
Beside getting a rPI2, not that I can think of, unfortunatly

**Comment by Jean85** [comment]
There's no way to 'nice' it? I have a lot of background CPU-intensive processes, like transmission, and a "nice 10" solved it all...

**Comment by Razzeee** [comment]
I'm not sure what your talking about

**Comment by Jean85** [comment]
I'm talking about this: https://en.wikipedia.org/wiki/Nice_(Unix)

**Comment by Razzeee** [comment]
I don't think you can, as it's inside of the kodi task
