### ISSUE TITLE
Feature request: lists and friend activity

### ISSUE THREAD

**Issue by szklany** [razzeee/script.trakt#213]
There are two features missing that i think would really improve the overall trakt experience.
1. Being able to sync user made trakt lists i.e. if i follow a list on trakt it will show up in Kodi, where i am then able to watch the movies that are in my library. This could be done via the tags. I feel like having something like this gives more purpose to the list function in trakt.
2. Friend activity. It would be nice to have a little area in Kodi where it's possible to see what others are watching or have watched lately. I think this would be a good way to get more Kodi users interested in trakt.

**Comment by razzeee** [comment]
Please one issue for each. 
The first one is already opend if you have a closer look
