### ISSUE TITLE
Expired token - shouldn't it be a popup error in Kodi?

### ISSUE THREAD

**Issue by insurw** [Razzeee/script.trakt#215]
I found this in the debug log in several places:
"OAuth - Unable to refresh expired token (error occurred while trying to refresh the token)"

Anyway, I guess the oauth error was the reason scrobble and manual updating failed. Though strangely enough only happened on one of my profiles (they use same login). But the addon gave no indication there were any oauth problems.

**Comment by Razzeee** [comment]
Hrm, this shouldn't happen in the first place. The token should expire and refresh automatically.

**Comment by insurw** [comment]
Here's the log: http://pastebin.com/YntrrN9Q
Works fine after I created a new token.

**Comment by insurw** [comment]
Even though it's not your fault shouldn't the addon show a popup and not just in the debug log?

**Comment by Razzeee** [comment]
Well, it would be nice. But as that is a bug that shouldn't happen anywhere I would need to generally capture errors and throw them at the user. And I really think that would be a bad idea.
