### ISSUE TITLE
script.trakt fails on Kodi start

### ISSUE THREAD

**Issue by Clearmist** [razzeee/script.trakt#217]
Installing from a zip fails without error. Manually placing the trakt addon in to the Kodi addons folder results in "Script failed!: trakt" appearing on Kodi boot.

Kodi 14.2 (the most result stable release) Win32

**Comment by razzeee** [comment]
Is there a reason your not using the kodi repo?

**Comment by Clearmist** [comment]
Razzeee, the trakt.tv downloads page directs to this Github page. The instructions on this Github page were to either install via the .zip or to manually extract the repository to the addons folder. I hadn't yet used the built in search function within Kodi. Doing that now I was able to install the script.

**Comment by razzeee** [comment]
Well the instruction does say you should install the repo version
https://github.com/trakt/script.trakt#installation
