### ISSUE TITLE
service.py error

### ISSUE THREAD

**Issue by Lunatixz** [Razzeee/script.trakt#217]
12:12:49 T:7112   DEBUG: JSONRPC: Incoming request: {"params": {"playerid": 1}, "jsonrpc": "2.0", "method": "Player.GetItem", "id": 1}
12:12:49 T:7112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "Y:\portable_data\addons\script.trakt\service.py", line 400, in onPlayBackStarted
                                                self.type = result['item']['type']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--

**Comment by Razzeee** [comment]
Can you post a full log with debugging ing kodi and in the trakt addon acivated?
There should be a log row with ```[traktPlayer] onPlayBackStarted() -``` in it

**Comment by Lunatixz** [comment]
Nope, No logs with '[traktPlayer] onPlayBackStarted()'... 
I took a look at service.py, looks like line 386, the print you are looking for is wrapped by a try exception so it's ignored when result returns a nonetype... which then trickles down to line 400.

I've noticed this error in my logs for a few weeks... just figured I'd let you know...

**Comment by Razzeee** [comment]
I'm not seeing a try wrapped around this?
https://github.com/Razzeee/script.trakt/blob/master/service.py#L386

**Comment by Lunatixz** [comment]
is wrapped around your log function which is line 386 =P

**Comment by Razzeee** [comment]
I think the interesting thing would be why this happens, ```Player.GetItem``` should return an result as long as ```self.isPlayingVideo()``` is true? Is there a specific case where this happens?

**Comment by Lunatixz** [comment]
I think you are forgetting the first rule of scripting for Kodi, don't rely on consistent returns... I wrap everything in exceptions, even If i'm 99% sure of the return, because there is always that one case where you get the unexpected ;). I'd assume the heart of the problem has to do with Kodi v15 and something changing in how the player handles playlists... since i'm always running PseudoTV Live when I see your errors... since playing a playlist is a fairly common function I wouldn't call the problem unique to PseudoTV... which is why I brought it up :)

**Comment by Razzeee** [comment]
Can't say I'm using playlists. Will have to dig, to find that, but I'm not sure if it's really cool to just give a warning for this. I would think this qualifies as a potential bug that could be fixed within kodi, if this holds true.

**Comment by Lunatixz** [comment]
I agree, still leaves your plugin generating errors tho... I'd suggest a kodi ticket, but also I think it's proper coding to make exceptions in your code when you can't guarantee the data.I've got a list a page long of odd little bugs I find in Kodi... problem is tracking down why they all occur, for example I found a bug which causes the bool condition for player.paused to stop reporting accurate info. Flat out stops reporting true when media is paused... can't seem to find the exact root of the issue, but I had to code around it, till Kodi can issue a fix...

**Comment by Razzeee** [comment]
Just because I'm curious do team kodi know about your problems? 
Also can you give me a guide to reproduce it, if it's happening consistent?

**Comment by Lunatixz** [comment]
Sure, I've helped resolve a few bugs... but some like the pause issue requires time on my part to track down the mechanism causing the problem, I mentioned it to a team member and they said its working fine... but for me it fails once and awhile... when and why it fails requires a bit of work...

as for reproducing the cause of the getitem issue, I'll keep an eye on it... really a matter of logging every instance of getitem, log prior to the call...

**Comment by Razzeee** [comment]
Can you gist the try your using now? Probably just a simple 
    if not result: 
         Return

?
