### ISSUE TITLE
Import played date/time from trakt.tv

### ISSUE THREAD

**Issue by insurw** [Razzeee/script.trakt#218]
Is it possible or doesn't the API supply that info? This would be useful for TV shows when creating a Smart playlist like "Not played in the last X months/years", it'd specially useful for e.g. The Simpsons that I like to play an "unwatched" random episode every time. 

I just rearranged/renamed my Simpsons folder and I lost all that data. I was hoping I'd be able to import it from trakt, but it doesn't seem so. I still have backups of my Kodi library so I guess I could get the data from the SQL database. But that seems a lot of manual work, though maybe not if I learn SQL.

**Comment by Razzeee** [comment]
Couldn't think of a usecase to do this, so far, but this seems to be legit. Not sure when I will have time to look at it.

**Comment by insurw** [comment]
It seems your addon actually does what I want. :) Maybe you misunderstood me? I just didn't set my Smart Playlist properly. First I thought it was Kodi that didn't delete all data when cleaning the database. (Which is kinda true, as removing and readding a show will still have its e.g. "last played" data. Though I think it's tied to the file path.) But I tried with a complete new install and no it's the addon that added the "last played" to Kodi when syncing. I.e. when it says "Loading episode data from Trakt. Updating X of Y episode playcount(s) in Kodi"

**Comment by Razzeee** [comment]
Em, yeah it does so that. Sorry, must have been my cold speaking ;)
