### ISSUE TITLE
Update readme with PIN instructions

### ISSUE THREAD

**Issue by rectifyer** [razzeee/script.trakt#218]
Noticed the readme still mentions username/password, but PIN auth is used now.

**Comment by razzeee** [comment]
Thanks for the heads up.
Will need some time to reach the main trunk but I've changed it in the dev

**Comment by elrui** [comment]
Just to let you know the pin url seems to be wrong. After login it shows a wrong redirect. I tried using the url without www at the beginning and it worked well.

**Comment by razzeee** [comment]
works for me in chrome :/

**Comment by elrui** [comment]
When I use https://www.trakt.tv/pin/999 I get the login screen (redirected to https://www.trakt.tv/auth/signin), even if I am already logged in. Then, when I try to login with Google, I get a redirect error.

I'm attaching a couple of screenshots for you.
![screen shot 2015-06-22 at 2 59 39 am](https://cloud.githubusercontent.com/assets/7256126/8277690/ec5edadc-188a-11e5-8e4a-d758cdc2baaa.png)
![screen shot 2015-06-22 at 3 00 18 am](https://cloud.githubusercontent.com/assets/7256126/8277692/ec72810e-188a-11e5-8d0d-d7fb5abcd7ff.png)

This is complete error trace from the Google page:

```
from_login=1
response_type=code
scope=https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
access_type=offline
redirect_uri=https://www.trakt.tv/auth/auth/google_oauth2/callback
state=67ec185913af6319ceaf54dd1a97552021dddc0546fe4d61
as=719fba086a72b972
client_id=251026498157.apps.googleusercontent.com
authuser=0
hl=en
```

However, if I go to https://trakt.tv/pin/999 instead, I get my pin and everything works fine.

I'm using Chrome Version 43.0.2357.124 (64-bit) on Mac OSX 10.10.3

Hope this helps.

**Comment by razzeee** [comment]
@elrui 
well that google login part was important. seems like there is an problem, that @rectifyer has to fix
