### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by rambounchained** [razzeee/script.trakt#219]
Original post: Everything is working, as the movies or tvshows I see, is showing right away on my trakt account, facebook and twitter are working too. But if I watch something in my livingroom, it does'nt get marked as watched in the bedroom. It goes the same way if I watch something in my bedroom, when syncronizing is done, in the livingroom, it does'nt get marked as watched. 

My post: I am having the same issue as the poster above. The only difference is that I am using MySQL on W8.1 and an Android Mach 8 as a client. I can't get things to sync on my test machine either. All are running 14.2.

Log w/ debugging enabled: http://pastebin.com/y88SV5v9

**Comment by razzeee** [comment]
Please reach out to the trakt support. And cooperate with them. Ask why your account is returning a 500 error when calling /sync/collection/shows

**Comment by rambounchained** [comment]
When I did that he said to go to the git

**Comment by razzeee** [comment]
I'll try to sort this out. Please have a little patience

**Comment by razzeee** [comment]
Can you try again the trakt team said they pushed a fix

**Comment by rambounchained** [comment]
They did. Working great. Thanks.
