### ISSUE TITLE
Clearing watched status

### ISSUE THREAD

**Issue by mularj** [Razzeee/script.trakt#221]
Hi.  Is there any way to add functionality to the script whereby when I toggle the watched status in Kodi it goes out to Trakt and removes the watched/history?  At the moment if I want to clear the watched status it just comes back on the next sync.  Logging into Trakt manually and clearing it is painful.

Thanks,  Jim.

**Comment by Razzeee** [comment]
Try to install the context menu addon for toggle watched. Then you should be able to change it from the context menu.

**Comment by anaconda** [comment]
It's something I'd like to have too (I mean it be done automatically - a setting to enable it would be okay, if needed).
It's not something I've tried to investigate, but (un)marking as watched should be fire a `VideoLibrary.OnUpdate` notification:
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/notifications.json#L202
