### ISSUE TITLE
Error syncing movie library

### ISSUE THREAD

**Issue by danpowell88** [razzeee/script.trakt#222]
I've done a fresh install of 14.2 Helix and the trakt plugin.

TV Shows sync fine but movies fail with the following error

> 09:17:15 T:1128   ERROR: Exception in thread trakt-sync:
>                                            Traceback (most recent call last):
>                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
>                                                self.run()
>                                              File "C:\Users\m\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 256, in run
>                                                sync.sync()
>                                              File "C:\Users\m\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 930, in sync
>                                                self.__syncMovies()
>                                              File "C:\Users\m\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 842, in __syncMovies
>                                                self.__addMoviesToKodiWatched(traktMovies, kodiMovies)
>                                              File "C:\Users\m\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 769, in __addMoviesToKodiWatched
>                                                chunked_movies = utilities.chunks([{"jsonrpc": "2.0", "method": "VideoLibrary.SetMovieDetails", "params": {"movieid": kodiMoviesToUpdate[i]['movieid'], "playcount": kodiMoviesToUpdate[i]['plays'], "lastplayed": utilities.convertUtcToDateTime(kodiMoviesToUpdate[i]['last_watched_at'])}, "id": i} for i in range(len(kodiMoviesToUpdate))], chunksize)
>                                              File "C:\Users\m\AppData\Roaming\Kodi\addons\script.trakt\utilities.py", line 441, in convertUtcToDateTime
>                                                local = utc.astimezone(tzlocal())
>                                              File "C:\Users\m\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz.py", line 113, in utcoffset
>                                                if self._isdst(dt):
>                                              File "C:\Users\m\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz.py", line 157, in _isdst
>                                                return time.localtime(timestamp+time.timezone).tm_isdst
>                                            ValueError: (22, 'Invalid argument')

Timezone is set to australia 12H

``` xml
<locale>
        <audiolanguage>default</audiolanguage>
        <charset default="true">DEFAULT</charset>
        <country>Australia (12h)</country>
        <keyboardlayouts default="true">English QWERTY</keyboardlayouts>
        <language default="true">English</language>
        <subtitlelanguage>default</subtitlelanguage>
        <timezone default="true">default</timezone>
        <timezonecountry default="true">default</timezonecountry>
    </locale>
```

Trakt settings are as follows (removed sensitive data)

``` xml
<settings>
    <setting id="ExcludeHTTP" value="false" />
    <setting id="ExcludeLiveTV" value="false" />
    <setting id="ExcludePath" value="" />
    <setting id="ExcludePath2" value="" />
    <setting id="ExcludePath3" value="" />
    <setting id="ExcludePathOption" value="false" />
    <setting id="ExcludePathOption2" value="false" />
    <setting id="ExcludePathOption3" value="false" />
    <setting id="PIN" value="XXXXXXXXXXXXX" />
    <setting id="PIN_Info" value="" />
    <setting id="add_episodes_to_trakt" value="true" />
    <setting id="add_movies_to_trakt" value="true" />
    <setting id="authorization" value='XXXXXXXXXXXX' />
    <setting id="clean_trakt_episodes" value="true" />
    <setting id="clean_trakt_movies" value="true" />
    <setting id="debug" value="false" />
    <setting id="hide_notifications_playback" value="false" />
    <setting id="kodi_episode_playcount" value="true" />
    <setting id="kodi_movie_playcount" value="true" />
    <setting id="rate_each_playlist_item" value="true" />
    <setting id="rate_episode" value="true" />
    <setting id="rate_min_view_time" value="75.000000" />
    <setting id="rate_movie" value="true" />
    <setting id="rate_rerate" value="false" />
    <setting id="rating_default" value="6" />
    <setting id="scrobble_episode" value="true" />
    <setting id="scrobble_movie" value="true" />
    <setting id="scrobble_notification" value="false" />
    <setting id="show_marked_notification" value="true" />
    <setting id="show_sync_notifications" value="true" />
    <setting id="startup_delay" value="0" />
    <setting id="sync_on_update" value="true" />
    <setting id="trakt_episode_playcount" value="true" />
    <setting id="trakt_movie_playback" value="false" />
    <setting id="trakt_movie_playcount" value="true" />
</settings>
```

**Comment by razzeee** [comment]
There is a movie in your kodi database with a last seen date not between  1970 and 2038.
You should remove these

**Comment by danpowell88** [comment]
I've scanned everything in from scratch

**Comment by danpowell88** [comment]
Just checked and no movies has any lastPlayed date set (in sqllite)

**Comment by razzeee** [comment]
Em, sorry got em mixed up.
Check trakt for watched outside of 1970 and 2038

**Comment by danpowell88** [comment]
I ended up finding it,  somehow a few movies were set to 1-1-1970 fixing
those fixed everything
