### ISSUE TITLE
Scrobbles HTTP sources (at least Vimeo) even though HTTP sources are exluded

### ISSUE THREAD

**Issue by insurw** [Razzeee/script.trakt#225]
Not sure if it's limited to Vimeo or happens with other addons too.

Here's log where it scrobbles a video titled Gravity in Vimeo.
http://pastebin.com/h4swNy05

**Comment by Razzeee** [comment]
Well seems like we want to filter out ```plugin://```
And it seems like it's a music video your watching? Maybe we should ignore those as well.

**Comment by anaconda** [comment]
Hm no, I think this needs to also check for `https://`:
https://github.com/Razzeee/script.trakt/blob/dev/utilities.py#L125

Your `startswith() > -1` looks broken though - it returns a boolean:
```python
>>> type('x'.startswith('x')), int(True), int(False), True > -1, False > -1
(<type 'bool'>, 1, 0, True, True)
```

**Comment by Razzeee** [comment]
Yeah,  I figured the https part when this issue opened up.

**Comment by Razzeee** [comment]
And yeah I think we exchanged starts with for something else lately.

**Comment by Razzeee** [comment]
Can you check if this is still valid?

**Comment by insurw** [comment]
@Razzeee Seems to be fixed.
