### ISSUE TITLE
Trakt add on does not scrobble on OSMC

### ISSUE THREAD

**Issue by Loewkie** [razzeee/script.trakt#227]
Log file: http://www.xbmclogs.com/pwzmiseyl

I'm running OSMC 0.9.9 (kernel: Linux 3.18.13-1-osmc) on a RaspPi 2.
Add on has issues scrobbling to trakt. Tried scrobbling a movie and tv show with PIN I had entered earlier. Then I entered a new PIN and tried again. Then I set the start delay to 0 and tried again. It didn't work for all attempts. If you need more info please let me know.

**Comment by razzeee** [comment]
Well seems like you try to watch something with a third party strm addon
`14:49:21 T:1740198944   DEBUG: [script.trakt] service: [traktPlayer] onPlayBackStarted() - Non-library file, not enough data for scrobbling, skipping.`

Whatever strm addon it is, it's not providing enough data, nothing I can do about it. If you reach out to that addons developer, you may want to link him to this https://github.com/trakt/script.trakt/wiki/Providing-id%27s-to-facilitate-scrobbling

**Comment by Loewkie** [comment]
The addon that I am using is [KMediaTorrent](https://github.com/jmarth/plugin.video.kmediatorrent).
I'll reach out to them and see what they can do about it. Until then I'd like to keep this issue open.

And: [Issue](https://github.com/jmarth/plugin.video.kmediatorrent/issues/125)
