### ISSUE TITLE
Episodes/movies often not getting scrobbled - have to launch manually to sync

### ISSUE THREAD

**Issue by insurw** [Razzeee/script.trakt#228]
About ~3/10 scrobbles aren't sent to trakt it seems so I'm forced to launch the addon manually. I'm not sure but I think this mostly (only?) happens when starting another file/video without stopping or waiting till the the current playing video finishes.
I'm thinking about making a script to launch the trakt addon on a schedule and just disable scrobble as it's so unreliable.

Here's a recent missing scrobble: http://pastebin.com/riFhG3nv
X-files Hungry is only in the log when started at 09:50:28. According to the Trakt website I finished the episode at 10:50. There's nothing about X-files there, but it was about then I played a couple Vimeo videos.

**Comment by Razzeee** [comment]
Yes, you have to stop the playback.

**Comment by insurw** [comment]
Meh it's just not that. I just used "play from here". Kodi marked it as watched and played next episode. I checked kodi.tv. Of course not scrobbled. I started the addon, but the addon didn't wanna send the watched status to trakt.tv According to the addon it's not marked as watched in Kodi's database I guess?

The occurrence of duplicates, missing scrobbles and forcing you to use Kodi in a specific way to scrobble (even when using manuall start) I might as well go back to marking stuff manually at trakt.tv

**Comment by Razzeee** [comment]
Well if Kodi knows of the play at least the sync should work. Will have to text what happens when how play from here behaves. Also it should scrobble fine if you watched 80 percent of the movie. 
And I never seen a duplicate so far, but my setup is quiet basic.
