### ISSUE TITLE
Can't fill in PIN in touch devices (3.0.2)

### ISSUE THREAD

**Issue by danialbehzadi** [razzeee/script.trakt#229]
When on android (or any other touch-only device), after tapping on the field, the touch keyboard will open under the trakt account authorization window, but there is no way to enter text on the field.

**Comment by flabb17** [comment]
exactly same problem !

**Comment by razzeee** [comment]
Are you using confluence?

**Comment by danialbehzadi** [comment]
No, re-touched

**Comment by razzeee** [comment]
Which kodi versions are you on? Have you had this working prior? Under which version? So the keyboard is opening? But you can't type?

**Comment by danialbehzadi** [comment]
Official Kodi 15-RC from Google Play.
I attached the screencap.
![screencap](https://cloud.githubusercontent.com/assets/3658678/8528693/e57e3398-2429-11e5-805c-324e96578345.png)

On 07/06/2015 09:23 PM, Razzeee wrote:

> Which kodi versions are you on? Have you had this working prior? Under
> which version? So the keyboard is opening? But you can't type?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/trakt/script.trakt/issues/229#issuecomment-118923491.

## 

Danial Behzadi

**Comment by razzeee** [comment]
@tknorris 
did you run into this? we're using the zorder of 2 for the window and thus the keyboard window is popping up in the background 
http://trac.kodi.tv/ticket/16102

**Comment by tknorris** [comment]
No, I don't use kodi on any touch devices, so it's not something I've ever tested. I have been told by others that re-touched is broken, though I can't vouch for that statement at all. I do know that the window works fine on my FTV using the remote for keyboard entry in Confluence.

**Comment by razzeee** [comment]
well I've just drafted a solution, but it's in the kodi core. I will PR it and then see what happens

**Comment by tknorris** [comment]
I installed Kodi on my phone to test this, and I can confirm it (as though the pic above wasn't enough to already do so). I also tried with Confluence and it just doesn't seem to pop a keyboard at all when you tap the edit control. The strange thing is the keyboard pops-up completely behind the window, not even just the edit control.

**Comment by razzeee** [comment]
yes, it also happens on windows, but your unlikely to click into the edit control there.

**Comment by tknorris** [comment]
Hmm, yep, you are right. It's happening on linux as well. ~~This might be a new issue because I don't remember seeing this on Helix.~~

Cancel that, just tested on another box running Helix and it does the same.

**Comment by razzeee** [comment]
Haven't tested, but in the kodi forum there are reports of 14.2 also having this.

**Comment by tknorris** [comment]
I justed tested w/ my old dialog and it works OK...It seems like the issue is setting the z-order explicitly in the dialog

**Comment by tknorris** [comment]
Just tested..if you remove the explicit z-order it works fine...I'm not sure why that's there anyway? I guess you could argue that the keyboard pop-up should always have the highest z-order of anything except pop-ups, but it seems like a simple fix is just to remove the z-order from the window xml for now.

**Comment by razzeee** [comment]
Because it will get stuck behind the dialog where you can delete the addon for e.g.
https://github.com/xbmc/xbmc/pull/7432

**Comment by tknorris** [comment]
That seems like less of an issue than the keyboard not working on any touch device, IMHO. ;-)

**Comment by razzeee** [comment]
Well the it's about to how you go there, so it will work 50/50 and cause confusion. Better but not really good.

**Comment by tknorris** [comment]
agreed, but there's a work around to the dialog getting hidden behind the info window (i.e. "Don't do it that way"),but there isn't a work around to the keyboard being under the window. (one interesting thing to note is you can still actually use the keyboard when it's hidden)

**Comment by tknorris** [comment]
So, I found a workaround for the keyboard issue. But it's very hard. The main thing to realize is the text for the keyboard doesn't show up until you hit enter and even though the keyboard is behind the dialog, it's actually still taking input. So, what you have to do is kinda guess where the right keys are, tap them to enter the PIN, then tap the enter button (on my screen it's just below the "No Thanks" button). If it's wrong, tap the edit control again, fix the text (you have to do it blind) and hit enter again..rinse, repeat until you get it right...It sucks, but it works...

also, note, it helps if you bring up a keyboard you can actually see beforehand ot get an idea of where the keys are..For example, the backspace key is just above the right half of the enter key.

**Comment by razzeee** [comment]
A new version is waiting to be reviewed by the kodi team since 2 days, so please be patient.

**Comment by razzeee** [comment]
Update has been pushed and should address this
