### ISSUE TITLE
Sync after startup library sync

### ISSUE THREAD

**Issue by Luxoboy** [Razzeee/script.trakt#231]
Hey there,

I'm running latest OSMC release on a RPi2.

Trakt is setup correctly and everything is working smoothly.
I only have an issue (if one can call that an issue): I have Kodi set up to update library after startup, but the Trakt addon doesn't sync after that update.
If I manually update the library, the addon is triggered and syncs.

I tried to increase the "Startup delay" up to 10 in the addon's options (I am not aware of what that option actually does).

Any info/help appreciated. :)
Thanks.

Cheers!

**Comment by Razzeee** [comment]
Can you try to disable the startup delay?

**Comment by Luxoboy** [comment]
Do you mean setting it to zero?
It was the default value and it was not working either.

**Comment by anaconda** [comment]
AFAIK startup scan is started (and can finish) before add-ons are instantiated.

**Comment by Razzeee** [comment]
if that's the case, there is not much we can do about it.
Hard to say anything without a logfile.
