### ISSUE TITLE
Can't enter pin ubuntu

### ISSUE THREAD

**Issue by FlatlandNative** [razzeee/script.trakt#231]
The "User" box is greyed out and cannot be selected and there is a field below that says "How do I authorize the trakt addon to acess my trakt.tv account?" I  receive error script failed. I tried installing trakt from kodi repo itself and also the github zip below the https clone link. Not sure what I am doing wrong at this point but I can't seem to find where or how I would enter the pin.  I saw there was a fix 6 days ago about entering the pin so I hope I am just not grabbing the wrong version.

**Comment by razzeee** [comment]
Well you should not install from github as that won't pull in the dependencies. Please remove the files you downloaded manually and install from the official repo, you should be fine then.

**Comment by FlatlandNative** [comment]
I tried the repository before and just tried it again, receiving the same problem. User box is grey and the other box below says "How do I authorize the trakt addon to acess my trakt.tv account?". It's installing version 3.0.3. I tried updating my repository, I'm using the default confluence skin.

**Comment by razzeee** [comment]
I will need a logfile then https://github.com/trakt/script.trakt#creating-logfiles

**Comment by FlatlandNative** [comment]
19:54:06 T:140403969910720  NOTICE: UpdateLibraries: Starting video library startup scan
19:54:06 T:140402732553984  NOTICE: Thread VideoInfoScanner start, auto delete: false
19:54:06 T:140403969910720  NOTICE: initialize done
19:54:06 T:140403969910720  NOTICE: Running the application...
19:54:06 T:140403106637568  NOTICE: -->Python Interpreter Initialized<--
19:54:06 T:140403969910720  NOTICE: starting zeroconf publishing
19:54:06 T:140402715768576  NOTICE: Thread JobWorker start, auto delete: true
19:54:06 T:140403969910720  NOTICE: ES: Starting event server
19:54:06 T:140402707375872  NOTICE: Thread EventServer start, auto delete: false
19:54:06 T:140402707375872  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
19:54:06 T:140402707375872  NOTICE: UDP: Listening on port 9777
19:54:06 T:140402346686208  NOTICE: Thread JobWorker start, auto delete: true
19:54:06 T:140402698983168  NOTICE: Thread TCPServer start, auto delete: false
19:54:06 T:140402732553984  NOTICE: VideoInfoScanner: Starting scan ..
19:54:07 T:140403098244864  NOTICE: -->Python Interpreter Initialized<--
19:54:07 T:140403106637568  NOTICE: Previous line repeats 2 times.
19:54:07 T:140403106637568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named 'requests.packages.urllib3'
                                            Traceback (most recent call last):
                                              File "/home/kv/.kodi/addons/script.trakt/default.py", line 6, in <module>
                                                from service import traktService
                                              File "/home/kv/.kodi/addons/script.trakt/service.py", line 6, in <module>
                                                from traktapi import traktAPI
                                              File "/home/kv/.kodi/addons/script.trakt/traktapi.py", line 5, in <module>
                                                from trakt import Trakt, ClientError, ServerError
                                              File "/home/kv/.kodi/addons/script.module.trakt/lib/trakt/**init**.py", line 3, in <module>
                                                from trakt.client import TraktClient, **version**
                                              File "/home/kv/.kodi/addons/script.module.trakt/lib/trakt/client.py", line 3, in <module>
                                                from trakt.core.http import HttpClient
                                              File "/home/kv/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 5, in <module>
                                                from trakt.core.request import TraktRequest
                                              File "/home/kv/.kodi/addons/script.module.trakt/lib/trakt/core/request.py", line 1, in <module>
                                                from requests import Request
                                              File "/home/kv/.kodi/addons/script.module.requests/lib/requests/**init**.py", line 58, in <module>
                                                from . import utils
                                              File "/home/kv/.kodi/addons/script.module.requests/lib/requests/utils.py", line 26, in <module>
                                                from .compat import parse_http_list as _parse_list_header
                                              File "/home/kv/.kodi/addons/script.module.requests/lib/requests/compat.py", line 42, in <module>
                                                from .packages.urllib3.packages.ordered_dict import OrderedDict
                                              File "/home/kv/.kodi/addons/script.module.requests/lib/requests/packages/__init__.py", line 95, in load_module
                                                raise ImportError("No module named '%s'" % (name,))
                                            ImportError: No module named 'requests.packages.urllib3'
                                            -->End of Python script error report<--
19:54:07 T:140402749339392  NOTICE: -->Python Interpreter Initialized<--

in-case that wasn't enough full log is http://pastebin.com/H0TpEmvG

**Comment by razzeee** [comment]
Anything special about your setup?
The installation states your missing urllib3 and that is baked into one of the dependencies.

Please try again to delete all addon folders:
script.trakt
script.module.trakt
script.module.six
script.module.requests
script.module.dateutil
script.module.arrow

Also remove these from userdata\addon_data
Then reinstall script.trakt from within kodi via the addon manager and only there.

**Comment by FlatlandNative** [comment]
Did exactly that, I found all of those files within my addon folder deleted them, and only found script.trakt within addon_data, so I deleted that. Opened up Kodi, went to "Kodi Add-on repository" version 2.1.32 and installed trakt version 3.0.3, upon installation I have the exact same problems. It told me it was enabling each of those addons we just deleted, six requests dateutil trakt and arrow. Nothing weird about my kodi install, literally only have loaded tv and movies onto it, haven’t customized at all.

**Comment by razzeee** [comment]
@fuzeman have you seen this error somewhere before?

**Comment by fuzeman** [comment]
My guess is the installation of the requests library is corrupt, check what is in this directory:

```
/home/kv/.kodi/addons/script.module.requests/lib/requests/packages/urllib3
```

That `urllib3` directory should look like this:
![](http://i.imgur.com/7Vxve5x.png)

---

It appears kodi caches addons into `addons\packages`, you could try reinstall again but delete the module zip files from `addons\packages` as well.

**Comment by FlatlandNative** [comment]
![buntu](https://cloud.githubusercontent.com/assets/12928338/8750165/6cd179d8-2c6b-11e5-83b0-f9198ba3cc7d.JPG)
There is a shot of /home/kv/.kodi/addons/script.module.requests/lib/requests/packages/urllib3

So your saying I should delete the addons, delete the zips within addons\packages, and delete the userdata\addon_data, and then finally try installing again?

Basically just delete all of those files while kodi is shut down, open up kodi and try reinstalling trakt?

**Comment by FlatlandNative** [comment]
Tried exactly that, found an old Trakt 2.3 something script in my addons\packages folder, deleted that plus everything else I tried from the last time. I only deleted the zips that had one of the following names "script.trakt
script.module.trakt
script.module.six
script.module.requests
script.module.dateutil
script.module.arrow" , I also deleted addons with those names and userdata\addon_data with those names.

Then I loaded up kodi and installed trakt again from the repository. Still stuck.
![trakt](https://cloud.githubusercontent.com/assets/12928338/8753407/3573ad42-2c81-11e5-9782-0cb34e7f8051.JPG)

**Comment by razzeee** [comment]
The user box is supposed to be greyed out. You need to select the "How do I authorize..."-button and click it.

**Comment by FlatlandNative** [comment]
I do and it tells me there's an error in the script. I will enable debugging here in a second and verify that I am recieveing the same debug info but clicking on "How do I authorize..." at the moment displays a popup error in the bottom right of XBMC.

**Comment by FlatlandNative** [comment]
http://pastebin.com/R1yx09kV full log from debug. Tried a couple more times to uninstall and delete files from the 3 folders, no success. Not sure where to head from here, I am deleteing the files in question each time and they get pulled again I'm not sure how they could keep corrupting.

**Comment by FlatlandNative** [comment]
If I were to uninstall Kodi would I be able to start from scratch essentially? Or are there more files that would need to be removed?

**Comment by razzeee** [comment]
I'm not familiar with how it's handled by ubuntu, but when you have uninstalled it, check the `/home/kv/.kodi/` folder and if it is still there delete `.kodi` completely

**Comment by FlatlandNative** [comment]
I'm feeling defeated. Tried that made sure there was no .kodi folder. Reinstalled. Still no luck. Not sure what to even try any more.

**Comment by razzeee** [comment]
Well we could try to update the request package, as I think we're on 2.6.0 and the newest stable is 2.7.0
But that should be done here https://github.com/beenje/script.module.requests

**Comment by razzeee** [comment]
Use this PR https://github.com/beenje/script.module.requests/pull/6 to try

**Comment by FlatlandNative** [comment]
Still kind of new to github, I am used to running clone on the repository, how do I work with this Pull Request? I'm assuming the idea here is to just replace my old script.module.requests with this new one?

**Comment by razzeee** [comment]
Yes, download it from here https://github.com/Razzeee/script.module.requests

**Comment by FlatlandNative** [comment]
Deleted the old script.module.requests, copied the new clone to that folder. Opened Kodi and tried running configure on trakt.

Still getting an error but I think this one might be different if I'm not mistaken?
http://pastebin.com/PmfguVGh

**Comment by razzeee** [comment]
Yes, thats a different one. Something seems to be wrong with your sqlite installation. So can you reinstall/repair that one?

**Comment by FlatlandNative** [comment]
Tried removing "sqlite" and reinstalling (with sudo apt-get remove/install), noticed that was version 2. Did the same thing then with sqlite3. Both times received errors similar to this, I think it is the same sqlite error.

http://pastebin.com/yYvuyps2

**Comment by razzeee** [comment]
Are you able to try this? http://stackoverflow.com/a/19748196/2859813
You don't need to do the manage.py part

**Comment by FlatlandNative** [comment]
already had both installed. Should I try removing?

**Comment by razzeee** [comment]
Even the dev one?

**Comment by FlatlandNative** [comment]
I accidentally closed the terminal but I think you might be right and that said it said there were a few changes for that one. 

edit: had a spare laptop with ubuntu installed, ran the kodi install and installed trakt with ease. I'm sorry my computer is a problem child :(. Is it too soon to consider a fresh install of ubuntu? The one thing holding me back is I have a mdadm raid 6 built and I am not sure how that works if I reinstall OS. The OS is on a ssd not in the raid so I think it might work?

**Comment by razzeee** [comment]
Well, reinstall should be easy if it's really on the ssd. But obiously I'm in no possition to give you support on hardware/reinstall topics ;)

**Comment by FlatlandNative** [comment]
understandable, I just feel like I'm probably wasting your time for a problem that only exists on my machine when I can easily wipe the slate and be fine. Sorry about that, thanks for the help.

**Comment by razzeee** [comment]
Your welcome

**Comment by FlatlandNative** [comment]
Reinstall of ubuntu was easy, trakt addon worked with no problems. Thanks.
