### ISSUE TITLE
Issues scrobbling local files

### ISSUE THREAD

**Issue by Loewkie** [razzeee/script.trakt#232]
http://xbmclogs.com/psymew6el
http://xbmclogs.com/psymew6el#line-1010

I'm trying to get Trakt to scrobble local files for me. I've looked at the log file and it doesn't seem to be able to ID the file. All it recognizes is the file name. I'm almost sure that it just needs more details besides the file name and running length of the episode, but I'm just hoping that there is another way. Editing all those files is going to take more effort than just simply marking them by hand.

**Comment by razzeee** [comment]
Well they need to be scraped and in your Kodi library.
Renaming is really easy with the correct tool, I would suggest FileBot.

**Comment by Loewkie** [comment]
Thank you.
