### ISSUE TITLE
dependencies not met, Contact Author

### ISSUE THREAD

**Issue by Xpdite** [Razzeee/script.trakt#233]
Just a head up that when I went to install trakt on a clean build of Kodi 15.2 I received the following error.
dependencies not met, Contact Author

**Comment by Razzeee** [comment]
Please install via the official repo

**Comment by Xpdite** [comment]
great, what is the official repo?  Followed the instructions from the Trakt site

**Comment by Razzeee** [comment]
Go to your settings then add-ons then install from repository then search for trakt there and install from there. 

The setup explained on github is for development only

**Comment by Xpdite** [comment]
It may be helpful if that was posted somewhere.  If you go to Trakt.tv it
shows as a download for kodi.  they even document how to install but it did
not seem to work.
When I tried to install from repository it was not coming up.  I ended
installing Wookie lite just to get Trakt back  :)
Thanks for replying, it is greatly appreciated.

**Comment by Razzeee** [comment]
I would be very interested where you read that it should be installed like that, as our readme states in the first sentence. That you should not install from here:
https://github.com/Razzeee/script.trakt#installation

**Comment by Xpdite** [comment]
You are correct but easy to miss when coming from
http://trakt.tv/downloads and click on Kodi

Think the issue for me was that the Kodi repo was missing from my install

Again, thanks for setting me straight
