### ISSUE TITLE
Transfer tv ratings to kodi

### ISSUE THREAD

**Issue by wintermute2517** [razzeee/script.trakt#233]
Since there is no Trakt scaper and we're all using it and rating our shows/movies it would be nice it the script could pull our trakt ratings and put them in kodi to replace those scraped from other sources.

For example, I sort my tv shows by ratings and the people who rate shows on thetvdb live on a different planet than I do, to me thunderbirds is a 6-7ish rating but over there it's rated 9. 

It would also be nice if there was an option to have the script do an average of a show's episodes rating and put that as the show's rating on kodi. If an episode or show isn't rated (on trakt) to just ignore it.

**Comment by razzeee** [comment]
Well thats really messing up your fields then, so I'm not going to programm this. But maybe we can introduce a user rating to kodi itself, thats where this should go to.

**Comment by razzeee** [comment]
https://github.com/Razzeee/script.trakt/issues/201
