### ISSUE TITLE
When syncing back from trakt only one of two episodes get marked as watched in kodi

### ISSUE THREAD

**Issue by jeder77** [Razzeee/script.trakt#234]
I often have episodes intentionally twice in my library. Once as a strm file from the SALTS addon and once in my native language in another folder. Both are scraped correctly and appear with correct info in my library. When I watch the strm version it gets corrently scrobbled to trakt. But on the next sync back from trakt or via manual launching of the trakt addon, the other (local) version does not get marked as watched.

Is it possible to add sth like a "Mark TV episodes from Trakt history as watched in Kodi **for all versions of the episodes**"?
somehow relates to [http://forum.kodi.tv/showthread.php?tid=220547&pid=2077318#pid2077318](url)  but I couldn't find the corresponding github issue, so please close this one if the user already issued one.

**Comment by akuiraz** [comment]
+1

I have also been wishing for this... I have some episodes downloaded the rest are .strm's from SALTS...

**Comment by Razzeee** [comment]
Feel free to send a PR, but I'm not going to spend time on this. Sorry.
