### ISSUE TITLE
Scrobble issue with double episodes (Kodi)

### ISSUE THREAD

**Issue by Waldner11** [razzeee/script.trakt#236]
Hey,

I've noticed the scrobbling of double episodes doesn't work with kodi. There's just the first one who is watched after. I need to manually check-in the second. 
Kodi sees it's a double episode but not trakt. Here's how it was : 
Seinfeld.S05E18-E19.The.Raincoats.720p.WEBRip.AVC-NTb.mkv
I had this problem with every other double episodes from Seinfeld

Could you take a look at it please? Thanks in advance.

Here's the logfile that i've retrieved from Kodi : http://pastebin.com/tFR2Mbqa

P.S. I use Kodi 14.2 and Trakt 3.0.3

**Comment by razzeee** [comment]
I just used this feature yesterday on an multi part episode. Did work fine for me, will have to investigate.
Btw. I'm using the same versions you have.

**Comment by Waldner11** [comment]
Ok, thanks, if you need any more info, I'm available.

**Comment by razzeee** [comment]
Seems to be something about how you queried these episodes. Have you added them via a play all or play next feature? Playlist or something like that?

**Comment by Waldner11** [comment]
No, I just clicked on episode 18 to play it.

Edit : I use a custom skin called RAPIER.

Here's a screen of what i see, not same episode but i would just click on the Season 6 Episode 14 episode to play both episodes.

![view](https://cloud.githubusercontent.com/assets/13509030/8895008/fb788486-33ca-11e5-9953-11946d10f0fd.JPG)

**Comment by razzeee** [comment]
I will have to try the skin then, will probably not have any time this week for that.

**Comment by Waldner11** [comment]
Any update on this?

**Comment by razzeee** [comment]
I tried to reproduce it with rapier and invader zim double episodes. But they work fine and it is only querying one double episode.

I can guess what the problem is, but it's hard to fix without reporducing it and I'm not having time for that right now.

**Comment by Waldner11** [comment]
Thanks very much for trying, if you need more details about my configuration rapier/trakt/kodi I'd have no problem sending them to you.

**Comment by Waldner11** [comment]
I'm not sure if it is related but I got a weird issue yesterday:
I was watching Seinfeld.S07E11, scrobbling was fine but all of a sudden during the middle of episode I got an other alert saying the scrobbled file was the Seinfeld.S07E22 (the one playing was still the S07E11), I had to stop/start playing the episode to get back to scrobble the S07E11. (it started where I was, 11 minutes something)
Atfter finishing the episode I had two watched items for the S07E11 on my trakt dashboard. The first one had a time around the time where I had the issue and the other one when I finished watching the episode.
It happened once or twice before, just for Seinfeld episodes.
Just thought I should mention this.

I managed to retrieve a log : http://pastebin.com/pr0JKvb9

Edit : By the way, I'm soon going to watch another double episode, do you wish me to send another log file?

**Comment by razzeee** [comment]
Data is always good. Just be sure you have enabled the log correctly. See the project documentation for that.

**Comment by Waldner11** [comment]
Ok, just tried again with a double episode. Still the same issue, only the first one is scrobbled.
This time i tried to play the second episode. I checked the Rapier skin and trakt to be sure i had the latest version on both of them before enabling the debug option.
Not sure what I can do more. Hopefully this will help you a bit.
http://pastebin.com/U5bGAepq

Do you think this could be related to Seinfeld only? I only ever played double episodes from this show so far.

Edit : I don't mind too much doing some more testing but it would be better if I did not had to watch the whole episode for it. Right now I watch the whole episode because I don't know exactly what triggers the scrobbling events. I'm pretty sure that just starting an episode then going to the end before ending/stopping it would produce the same thing, but I'm just not sure.

**Comment by Waldner11** [comment]
I've done some further testing and I believe it could be related to Seinfeld double episodes. I've tried this file : Battlestar.Galactica.(2003).S04E19E20... and the double scrobbling worked. I thought maybe the "-" between episodes of Seinfeld maybe was responsible but I tried without and it was still the same after updating my library and everything.
Do you have the means to further debugging your code? Maybe I could send you a link where you can find a double episode from Seinfeld?
(I have tried the default skin too and it doesn't work either)

**Comment by razzeee** [comment]
Well to be honest I think I know what's going on. 
For some reason you added not one double episode, but the double episode and some after that. Could be a playlist, that's what the log says. 
And I know the logic can't handle that at the moment. But I'm not sure when I will have time to work on it.

**Comment by Waldner11** [comment]
I never use Kodi like that, I always play each episode by click. 
I've tried something else given what you said, I cleaned my entire library of Seinfeld except for a double episode and tried several things (including playing it from files (not library). Atfer the 30 minutes bar which I assumed is somewhere around where the 2nd episode should be, there was still nothing for episode 2 scrobble.

Here are the results : http://pastebin.com/SFDn4sZq

I hope it will narrow down a bit the issue.

**Comment by razzeee** [comment]
Can you copy and past me the file names of one of the episodes that does this + episodes that would follow in that directory, if you kept watching?

**Comment by Waldner11** [comment]
Sure, it was this episode : Seinfeld.S07E21E22.The.Bottle.Deposit.720p...
And there were no other episode after, in my Seinfeld library it was the only file remaining. (at least for the last pastebin code i've sent you)

Edit : I just want to clarify what should contain the last pastebin I've sent you.

Given what you've said about the "playlist" thing, I've decided to do this :
- Remove all seinfeld episodes from my folder and library to just have a double episode remaining (Seinfeld.S07E21E22) to ensure that it shouldn't have any playlist thing for seinfeld
- Once it was done, I've tried playing the double episode multiple times, including one where i played it from the folder (not in the library)
- The thing i was trying to do was playing it from the start then go to like the time "3x:xx" to see if there was any reference to the seconde episode of the double episode
  I didn't see any reference on each time I've tried to play the episode.

So the pastebin I've sent you shouldn't have any reference to any other Seinfeld episode except the 21 and 22 from Season 7, given the fact that at the time of the tests there were no other episodes in the library and folder.

I hope it's clearer like this. Don't hesitate to ask me anything.

**Comment by razzeee** [comment]
Can you try again with this build? https://github.com/Razzeee/script.trakt/tree/dev
You might want to use a test account, as that is a beta build and an untested fix for your problem.

**Comment by Waldner11** [comment]
It doesn't seem to solve the issue. This time I've tried this episode :
Seinfeld.S09E23-E24.The.Finale.720p...
The version of trakt I've tested was 3.0.4 Beta 1
http://pastebin.com/fR4aZuiq

**Comment by razzeee** [comment]
Please try again, I pushed another update

**Comment by Waldner11** [comment]
I don't see it. Do you have changed the n° version?

**Comment by Waldner11** [comment]
I've tried the new one (who doesn't seem to have a different number version)
It didn't seem to scrobble anything (it was enabled) nothing appeared on my screen and nothing on the trakt website. 
http://pastebin.com/T9mdLaiu (still the Seinfeld.S09E23-E24.The.Finale.720p... episode)
Edit : It's possible that it didn't replace properly the previous file (I load the script from 'Install from zip files' without uninstalling the previous one(i just disable the previous before installing the new one)

**Comment by razzeee** [comment]
Yeah, I'm not bumping the version for each push.
And I really should not try to code without being able to test it, none the less I just pushed a fix for the above problem.

**Comment by Waldner11** [comment]
I understand that you do not update the number version but could you at least bump the beta number, that way I can assure more safely that I'm testing the right version. I'm going to try now, I'll let you know.

**Comment by Waldner11** [comment]
It seems to be working !
I had the trakt scrobble alerts on my screen + both episodes were watched on trakt website. 
Here's the log if you want to see more :
http://pastebin.com/KMQycLnf

**Comment by razzeee** [comment]
Should be fixed in the next release.

**Comment by Waldner11** [comment]
Great! Thank you very much!

Can I continue to use this beta version or do I need to rollback to 3.0.3 in order to have an auto-update from trakt when you will deploy the next release?

**Comment by razzeee** [comment]
I'm not sure, as I haven't it used that way. But it should update automatically from the beta to the correct release, when it comes out.

**Comment by Waldner11** [comment]
Ok, we'll see then. I consider this closed. Thanks again!

**Comment by Waldner11** [comment]
Hi,
I'm still using the latest beta version you sent me and there seems to be a bug with Seinfeld single episode. 
I noticed earlier that an episode didn't scrobble so I tried again with another one and it didn't work.
Seinfeld.S08E13.The.Comeback.720p.WEBRip.AVC-NTb.mkv (didn't work)
I tried with another episode from another show and it worked (Show.Me.A.Hero.S01E02.Part.2.720p.HDTV.x264-KILLERS.mkv)
You can see both attempts with this pastebin :
http://pastebin.com/dXSbrPHs

Sorry to bother you again with this.

Edit : I've tried several single episodes from Seinfeld and none of them scrobble. But the double episode from the same show scrobbles fine.
Edit 2 : Single episode scrobbling for Season 8 (of Seinfeld) doesn't work but for Season 9 single episodes it works. (it seems strange but it's real, at least on my side)

**Comment by razzeee** [comment]
Please try again. I've gone back to the first error and tried to fix that one correctly. So you only need to test against the original problem.

**Comment by Waldner11** [comment]
Yeah, everything seems to work now, I've tried several episodes from several shows + double episodes and it seems to work nicely.
Thank you, I'll let you know if I encounter any other issues.
