### ISSUE TITLE
Scrubbing not working

### ISSUE THREAD

**Issue by aktur** [razzeee/script.trakt#241]
On new Raspberian I've installed Kodi from repo and git cloned script.takt. I've used PIN method for activation but scrubbing is not working. What I see in the log file is:

WARNING: [script.trakt] trakt.interfaces.base: request failed: Not Found - "method exists, but no record found" (code: 404)

My trakt account is OK as scrubbing works from Plex and Infuse. I've performed sudo apt-get update; sudo apt-get upgrade but still no joy.

**Comment by razzeee** [comment]
I'll need a complete log to help you in any way

**Comment by aktur** [comment]
Here http://xbmclogs.com/pw1cipjh5

**Comment by razzeee** [comment]
Your trying to use a strm source that is not supported. Use local files or contact the addon dev and let them take a look at https://github.com/trakt/script.trakt/wiki/Providing-id's-to-facilitate-scrobbling

**Comment by aktur** [comment]
It would help if you list that only limited number of sources is supported. We'll spare some time this way to enjoy life instead.

**Comment by razzeee** [comment]
Will do, but mostly this is due to the other devs. As they need to provide the needed meta data

**Comment by aktur** [comment]
Sure, it is always somebody's else fault.

**Comment by razzeee** [comment]
Thanks for your analysis. If you can do better please send a pull request. 
I won't go and support any pirate addons. If they want to be supported it's up to them. 

Just from a man power perspective, I can't go and work on every streaming projects for kodi out there  that might or might not use trakt. 
So script.trakt has a interface with a documentation to take care of this usecase.
