### ISSUE TITLE
Episodes are no longer marked as watched on trakt.tv

### ISSUE THREAD

**Issue by Hubro** [razzeee/script.trakt#243]
This used to work beautifully, but hasn't worked for weeks. I have watched a couple of seasons of South Park and several episodes of The Office the last couple of weeks, but nothing has been marked as watched on trakt. I have tried re-authorizing, but it still doesn't work.

EDIT: I have now also removed the add-on, purged all its files from the kodi directory and reinstalled it. Episode views are still not updated on trakt.

I have checked the "sync on library update" option and updated the library probably 100 times the last few weeks. The traks popup shows up at the end saying "Syncing movie views" and "Syncing episode views".

Does this affect everybody or just me?

The log was over 10 000 lines long, so I have grepped out the lines containing "trakt" and added them below. Still it's over 1000 lines...

I can upload the full log somewhere if you need it.

**(Removed the log since it was unnecessary and huge)**

**Comment by razzeee** [comment]
Hey,

you are the first one reporting this.
Please check https://github.com/trakt/script.trakt#creating-logfiles for a how to enable debug logging and send me a log, prefareable through http://pastebin.com/

**Comment by Hubro** [comment]
What I did in detail, just in case it's relevant:
1. Enabled debug mode
2. Enabled Trakt debug mode
3. Exited Kodi
4. Deleted all logs
5. Started Kodi
6. Library automatically updates on startup, which is followed by Trakt sync
7. Exited Kodi

Immediately I found some very interesting lines in the log:

<pre>11:18:58 T:140511306299136   DEBUG: [script.trakt] sync: [Episodes Sync] Getting episode collection from Trakt.tv
11:18:58 T:140511306299136    INFO: [script.trakt] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (2): api-v2launch.trakt.tv
11:18:58 T:140511306299136   DEBUG: [script.trakt] sync: [Episodes Sync] Invalid Trakt.tv show list, possible error getting data from Trakt, aborting Trakt.tv collection update.
11:18:58 T:140511306299136   DEBUG: [script.trakt] sync: [Episodes Sync] Error getting Trakt.tv collected show list, aborting tv show sync.
11:18:58 T:140511306299136   DEBUG: [script.trakt] sync: [Sync] Finished synchronization with Trakt.tv</pre>

Here is the whole log: http://pastebin.com/raw.php?i=PPbXJfZZ

**Comment by razzeee** [comment]
Try to reach out to justin at trakt and let him check your account collection and probably watched. There were some cases in the past, where specific shows had data that broke the api.

Write at support@trakt.tv

**Comment by Hubro** [comment]
I have sent a mail informing them of the issue, including a link back here.

**Comment by Hubro** [comment]
I added some debug lines to sync.py line 109:

```
import traceback
logger.debug("[Episodes Sync] Exception: " + traceback.format_exc())
```

And immediately realized that this is way over my head:

<pre>12:45:51 T:140551504508672   DEBUG: [script.trakt] sync: [Episodes Sync] Exception: Traceback (most recent call last):
                                              File "/home/tomas/.kodi/addons/script.trakt/sync.py", line 102, in __traktLoadShows
                                                traktShowsCollected = self.traktapi.getShowsCollected(traktShowsCollected)
                                              File "/home/tomas/.kodi/addons/script.trakt/traktapi.py", line 152, in getShowsCollected
                                                Trakt['sync/collection'].shows(shows, exceptions=True)
                                              File "/home/tomas/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 16, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/tomas/.kodi/addons/script.module.trakt/lib/trakt/interfaces/sync/core/mixins.py", line 36, in shows
                                                **kwargs
                                              File "/home/tomas/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 16, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/tomas/.kodi/addons/script.module.trakt/lib/trakt/interfaces/sync/core/mixins.py", line 18, in get
                                                authenticated=kwargs.pop('authenticated', None)
                                              File "/home/tomas/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 128, in get
                                                return self.request('GET', path, params, data, **kwargs)
                                              File "/home/tomas/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 104, in request
                                                response = self.session.send(prepared, timeout=timeout)
                                              File "/home/tomas/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 573, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/tomas/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 370, in send
                                                timeout=timeout
                                              File "/home/tomas/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
                                                body=body, headers=headers)
                                              File "/home/tomas/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
                                                self._validate_conn(conn)
                                              File "/home/tomas/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
                                                conn.connect()
                                              File "/home/tomas/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connection.py", line 238, in connect
                                                ssl_version=resolved_ssl_version)
                                              File "/home/tomas/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 262, in ssl_wrap_socket
                                                ctx.set_verify(_openssl_verify[cert_reqs], _verify_callback)
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 753, in set_verify
                                                _lib.SSL_CTX_set_verify(self._context, mode, self._verify_callback)
                                            TypeError: initializer for ctype 'int(*)(int, X509_STORE_CTX *)' must be a pointer to same type, not cdata 'int(*)(int, X509_STORE_CTX *)'</pre>

Can you make any sense of that? Is trakt responding with corrupted encrypted data? Or is there a Kodi bug regarding certs?

**Comment by razzeee** [comment]
Thats probably something @fuzeman can help us with

**Comment by fuzeman** [comment]
I've found a couple of related issues: https://github.com/kennethreitz/requests/issues/2310, https://github.com/pyca/pyopenssl/issues/167

The installation of "PyOpenSSL" at `/usr/lib/python2.7/dist-packages/OpenSSL` must be broken somehow, the following commands _might_ fix it (assuming it's out of date):

```
pip install --upgrade pyOpenSSL
```

Doing a fresh install could work as well:

```
pip uninstall pyOpenSSL cryptography
pip install pyOpenSSL
```

See https://pip.pypa.io/en/latest/installing.html if you don't have "pip" installed.

**Comment by Hubro** [comment]
That makes a lot of sense, I recently upgraded from Debian 8 Jessie to Debian stretch.

I tried your commands, but pip just kept crashing. I tried `pip freeze` to see which versions were installed, but that command also just crashed. `pip list` did too.

Such is the risk of Debian testing I suppose. I've now run `apt-get upgrade` which updated lots of python related packages, and pip now works as intended, but I'm not allowed to touch pyOpenSSL:

<pre>$ sudo pip uninstall pyopenssl cryptography
Not uninstalling pyOpenSSL at /usr/lib/python2.7/dist-packages, owned by OS
Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, owned by OS</pre>

Running `sudo pip install --upgrade pyopenssl` crashes, presumably because of the above.

The Kodi issue is still there. I'll keep trying later today.

**Comment by Hubro** [comment]
I have tried:

```
sudo apt-get install --reinstall python python-openssl python-cryptography
```

But the error still occurs. I'm kinda stuck at this point. Is there any way I can get Kodi to use a different python installation, where I can control the versions of installed libraries?

Also I have confirmed that the versions installed are the most recent stable versions:

<pre>$ pip freeze | egrep -i "ssl|cryptography"
cryptography==0.9.3
pyOpenSSL==0.15.1</pre>

**Comment by razzeee** [comment]
I don't think that's possible for the Linux version of kodi. Other versions have the python version bundled.

**Comment by Hubro** [comment]
There's a compile option `PYTHON_VERSION` where I can specify a string to be appended to the python executable path, for example "2.7.10". I'm going to try installing python 2.7.10 and linking the executable to `/usr/bin/python2.7.10-kodi`, then compile Kodi with `PYTHON_VERSION=2.7.10-kodi`.

If that works I can try with different versions of PyOpenSSL.

One thing I'm wondering though; if Kodi compiles successfully, how do I confirm that it's actually using `/usr/bin/python2.7.10-kodi`, and not the system python?

Also, what python libraries must be installed for Kodi to work?

I'll cross those bridges when I get to them.

**Comment by Hubro** [comment]
I successfully compiled Kodi to use a custom python installed using pyenv. Python is now using these library versions:

<pre>$ python2.7.10-kodi -m pip freeze | egrep -i "crypt|ssl"
cryptography==1.0
pyOpenSSL==0.15.1</pre>

And the error is gone! Awesome!

Thanks for your help guys :)
