### ISSUE TITLE
Unwatched items on Kodi goes back to Watched after Update Library

### ISSUE THREAD

**Issue by Waldner11** [razzeee/script.trakt#244]
Hi,

I've recently started to use the sync episode function from trakt (for the collected purposes) and there's 
a bug with it on Kodi.
Usually my main tv show page in kodi where i launch my episode consists of my shows who are unwatched. So I unwatched the show that I already watched/collected for it to appear on this main page. (they do appear on the unwatched page at this point)
But every time I update my library, they disappear after being synced with trakt. (they go back to watched)

Thanks in advance.

**Comment by razzeee** [comment]
You need to remove the watched from your trakt profile also. This is intended behavior otherwise.

**Comment by Waldner11** [comment]
Hum, it seems flawed to me, given the fact that we can have multiple plays for a show.
I don't understand why watch/unwatch items for Kodi would have necessarily the same state than in Trakt.
Another way would be to stop the syncing for collected shows i suppose? I never had the issue before or did it change?

**Comment by razzeee** [comment]
Stopping sync should work. Hasn't changed at least not in this year.

**Comment by Waldner11** [comment]
Ok, no chance for it to change?

**Comment by razzeee** [comment]
Not planned, would mean a full sync rewrite and probably some solution how to track that info. It's unfortunatly not that simple.

**Comment by Waldner11** [comment]
You write the code so I'm not going to disagree but once again I find that strange. Why previously watched/collected items on trakt makes watched items in kodi. You can have collected items in kodi/trakt that are not watched.
Anyway, thanks for your answers. Hope it gets implemented in the future.

**Comment by razzeee** [comment]
`You can have collected items in kodi/trakt that are not watched.`
That shouldn't be a problem.

If you watched something before on trakt, why shouldn't it be watched in kodi? If you don't want to sync that way, you can disable this in the sync settings.

**Comment by Waldner11** [comment]
Oh yes! I didn't know we could do that on trakt settings. 
It's exactly what I wanted. 
Thanks.
