### ISSUE TITLE
TV Series collection mixup

### ISSUE THREAD

**Issue by anatolyra** [razzeee/script.trakt#245]
Hello,

I've stumbled on a very strange issue. I have 'House of Cards' in my trakt collection. When opening kodi the trakt addon syncs with the site. It then removes 'House of Cards' from my collection (on the site) and adds another show with the same name but from 1990, and bring this show into my local kodi library. I have a similar issue with several other shows.

Do you have any ideas as to what might be the problem?

Thanks!

**Comment by rectifyer** [comment]
Can you double check that it is scanned into Kodi correctly using the correct show metadata? Behind the scenes, the IDs are used to match on Trakt.tv and it sounds like the Kodi show has the incorrect IDs.

**Comment by razzeee** [comment]
You might want to add the year of house of cards to your show folder name.

**Comment by anatolyra** [comment]
How do I check for the kodi show ID? Or for that matter the ID of the show
on trakt?

**Comment by anatolyra** [comment]
I don't know if it's relevant, but it started happening after I removed Genesis and added SALTS. I since have installed back Genesis and removed SALTS without any improvement.

**Comment by razzeee** [comment]
Sorry, can't give support for those shady addons

**Comment by zecompadre** [comment]
take a look if u are using kodi & genesis

https://github.com/lambda81/lambda-addons/issues/52

**Comment by anatolyra** [comment]
Perfect! Thanks!

**Comment by zecompadre** [comment]
@anatolyra  solved ?

**Comment by anatolyra** [comment]
@zecompadre Solved, thank you!
