### ISSUE TITLE
[Feature request] Add an option to manually Scrobble or to prevent instant scrobble after starting a video

### ISSUE THREAD

**Issue by onesolo** [razzeee/script.trakt#246]
I love this addon cause I can scrobble what I'm watching to my social networks... but it has an disadvantage with the automatic scrobbling, sometimes you wanna just test audio or video setup, or check if that movie is ok or something like that and in reality you're not watching the full movie, like from the 1st minute till the last... still after you enter the video, Trakt, obviously, scrobbles that...

Is it possible to add an option so that only scrobble what we are seeing for at least some amount of time or percentage of the movie seen?!? Or some sort of pop-up asking if we want in reality scrobble what we are seeing ?!

I think this is something that a lot of folks would appreciate. As I told, as an option...

Thkx in advance

**Comment by razzeee** [comment]
This is now in development and will be in the next version. Whenever it may come out.
