### ISSUE TITLE
Proxy Enabled: Authorize and Scrobbing Fails For Kodi 16.0

### ISSUE THREAD

**Issue by war59312** [razzeee/script.trakt#252]
Hi,

Went to Authorize Trakt on my NVIDIA Shield and I got:

"Can not connect to trakt" and "Trak.tv Pin Authorization Failed"

Then I turned off Proxy and then I got:

"Trakt Authorization Completed"

So Proxy does NOT work with your trakt addon.

Proxy seems to be working just fine with all other addons I've tried.

Proxy is Privoxy running on Windows 8.1 x64.

Should note that it is only the Acivating step that is broken with Proxy.

Trakt scrobbing after I acivated it, is working just fine with Proxy enabled.

Thanks for the help,

Will

Update: Correction, scrobbing was working with proxy enabled because it was not really enabled. It seems it does not get enabled until a reboot of Kodi.

Upon that reboot with Proxy enabled, Trakt is failing to scrob. Bummer! :(

So I'm having to run with Proxy off which stinks. I use the Proxy to block evil stuff (ads, spyware/malware sites, etc.).

**Comment by razzeee** [comment]
Well it was confirmed working here
https://github.com/Razzeee/script.trakt/issues/181

Can you attach a logfile?

**Comment by war59312** [comment]
Whoops, forgot all about this, sorry. Will upload a log when I get to the house.

Thanks.

**Comment by war59312** [comment]
As promised.

Log: http://xbmclogs.com/pq5rtxszk

**Comment by razzeee** [comment]
I'm not sure if you have configured kodi/trakt correctly for logfiles see https://github.com/trakt/script.trakt#creating-logfiles

**Comment by war59312** [comment]
I had done exactly that.

Rebooted Kodi after turning on debug in both Trakt and Kodi.

But I'll get you a new log tonight.

Edit:

New Log @ http://xbmclogs.com/pqbifxfjg

See lines 990, 1134, 1135

**Comment by war59312** [comment]
Um. Odd. Not sure why my log got deleted. Bad website, bad!

**Comment by war59312** [comment]
No Proxy Debug Log: http://xbmclogs.com/pel5vs6nr

Proxy Enabled Debug Log: http://xbmclogs.com/ptkknqqen

So you can compare.

I still don't see any trakt debugging info. So looks like trakt debug option is not working with 16.0.

I turned on all the new component level debugging for this log: http://xbmclogs.com/pjtykrtko

Perhaps this error below gives a clue to why no log?

"ERROR: No handlers could be found for logger "traktapi""

**Comment by razzeee** [comment]
Any changes here? Are you able to provide working logfiles now? :)

**Comment by war59312** [comment]
Sorry, been busy. Will see if I can test next weekend for you.

FYI: Last I tried, a few weeks ago, this same issue still applied.

**Comment by razzeee** [comment]
Did you end up testing this?
