### ISSUE TITLE
Can't install on OpenElec 6.0 / Kodi 15.2

### ISSUE THREAD

**Issue by gcleaves** [razzeee/script.trakt#253]
I had this working on a previous version of Kodi but can't install since upgrading. When I install from repository I just get a message saying "Install failed." When I try installing from the zip downloaded from your .md file, Kodi complains "Add-on does not have the correct structure."

I love the functionality this add on provides. Any help installing would be very appreciated!

**Comment by razzeee** [comment]
Please only try to install via the repository.

Just checked, that it works for me. You'll need to post a debug log, for more help.

**Comment by gcleaves** [comment]
Reboot seems to have fixed. Sorry for the false alarm.
