### ISSUE TITLE
Media played from widgets does not get marked as watched. 

### ISSUE THREAD

**Issue by jctennis** [razzeee/script.trakt#255]
When playing a media file from the Kodi home screen widget, there is no scrobbleing done to Trakt.tv. When playing the exact same file from the library everything works as expected.

**Comment by razzeee** [comment]
Working fine here, tested with Kodi 17 and Trakt 3.0.6 (3.0.5) should be similar.
If it's not working, it will probably be down to the Kodi version your using.
