### ISSUE TITLE
Episode not marked as watched

### ISSUE THREAD

**Issue by HydrelioxGitHub** [razzeee/script.trakt#256]
I use Kodi on an Android TV (Nvidia Shield). I notice that when I watch several tv shows episode in a row (using inside feature) only the last episode is marked as watched on Trakt. 

For exemple if I watch episode 4, 5 and 6 of a show only the 6th will be watched on Trakt. (Sorry for my English)

**Comment by razzeee** [comment]
What's inside feature?

**Comment by HydrelioxGitHub** [comment]
Feature that read the next episode without having anything to do. (Up next)

**Comment by war59312** [comment]
I beleive he's talking about this:

http://forum.kodi.tv/showthread.php?tid=228435

**Comment by razzeee** [comment]
Well if he is, it's setting the correct watched flag in kodi and will sync it fine. Everything else is a problem of that script not handling the end of an episode correct.

**Comment by HydrelioxGitHub** [comment]
Yes I am talking about that. I didn't figure out it was an add-on. Sorry for the misunderstanding

**Comment by HydrelioxGitHub** [comment]
So the problem is coming from that add-on and not from the trakt one ?

**Comment by razzeee** [comment]
Correct, it's skipping the current episode in a "weird" way.
