### ISSUE TITLE
episode not marked as watched in kissanime

### ISSUE THREAD

**Issue by c-h-u-c-k** [razzeee/script.trakt#258]
Hey there, seems to work great for  everything but the kissanime add-on, which has really improved. I enabled extra metadata as well as the anidb TV info add-on, so the stream shows the proper metadata, but I can't get trakt to scrobble.  Thanks

**Comment by razzeee** [comment]
You might want to reach out to the author of that and hand em this url https://github.com/trakt/script.trakt/wiki/Providing-id's-to-facilitate-scrobbling
Not much we can do about it
