### ISSUE TITLE
trakt not working in kodi

### ISSUE THREAD

**Issue by afonsorp** [razzeee/script.trakt#260]
Hi, 
in the last couple of days trakt is not working. i’m using kodi (openelec in raspberrypi). 
Went for the logs and found this:

11:32:55 979.024231 T:1650631744 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- 
NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! 
Error Type: <type 'exceptions.ImportError'> 
Error Contents: No module named trakt 
Traceback (most recent call last): 
File "/storage/.kodi/addons/Razzeee-script.trakt-64ca297/default.py", line 6, in <module> 
from service import traktService 
File "/storage/.kodi/addons/Razzeee-script.trakt-64ca297/service.py", line 6, in <module> 
from traktapi import traktAPI 
File "/storage/.kodi/addons/Razzeee-script.trakt-64ca297/traktapi.py", line 5, in <module> 
from trakt import Trakt, ClientError, ServerError 
ImportError: No module named trakt 
-->End of Python script error report<—

**Comment by razzeee** [comment]
Please uninstall and reinstall from the official kodi repo. Seems like you installed by zip file?

**Comment by afonsorp** [comment]
i tried that already :/
the same problem:
"Error Contents: No module named trakt"

**Comment by afonsorp** [comment]
Sorry, closed the issue by mistake!

**Comment by razzeee** [comment]
Can you post a full logfile via pastebin or xbmclogs?

**Comment by afonsorp** [comment]
ok, i'll do that as soon as i leave work

**Comment by afonsorp** [comment]
@Razzeee , here is the full log file:
http://xbmclogs.com/pbikacfuq

**Comment by razzeee** [comment]
sorry, please activate logging first https://github.com/trakt/script.trakt#creating-logfiles

**Comment by afonsorp** [comment]
sorry, my bad.
updated: http://xbmclogs.com/pufzikbrc

**Comment by razzeee** [comment]
That logfile still looks wrong, do you have both settings activated?

**Comment by afonsorp** [comment]
hmm, yes.
Activated kodi and trakt debug

**Comment by afonsorp** [comment]
do you need me to do something else?

**Comment by razzeee** [comment]
I can't tell anything from that logfile. Please make sure you have both log options activated and maybe restart your box before creating the logfile. 
You will have letters in the top left with some cpu data etc.

**Comment by afonsorp** [comment]
yes, i had those letters with some info. i also restarted before creating the log file.
Not sure why don't have more info :/

**Comment by razzeee** [comment]
And you also went into the script.trakt settings and activated logging there?

**Comment by afonsorp** [comment]
yes, i also did that.
is it possible that, somehow, when i was trying different installs (.zip and repository) i ended up with two different versions activated?

**Comment by razzeee** [comment]
Yes, very likely. If you really installed from zip, there might be a script.trakt folder and a script.trakt-master folder depending on what you downloaded. You should remove both and install from repo again.

**Comment by war59312** [comment]
+1

Hey,

Same issue here on my Nvidia Shield. Broken in last 48 hours. 

Never installed from zip, just from repo.

Looks like it tries to work as it causes Kodi UI to freeze (not respond to controller input) for over 3 minutes while it tries to do its thing. That really needs to be fixed. Very annoying.

That said, need to do further testing as it could be this special build of Kodi I'm running. Will test with release version when I arrive back at the house later this evening.

Just that I noticed it last night when watch NCIS. Trakt never saw both episodes. Was fine Sunday.

And of course I will give a full debug log.

Thanks,

Will

**Comment by razzeee** [comment]
Just tested on my shield running script.trakt 3.0.7 and the latest kodi nightly as of today (v17) and can't replicate any of your pains :/

**Comment by war59312** [comment]
And of course I get home and it's working again. :)

So must have been on trakt's end.

Will see if I can duplicate the UI Freezing.. Will open new issue if so.

Thanks.

**Comment by afonsorp** [comment]
hey, I've repeated the process.
Hope this can give you something more to work on:
http://xbmclogs.com/pspdkvf78

Thanks

**Comment by razzeee** [comment]
That log has the same problem. I'm completely in the dark.
Can you remove anything with trakt in the name from your addon folder?
Then please check if you have the official repo installed and install script.trakt from there only.

**Comment by afonsorp** [comment]
I looked every files with trakt in their name.
removed them from my system. 
Reinstall from repo.

This made it work again. Not sure what made him stop in the first place though.

Tks Razzeee

**Comment by razzeee** [comment]
Good to hear!
