### ISSUE TITLE
scrobbling after some watched time in a movie

### ISSUE THREAD

**Issue by dmnc-net** [razzeee/script.trakt#261]
Likewise a rating dialog, scrobbling should start after some time spent in a movie (real time, don't mean after some percentage of duration which can be achieved quickly by seeking). Delay in minutes is fine but not the best option.

**Comment by razzeee** [comment]
Not sure start your trying to say

**Comment by war59312** [comment]
These delay options seem to do nothing in Kodi 16 by the way. No delay no matter what the settings I try.

Once debug logging is fixed, see https://github.com/trakt/script.trakt/issues/252, I will post full debug log.
