### ISSUE TITLE
Trakt fails to add or remove TV show and movies from collection.

### ISSUE THREAD

**Issue by jhall13614** [razzeee/script.trakt#262]
When I right click on an movie or TV show in genesis and select trakt manager and add to collection i get a response in the bottom right saying that it failed.

here is a link to my logfile
http://goo.gl/sQ6T0u 

Thanks in advance for any help

**Comment by razzeee** [comment]
Sorry, but you are not even using this addon, as it's not in your logfile.

**Comment by jhall13614** [comment]
Here is this logfile. I actually open up my Trakt collection first and tried to remove items. Then I left and tried to add some. 

http://goo.gl/K7fpcd 

hopefully this helps, because i can get my Trakt collection I just cant add or remove anything.

**Comment by razzeee** [comment]
You still don't have this addon installed.

**Comment by jhall13614** [comment]
http://goo.gl/SXAXgV

sorry. i just realized what you meant. I installed it and authorized it then did the same thing.

**Comment by razzeee** [comment]
Well if you had that option before, it is not part of this addon. I suspect it being a Genesis function.

**Comment by jhall13614** [comment]
OK. I can add to collection from the Trakt site and it still doesnt add on genisis so i guess that makes sense. it just sucks.

**Comment by jhall13614** [comment]
thanks for trying
