### ISSUE TITLE
Scrobbing Locks Up Kodi 16.0 UI

### ISSUE THREAD

**Issue by war59312** [razzeee/script.trakt#263]
Hi,

If scrobbing for whatever reason takes a while it locks up the UI until the scrobbing successfully completes.

That is, the video keeps playing fine, but most button controls are ignored and you can not bring up the "info screen". Not sure what that screen is called. The normal screen that is shown when you pause a video.

Once the scrobbing completes then control is returned asap. You can open the "info screen" again. I've seen it take 2 minutes before.

More often than not "Working" overlay is displayed the entire time trakt is trying to do scrobbing in the bottom right of the screen.

For one the UI should not "lock up". As in should still be responsive to controls. The loading overlay should not be shown and it should have a reasonable timeout. Say 10 seconds. Just try again later say in 60 seconds, then again in 5 minutes, then 10, etc.

Will try and get a log next time it happens. But see other post https://github.com/trakt/script.trakt/issues/252 , trakt debug is not working.

This is on an Nvidia Shield. Latest public firmware.

Thanks,

Will

**Comment by robotard** [comment]
Not sure if related, so feel free to branch to separate ticket, but no longer see rating screen after viewing a tv show in Kodi 16 (downloaded today)

**Comment by razzeee** [comment]
Haven't had any of those problems so far on my shield.

**Comment by robotard** [comment]
Freebox mini 4K exhibits no sync, and my MacBook too

**Comment by razzeee** [comment]
@robotard 
logfile please. And open your own issue :)

**Comment by war59312** [comment]
Only seems to happen if for whatever reason Trakt takes awhile to respond.

Still happens with 16 RC1 as well.

Guess a good way to duplicate is to limit bandwidth to keri to say 56k speeds.

Thing is, it is in fact scrobbling basically instantly as expected as it shows up on trakt page instantly.

It's just the ui failure. And not a skin problem either as it happens with default Confluence skin.

Another attempted debug log: http://xbmclogs.com/p64pemszb

Edit: Why do my logs keep getting deleted. Default is 2 weeks. WTF!

Looks like debugging in 16 RC1 finally works. :)

Edit: Well just as bad on 16 RC 1. Bummer!

Does NOT matter if scrobble notifications are enabled or not. Happens either way.

Happens with SPMC 16.1.1 as well. Sucks!

**Comment by war59312** [comment]
Ok happens without even trakt installed. So looks like its Kodi issue after all.

Just happened with trakt even more so.
