### ISSUE TITLE
Rating Dialog not triggering for streams or .strm files

### ISSUE THREAD

**Issue by agoMiST** [razzeee/script.trakt#269]
The rating dialogue no longer triggers in Kodi when watching streams or .strm files.

It functions as it should for local video files, so it's not completely broken.

I'm running Kodi 16.0 Jarvis on a Nvidia Shield TV, which I only set up on Sunday, however I didn't watch a film (I only rate them) until after the Trakt add on update, so I don't know if this issue was present before the update or new to the update.

Kodi Log: http://xbmclogs.com/p1bpc98mg
(Episode rating switched on, using SALTS to access my collection via Trakt, one episode watched, Scrobbled successfully, rating dialog failed to activate)

**Comment by thwaller** [comment]
this could be closed with the release of 3.1.3? This issue appears corrected.
