### ISSUE TITLE
Trakt Features no longer working on Kodi

### ISSUE THREAD

**Issue by unsunghero** [razzeee/script.trakt#270]
I contacted trakt.tv directly regarding and issued that has started around a month ago.  They have directed me here and asked me to post my log file, I explained that I am new to this and unsure what my log file is and where to get it.

Firstly can somebody confirm, is this the log file accessed in Kodi via... System> File Manager> Add Source> special://logpath?

Secondly and the main issue, Both Kodi and Trakt plugin have worked smoothly until around a month ago.  This is the feature I usually use:  Open Kodi> Genesis> My Genesis> Trakt: Episodes.  Usually at this point an up to date list of my latest episodes are displayed, the ones I've already watched are ticked.

About a month ago, this list would no longer load and neither would any of the other lists within My Genesis, other than Trakt: Episodes.

Thank you in advance

**Comment by razzeee** [comment]
Sorry, this is not a Genesis support site. That's a different addon.

**Comment by unsunghero** [comment]
The problem is with Trakt, not Genesis.  If you read above, support from Trakt.tv have listened to the problem and suggested posting here.

**Comment by rectifyer** [comment]
It does appear this is a Genesis issue based on the menu item you indicated. I don't recall the original support ticket exactly, but I must have either overlooked or not seen the part indicating this was related to Genesis. I'd recommend reaching out directly to them.
