### ISSUE TITLE
Not scrobbling status for homescreen widgets.

### ISSUE THREAD

**Issue by thricerocks86** [razzeee/script.trakt#272]
After several tests, I found that the widgets are causing the problem with sync issues. It seems like a lot of people probably do not realize only the widgets are not scrobbling. If I watch an episode from my library folder scrobbling works fine, but through any widget it does nothing. It also works within addons that I have authorized. I tried this on all the 3.x versions available in the repo with the same results.

**Comment by razzeee** [comment]
Working fine here. I've been watching stuff from the home screen only since month.

**Comment by thricerocks86** [comment]
What skin are you using? Maybe it is skin dependent, I'm on mimic.

**Comment by razzeee** [comment]
I'm using estuary

**Comment by thricerocks86** [comment]
I'm talking about playing directly from widgets. Estuary widgets take you directly into the season view, so you aren't actually playing from the widget.

**Comment by razzeee** [comment]
@thricerocks86 
I don't think recently added episodes do that, they just start playing.

**Comment by irn-bru** [comment]
I just wanted to add that it's not working for me either. I'm using the Aeon Nox 5: SiLVO skin on Jarvis 16.0 and playing from the home screen latest episodes widget doesn't scrobble. It's not a massive problem -- would be great if it worked obviously -- but I did want to make a note of it in case others had the same issue.

I'll go ask Mike on the skin's forum thread and see if it's a known issue.

**Comment by thricerocks86** [comment]
Yeah, the app only seems to get tested on the default skin... So I would stick to using it. It's estuary for the newest beta right now.

**Comment by razzeee** [comment]
It's likely, that those skins use an addon to generate that homescreen and that addon seems to not set the needed data for script.trakt.
Never had such issues, when using arctic zephyr, which uses BigNoids service.library.data.provider

**Comment by razzeee** [comment]
I'll close this as this seems to be stuck in limbo, if you have new infos, please feel free and post them.
