### ISSUE TITLE
Plugin scrobbles wrong user

### ISSUE THREAD

**Issue by CoryAlbrecht** [razzeee/script.trakt#277]
We have two profiles in Kodi and the Trakt was configured on each to a different Trakt account. Or so we thought. However, a sign in/connecting on one profile appears to disconnect the other, and the plugin then scrobble watches on _both_ Kodi profiles to the most recently connected Trakt account.

**Comment by razzeee** [comment]
As far as I remember this is a problem in Kodi itself not shutting down the addon correctly. I will try to have a look at the core, but it might take a while to find/fix this.

**Comment by razzeee** [comment]
For reference http://trac.kodi.tv/ticket/16280

**Comment by razzeee** [comment]
Closing, let me know if it still happens
