### ISSUE TITLE
Bookmarks sync

### ISSUE THREAD

**Issue by thwaller** [razzeee/script.trakt#279]
I have tried using the sync of bookmarks, but it only works to copy/sync _to_ Kodi. I tried to clear the bookmarks data in the DB, and enabling this feature re-populates the old data. Is there a way to sync _from_ Kodi _to_ Trakt? Or is there a way to manipulate this data from Trakt.tv? I do not know where the data being populated came from, but it is not valid, thus not allowing the use of this new feature.

**Comment by razzeee** [comment]
The get set on trakt automatically if you scrobble something and stop somewhere in between. As far as I know there is no frontend on trakt to access those.
Only @rectifyer will know more.

**Comment by rectifyer** [comment]
This is for the playback progress? If so, then yeah we don't have a way to manage those on the website. Its on my task list as something to look into, just hasn't been a very common thing user's have requested.

**Comment by thwaller** [comment]
Yes, this is the playback progress that is stored in the local bookmarks database for Kodi. The latest revisions of Trakt addon sync the playback progress. The issue I am having is that I can clear the local bookmarks, or playback progress, and with the feature enabled on Trakt addon, Trakt will continually repopulate the bookmarks I have deleted with the progress it has stored at Trakt.tv.

Where my problem is starting....I will often watch a small portion of a movie, especially when verifying that the scrapers and Trakt have matched it up to the correct cover and IMDB/TMDB/TVDB id. With this, it seems to scrobble and record the playback progress. I just wipe these out locally as they are not "real" watches. Given this, I have found the easiest way to avoid this is to disable the new playback progress sync features.

Is there another way of doing this? I know this is a new feature and @rectifyer is working on stuff at his end (understandably low priority), so maybe just in my case it is best to disable for now?

**Comment by thwaller** [comment]
Is disabling the progress in Trakt as simple as disabling scrobbling and just having the watched flag sync?

**Comment by thwaller** [comment]
I have also noticed that SALTS has a "use trakt bookmarks" feature. I can see a use to this with other addons using that. The local bookmarks are not so universal as to be used across all addons. Trakt will have a bookmark for a specific movie or tv show itself, where Kodi will have it for a specific file. One good feature of Trakt and its associated addon is that once a movie is watched, the syncing marks all copies of it locally watched, whether a local file or a stream file.

**Comment by thwaller** [comment]
I closed this issue as I do not believe there is a bug here, nor is it a feature request for the addon.
