### ISSUE TITLE
Userrating box not appearing

### ISSUE THREAD

**Issue by thwaller** [razzeee/script.trakt#280]
This issue is with addon v3.1.3 on Kodi 16. I have found an instance where the rating selection does not appear after viewing. I streamed a tv show from Genesis. The play appeared on Trakt, but it never asked for a rating. Here is a piece of the log from that time:

23:10:24 T:2729384768  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.8.2
23:10:25 T:2729384768   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
23:10:25 T:2729384768  NOTICE: metahandler: No SQLite rows requiring update
23:10:25 T:2771348288   ERROR: /home/brian/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
23:10:26 T:2771348288   FATAL: [script.trakt] service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'KeyError'>
                                            Error Contents: ('id',)
                                            Traceback (most recent call last):
                                              File "/home/brian/.kodi/addons/script.trakt/service.py", line 42, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/home/brian/.kodi/addons/script.trakt/scrobbler.py", line 235, in playbackEnded
                                                self.__scrobble('stop')
                                              File "/home/brian/.kodi/addons/script.trakt/scrobbler.py", line 275, in __scrobble
                                                response['episode']['episodeid'] = self.curVideo['id']
                                            KeyError: 'id'
                                            -->End of Python script error report<--

The "memory leaks" portion is appearing numerous times throughout the log.

**Comment by razzeee** [comment]
@tknorris 
Not sure if we missed something

**Comment by thwaller** [comment]
Let me know if I can provide any more info. I am testing right now further. The progress bar is working on Trakt.tv, so that part works. I will try and collect as much detail as I can to help. This was working yesterday, so as there has not been an update, I will test multiple addons and local files to see if there is a pattern.

**Comment by thwaller** [comment]
Test just done with SALTS. Tv show completed, returned to the episode list in Kodi. After a short wait, the "watched" check appeared as is expected with SALTS. The rating dialog never did appear. This tv show is a SALTS episode and played with SALTS. The use alternate addon option was not used.

Prior to tracking every play for this, there were some in which the "watched" flag was not set locally or on Trakt.tv. I had to manually set it to watched.

Second test for Genesis. Same as above except the "watched" flag was immediately set. No rating dialog. This behaviour differs from yesterday.

**Comment by tknorris** [comment]
Bleh, yeah, I missed something. I had scrobbling turned off when I tested so that method didn't execute. I'll  commit a fix in a sec.

**Comment by tknorris** [comment]
https://github.com/Razzeee/script.trakt/pull/238 submitted for this.

**Comment by thwaller** [comment]
Looks like I have missed the same, the scrobbling on vs off. At least this explains the working / not working from day 1 to day 2.

**Comment by thwaller** [comment]
@tknorris ok to use from your page? I tried it and still have issues.

SALTS library item, alternate addon Exodus, SALTS sources kept failing. Scrobble not appearing on trakt.tv. Did nor show up as watched on trakt.tv or marked watched in Kodi. Manually ran the addon, appeared as watched on trakt.tv. Manually set the rating.

**Comment by tknorris** [comment]
Exodus doesn't use the trakt addon for scrobbling. It does it's own internal scrobbling, so if you are having problems w/ not seeing scrobbles it's an Exodus issue, not a trakt addon issue.

**Comment by thwaller** [comment]
I see. I will load the one you have modified a few hours ago and try again. Exodus has a few weird issues, I have no doubt you are correct. If I remove my Trakt authorization, would it then use the addon?

**Comment by thwaller** [comment]
@tknorris Is there a proper setting for SALTS to work with the addon, if that is possible, to avoid any issues? I ask as it does relate to this program and I know you contribute on SALTS as well. Want to ensure my resting is done with the right settings and knowledge of the workings.

**Comment by tknorris** [comment]
if you use SALTS with the trakt addon authorized, it should scrobble to trakt as needed and pop-up the ratings dialog as configured.

**Comment by thwaller** [comment]
SALTS 2.0.13 with the Trakt addon 3.1.3 (from your page with today's mod) is marking watched and scrobbling (showing the progress on trakt.tv), but is not showing the dialog to rate. IS this a trakt addon issue or a SALTS issue? Trakt is authorized in SALTS and addon is configured as well. In SALTS config, there is no option I can see to enable rating dialog upon completion. I will also test on 1Channel.

**Comment by tknorris** [comment]
The rating dialog pop-up is configured in the trakt addon, not SALTS

**Comment by tknorris** [comment]
I just reconfirmed for me that I am getting ratings dialogs w/ scrobbling turned on via playback from SALTS using my updated script.trakt code. If you can't get it working, a log showing playback stop from SALTS w/ debug turned on and "Enable debug mode" turned on in the trakt addon would help.

**Comment by thwaller** [comment]
I will have to get you a log. SALTS does not work, 1Channel errors out and directs to look at the log and I will test Genesis next. Although discontinued, it still gives the least problems and worked fine yesterday. One thing I can add is that I manually end the playback via the "x" key. I do not let the ending credits play out.

**Comment by tknorris** [comment]
That shouldn't matter, that's the same way I'm testing.

**Comment by thwaller** [comment]
Ok, I have a log file generated for you. A fresh open of Kodi, navigate direct to the stream from a SALTS library item, played the selection, used "x" to end at the start of credits and waited until the watched check was displayed in Kodi, approx 30 seconds or so. No ratings dialog displayed.
[kodi.old.log.txt](https://github.com/trakt/script.trakt/files/160067/kodi.old.log.txt)

I did not look at the log, so if there is anything personal, please make sure it is removed. I just wanted to get you data on this quickly.

**Comment by tknorris** [comment]
According to this log you are not running the code from my github. Your log shows:

```
File "/home/brian/.kodi/addons/script.trakt/scrobbler.py", line 275, in __scrobble
    response['episode']['episodeid'] = self.curVideo['id']
KeyError: 'id'
```

But that output doesn't match the code that's in my github.

**Comment by thwaller** [comment]
Hmm, that is the ZIP I downloaded from https://github.com/tknorris/script.trakt

**Comment by tknorris** [comment]
I didn't bump the version number so kodi probably installed from the package cache rather than the zip you downloaded.

**Comment by thwaller** [comment]
How can I correct that? I selected install from ZIP and selected the download. I could install a prior version, then the ZIP?

**Comment by tknorris** [comment]
Try deleting all the zip files in .kodi/addons/packages then reinstalling the zip you downloaded.

**Comment by thwaller** [comment]
Ok, can I verify that it is correct before proceeding again?

**Comment by tknorris** [comment]
you can check addons/script.trakt/scrobbler.py line 275 matches what's in my github: https://github.com/tknorris/script.trakt/blob/master/scrobbler.py#L275

**Comment by thwaller** [comment]
Ok, no, it did not update. That line does not match. I will just replace that file.

**Comment by thwaller** [comment]
I can visually see it is changed now. I believe this may have been an issue for a bit. When I select a file to install, I was sort of expecting Kodi to install that file and its contents as instructed, not use files it was not told to use. I also ensured Auto-Update is turned off. I will no longer be trusting Kodi to do as it says, it clearly does not.

**Comment by razzeee** [comment]
@thwaller 
it's more a github problem then a kodi problem. Github zips the files like this: script.trakt-master
So if you install that from zip and have had script.trakt installed before, it won't replace the old script.trakt folder but create a new one which is named script.trakt-master. Kodi is now faced by two addons trying to register as the same addon and probably chooses the first it hits. And that's the old one.

**Comment by thwaller** [comment]
I see. Is there a suggestion to keep all in the same folder, and not create different folders for the same addon? I would like to be sure the proper folder is being used. Having 2 that you assume one is being picked is questionable. This would explain some issues with multiple addons I have tried to install from GitHub with. Manual is always an option I guess.

**Comment by razzeee** [comment]
Edit the zip files you download and remove the - branchname not much you can do about the rest.

**Comment by thwaller** [comment]
With the files from tknorris, I would call this completed. I believe there still may be an issue with 1Channel and Trakt working together, but I believe it would be better as a separate post or maybe even at the 1Channel GitHub.
