### ISSUE TITLE
Keep watched statuses synced between Kodi and Trakt?

### ISSUE THREAD

**Issue by rfgamaral** [razzeee/script.trakt#282]
This is more like a question and somewhat a feature request... Not exactly for "Keep watched statuses synced between Kodi and Trakt" because I know that's already implemented.

My question is, how does this feature work and when it's executed? On each library update? Periodically? On any other action? Does it sync **everything** on both databases or does it filter somehow what to sync?

Here's my use case scenario so you understand my problem:

I had Kodi synced with Trakt before I left on a business trip where I took some episodes of a particular show with me to watch during flights. This were obviously not synced because I had no Internet connection during flight. When I got access to an Internet connection, I manually set the watched status for the particular episodes on Trakt.tv website. When I got home, I launched Kodi and manually invoked the sync action within this plugin - to get my watched status from the watched episodes on the flights.

This worked, but a) I shouldn't need to do this manually and b) it raised another issue...

I have another TV show fully marked as watched on Trakt but I'm currently re-watching it (from the very beginning) with my girlfriend who never saw this particular old TV show. When I invoked the sync action from the plugin, all the episodes from all seasons were marked as watched on Kodi. How could I possibly prevent this?

Perhaps - not sure if it's a good idea or not - add an option to prevent syncing watched statuses between Kodi and Trakt **if** a particular show _has ended_ **and** is _100% watched_? Not sure if there's a better way to differentiate this...

Thoughts on this? Or is there anyway I could have prevented this already?

**Comment by thwaller** [comment]
There is an option you can deselect called "Mark ___ from Trakt history as watched in Kodi" on the synchronize tab of the addon settings. Is that what you are looking for? In Kodi, you could then "mark as unwatched" and start over. In Trakt, it should count them as a second play for all the episodes.

**Comment by razzeee** [comment]
No, there is no solution around for that usecase. I even see setting the watched status in Kodi to unwatched as false, as it obviously shouldn't be unwatched in your profile.

**Comment by rfgamaral** [comment]
> There is an option you can deselect called "Mark ___ from Trakt history as watched in Kodi" on the synchronize tab of the addon settings. Is that what you are looking for?

But I actually want that feature because of the scenario I just mentioned above. I marked the episodes as watched directly on the website and I need them synced back to Kodi.

> I even see setting the watched status in Kodi to unwatched as false

Not sure what you mean by this...

Well, I marked one full season as unwatched on Kodi and it hasn't synced to Trakt. Trakt remains with the all the seasons watched. Let's see if Kodi gets synced back to watched if I don't explicitly invoke the sync action.

**Comment by razzeee** [comment]
Then make sure it doesn't sync on library update.

**Comment by rfgamaral** [comment]
But syncing is one of the features of this plugin that I like... :(

I don't usually watch too many stuff outside of Kodi, but when I do, I really didn't want to be bothered with syncing watched statuses.

I guess there's no way around this...

**Comment by razzeee** [comment]
Well it would sync pretty much automatically due to the library update. But your set something as unwatched but only in kodi, breaks our logic.

**Comment by rfgamaral** [comment]
Ok. Thanks.

**Comment by MYeager1967** [comment]
I can't get the sync to work at all. Watching something on one instance of Kodi isn't marking it as watched on the other.
