### ISSUE TITLE
Dependencies not met. Please contact add-on author

### ISSUE THREAD

**Issue by Wireless-Mind** [razzeee/script.trakt#283]
[](url)All of a sudden my Trakt.Tv add-on for Kodi (v15.2) is displaying message, "Dependencies not met. Please contact add-on author. When I look in Programs and Repositories I can not find the Trakt add-on to install. Therefore, I downloaded "trakt-script.trakt-3.1.2-0-g0df4d1c.zip" and "script.trakt-master.zip files and attempted to install each. However, I received the same :Dependencies not met error message for both install attempts. Please let me know what I have to do to get this add-on reapplied/installed. I have ttached is URL link to my log files, perJustin Nemeth.
[http://xbmclogs.com/pv86brdv](url)

**Comment by razzeee** [comment]
15.2 is not able to run anything newer than 3.0.7 so you should remove all you have installed right now, best do this from outside Kodi. Then install again from inside Kodi and the official Repo.

**Comment by Laaderlappen** [comment]
I removed all trakt folders from the kodi main folder and still get dependencies not met.

Perhaps you could provide us with the 3.0.7 zip so we can install trakt again,  because the addon is missing from the kodi repo.

**Comment by thwaller** [comment]
https://mirror.umd.edu/xbmc/addons/isengard/script.trakt/ (this one I used for testing)
https://github.com/trakt/script.trakt/releases/tag/3.0.7 (source)

**Comment by Laaderlappen** [comment]
Thanks! I found it like 2 mins after posting The message, 3.0.7 installed and tested with no problems, all is working fine now.

Thanks again!

**Comment by dome115** [comment]
hello can someone help me to install the 3.0.7, how do I delete the original files and install the new once so I stop receiving the  "Dependencies not met. Please contact add-on author.

**Comment by thwaller** [comment]
Download the 3.0.7 (https://mirror.umd.edu/xbmc/addons/isengard/script.trakt/) fro a source of your choice. Once you have the zip file, in Kodi, go to System -> Settings -> Add-ons. Select "Install from ZIP file" and browse to where you saved it. Click on "Ok" and it will install the file.

Once done, you should verify the version by looking in the add-ons listing, it will be in the Program Add-ons section.

**Comment by dome115** [comment]
https://github.com/trakt/script.trakt/releases/tag/3.0.7 (source) what about this file?

**Comment by dome115** [comment]
thank you

**Comment by thwaller** [comment]
To manually delete the existing files for the addon, go to your Kodi folder. In Ubuntu, it is Home -> .kodi -> addons. You are looking for folders 1) script.trakt and/or 2) script.trakt-master. Deleting them (one or both depending on what you have) will delete the files currently installed. I am unsure if the settings will go away as well so be aware.

While in the above folder (addons), there is a folder called "packages". In that folder, you can also delete the corresponding ZIP files of the folders you deleted above. That deletes the ZIP of what was installed previously. There may or may not be a ZIP file there for them.

I am unsure of the "official Repo" to get version 3.0.7, but the link I provided works for me. My apologies for sending to a non-official Repo.

**Comment by dome115** [comment]
ok thank you I will do all that and will let you know..

**Comment by thwaller** [comment]
Regarding the source file link, I am unsure. I do not know if that is the same or not, I have not used it. The ZIP I used is from the umd.edu URL.

**Comment by dome115** [comment]
i only just received the box it was working then it started with all the above.. not sure how to do it all, i cant find the KODI files you mentioned, can i call you and you can run me through it if you have time..?? is that possible

**Comment by dome115** [comment]
i will need to contect the box to my computer, is that batter?

**Comment by dome115** [comment]
DVB link connection los
DVB client view lost
Angus TV client lost
Media Portal
all these pop ups are continuously happening, how can i fix this up please

**Comment by thwaller** [comment]
It sounds like you have more issues than just with the Trakt addon. You may want to start a ticket for your exact issues. This topic is only to resolve the issue of running Trakt on v15.2 of Kodi. The Trakt addon scrobbles and tracks plays to the trakt.tv web site only.

**Comment by Wireless-Mind** [comment]
Thanks everyone I got Trakt.tv  addon to work by uninstalling the updated Trakt addon and installing Trakt.tv v3.0.7 zip as recommended by Razzeee  using the link(s) provided by Thwaller in this thread.  I appreciate everyone's assistance.

**Comment by rectifyer** [comment]
Any ideas why v3.0.7 doesn't show up in the official repo for Kodi 15.2?

**Comment by razzeee** [comment]
Just tied it with a 15.2 installation, everything listed and installing fine.
![image](https://cloud.githubusercontent.com/assets/5943908/13937819/71b5c29e-efc8-11e5-9e8d-5cd3e0185689.png)

You can also see here that it's listed http://mirror.de.leaseweb.net/xbmc/addons/isengard/addons.xml
