### ISSUE TITLE
No User Rating Box Appears After Watching Episodes

### ISSUE THREAD

**Issue by MBooysen** [razzeee/script.trakt#284]
Hi,

I'm new here so apologies if im doing this wrong.
My Issue:

Since about 3 weeks ago i am not getting the Trakt User Rating Box After Watching Episodes and the "tick" on my watched episodes are not there or showing my watched episodes. I am using SALTS latest version that updated from tknorris beta repo and also the lastest Trakt update.

Any comments in resolving this would be appreciated.

Regards,
Mark

**Comment by thwaller** [comment]
This issue appears to be fixed on the latest update found here:
https://github.com/tknorris/script.trakt
I am using this version and all works with the latest version of SALTS v2.0.14. The ZIP file there does not bump the revision of the Trakt addon, at 3.1.3, so you will need to be sure that the new files are added. If you look at tknorris's beta repo, https://github.com/tknorris/script.trakt, there is a version 3.1.4-alpha1 there, I think that would be the same or further improved from the first link.

**Comment by MBooysen** [comment]
MANY Tx thwaller!! That seems to have done the trick. 

Cheers and Have a Good one!!!

Mark

**Comment by MBooysen** [comment]
Hi thwaller.

Ive just reopened the issue. Ive noted that although the Rating Box has returned and you can now rate episodes it does however not put a watched "tick" next to the episode as watched.

Did i do someting wrong?

Many Tx,
Mark

**Comment by thwaller** [comment]
When using SALTS, give it a bit for the check mark to appear to indicate watched. You are giving it time to send the watched flag to Trakt, then it syncs back to Kodi. You can test this by either checking back in  about a minute or so or just wait at the screen and it will appear on its own. I attempted to find my post where this was explained to me but could not quickly find it.

**Comment by thwaller** [comment]
Genesis and 1Channel appear almost immediately, SALTS requires the short wait as it works through Trakt first and Exodus does not work at all at this time (at least for me). It was explained to me that Exodus does not use the Trakt addon for this and does it on its own, so it is a Exodus issue.

**Comment by MBooysen** [comment]
Tx thwaller!!! You were 100% correct. I gave it a couple of seconds and the tick apeared. MANY thanks for your assistance much appreciated.

Keep well!!
Mark
