### ISSUE TITLE
[Feature request] Trakt.tv ratings visible as hearts on posters.

### ISSUE THREAD

**Issue by MeDeVILe** [razzeee/script.trakt#285]
Would be nice to have something similar to 
![rating](https://cloud.githubusercontent.com/assets/6697190/13620012/c3a8c2d6-e58c-11e5-8c4e-51aaed123a70.jpg)
![rating1](https://cloud.githubusercontent.com/assets/6697190/13620013/c3ab2454-e58c-11e5-9d56-6fe29c1222c3.jpg)

Is it possible or does it have to be implemented in skin?

**Comment by razzeee** [comment]
Yes, that's the skins work. If you want to get the ratings from trakt, there will hopefully soon be a scraper for that again. You can preview it here: http://forum.kodi.tv/showthread.php?tid=259457&pid=2273187#pid2273187
