### ISSUE TITLE
Switch to device auth (instead of PIN auth)

### ISSUE THREAD

**Issue by rectifyer** [razzeee/script.trakt#286]
A few weeks ago we added an easier authentication method for devices. This replaces PIN auth and is much simpler for the user since there is no specific PIN url and no text entry needed in the Kodi plugin itself. I'm sure this is already on the radar, but I just wanted to post so we can discuss.

**API docs:**
http://docs.trakt.apiary.io/#reference/authentication-devices

**Code example:**
https://github.com/tknorris/salts/compare/3a372bbd6bda8bb033bdba90b6efc0cb99c5a36d...ce9421922929c6f8458e3ede1e609abb2dc20f15

**Comment by razzeee** [comment]
Waiting for fuzeman to say he's done with testing. https://github.com/fuzeman/trakt.py/issues/46#issuecomment-192581453

Maybe I'll draft a version later.

**Comment by rectifyer** [comment]
Oh cool, didn't realize it was in process in trakt.py. Very nice :)

**Comment by razzeee** [comment]
https://github.com/trakt/script.trakt/releases/tag/3.1.5

**Comment by rectifyer** [comment]
Awesome! I'm already seeing a bunch of installs with the updated auth. I wrote an official blog post about it too. Thanks for the great work :)

https://blog.trakt.tv/kodi-scrobbler-sync-plugin-1f148b5070a5

**Comment by razzeee** [comment]
Thank you! One thing I have to nitpick, but you probably already know, that playback sync option is only for downloading progress to kodi. Even when disbaled, the scrobble should set the progress on trakt :)

**Comment by rectifyer** [comment]
Yeah, good point. I'll make that more clear.
