### ISSUE TITLE
Trakt.tv connection has failed on Kodi

### ISSUE THREAD

**Issue by LaurieDH** [razzeee/script.trakt#290]
After setting up a Trakt.tv account to use on Kodi and had it working successfully, for some reason it stopped working and I have not been able to re-establish a connection since. Here's exactly what I did: after setting up my Trakt.tv account and setting it up and Kodi (which, as I said, worked perfectly). I then went on to the Trakt.tv website and organized the tv show list that I first built on Kodi. I organized my list alphabetically, added more shows to the list and when I brought my list up on Kodi, everything was there, and in the order that I added the shows. In the mean time, I had also added a new list (titled Christmas, for all of our fav Christmas stuff). I then went on to Kodi, went thru the process of adding the Christmas category to my menu bar (on The Beast). All went well. But, when I tried to open the new category, it was empty. Then when I went back to look at the TV show list that I made, that was also empty. After some digging in Kodi (checked my email and password in the Trakt.tv section, which was fine, but then when I checked another section, it had my Trakt.tv Connection, in red. So, I no longer had a Trakt.tv connection. Needless to say, I have tried everything from re-authorizing Trakt.tv with new pins, revoking the account and setting it up again..and no luck. So, I'm asking you for anything that can help me.

**Comment by razzeee** [comment]
Sorry, it sounds like your not using this addon, as this addon never would ask you for your password.
Your probably referring to a different addon.

Another thing, please don't be offended, but line breaks help other people to read your stuff ;)

**Comment by LaurieDH** [comment]
Thanks for the quick response...I probably sound pretty frustrated, which I am. When I activated Trakt.tv on Kodi (I use The Beast), I followed a couple of YouTube videos to help me do it. As I said, everything was working beautifully, and then after trying to add the new list it all crashed. I can't help thinking it's something I did myself, and just can't figure out what I did.

**Comment by razzeee** [comment]
Unfortunately this addon doesn't support lists. So your problem is probably with another addon using trakt
