### ISSUE TITLE
Can't install Tarkt app

### ISSUE THREAD

**Issue by IdanRadai** [razzeee/script.trakt#303]
Hi there,
Tried to find it under koi repo, programs, it's wasn't there.
tried to install with the zip file an got the - Dependencies not met... error

could you help me please?
thanks!

**Comment by stuc30** [comment]
Yep its the line..
addon="xbmc.python" version="2.24.0"
means it will only install on kodi 16 onwards...

**Comment by IdanRadai** [comment]
anyway to get an older version ?
I'm using the 14.2 because in all other higher koi ver. all of my local video are lagging and stuttering...

I'm wish I'll find a solution for the stuttering but yet to find one...(you might know about it something?)

**Comment by razzeee** [comment]
You should be able to install the addon from the official repo. But version 3.0.4 is the newest you can get.
