### ISSUE TITLE
Message appearing in log

### ISSUE THREAD

**Issue by thwaller** [razzeee/script.trakt#304]
WARNING: [script.trakt] trakt.interfaces.base: request failed: Not Found - "method exists, but no record found" (code: 404)

I am seeing this warning numerous times in the log during playback. While this happens, there is no flag sent to trakt.tv that the episode was watched and I am not asked to rate. I can add that it is only for certain series, not all. I have tried to completely remove the series, from library and database (manually) and readding it, the results are the same.

**Comment by thwaller** [comment]
Further investigation shows this only happens with 1channel plugin, @tknorris . I do need to add...1channel is **my** most used addon by far, so this could mean nothing. It is tv series specific, meaning if it happens on show A, it will continue to happen, and if show B works fine, it continues to work fine. No testing on movies yet and I will look at other addons more as well to see if 1channel is actually a factor or not. The specific shows discovered are with active subscription set in 1channel and added to Kodi library.

I have recently added my API to Metahandlers addon, so it is no longer producing errors with TMDB, it did not have effect on this issue.

Additionally, shows are common and have entries appearing and active in IMDB, TVDB, TMDB, Trakt.tv, etc. There should be no issues with data match. Manual setting to watched in Trakt.tv and setting of rating works fine and syncs Trakt <--> Kodi perfectly.

Also note that while the trakt portion fails with the above error, the watched flag local to Kodi is being set.

**Comment by tknorris** [comment]
I'll take a look at it when I have time. It's probably an imdb number issue in 1ch.

**Comment by tknorris** [comment]
Does it only happen with library integration?

**Comment by tknorris** [comment]
It might be better to close this issue here and open it against 1ch instead. I doubt this is a trakt add-on issue.

**Comment by thwaller** [comment]
-- Does it only happen with library integration?
Unknown. I add items I watch into library and watch from there. I will check on it and see.

-- It might be better to close this issue here and open it against 1ch instead. I doubt this is a trakt add-on issue.
Can the issue be transferred? I cannot say whether it is or is not narrowed down to 1ch at this time, only that it is for sure an error on the trakt script, cause unknown, could be 1ch as you suggest.

**Comment by tknorris** [comment]
It can't be transfered but I think it better to not discuss things like 1ch in trakt's repo

**Comment by thwaller** [comment]
Ok, I will close it. Only reason 1ch was mentioned is it appears as a common in the issue, only common to start was trakt. Closing now, will reference it.
