### ISSUE TITLE
Sync watched status - error

### ISSUE THREAD

**Issue by RottenKid** [razzeee/script.trakt#305]
Hello, 

I use Kodi 16.1 with Trakt add-on version 3.1.6 and everytime when I try to sync the watched status I get the following message in the log:

> 17:07:29 T:8520   DEBUG: [script.trakt] syncEpisodes: [Episodes Sync] Getting episode collection/watched/rated from Trakt.tv
> 17:07:29 T:8520   DEBUG: [script.trakt] trakt.core.http: OAuth - Missing "created_at" or "expires_in" parameter, unable to determine if token is still valid
> 17:07:29 T:8520   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/collection/shows HTTP/1.1" 200 None
> 17:07:31 T:8520   DEBUG: [script.trakt] trakt.core.http: OAuth - Missing "created_at" or "expires_in" parameter, unable to determine if token is still valid
> 17:07:32 T:8520   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/watched/shows HTTP/1.1" 200 None
> 17:07:36 T:8520   DEBUG: [script.trakt] trakt.core.http: OAuth - Missing "created_at" or "expires_in" parameter, unable to determine if token is still valid
> 17:07:36 T:8520   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/ratings/shows HTTP/1.1" 200 None
> 17:07:36 T:8520   DEBUG: [script.trakt] trakt.core.http: OAuth - Missing "created_at" or "expires_in" parameter, unable to determine if token is still valid
> 17:07:42 T:8520   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/ratings/episodes HTTP/1.1" 500 None
> 17:07:42 T:8520 WARNING: [script.trakt] trakt.core.http: Continue retry since status is 500, waiting 5 seconds
> 17:07:45 T:4600   DEBUG: Thread JobWorker 4600 terminating (autodelete)
> 17:07:45 T:8864   DEBUG: Thread JobWorker 8864 terminating (autodelete)
> 17:07:45 T:7632   DEBUG: Thread JobWorker 7632 terminating (autodelete)
> 17:07:47 T:8520 WARNING: [script.trakt] trakt.core.http: Retry # 1
> 17:07:53 T:8520   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/ratings/episodes HTTP/1.1" 500 None
> 17:07:53 T:8520 WARNING: [script.trakt] trakt.core.http: Continue retry since status is 500, waiting 5 seconds
> 17:07:58 T:8520 WARNING: [script.trakt] trakt.core.http: Retry # 2
> 17:08:06 T:8520   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/ratings/episodes HTTP/1.1" 500 None
> 17:08:06 T:8520 WARNING: [script.trakt] trakt.core.http: Continue retry since status is 500, waiting 5 seconds
> 17:08:11 T:8520 WARNING: [script.trakt] trakt.core.http: Retry # 3
> 17:08:15 T:8520   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/ratings/episodes HTTP/1.1" 500 None
> 17:08:15 T:8520 WARNING: [script.trakt] trakt.core.http: Continue retry since status is 500, waiting 5 seconds
> 17:08:20 T:8520 WARNING: [script.trakt] trakt.interfaces.base: request failed: Server Error - "server error" (code: 500)
> 17:08:20 T:8520   DEBUG: [script.trakt] syncEpisodes: [Episodes Sync] Invalid Trakt.tv show list, possible error getting data from Trakt, aborting Trakt.tv collection/watched/rated update.
> 17:08:20 T:8520   DEBUG: [script.trakt] syncEpisodes: [Episodes Sync] Error getting Trakt.tv collected show list, aborting tv show sync.
> 17:08:20 T:8520   DEBUG: [script.trakt] sync: [Sync] Finished synchronization with Trakt.tv

Any idea how can I fix this? 

Thank you in advance.

**Comment by razzeee** [comment]
Probably a server error, so it's either your connection or trakt had server problems.

**Comment by RottenKid** [comment]
I have this issue from a long time (two months or so) everything is working beside Retrieve watched status.

**Comment by razzeee** [comment]
Then try to reach out to the trakt guys and ask them if something with your watched episodes is broken.

**Comment by RottenKid** [comment]
Razzeee: OK, thank you very much.
