### ISSUE TITLE
Error log entry - watched not set in Trakt.tv

### ISSUE THREAD

**Issue by thwaller** [razzeee/script.trakt#313]
The following line appears in the Kodi log fine after viewing an episode (in my specific usage 1channel plays it), Kodi marks the episode as watched but nothing is sent to trakt.tv and the rating is not asked for.

06:01:06 T:140559758903040  NOTICE: 1Channel: Service: Played 43:06 of 43:35 total = 98%/90%
06:01:06 T:140559758903040  NOTICE: 1Channel: Service: Resetting...
06:01:07 T:140560320952064 WARNING: [script.trakt] trakt.interfaces.base: Request failed: Not Found - "Method exists, but no record found" (code: 404)
06:01:07 T:140560757495552  NOTICE: URLResolver: Initializing URLResolver version: 3.0.13

The percentages for both being marked as watched and enough playback to ask for rating are both met and all else seems as normal. After all of this, if I manually run the Trakt addon in the Programs section of Kodi, the episode gets marked as watched on trakt.tv. I can then set the rating there, run trakt addon again, and the rating is synced as well.

What looks to be the cause of this? I can provide a full log if needed. The addon is at 3.1.7 which is the current version on the Kodi repository, but not the current version here. I understand that upgrading the the version here (not on the repository) may be a fix, but I do not want to alter anything if the issue is not yet resolved. Kodi is at 16.1, latest stable/non-beta repository.

**Comment by thwaller** [comment]
Update: I have decided to dig further and in the process, I have just updated the addon to 3.1.8 with the reverted change, although I doubt the reverted change will make a difference here. Just an FYI in case anyone is looking into this.

Further update: Since the upgrade of the trakt addon, there has been no change.

**Comment by thwaller** [comment]
I can share what I found to help anyone else that may have this issue. It is failing to scrobble to trakt.tv. The data is being sent, the correct series, the correct season, the correct episode number and the correct episode name. During the viewing, the scrobble fails. After the viewing, it fails to mark watched and ask for a rating for trakt.tv. Please note that manually running the trakt.tv addon immediately after will work, the episode is marked as watched without problem.

The addon playing is 1channel. I have found that this specific series is extremely problematic. I tested a few others and have not encountered any issues to report. I have tried SALTS on a few as well, no problems to report there. Seems likely an issue matching the metadata, but the data passed is correct. It is very possible I am missing something, and I can say that currently this is an issue on all episodes within this series. Earlier in the series, it is recalled that scrobble and rating did in fact work, so it may be either a change in the trakt addon or something that developed into an issue with the progression of seasons / episodes.

Additionally, if I use the Kodi addon to allow me to use a different addon and select SALTS, it works fine with the same episode, shows up on trakt as watch and rating is asked for. So this appears to be narrowed down to an addon using trakt outside of itself, appears to be tied to the metadata pass and may be specific to 1channel.

I can provide this, which appears to show a malfunction when the trakt addon is in play:
19:56:30 T:140121043072768   DEBUG: [script.trakt] service: Queued dispatch: {u'action': u'seek', u'time': 2218871, u'offset': -30000}
19:56:30 T:140121043072768   DEBUG: [script.trakt] service: Dispatch: {u'action': u'seek', u'time': 2218871, u'offset': -30000}
19:56:30 T:140121043072768   DEBUG: [script.trakt] scrobbler: playbackSeek()
19:56:30 T:140121043072768   DEBUG: [script.trakt] scrobbler: scrobble()
19:56:30 T:140121043072768   DEBUG: [script.trakt] scrobbler: scrobble sending show object: {'title': u'The Good Wife'}
19:56:30 T:140121043072768   DEBUG: [script.trakt] scrobbler: scrobble sending episode object: {'season': 3, 'number': 21, 'title': u'The Penalty Box'}
19:56:30 T:140121043072768   DEBUG: [script.trakt] trakt.core.http: OAuth - Missing "created_at" or "expires_in" parameter, unable to determine if token is still valid
19:56:30 T:140121186744064  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 23
19:56:30 T:140121186744064  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 23
19:56:30 T:140121043072768   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "POST /scrobble/start HTTP/1.1" 404 None
19:56:30 T:140121043072768 WARNING: [script.trakt] trakt.interfaces.base: Request failed: Not Found - "Method exists, but no record found" (code: 404)
19:56:30 T:140121043072768   DEBUG: [script.trakt] scrobbler: Failed to scrobble episode: {'title': u'The Good Wife'} | {'season': 3, 'number': 21, 'title': u'The Penalty Box'} | 86.0058215237 | start

**Comment by thwaller** [comment]
@tknorris - could you have a quick look at this? 1channel is 2.5.77 taken from your beta repository. SALTS does not have the issue, even on the problem episodes, just 1channel.

**Comment by tknorris** [comment]
1CH will never scrobble 100% of the time because it doesn't always have IDs to identify the shows/movies. In this case there are other shows referred to as "The Good Wife" and the scrobble is probably matching one of those rather than the one you intend. I added [this logic](https://github.com/trakt/script.trakt/wiki/Providing-id%27s-to-facilitate-scrobbling) to script.trakt to handle situations like this, but since 1CH doesn't have ID's available 100% of the time, when it doesn't it forces script.trakt to fallback to title matching which isn't 100% reliable.

**Comment by thwaller** [comment]
I see, and this makes perfect sense. I am closing the issue as this is a good enough answer for me. Thanks!

**Comment by tknorris** [comment]
Note, if you check the kodi log w/ debug turned on, just before playback starts you'll see a message like this from 1CH:

`ids meta is: imdbnum: %s; meta: %s`

That will tell you what ID's 1CH had available to give to trakt. If you don't see any good ones there, then everything is working as designed.

**Comment by thwaller** [comment]
@tknorris this might be best to post in your section, but is it possible to have 1channel look at local nfo files for the IDs needed?

**Comment by tknorris** [comment]
Only through Kodi library json rpc but Kodi doesn't return imdb number for episodes...

**Comment by thwaller** [comment]
I see, it is what it is. I am still looking for that line of code you stated, but your explanation makes perfect sense, and I did suspect it was the passing of meta data causing this. With or without that, your answer does basically solve the issue.

**Comment by thwaller** [comment]
FYI- I am unable to locate "meta:" anywhere in the log, but I can see "imdbnum:" in a few places, all with no good data, ie. 'None'. Thanks again, this does help.

**Comment by tknorris** [comment]
You have to have debug turned on when you start the stream. I started the same episode you did and this is what I get:

`23:33:51 T:140707911812864   DEBUG: 1Channel: ids meta is: imdbnum: tt1442462; meta: {'plot': u"Alicia defends a judge against misconduct charges stemming from his days as a prosecutor. Cary makes a career decision and Kalinda deals with the repercussions of Agent Delaney's investigation.\n\nGuest Starring: David Paymer, Stephen Root, Jerry Adler", 'rating': 7.4, 'title': u'3x21 The Penalty Box', 'mpaa': u'TV-14', 'TVShowTitle': 'The Good Wife', 'writer': u'Julia Wolfe', 'overlay': 6, 'premiered': u'2012-04-22', 'imdb_id': u'tt1442462', 'director': u'Michael Zinberg', 'genre': u'Crime,Drama,Mystery', 'studio': u'CBS', 'cover_url': u'http://thetvdb.com/banners/episodes/95451/4293737.jpg', 'season': 3, 'duration': u'2700', 'episode': 21, 'playcount': 0, 'trailer_url': u'', 'backdrop_url': u'http://thetvdb.com/banners/fanart/original/95451-1.jpg'}`

Notice I do have an IMDB ID but I'm playing from directly in the addon. It sounds to me like you are playing from the library which changes things.

**Comment by thwaller** [comment]
Yes, you are correct, playback from library. That is the cause of the issue, playback from library rather than addon direct? I still am not sold into having all driven by trakt, so I still use library on stuff. And yes, debug is/was on.

**Comment by tknorris** [comment]
It's complicated, but you are more likely to get a useful ID when using 1CH directly than when using it via the library. If you want to go through the code to see why oyu can, but it's too complicated to explain here.

**Comment by thwaller** [comment]
Understood, I might have a look see, maybe it will convince me to make the move from library to trakt.
