### ISSUE TITLE
Tract authorization not updating in Kodi

### ISSUE THREAD

**Issue by Robinoconnor5** [razzeee/script.trakt#319]
Hello I am a new Kodi user. I followed the steps to install the Trakt addon and created a trakt account.   I used the authorization code provided (after exiting Kodi to get to a web browser on my pc)within a few minutes going to trakt activate website. It didnt ask me to sign in It just had a box for the authorization code. Once I entered it asked me to allow , I clicked yes and it gave me the "whooo" message . I went back into Kodi and it gave me yet another code. I went through this process several times. Kodi shows enabled. I did the configuration yet Kodi says no trakt account found when i click on my shows or my movies  My Kodi user name is robinoconnor5.    Some of the instructions I found on the internet said once the trakt site authorized it should give me  a pin number to enter in Kodi but it never did that.

As I said I have to actually exit Kodi on my pc to open a web browser to go to trakt activate. I don't know if that is an issue . If so how do i get around. I tried leaving it open and going to the activate site using my phone but it didn't recognize the auth code doing it that way. 

Please advise

**Comment by razzeee** [comment]
Sorry for the late reply, I was on vacation.

It should work fine, when you do it from your phone, you just need to be signed into the website.

**Comment by Robinoconnor5** [comment]
Thanks. It is linked now.

Sent from Yahoo Mail on Android 

  On Sat, Oct 1, 2016 at 2:06 PM, Razzeeenotifications@github.com wrote:  
Sorry for the late reply, I was on vacation.

It should work fine, when you do it from your phone, you just need to be signed into the website.
