### ISSUE TITLE
Problem with authentication in trakt

### ISSUE THREAD

**Issue by a-goodarzi** [razzeee/script.trakt#321]
I upgrade my Ubuntu from 16.04 to 16.10.
in 16.04 it shows a pop-up to enter pin code.but Every time i entered the pin it shows me an error :)
I had Kodi Isengard and trakt script 3.0.7 on ubuntu 16.04 .

after upgrade to 16.10 it doesn't show me the pop-up again.
and this is my Kodi log:
[kodi.txt](https://github.com/trakt/script.trakt/files/531115/kodi.txt)

**Comment by razzeee** [comment]
can you try this? http://stackoverflow.com/questions/37009692/ssl-error-bad-handshake#38236543

**Comment by ghost** [comment]
I have a similar issue, although slightly weirder. 

It says that it is authenticated, but never actually is. Sync fails completely with trakt. The message says: "Account Authorization: Trakt Authorization Complete". 

I've set trakt up with kodi on other devices and trakt always responds with a WooHoo! is lime green to let you know your account is linked with kodi. On ubuntu, it doesn't do it all. It just keeps telling me that I need to verify my account after claiming my account has been verified.

Heres my info (let me know if you need anything else).

I installed kodi using the Advanced Packaging Tool (apt) on ubuntu and am using KODI from debian. Not sure if this is a debian issue or a trakt issue, but I figured I would start with trakt first seeing as that is what is **not** working.

Distributor ID: Ubuntu
**Description:  Ubuntu 16.04.1 LTS**
Release:    16.04
Codename:   xenial

_Old Log: http://pastebin.com/F8z2AvCu_

**Isolated Log: http://pastebin.com/4i6CNNxc**

**Comment by razzeee** [comment]
I'm not sure whats going on there, as your on a pretty old version of kodi/script.trakt. Which is using the old way to authenticate. Are your other devices on newer builds?

**Comment by xovertheyearsx** [comment]
I am not sure, how do I figure that out?

**Comment by ghost** [comment]
I don't know, how do I figure that out?

**Comment by razzeee** [comment]
Well are the others also ubuntu and installed via whatever your using?
Might want to look at this: http://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

**Comment by ghost** [comment]
I have a laptop using ubuntu that uses kodi and trakt and works. Works on Windows, works on android. Its just my desktop for whatever reason... not sure why. I will take a look at the link when I have some time.

**Comment by razzeee** [comment]
@xovertheyearsx @numb95 
has the last version fixed your problem?

**Comment by ghost** [comment]
i stopped using it after that issue so i couldn't say. i never did figure it out. sorry.
