### ISSUE TITLE
Seasons Marked as Watched

### ISSUE THREAD

**Issue by lakedaisy** [razzeee/script.trakt#327]
Trakt doesn't work correctly for my Kodi.  For example: Starting with no Seasons marked as Watched. If a TV show has 5 seasons (or any number greater than 1) and I go to Season 3 (or any Season prior to the last Season) and mark it as watched, all 5 seasons are marked as watched even though I haven't watched Season 4 & 5.  Now, with all 5 Seasons marked as Watched, I go to Season 4 (or any Season prior to the last Season) and mark it as UnWatched the check mark is removed from all 5 Season.   Is this the way trakt works? Or is this an error in my KodI?  Thanks for your input.  

My Kodi is set up with Pulse CCM. The skin is Xonfluence, eXtended MOD of Confluence.  I downloaded it from Ares Wizard.

**Comment by razzeee** [comment]
I just tried to reproduce it, but it doesn't happen for me :/

**Comment by lakedaisy** [comment]
any suggestions?  can I uninstall traktv and exodus and reinstall them?

**Comment by razzeee** [comment]
you should be able to, but I can't really offer any support for exodus. And if you tried to set an exodus show as watched, that's probably the root of your problem. I'm only using local media.

**Comment by lakedaisy** [comment]
I'm new to Kodi.  What does local media mean?  Maybe I can try that?

**Comment by razzeee** [comment]
Well you basically point kodi to your movie/show collection. Like rips etc.
See:
https://www.youtube.com/watch?v=yrInCGIdmdk

**Comment by lakedaisy** [comment]
Okay.  Thanks Razzeee.  I'll save my current Pulse t henload a new basic Kodi.  I'll try this tomorrow.

**Comment by razzeee** [comment]
Any news?

**Comment by lakedaisy** [comment]
No Razzeee it still works the same.  Only way I can mark prior seasons as watched is to mark each episode individually.  I've given up and no longer try to mark the prior seasons I have watched.
