### ISSUE TITLE
Kodi Addon doesn't allow to authorise Trakt Account

### ISSUE THREAD

**Issue by vasaregrv** [razzeee/script.trakt#333]
Clicking on "How do I authorize Kodi Addon" doesn't produce the QR Code or weblink. I've tried fresh installing Kodi retaining no data from earlier session and even that didn't help.

MacOS Sierra. 
Kodi 16.1
Trakt Script 3.1.7

**Comment by razzeee** [comment]
It's not supposed to create a QR or a weblink anymore. It should guide you to go to https://trakt.tv/activate
So can you get me a logfile of you trying it, please see the readme for additional infos.

**Comment by vasaregrv** [comment]
Nothing happens when I click on “how to authorise…” No pop-up nothing. I’ve attached log file just like you asked.

**Comment by sagr1989** [comment]
i am having the same issue error window shows up on kodi when I try to authorize my trakt account.

**Comment by razzeee** [comment]
I don't think your logfile made it to the internet :/

**Comment by vasaregrv** [comment]
Kodi was giving me error to upload the log file. That’s why I attached the file.

**Comment by sagr1989** [comment]
Thanks for the response. I uninstalled and then reinstalled and it worked.

**Comment by razzeee** [comment]
@vasaregrv I can't see any attachement

**Comment by vasaregrv** [comment]
Sorry. My bad. Here you go.

[kodi.txt](https://github.com/trakt/script.trakt/files/633597/kodi.txt)

**Comment by razzeee** [comment]
Please read https://github.com/trakt/script.trakt#creating-logfiles and create new logfiles using that. Your logfile doesn't have anything helpful :/

**Comment by jgginer** [comment]
Hi there
I have a similar problem, but I'm in a kodi Alpha release so if there's no way to get a fix I'll understand and be patient.

Since last week I was unable to sync, so I'tried to delete the addon and reinstall to see if that fixed the issue. Now seems that the addon setup seems to fail. Here you can see the log for the addon installation.
http://pastebin.com/THvQUfq7

The addon seems to be installed, even after the previous crash, but no access to the authorization web. I read before that no more QR should be expected. If I have no web browser on my htpc, can my kodi access to the authorization web page?

Is there another way to get the code to authenticate?

More info regarding my htpc
Ubuntu 16.04.1 LTS Kernel 4.4.0-53
Kodi 18.0-ALPHA GIT20161206
Trak version '3.1.8'

Thanks in advance for your help and your great Addon!!!

**Comment by vasaregrv** [comment]
@Razzeee, I understand the procedure. The problem is that, the add-on doesn't fail or crash to be logged into the file. That's why I can't reproduce the problem. When I click on "How do I authorise..." nothing happens. So, obviously it won't be written on log file. I have tried it numerous times.

**Comment by razzeee** [comment]
@jgginer 
Reads like your MAC address is acting weird, what hardware is this running on?

@vasaregrv 
Well it should still show up in logging, if you set it up correctly. We will need all data we can get.

**Comment by vasaregrv** [comment]
Log file uploaded!
http://paste.ubuntu.com/23596725

**Comment by razzeee** [comment]
Is this from the same session, where you activated the logging? Can you please restart after you enable the logging and then try again and upload the log?

**Comment by vasaregrv** [comment]
This is the new one!
http://paste.ubuntu.com/23601828

**Comment by razzeee** [comment]
Well you have the correct version and I can't see anything obvious that's going wrong. Not sure what's going on.

**Comment by jgginer** [comment]
@jgginer
Reads like your MAC address is acting weird, what hardware is this running on?
http://asrock.com/mb/Intel/J4205-ITX/index.es.asp

**Comment by razzeee** [comment]
No idea then

**Comment by jgginer** [comment]
So, there aren't any other way to add, even manualy the auth information?

If I change the version to 3.1.4, I can see the authentication dialog and I can enter it but when I try to send it I got a error that says something like "Cant connect"

Any help will be much appreciated!!

**Comment by razzeee** [comment]
No, there is no manual way. Try using the default skin to add your auth.

**Comment by jgginer** [comment]
:_(
Already tried with the same output. Seems that I can see autorization screen with 3.1.4 or previous. But doesnt authorize anyway :(

**Comment by RobLoach** [comment]
Getting the following error....

```
GetDirectory - Error getting
Previous line repeated 3 times.
Control 7600 in window 10000 has been asked for focus, but it can't
Trakt split over multiple files, unsupported.
```

Kodi 18, LibreELEC.

**Comment by razzeee** [comment]
@RobLoach 
That
> Trakt split over multiple files, unsupported.

Does not sound like your using this addon

**Comment by jgginer** [comment]
Seems that's a certificate issue. 
I fix it changing your 3.1.8 version file "~/.kodi/addons/script.module.trakt/lib/trakt/core/http.py"
The actual line:

            self.session.mount('https://', HTTPSAdapter(ssl_version=ssl.PROTOCOL_TLSv1, **self.adapter_kwargs))

by this one:

            self.session.mount('https://', HTTPSAdapter(ssl_version=ssl.PROTOCOL_TLSv1_2, **self.adapter_kwargs))

And works. Certificate on the autorization page acepts TLS v 1.2 and fails (at least for me) with TLS v 1.0

Feel free to double check it and add it to yor version if you like.

Regards

**Comment by razzeee** [comment]
Thanks letting us know @jgginer we'll check if we can do that

**Comment by fuzeman** [comment]
@jgginer Could you check if the protocol auto-negotiate mode works?

Just drop the `ssl_version` parameter completely:
```
        self.session.mount('https://', HTTPSAdapter(**self.adapter_kwargs))
```

or specify `ssl.PROTOCOL_SSLv23`:

```
        self.session.mount('https://', HTTPSAdapter(ssl_version=ssl.PROTOCOL_SSLv23, **self.adapter_kwargs))
```

**Comment by razzeee** [comment]
can you retry with jarvis or krypton?

**Comment by jgginer** [comment]
@fuzeman: I'll try to check and report back.

@Razzeee:
This is my environment:
Ubuntu 16.04.1 LTS Kernel 4.4.0-53
Kodi 18.0-ALPHA GIT20161206
Trak version '3.1.8'

**Comment by razzeee** [comment]
Weird, you should have trakt 3.1.9 already

**Comment by jgginer** [comment]
Sure thing if I had let marked the auto update option 😜.
As I had modified the file by my self and want the addon working I take the precaution of unmark that option.

**Comment by razzeee** [comment]
Well if you don't update the trakt module and revert the trakt addon, then there is no reason for you to test this.

**Comment by jgginer** [comment]
Works with:
`self.session.mount('http://', HTTPAdapter(**self.adapter_kwargs))`

**Comment by razzeee** [comment]
I'm going to close this for now, for lack of feedback.
