### ISSUE TITLE
Multiples play of a movie

### ISSUE THREAD

**Issue by NunoVilhenaSantos** [razzeee/script.trakt#335]
Hi,

Sorry for bothering with this issue, but i didn't find any info about the problem that i'm experience for quite some time.

The issue is that i use 3 PC with windows and linux install on them and also wetek play box, the kodi is install on all of them, to be able to use when a please.

I don't know if this is create the problem with the trakt database, because i use TraktRater_v2.2.4 to update from imdb the scores i gave to movie instead of do it on kodi after i watched the movie.

But after a while of using kodi the database of trakt starts to show more plays on each, sometimes i start to see the new movies with 3, 4 ou 5 plays, and at first i did use TraktRater to perform a clean on movies watch but again after a while i saw that again each movie that i saw only once is marked with 2, 3 or 4 play.

So i'm addressing this issue to help understand what i'm doing wrong or if this a bug with a addon.

I'm using SALTS and Genesis on all of the installations of kodi, the only installation that i use to create .strm files is on the wetek play, otherwise i use SALTS or Genesis directly to see a specific movie that i'm unable to get my hands on.

Thanks for addons, it's a fantastic, and keep the good works.

And sorry for my english.

**Comment by razzeee** [comment]
If your using SALTS your probably not using this addon at all, as I've heard it has it's own implementation.
