### ISSUE TITLE
Unpause/Jumpback

### ISSUE THREAD

**Issue by unlocKing** [razzeee/script.trakt#337]
I've been using the Unpause Jumpback script which plays back to the past 15 seconds after you unpause anything, the problem now with the last update of trakt is that it no longer works.

It only plays from where it was paused, I think it has to do with the scrobbling, can you take a look please:

https://github.com/Memphiz/script.xbmc.unpausejumpback/tree/master/script.xbmc.unpausejumpback

Cheers!

**Comment by razzeee** [comment]
So if you disable trakt it starts working for you again?

**Comment by unlocKing** [comment]
Disabling Trakt actually crashed my system, had to restart..

Now disabled, it's still the same.. So, I now have done a clean install with the jumpback addon and trakt (but not logged in) only and it works fine, adding my trakt info and it breaks the jumpback feature.

Would it be possible to add this feature into Trakt as it's very useful when going back to watch something for a quick reminder what you have seen so far? :)

**Comment by unlocKing** [comment]
Been a while, noticed a few updates to the unpause jumplack addon have passed.. it's working again now.
