### ISSUE TITLE
Duplicate scrobbles of shows appear with identical play times.

### ISSUE THREAD

**Issue by kevjs1982** [razzeee/script.trakt#338]
![formulae](https://cloud.githubusercontent.com/assets/1839810/21624661/d18ba232-d1ff-11e6-9b6d-b2da91020fc3.png)

I've noticed a small number of films get dozens of scrobbles at the same time in the library from Kodi.

I THINK I've narrowed it down - seems to only be an issue with films that **do not** have an IMDB ID linked to them - initially I had a number of films with this issue, but after fixing the NFOs and reloading the data in Kodi only this "film" remains an issue (it doesn't exist on IMDB).  I have a few more "films" which have been watched but they don't appear in Trakt at all (they have no IMDB or TMDB entry).

The number of scrobbles appears to increase by one each time I perform a Trakt sync (i.e. every time the library is updated).

I have disabled the Title/Year matching option on all the Kodi machines yet the issue exists.

![screenshot116](https://cloud.githubusercontent.com/assets/1839810/21624838/8b2f0422-d200-11e6-86f7-61232ae35625.png)

**Comment by razzeee** [comment]
Can you provide the nfo file?

**Comment by kevjs1982** [comment]
Attached - obviously with an .nfo extension normally
[Formula E - Ice Drive - Full Documentary-1NveoIpyvSU.txt](https://github.com/trakt/script.trakt/files/684203/Formula.E.-.Ice.Drive.-.Full.Documentary-1NveoIpyvSU.txt)

**Comment by razzeee** [comment]
It's due to the fact, that trakt doesn't know a year for that "movie". 

This should fix this problem in the future: https://github.com/Razzeee/script.trakt/commit/58aa46697ef64e959523d534acbc4e46ebf9103c

Not sure when I'll push that to the kodi repo

**Comment by kevjs1982** [comment]
Thanks 👍 

That explains why it's started doing the same for "Hitler's Olympics" too https://trakt.tv/movies/hitler-s-olympics - do you know where Trakt.tv picks the year up from - IMDB has it but Trakt.tv isn't showing it?

In any case I've added the correct data for both to TheMovieDB so hopefully Trakt.tv will pick the correct data up soon.

**Comment by razzeee** [comment]
It's getting it from tmdb. I just triggered a refresh for the olymics movie, might take some time to refresh, depends on the system load.

**Comment by razzeee** [comment]
I've pushed the code, so if our using Krypton or newer, the problem will be gone.
