### ISSUE TITLE
Script suddenly stopped working

### ISSUE THREAD

**Issue by sharkykh** [razzeee/script.trakt#340]
Hello,
I don't know if the problem is on my side (I didn't do anything out of the ordinary on Kodi/Trakt),
but when I try to sync my library using the script it stops prematurely.
[I enabled logging and this is what I got (from script start to finish)](http://pastebin.com/zQBUgnf5)
Scrobbling also stopped working.
It looks like I can't connect to the server (however, the Trakt.tv site is working fine for me)

I continued to look up the errors from the log file and tried re-authorising the addon to my Trakt user, as suggested [here](https://github.com/trakt/script.trakt/issues/228#issuecomment-119510988).
The window just closed and [this is what I got in the log.](http://pastebin.com/AWNa0pjf)

I was hoping someone here might know a fix?

**Comment by sharkykh** [comment]
Looks like [python requests module](https://github.com/kennethreitz/requests) got updated to version 2.12.4 recently. After downgrading back to 2.9.1 the script seems to work as before, 
But maybe that update is necessary...

Log file after running script.trakt (Sync)
```
11:14:22 T:4536   ERROR: C:\Users\Kfir\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
11:14:22 T:4536   ERROR: C:\Users\Kfir\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning

```

**Comment by razzeee** [comment]
Can you try the newest versions of https://github.com/razzeee/script.module.trakt and https://github.com/trakt/script.trakt

**Comment by sharkykh** [comment]
Thanks for replying.
I did that, also updated the requests module to the newest version again.

Looks like it worked,
but I'm not so sure because the sync took longer (than usual) to finish.
[Log file](http://pastebin.com/yG2fQzT4)

**Comment by razzeee** [comment]
Should be fine, might be due to the first run.

**Comment by sharkykh** [comment]
Yes, it got faster :)
Thank you

**Comment by razzeee** [comment]
One quick question, which kodi version are you using?

**Comment by sharkykh** [comment]
Jarvis 16.1
