### ISSUE TITLE
Kodi Addon not showing popup with authorisation code. please fix asap

### ISSUE THREAD

**Issue by lukehansford** [razzeee/script.trakt#342]
The kodi addon is broken as it wont show the authorisation pop up with the code.

this has been reported on the offficial kodi forum and I have tested it on fresh installs and devices

**Comment by razzeee** [comment]
wait for tomorrow please. Should fix itself if your on jarvis+

**Comment by lukehansford** [comment]
what must we do on our end?

**Comment by delahaya** [comment]
Also experiencing this issue.

**Comment by ib1ub12** [comment]
yeah am having same problem ...hope they fix it soon

**Comment by delahaya** [comment]
What OS are you running?

Sent from Nylas Pro<https://link.nylas.com/link/f5hemx0sjlfhp6njlqw2yqho/local-0457b4e9-ef4b/0?redirect=https%3A%2F%2Fnylas.com%2Fnylas-pro%3Fref%3Dn1>, the most powerful email app for work

On Jan 17 2017, at 10:04 pm, ib1ub12 <notifications@github.com> wrote:

yeah am having same problem ...i was told to...... please attach a log file at https://github.com/trakt/script.trakt and open an issue with all the details. when asked where to find a log and how to attach it i was then told.....here should be steps in that link how to get the log file. ...well i dont see any steps on how to do this

**Comment by ib1ub12** [comment]
android box


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by razzeee** [comment]
Make sure you have the repository updated everything jarvis+ works again.

**Comment by ib1ub12** [comment]
hey thanks man it is working again and FYI the version of trakt i have is 3.1.7, same version that was there when this all started. not 2.1.9


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by razzeee** [comment]
Yes, correct. I realized after writing this that Jarvis users just would
get a dependency update, not an update for the main addon.

**Comment by ib1ub12** [comment]
yeah the trakt.py version is 2.12.0


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
