### ISSUE TITLE
Rating/ show history

### ISSUE THREAD

**Issue by PsychoFanGirl** [razzeee/script.trakt#344]
My watched shows on kodi are no longer showing up on my trakt history
Also after watching a show i no longer get the trakt rating box showing up

**Comment by razzeee** [comment]
Refresh your addon listing. If your on jarvis or newer.
http://i.imgur.com/gxpA0zZ.gifv

**Comment by PsychoFanGirl** [comment]
How do i do that

**Comment by razzeee** [comment]
Just look at the gif in the previous post

**Comment by PsychoFanGirl** [comment]
Mines different then thw video it doesnt have an update thing

**Comment by PsychoFanGirl** [comment]
Okay so ive talked to 10 people made account on 3 websites and spent 2 days
And you finally told me how to fix it
Thank you so much

**Comment by PsychoFanGirl** [comment]
Could you tell me something
