### ISSUE TITLE
no longer scrobbling

### ISSUE THREAD

**Issue by lukehansford** [razzeee/script.trakt#345]
from today the addon is no longer scrobbling anything.

**Comment by pirathotten** [comment]
I have noticed this as well, nothing scrobbled since January 17

**Comment by lukehansford** [comment]
I managed to fix it by uninstalling the addon and the script from the dependancies area and manually deleting the addon and script from kodi folder in windows 10 and reinstalled the addon and copied over the zip of the script into the kodi addon script folder from the github here.

select clone or download and then download as zip and unzip it then paste the contents to
C:\Users\(yourusernamehere)\AppData\Roaming\Kodi\a ddons\script.module.trakt

https://github.com/Razzeee/script.module.trakt

I logged into kodi today and it had an update for the script even though i already had the latest 2.12 wjocj is what I think messed it up for me.

hopefully it will be ok now
