### ISSUE TITLE
Trakt Setting Custom Link

### ISSUE THREAD

**Issue by jnewbury2280** [razzeee/script.trakt#348]
Does anyone know the path to the Trakt Setting? I want to create a menu item that will jump to the Trakt settings.

**Comment by razzeee** [comment]
You should be able to write a contextmenu addon like done here https://github.com/Razzeee/context.trakt.contextmenu/blob/master/addon.py#L6 and just call https://github.com/trakt/script.trakt/blob/0ed3f5e8db25ffd5b953800cfa5887f4e67e7fa5/service.py#L73 instead

**Comment by jnewbury2280** [comment]
I think that is a bit above my head. I guess I will just go the long way.


Sent from Justin's iPhone 6

On Jan 24, 2017, at 3:47 PM, Razzeee <notifications@github.com<mailto:notifications@github.com>> wrote:


You should be able to write a contextmenu addon like done here https://github.com/Razzeee/context.trakt.contextmenu/blob/master/addon.py#L6 and just call https://github.com/trakt/script.trakt/blob/0ed3f5e8db25ffd5b953800cfa5887f4e67e7fa5/service.py#L73 instead

-
