### ISSUE TITLE
Improve wording for the four sync types

### ISSUE THREAD

**Issue by Razzeee** [Razzeee/script.trakt#35]
- Add movies
- Update playcount in kodi
- Update playcount in trakt
- Delete movies

These could probably have better names. It should make clear that the updates are about your history/watched and add/delete is about the collection.

**Comment by s7eele** [comment]
@Razzeee ill probably feel stupid after asking butvin what context are u referring to:

context menu items?
settings?
msgs displayed during sync?

i just looked at settings again and im not sure how much the wording there can/needs to be improved upon, i think its pretty clear

i have never actually used the clean trakt collection options, is it safe to assume it clears the respective collection (movie/tv) on trakt and rebuilds it using the kodi library?

i know its not much of a contribution but thought i would go ahead and break the ice, ill b thinking on it still, thx

**Comment by Razzeee** [comment]
@s7eele 
It's mostly about the settings, msgs during sync will be aligned to these.

Clean trakt just deletes items from your collection you kodi no longer stores. So the ones you removed locally.

**Comment by mikesilvo164** [comment]
I like the new wording you suggested. Maybe Add movies to collection and Remove movies from collection? Might also run into some translation issues though...

**Comment by Razzeee** [comment]
- Add new movies to trakt collection
- Remove deleted movies from collection
- Add watched movies to trakt history
- Mark movies from trakt history as watched in kodi

But you might be right about the translations

**Comment by mikesilvo164** [comment]
I like that... very precise and not much room for confusion IMHO. My suggestion would be to outsource the translations to the fine folks at the trakt VIP forum or the kodi forum once you have decided on the final wording... Maybe start your own or thread or ask if somebody wants to handle that stuff for you. I'm sure you could fine plenty of volunteers for either. :)

**Comment by Razzeee** [comment]
@mikesilvo164 
I would like to use the default kodi translation workflow
http://forum.kodi.tv/showthread.php?tid=142736

**Comment by mikesilvo164** [comment]
I think you just need to sign up and add your project. I myself have to look into transifex for the translations for my skin mod. I have no idea how hard that would be since I haven't checked into it yet. Hopefully it is easy like just linking your GitHub project to the site and just pulling updates similar to a Git Pull or something...

Thanks for working on this. Since you've fixed the ratings and scrobble it has been a lifesavor.

**Comment by Jobespierre** [comment]
I favour of your last suggestion as well, very clear like that!

**Comment by chewara** [comment]
-Add new movies to trakt collection
-Remove deleted movies from trakt collection
-Add watched movies to trakt history
-Mark movies from trakt history as watched in kodi

just added trakt in second row

**Comment by Razzeee** [comment]
Done
