### ISSUE TITLE
Stopped working for older version

### ISSUE THREAD

**Issue by Suusepuus** [razzeee/script.trakt#350]
I'm using an older version of the script (3.0.7) on Kodi 15.2, because my device cannot be updated to a newer version of Kodi. This version stopped scrobbling and syncing. Is there any way to keep using Trakt on Kodi  15.2?

**Comment by razzeee** [comment]
I'm well aware of this problem. I've made a version addressing this. I don't have an old version anymore and the changes might potentially be dangerous to your trakt account. That beeing said, another user is already test driving that version. When he reports back and there isn't a new problem, everybody will get that version.

**Comment by bastarfromnowhere** [comment]
Hello,
Yesterday i have exactly the same issue with my Trakt 3.0.4 under Kodi Helix...
Nothing work anymore... :( 

I tried to reinstall it, same probleme.
I tried to revoke it from my Trakt Account & re-activate it ... and now it's impossible to pair them, i'd got "Error Code Pin Message". I'd just saw that the authentification is different now ... God damn ...

I just remember that i have made some Update of Python yesterday too and other stuff & since them trakt doesn't want to work 
I'm F... up or I'm F... up ?

thx for helping

**Comment by razzeee** [comment]
Try again please

**Comment by bastarfromnowhere** [comment]
Bravo !

It's working now after a Trakt.Py Update ;)

Good Job

**Comment by Suusepuus** [comment]
For me it is still not working with Trakt 3.0.7 and Kodi 15.2.  It says there is no update for Trakt.

**Comment by razzeee** [comment]
That's correct there haven't been an update to trakt. The dependencies have been updated.

**Comment by Suusepuus** [comment]
It's working now after I authorized the app again. Thanks!

**Comment by soulm1986** [comment]
Hello everyone,

I've used kodi (14.2 on ATV2) and trakt for a long time now. And since january i've met the same issues with trakt. I don't know how to update trakt.Py or authorize the app again, could you explain it to me ?
Thanks guys.

**Comment by Suusepuus** [comment]
In the addon settings I pressed the link "how to authorize..." and followed the instructions. That re-authorized my account and everything started working again. No need to update trakt.py for me.

**Comment by Alpume** [comment]
Hi!. 

I have similar situation (old Kodi version), in my case is Kodi 16 with Trakt 3.1.7 addon.
This is my log: http://pastebin.com/GcKB7n8E
In [this other closed issue](https://github.com/trakt/script.trakt/issues/333) was mentioned a possible solution, but it didn't work for me.

Thaks.

**Comment by razzeee** [comment]
@Alpume 
What's the versio of your script.module.trakt and script.module.requests?

**Comment by Alpume** [comment]
Hi @Razzee, I have installed these versions:
script.module.requests 2.12.4
script.module.trakt 2.13.0

Thanks for your quick response.

**Comment by razzeee** [comment]
@Alpume so you've tried to reauthorize?
I can't really help you without a full logfile. It looks like it might be your OS.

**Comment by Alpume** [comment]
It's a new installation for a HTPC, Trakt plugin never asked me for credential or showed a QR. I tried same operation in Ubuntu 14.04, Ubuntu 15.10, Elementaryos 0.2, Xubuntu 14.04 and Xubuntu 15.10 at the end. 

You have [here](https://pastebin.com/4DpdLLba) a new and complete debug logfile.

**Comment by razzeee** [comment]
What's your version of `cryptography` and can you update it?
https://github.com/kennethreitz/requests/issues/3710

**Comment by Alpume** [comment]
Hi @Razzee. My version is 1.0.1. It's provide by Ubuntu package manager.

I'll try to update it manually. I'll comment you the results.

**Comment by Alpume** [comment]
Well, I think I'm new in this, and I haven't found how update it. Deb repository has same version.

Could you help me?. Thanks.

**Comment by Alpume** [comment]
It woks!!. I fixed it. I added the 16.10 main repository and updated to version 1.5.2.
Thanks for all!!.
