### ISSUE TITLE
Edit scrpit.trakt to use on widget on home screen (example: titan skin netflix view2)

### ISSUE THREAD

**Issue by ghost** [razzeee/script.trakt#352]
I have  a feature request/question regarding kodi context menus. In kodi 17 with titan skin (Netflix view) you can use context menu on widget items, where in 16 you couldn't. I downloaded the trakt context menu addon which only worked with tv shows and movies library view, but edited it to work in all views. I got the trakt menu to come up, but the only option was synchronize library. I then saw it was linked to script.trakt. it got very complicated after that. TLDR: just wondering if its possible to add trakt menu to home screen widget contexts. just want to browse movies and tv shows linked at home, and say add to collection or mark watched. TIA! btw this is for personal use.

**Comment by razzeee** [comment]
Well I think that might be a kodi problem, we just give it this to decide: https://github.com/Razzeee/context.trakt.contextmenu/blob/master/addon.xml#L10

So it should show it for every show/movie/episode etc

**Comment by razzeee** [comment]
As this is a problem of core, I'm going to close this.
