### ISSUE TITLE
Trakt is not scrobbling

### ISSUE THREAD

**Issue by grossier** [razzeee/script.trakt#355]
My trakt addon 3.1.9 (but also 3.1.7 before) is not scrobbling anything and showing movie marking popup. However other features like watchlist or next episode are working fine. When I'm restarting there is a little popup which says there is an error in an addon. I'm on the newest OSMC 2017.02-2, which is based on Kodi 17.
In attachment I put my log.
[kodi.pdf](https://github.com/trakt/script.trakt/files/769251/kodi.pdf)

**Comment by sharkykh** [comment]
I noticed the error is about a latin character ó ([\xf3](http://www.codetable.net/hex/f3))
I'm not sure where the error is originating from, so you should wait for the people who do.
But, did you enter this character anywhere in Kodi? Maybe in a profile name?

```
00:45:22.636 T:1690301424 ERROR: EXCEPTION Thrown (PythonToCppException) :
  -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

Error Type: <type'exceptions.SyntaxError'>

Error Contents: NonASCII character '\xf3' in file
  /home/osmc/.kodi/addons/script.module.requests
  /lib/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py
on line 1, but no encoding declared;
see http://python.org/dev/peps/pep-0263/ for details (_implementation.py, line 1)
```

**Comment by grossier** [comment]
This could be because ó is my native letter. I don't remember typing ó in any place, more possible is ł. For sure ó it is not in my profile name. Thanks for help.

**Comment by razzeee** [comment]
Sorry, but you have banned addons installed, so I won't be able to help you. And your probably mixing the trakt addon up with other addons.
