### ISSUE TITLE
Ask for rating when disabled in settings

### ISSUE THREAD

**Issue by spirann** [razzeee/script.trakt#357]
Trakt ask for my rating after every episode but it's disabled in the settings.
I'm on Krypton Android TV 

Here's my settings.xml
[settings.txt](https://github.com/trakt/script.trakt/files/778473/settings.txt)

I've replaced my personnal infos by XXX

**Comment by razzeee** [comment]
A logfile as specified in https://github.com/trakt/script.trakt#i-found-something-that-doesnt-work would be great

**Comment by spirann** [comment]
After rebooting kodi in debug mode to start a new clean log, the problem has disappeared. So I think I just needed to reboot kodi. Sorry for the time waste.

**Comment by razzeee** [comment]
Weird, was that the first restart with Krypton or just a normal one?

**Comment by spirann** [comment]
First one I think.
