### ISSUE TITLE
Trakt 3.0.4 add on issue with pin code & Kodi Helix

### ISSUE THREAD

**Issue by bastarfromnowhere** [razzeee/script.trakt#359]
Hi,

i just saw a post with the same issue, i past it here

"Have been using the Trakt.tv app for years now, and have NEVER had any issues until recently. I noticed the rating window wasn't opening after watching a movie (been a few days now). So I did some troubleshooting and when I decided it most likely needed to be re-connected, it wouldn't allow me to Authorize the PIN I had received from http://trakt.tv/pin/999 . . I have never had any compatibility issues between Kodi and Trakt.tv, so this came as a surprise to me, so I decided to make it know. I have already uninstalled / reinstalled, and tried multiple authorization PIN's, I have checked for online issues signing in & out, and even tried changing me password / Username . . Nothing so far. Pls. advise ASAP . . Thanks "

So i have exactly the same issue ! Does someone find a way to make it work !?

At the beginning the rating window didn't poped up after watching a media then i unpaired my Kodi with Trakt and now it's impossible to have a PIN code which pair my kodi i have the PIN error code in my Kodi !

I use kodi Helix with Trakt 3.0.4 and it's impossible for me to update it ...

here is my log: http://pastebin.com/YeRzz2FP

Thx for helping

**Comment by razzeee** [comment]
Try again please

**Comment by bastarfromnowhere** [comment]
Hi @Razzeee

I just tried this morning and it's the same Error Pin Code Authentification.

:(

Thx for your help

**Comment by bastarfromnowhere** [comment]
Hey @Razzeee 

Sorry for my last test ... But it's working now !! Thank u so much u are great!!

I didn't understand last time that i have to do update ! I just tried to connect to my Trakt Add On, but in fact yesterday night when i did the Trakt.Py Update ... PAF !!! Trakt Unlocked itself !! 

Thx for your job again 

Issue Solved

**Comment by soulm1986** [comment]
Hi Razzeee.

Still have issues with Kodi (14.2 on ATV2) and trakt. I can't authorize the add-on, it returns "pin error" when i enter the pin code provided on trakt.tv/pin/999.

I tried to save the log file, here : 
[Kodi Log File Soulm1986.txt](https://github.com/trakt/script.trakt/files/881692/Kodi.Log.File.Soulm1986.txt)

I think it says i need to upgrade python... but i don't understand how to do that...

Thanks guys.

**Comment by bastarfromnowhere** [comment]
Hi,
I just went into "system" and to the "Add On" section in KODI, and then into the setting with "Update available", i found it here!  Inside it, there was an update of Python wich name is Trakt.py that i have to did !! That's all

Hope it will help

**Comment by soulm1986** [comment]
Thanks @bastarfromnowhere  i went to trakt.py on Kodi, but i can't find any update. It seems I have 2.13.0 version of Python.

Still not working...
