### ISSUE TITLE
New movies in Kodi library are being added to trakt as "watched"

### ISSUE THREAD

**Issue by mzaki83** [Razzeee/script.trakt#36]
Seems to only affect newly added movies. Noticed similar issues that have been closed (21, 26), but problem persists for me, and seems to happen regardless of whether or not movie has an IMDB ID.

**Comment by Razzeee** [comment]
Please make sure your on the newest build. You might have to delete your old addon folder and your old settings before installing the new

**Comment by mzaki83** [comment]
I was definitely on the newest build. Just deleted all traces of the addon and reinstalled though. Will test and report back. Thanks.

**Comment by mzaki83** [comment]
Fixed. Thanks.
