### ISSUE TITLE
French language update for addon Trakt

### ISSUE THREAD

**Issue by bubuleur** [razzeee/script.trakt#360]
Hello,
I come to you to give my contribution I updated the translation in French of the addon Trakt for kodi
http://www83.zippyshare.com/v/BvNnu0RA/file.html
If you could put it in the next update
In thanking you
Have a good day

**Comment by razzeee** [comment]
Please refere to https://github.com/trakt/script.trakt#translations for translations

**Comment by bubuleur** [comment]
Can you do it I really do not know or go
In thanking you
