### ISSUE TITLE
Vote after watched a film or episode no longer works with kodi 17 

### ISSUE THREAD

**Issue by Choukajohn** [razzeee/script.trakt#364]
Option to have vote popup appearing just after viewing a movie or an episode no longer works in kodi 17. If the popup doesn't appear and if I try to vote through addon trakt contextmenu it doesn't work. If I manually launch synchronization with trakt, next popup or next vote with trakt context menu will work but only once.

**Comment by razzeee** [comment]
https://github.com/trakt/script.trakt#i-found-something-that-doesnt-work
Please read this and provide more data. Kodi 17 is working fine here.

**Comment by Choukajohn** [comment]
Hi Razzeee,
Sure you're right, sorry you will find attached the debug log.
There is some fatals errors related to the script trakt.
I tried to reproduce context in wich issue appears.
Thanks.
[kodi.zip](https://github.com/trakt/script.trakt/files/803221/kodi.zip)

**Comment by fbacker** [comment]
I also having issue with the latst Kodi v17 and trakt.tv plugin 3.1.9

When deleting the plugin to reinstalled I found this in the logs.

	19:55:59.611 T:506200   ERROR: XFILE::CFile::Delete - Error deleting file C:\Users\kidkic\AppData\Roaming\Kodi\addons\packages\script.trakt-3.1.9.zip
	19:55:59.611 T:506200   ERROR: XFILE::CFile::Delete - Error deleting file special://home/addons/packages/script.trakt-3.1.9.zip
	19:55:59.611 T:506200   ERROR: XFILE::CFile::Delete - Error deleting file C:\Users\kidkic\AppData\Roaming\Kodi\addons\packages\script.trakt-3.1.9.zip
	19:55:59.611 T:506200   ERROR: XFILE::CFile::Delete - Error deleting file special://home/addons/packages/script.trakt-3.1.9.zip
	19:55:59.611 T:506200   ERROR: CAddonInstallJob[script.trakt]: MD5 mismatch after download. Expected c95fd55012ecc0aa68deadb0cb23e94b, was

To point out here I've installed Kodi from Windows Store. And after a lot of troubles I manage to understand that the files are not in the **C:\Users\kidkic\AppData\Roaming\Kodi** location but in **C:\Users\kidkic\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi**
Maybe this can be the issue why it ins't installed correctly? Because after download the zip file isn't located and the actual install can't be made (no authorization window)

**Comment by razzeee** [comment]
@fbacker 
That's just a failed download.

I just tested the same on with the windows store, works fine here.

**Comment by Choukajohn** [comment]
For information, I had the issue with the 3.1.9, I tried to reinstall it several times and finally I installed the last version from github with no luck.

**Comment by razzeee** [comment]
So do you have any repos other then the official kodi repo set up?

**Comment by Choukajohn** [comment]
No I don't, I just tried to install last version from github zip file.

**Comment by fbacker** [comment]
I've deleted my logs and restarted Kodi.
When to Kodi Add-on repository and installed trakt.

	10:57:00.963 T:261696   ERROR: SQL: [Addons27.db] Abort due to constraint violation
												Query: insert into package(id, addonID, filename, hash)values(NULL, 'script.trakt', 'special://home/addons/packages/script.trakt-3.1.9.zip', 'C95FD55012ECC0AA68DEADB0CB23E94B')
	10:57:00.963 T:261696   ERROR: CDatabase::ExecuteQuery - failed to execute query 'insert into package(id, addonID, filename, hash)values(NULL, 'script.trakt', 'special://home/addons/packages/script.trakt-3.1.9.zip', 'C95FD55012ECC0AA68DEADB0CB23E94B')'

Attaching full logs
[kodi.zip](https://github.com/trakt/script.trakt/files/810313/kodi.zip)

Diving a little deeper I find the downloaded zip file: 
C:\Users\kidkic\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\addons\packages

	Computer said
	C95FD55012ECC0AA68DEADB0CB23E94B
	Kodi logs said
	c95fd55012ecc0aa68deadb0cb23e94b

Also I got the trakt plugin installed folder
C:\Users\kidkic\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\addons\script.trakt

**Comment by razzeee** [comment]
@fbacker 
Well  if that's true, it's either a problem with your system or a core kodi problem. Would be nice if you report at trac.kodi.tv

**Comment by razzeee** [comment]
@Choukajohn 
not sure what exactly is going on, but your ssl fails. I've found this which you might want to check
http://stackoverflow.com/questions/37009692/ssl-error-bad-handshake

**Comment by Choukajohn** [comment]
@Razzeee
Thx for your help.
Maybe I am using this python package (letsencrypt script or maybe flexget ?) so I tried to update it first.
Will see if the issue still persists.

**Comment by Choukajohn** [comment]
Ok I have some news.
I tried to update openssl pip package and issue is still here.
Like I said in first post, if I synchronize trakt and then try to vote it works. In fact if I launch a video, right after a manualy sync, then I go directly to the end then stop the video, the vote popup appears normaly. I tried on severals movies and it works all the time.
But, if I really watch a movie, in the end it doesn't work and the vote popup doesn't appears. It seems to be a sort of standby issue or something like.

**Comment by razzeee** [comment]
beats me, maybe @fuzeman has an idea (sorry to ping you again :( )

**Comment by razzeee** [comment]
@fbacker also attach your `Addons27.db` if you create that ticket

**Comment by Choukajohn** [comment]
Hi,
Addon is working well since several days now so I think I can mark the issue as solved.
I didn't do anything, maybe some updates on my OS solved the problem.
Anyway, thanks for your help.

**Comment by fbacker** [comment]
My Windows crashed so needed to format an reinstall everything. This time
installed standalone (not windows store) and it works great 👍
Also remember now that last install was an Kodi upgrade. From standalone to
windows store. From 16.1 to 17.
