### ISSUE TITLE
Disable playcount updating/syncing

### ISSUE THREAD

**Issue by brimur** [razzeee/script.trakt#365]
I know some people think playcount is important but for me a video is either watched or unwatched. When runnning trakt sync, updating the playcount takes hours so it would be great to disable it in the options. Is there any chance of that?

**Comment by razzeee** [comment]
Playcount isn't syncing. It's just syncing watched/unwatched.

**Comment by brimur** [comment]
Thanks Razzeee, I thought maybe something else might be going on because of how long it took to do a sync, I did a new setup on a new amlogic quad core device and it took over 12 hours to "update the playcount" for 10000 items. I did a plex server setup pointing at the same location and the trakt sync only took a minute or two. Not saying at all that its your script, just saying thats why I posted here, because I thought this playcount thing was something else.

**Comment by brimur** [comment]
Meant to close...
