### ISSUE TITLE
Previously watched content is not updated to Kodi

### ISSUE THREAD

**Issue by ghost** [razzeee/script.trakt#369]
Since having installed Kodi 17 fresh (17.1), and installing Trakt, all media that was previously watched has not been updating my watched status in Kodi. Scrobbling works, but not the other way (where all my shows and movies are not being registered as seen. I have tried restarting the PC, re-installing Trakt add-on.

Settings file: https://paste.ubuntu.com/24330245/
Logfile: https://paste.ubuntu.com/24330287/ (Sorry, I don't know how to extract Trakt-only logfile)

System details: Linux samsang 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Installed on MySQL database.

Edit: scrobbling does NOT work either.

**Comment by razzeee** [comment]
Have you removed the authorization stuff from your settings or is it really not filled? You might want to reauthorize then, and I will need a log with both debug flags activated, see logfile at the top of the repo.

**Comment by ghost** [comment]
Oh wow, I had authorized (via trakt.tv/activate), but my settings were wiped after a crash from Kodi's part. Everything is updating fine now.
