### ISSUE TITLE
Unrating Not Working

### ISSUE THREAD

**Issue by ghost** [razzeee/script.trakt#372]
It seems that the unrate option is not working. I went through the code in service.py in doManualRating there is the following code:

```
if action == 'rate':
    if not 'rating' in data:
        rateMedia(media_type, [summaryInfo])
    else:
        rateMedia(media_type, [summaryInfo], rating=data['rating'])
```

Shouldn't that be:

```
if action == 'rate':
    if not 'rating' in data:
        rateMedia(media_type, [summaryInfo])
    else:
        rateMedia(media_type, [summaryInfo], rating=data['rating'])
elif action == 'unrate':
    rateMedia(media_type, [summaryInfo], unrate=True)
```

If I add the elif part, the item is correctly unrated on Trakt. However, there is still no notification in Kodi that says that the item was unrated. So there is also something not working in rating.py

**Comment by razzeee** [comment]
Totally possible, might have been broken when I rewrote the whole thing. Never bubbled up, as we're not using the unrating function right now, I think?

**Comment by ghost** [comment]
Yes, I don't think you are using it right now. However, I'm calling that function in script.trakt externally from my addon.  I'm using unrating every now and then, so it would be nice to have that feature.

**Comment by razzeee** [comment]
Are you able to send a PR?

**Comment by ghost** [comment]
Sorry for the late reply. What do you mean by PR?

**Comment by razzeee** [comment]
A pull request, basically how you send code via github

**Comment by ghost** [comment]
Ahh, git pull.
So do you mean on which commit my suggestion above is based? In that case, I've been using the pull from commit 0178290, but the same applies to the latest one as well: 8658af6.

**Comment by razzeee** [comment]
No :)
I was hoping, that you would edit the code on your github and send it to us via a github pull request :)

**Comment by ghost** [comment]
Ah, you mean doing a git push. I've forked and added the necessary code: https://github.com/bubblesaddon/script.trakt

Could you let me know once you release a new version with the new fix, so that I can add it to my Kodi repo.
