### ISSUE TITLE
Trakt stopped syncing with Jarvis/exodus

### ISSUE THREAD

**Issue by RacerXnyc** [razzeee/script.trakt#376]
Hey~o,

So I fired up Kodi recently 16~Jarvis, and I noticed that trakt gave me an error and told me to check the log.

And I notice that now that it's not updating the watched status for shows that I've just watched. Once I mark it manually as 'watched in Trakt', then it will remember that change the next time I load Kodi. It also remembers shows that I save to my list. 

I have a link for my recent log, with debugging turned on, and it does seem that there are some Trakt errors.

Thanks!

https://paste.ubuntu.com/24398034/

**Comment by razzeee** [comment]
Sorry, no support for exodus or other illegal addons

**Comment by RacerXnyc** [comment]
Ok, well, addons aside- the error "problem check the logs" is part of the Kodi UI as soon as Kodi starts.  It's the same little pop-up ribbon that tells me that addons have updated.  I have auto updating on, but I don't know if that's part of the problem or not.

Not sure if that changes anything.
