### ISSUE TITLE
[REQ] Quick pull every x minutes

### ISSUE THREAD

**Issue by brimur** [razzeee/script.trakt#377]
It would be great to have the quick pull method available that is triggered every x minutes similar to the Plex add-on. Any chance of getting this? 
Also, is a library update the only automated way that the script does a sync or is it also on a schedule that can be edited somewhere to change the interval?

Thanks

**Comment by razzeee** [comment]
I don't think we want to do this, but you can probably pull this of, via other plugins, doing a library scan.

**Comment by brimur** [comment]
> I don't think we want to do this, but you can probably pull this of, via other plugins, doing a library scan.

Lol,  I was like,  Razzeee, that name sounds vaguely familiar. It's been a few years. 👍
