### ISSUE TITLE
Collection, Watchlist, etc won't open

### ISSUE THREAD

**Issue by minutezmonster** [razzeee/script.trakt#381]
Kodi v17.1 Krypton
Exodus 1.0.1 (3.1.10)
Trakt 3.1.10

![image](https://cloud.githubusercontent.com/assets/28633981/25967877/93faa716-365d-11e7-96bb-eb21015a2008.png)

Failing to access My Movies or My TV Shows libraries; collection, watchlist, whatever.  When I click on them it will attempt to load for about a second and then do nothing or attempt to load for about 20-30 seconds and then still do nothing.  Then when I just go to, for example, the Movies section and pick Most Popular, the first page might come up but if I hit Next Page it won't load anything after that.

I don't know of this is an Exodus issue or a Trakt issue, but it just started happening yesterday (5/10/2017) and I know Exodus updated recently but haven't seen anyone have the problem from what I could find.

**Comment by razzeee** [comment]
Sorry, I'm not supporting exodus users.
