### ISSUE TITLE
Automatic sync after "Mark as watched"?

### ISSUE THREAD

**Issue by SamuelBolduc** [razzeee/script.trakt#382]
When I mark a show or an episode as watched manually in Kodi, it should sync right away with trakt, right? I'm pretty sure it worked as expected before. However, I recently made the switch to Kodi 18. Is it possible the feature is broken in that version?

Thank you!

**Comment by razzeee** [comment]
Unlikely, but trakt had some performance problems in the past days. I will
test it later / in the next days.

**Comment by amj87** [comment]
I have the same problem with Kodi 17.6, did you resolve it?

**Comment by steelwolf** [comment]
In my testing, if you mark something as watched in Kodi and then manually sync to Trakt, it still doesn't sync. The only successful way to sync from Kodi to Trakt is to play the episode.

**Comment by razzeee** [comment]
Logfiles would probably help here.
