### ISSUE TITLE
Trakt error syncing TV Show (force quit Kodi)

### ISSUE THREAD

**Issue by Fred-Vatin** [razzeee/script.trakt#387]
script version | Kodi | OS | 
------------------ | ---- | ----
3.1.11 | 17.3 | Win 10 x64 pro (french) 14393 

## Steps to reproduce and results

1. Have nfo for TV Shows and each episode with proper **uniqueid**
2. Scrape with Kodi nfo scraper
3. Run trakt add-on to sync movies and TV shows, rating and watched state.
4. Movies are sync with no issue
5. When TV Show episode sync starts, it is stuck at the very first show.

Cancel won't work. I have to quit kodi with Alt+F4.

## Details

My Kodi db has proper uniqueid for tvshow at **MyVideos107.db→tvshow_view→uniqueid_value**
and proper uniqueid for episode at **MyVideos107.db→episode_view→uniqueid_value**
And their **uniqueid_type** is tvdb.

Trakt runs the show sync after the movie sync even if in **trakt settings→synchonize→TV episodes** all is disabled. I guess it is because it wants to sync my rating for all my media sources. **But it means that I have no mean to avoid track being stuck at every sync now I have TV Show in my Kodi DB**.

[Here](https://gist.github.com/freMea/891fcb93747f2ba6357bf71becdb0d5e) is my trakt settings (I removed my credentials 😉).

Log after I enabled trakt debug mode. Here is the error:

```
13:52:57.894 T:9432   ERROR: Exception in thread trakt-sync:
            Traceback (most recent call last):
              File "E:\Medias\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                self.run()
              File "E:\Medias\Kodi\portable_data\addons\script.trakt\resources\lib\service.py", line 335, in run
                sync.sync()
              File "E:\Medias\Kodi\portable_data\addons\script.trakt\resources\lib\sync.py", line 65, in sync
                syncEpisodes.SyncEpisodes(self, progress)
              File "E:\Medias\Kodi\portable_data\addons\script.trakt\resources\lib\syncEpisodes.py", line 18, in __init__
                kodiShowsCollected, kodiShowsWatched = self.__kodiLoadShows()
              File "E:\Medias\Kodi\portable_data\addons\script.trakt\resources\lib\syncEpisodes.py", line 114, in __kodiLoadShows
                show['seasons'] = kodiUtilities.kodiRpcToTraktMediaObjects(data)
              File "E:\Medias\Kodi\portable_data\addons\script.trakt\resources\lib\kodiUtilities.py", line 188, in kodiRpcToTraktMediaObjects
                episodeObject = kodiRpcToTraktMediaObject('episode', episode, mode)
              File "E:\Medias\Kodi\portable_data\addons\script.trakt\resources\lib\kodiUtilities.py", line 133, in kodiRpcToTraktMediaObject
                'ids': {'tvdb': data['uniqueid']['unknown'], 'episodeid': data['episodeid']}, 'watched': watched,
            KeyError: 'unknown'
```

No other trakt ref in the log.

* My kodi install is fresh and clean. No other add-ons than the default ones that come with estuary (extendedinfo, etc.).
* I have none show saved in my trakt account, only movies. So I never tested the TV show sync before.
* If the show number 1 where trakt add-on sync is stuck is the same as the number 1 saved in **kodi DB→tvshow→idShow**, then the blocking show is **3%** and its TVDB uniqueid is **250749** and it is saved in my Kodi DB at **MyVideos107.db→tvshow_view→uniqueid_value**. 
* Show ref in trakt site: [here](https://trakt.tv/shows/3-2016).

## Expectations

Error proof just like it does with my movies.

**Comment by razzeee** [comment]
Your using the tvdb as scraper? Or manually set id's via nfo?

**Comment by Fred-Vatin** [comment]
nfo populated by ember with tvdb scrapper.

[Here](https://gist.github.com/freMea/f1c48af895c9f30cbadb7fcb42cf8fc0) is the nfo for the show.

But the **MyVideos107.db→tvshow_view→uniqueid_value** is here in kodi db. Where does trakt expect it to be?

**Comment by razzeee** [comment]
We're expecting the episode id to be available 
See: https://github.com/trakt/script.trakt/blob/master/resources/lib/kodiUtilities.py#L133

**Comment by Fred-Vatin** [comment]
Well, the first bug is the error is not properly handled. The sync process should terminate and show an error  notification and it doesn't. Instead, it comes unresponsive to cancel action and force user to quit kodi.

The second one is, if I understand, the script can not get the episode id. If yes it could be:
* the method may be not accurate in every case and a fallback is needed if possible
* the bug comes from Kodi that can not provide the ep. id if the source is from NFO scrapper.

Or it is something else. You're in the best position to investigate and figure out what is wrong and if it is needed to be fixed by you or Kodi team.

**Comment by razzeee** [comment]
you will probably need to write nfos for each episode, with the correct id embedded. I haven't used nfo so far, but I'm guessing kodi doesn't do mixed content sources. So it doesn't grab the episode details from online, but keeps them empty.

You may be able to check the kodi wiki (when it's back) how to do this.

**Comment by Fred-Vatin** [comment]
The thing is my episodes already have a nfo for each with all needed info for the kodi nfo scraper and more (with tvdb id and else). See this [gist](https://gist.github.com/freMea/c3f5c2e3b5a3d48a4914e99669a5afa8).

At this point, I don't know what I can do to go further. Need some feedback from Kodi team about that.

**Comment by Fred-Vatin** [comment]
Look at this [thread](https://forum.kodi.tv/showthread.php?tid=318661) from the author of **Light IMDb Ratings Update** add-on. The guy use ep. nfo (structured as mine) and succeeds to get uniqueid with its JSON-RPC request.

Maybe you need to change the way you perform get data.

**Comment by razzeee** [comment]
@freMea if you have your files like the author in the post, try to replace "tvdb" with "unknown" and let me know if that improves stuff.

**Comment by Fred-Vatin** [comment]
# SUCCESS !

Bug identified.

I created a new test profile in kodi with only one TV Show and only one episode.

In the episode NFO I replaced `<uniqueid type="tvdb" default="true">5787121</uniqueid>` with `<uniqueid type="unknown" default="true">5787121</uniqueid>`.

Trakt had no issue to sync.

Restore the NFO with proper tvdb type and Trakt bug occurs again.

---

So you need to fix this in the script to get the default uniqueid no matter the type.

You still need to throw an error notification and log it (specifying which episode misses the id) when it can not find uniqueid for an episode (it can happen that this field may be empty obviously). This error should be non-blocking, process other episodes list anyway until the end. And the cancel button should work.

(If it is not done yet) Throw and log an error if the script fails to find the episode on the Trakt DB specifying the uniqueid used. Non blocking-error.

**Comment by razzeee** [comment]
It's not that simple. It's "unknown" for anything < Krypton and other types for anything newer.

**Comment by razzeee** [comment]
Can you try https://github.com/Razzeee/script.trakt/archive/improve-matching.zip @freMea

**Comment by Fred-Vatin** [comment]
SUCCESS !  👍

**Comment by Fred-Vatin** [comment]
Is this issue still need to be open since it seems fixed now?

**Comment by razzeee** [comment]
No, thank you!
