### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by TessaVW** [razzeee/script.trakt#388]
Hi, I am a very basic user and having signed up for trakt.tv I followed the installation instructions and when I select Install the version starts downloading then I get an error saying unable to install to respository. See attached image, after attempting install this screen keeps returning.  I am using Kodi v17.3 on an android tv box.

![capture](https://user-images.githubusercontent.com/30653993/28868737-42cf1966-7772-11e7-9ee3-56721e0a0962.JPG)

HELP from a complete novice......

**Comment by razzeee** [comment]
Any more infos you can offer?

**Comment by TessaVW** [comment]
What else do you need to know? The guys at Trakt had a look and don't understand why I can't install.  I am using an Abox Android TV Box connected via HDMI to the TV and Ethernet cable to internet.  Kodi works fine.  Don't know waht else to tell you!

**Comment by razzeee** [comment]
- Did you install kodi from the android/play store?

- Did you install any repositories?

- Are you in a normal network or at a university or something out of the ordinary?

It's already weird, that you don't get any screenshots or artwork showing in that screen.

**Comment by TessaVW** [comment]
Bought box with Kodi 17.3 on it already and can stream fine with Exodus, Specto Fork etc

Has Fusion loaded

Home wifi only - box connected via ethernet cable to router

It is weird, shall I unistall Kodi and re-install from the play store?

**Comment by razzeee** [comment]
yeah, I would suggest reinstalling from the play store.
if that doesn't work, then I can't really help you as your using piracy apps, sorry
