### ISSUE TITLE
Kodi to Trakt only syncs last watched date of episode

### ISSUE THREAD

**Issue by Yveske82** [razzeee/script.trakt#392]
I deleted some watched statuses on some shows on Trakt because some things went wrong and thought to re-sync them from Kodi but now it seems that episodes that I watched more than once, only will sync the last watched date instead of all.
So if I watched an episode 3 times, for example: 03/11/2013, 28/01/2015 and 08/07/2017, only the 2017 will show back up on Trakt after syncing.

**Comment by razzeee** [comment]
Correct, kodi doesn't safe anything else. It only has a count of plays, not each date.

**Comment by Yveske82** [comment]
I see. Didn't know that. Guess I have to do it manually than.
Thanks for your reply and the add-on. Keep up the good work.
