### ISSUE TITLE
Rating Not Working

### ISSUE THREAD

**Issue by mdazmir** [razzeee/script.trakt#400]
Hi, I'm running Kodi Krypton (17.4) on my MacBook including two Kodi's plugin:
1. TRAK.TV Script (3.1.12)
2. Covenant (1.1.14)

Convent included TRAKT (Manager, Watched) functions but doesn't include the rating feature. So I've installed TRAK.TV Script for its "Rate on Trakt" feature but it doesn't seem to be working. Below are the log. Any guide would be appreciated:

`02:14:20.641 T:123145305063424   DEBUG: Thread LanguageInvoker start, auto delete: false
02:14:20.641 T:123145305063424    INFO: initializing python engine.
02:14:20.641 T:123145305063424   DEBUG: CPythonInvoker(41, /Users/John/Library/Application Support/Kodi/addons/script.trakt/defaultscript.py): start processing
02:14:20.667 T:123145305063424   DEBUG: -->Python Interpreter Initialized<--
02:14:20.667 T:123145305063424   DEBUG: CPythonInvoker(41, /Users/John/Library/Application Support/Kodi/addons/script.trakt/defaultscript.py): the source file to load is "/Users/John/Library/Application Support/Kodi/addons/script.trakt/defaultscript.py"
02:14:20.668 T:123145305063424   DEBUG: CPythonInvoker(41, /Users/John/Library/Application Support/Kodi/addons/script.trakt/defaultscript.py): setting the Python path to /Users/John/Library/Application Support/Kodi/addons/script.trakt:/Users/John/Library/Application Support/Kodi/addons/script.module.addon.signals/lib:/Users/John/Library/Application Support/Kodi/addons/script.module.arrow/lib:/Users/John/Library/Application Support/Kodi/addons/script.module.dateutil/lib:/Users/John/Library/Application Support/Kodi/addons/script.module.requests/lib:/Users/John/Library/Application Support/Kodi/addons/script.module.simplejson/lib:/Users/John/Library/Application Support/Kodi/addons/script.module.six/lib:/Users/John/Library/Application Support/Kodi/addons/script.module.trakt/lib:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.4-x86_64.egg:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python27.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.7:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages
02:14:20.668 T:123145305063424   DEBUG: CPythonInvoker(41, /Users/John/Library/Application Support/Kodi/addons/script.trakt/defaultscript.py): entering source directory /Users/John/Library/Application Support/Kodi/addons/script.trakt
02:14:20.668 T:123145305063424   DEBUG: CPythonInvoker(41, /Users/John/Library/Application Support/Kodi/addons/script.trakt/defaultscript.py): instantiating addon using automatically obtained id of "script.trakt" dependent on version 2.24.0 of the xbmc.python api
02:14:20.732 T:123145305063424    INFO: CPythonInvoker(41, /Users/John/Library/Application Support/Kodi/addons/script.trakt/defaultscript.py): script successfully run
02:14:20.787 T:123145305063424    INFO: Python script stopped
02:14:20.787 T:123145305063424   DEBUG: Thread LanguageInvoker 123145305063424 terminating`

**Comment by razzeee** [comment]
We'll need a full debug log, please refere to https://github.com/trakt/script.trakt#creating-logfiles
