### ISSUE TITLE
Error getting Trakt.tv collected show list, aborting tv show sync.

### ISSUE THREAD

**Issue by jgginer** [razzeee/script.trakt#402]
Hello

I was having some issues with my kodi library so I decided to reinstall all and addons as well.
Now my library works but I'm having some issues trying to sync it with my trakt account.
I'd double check that my kodi is autorized but sync doesn't complete.

Here is the full log
https://paste.ubuntu.com/25606014/

The main error is for movies:
`11:17:03.383 T:139769216485120   DEBUG: [script.trakt] resources.lib.syncMovies: [Movies Sync] Getting movie collection from Trakt.tv
11:17:03.387 T:139769216485120    INFO: [script.trakt] requests.packages.urllib3.connectionpool: Resetting dropped connection: api.trakt.tv
11:17:03.974 T:139769216485120   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "GET /sync/collection/movies HTTP/1.1" 200 None
11:17:04.501 T:139769216485120   DEBUG: [script.trakt] resources.lib.syncMovies: [Movies Sync] Error getting Trakt.tv movie list, aborting movie Sync.
`
And for tv shows
`11:17:13.496 T:139769216485120   DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Invalid Trakt.tv show list, possible error getting data from Trakt, aborting Trakt.tv collection/watched/rated update.
11:17:13.498 T:139769216485120   DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Error getting Trakt.tv collected show list, aborting tv show sync.`

I'm having the same scenario both for movies and for Tv shows. Seems that the addon can access to my library information, but cant get the list from trakt side.

So I'm a little bit lost.
Some help will be much appreciated
Scenario
`Linux J4205-ITX 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Kodi 17.4
Trackt Addon 3.1.12`

**Comment by razzeee** [comment]
Not sure what's happening there. A COMPLETE log might help, but not sure.

**Comment by jgginer** [comment]
Here you have, a complete log after starting kodi till the end of trakt sync
https://paste.ubuntu.com/25606992/

Regards and thanks in advance

**Comment by razzeee** [comment]
It's not even connecting, see line 791.
Please make sure you can reach trakt.tv from the system running kodi.

**Comment by jgginer** [comment]
Seems that I can reach trakt.tv

`ping trakt.tv
PING trakt.tv (104.20.82.229) 56(84) bytes of data.
64 bytes from 104.20.82.229: icmp_seq=1 ttl=56 time=2.74 ms
64 bytes from 104.20.82.229: icmp_seq=2 ttl=56 time=2.91 ms
64 bytes from 104.20.82.229: icmp_seq=3 ttl=56 time=2.74 ms
64 bytes from 104.20.82.229: icmp_seq=4 ttl=56 time=2.53 ms
--- trakt.tv ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 2.534/2.734/2.917/0.145 ms

traceroute trakt.tv
traceroute to trakt.tv (104.20.81.229), 30 hops max, 60 byte packets
 1  192.168.200.254 (192.168.200.254)  0.183 ms  0.449 ms  0.440 ms
 2  liveboxfibra (192.168.100.1)  0.782 ms  0.851 ms  1.037 ms
 3  * * *
 4  * * *
 5  * * *
 6  74.217.106.212.static.jazztel.es (212.106.217.74)  5.617 ms  3.377 ms *
 7  162.216.106.212.static.jazztel.es (212.106.216.162)  12.982 ms  13.193 ms  13.211 ms
 8  cloudflare.alta.espanix.net (193.149.1.179)  3.595 ms cloudflare.baja.espanix.net (193.149.1.56)  3.918 ms cloudflare.alta.espanix.net (193.149.1.179)  2.809 ms
 9  api-v2launch.trakt.tv (104.20.81.229)  2.808 ms  2.458 ms  2.813 ms
`

Any special url I should try to reach?

**Comment by jgginer** [comment]
I'd just removed the script installed from the kodi repo, deleted all the folders related to trakt on .kodi folder, installed trakt from the zip downloaded from Github and I just sync with any trouble.

So, consider this issue closed.

Thanks for your help
