### ISSUE TITLE
Optimisation: Collection Date customisation

### ISSUE THREAD

**Issue by badelie** [razzeee/script.trakt#403]
Hi
At the moment, it looks like Trakt add-on uses the current date/time when adding library items to Trakt.tv collection. I was wondering if an option may be added to change this to "date added" instead of current date/time. I started using Trakt add-on a few years after I started using Kodi, so a lot of my library items are added to Trakt.tvcolelction at the same time on the day I started using the add-on. I was hoping to somehow change this to have correct dates of collection.

I'm not aware of any other solution to fix this issue, outside the add-ono so I was hoping this may be an easy addition for the devs.

Thanks

**Comment by razzeee** [comment]
It should already do that, see:
https://github.com/trakt/script.trakt/blob/aff276fb1777d0976c0897628292066af3250e6f/resources/lib/kodiUtilities.py#L146

So it might be your platform, database or kodi version. You might want to check the logfile.

**Comment by badelie** [comment]
I see... Thanks for quick reply.
Perhaps it didn't use to do this in previous versions? My problem is in Dec 2014.

Kodi 17.3, Windows 10. I'll check logfile, thanks.

**Comment by razzeee** [comment]
This addon was rewritten at the beginning of 2015, so if you send your data before that, it might not have used that.
