### ISSUE TITLE
Movie sync title fallback matches different movies

### ISSUE THREAD

**Issue by sp74fg2** [razzeee/script.trakt#404]
I keep having issues syncing movies with identical names to trakt. If I see correctly it comes down to the title fallback coming in when they are actually not the same movie.

I have collected and seen the movie "[Blind (2014)](https://trakt.tv/movies/blind-2014)" and also collected "[Blind (2017)](https://trakt.tv/movies/blind-2017)". The latter will never get added on trakt because `compareMovies / findMediaObject` will end up going after the former which is already added on trakt.

This ends up being the matches:

(Kodi item to add)
``
DEBUG: [script.trakt] resources.lib.utilities: movie_col1 {'rating': 0, 'plays': 0, u'title': u'Blind', u'year': 2017, 'ids': {'imdb': u'tt1935089'}, 'watched': 0, 'watched_at': u'', u'userrating': 0, 'collected_at': u'2017-08-28 02:51:51+00:00', 'collected': 1, u'movieid': 15580, u'runtime': 5880}
``

(trakt item matched to)
``
DEBUG: [script.trakt] resources.lib.utilities: movie_col2 {'rating': 7, 'plays': 1, 'title': u'Blind', 'last_watched_at': '2014-07-05T16:42:12.000-00:00', 'year': 2014, 'ids': {'tmdb': '245844', 'imdb': 'tt2616810', 'slug': 'blind-2014', 'trakt': '149618'}, 'rated_at': '2014-07-20T14:39:17.000-00:00', 'progress': None, 'collected_at': '2014-09-06T23:34:07.000-00:00', 'collected': 1, 'watched': 1, 'in_watchlist': 0, 'paused_at': None}
``

(I have plenty of examples for this 😃... it can get as mainstream as "Wonder Woman".)

Imho the end result should not be a title match if the IDs IMDB is present and they are not matching. Would this make sense to add as a requirement at `findMediaObject` title match (or if anyone could add this as I'm a noob at python)?

**Comment by razzeee** [comment]
Sounds like a fun thing to write tests for :)
https://github.com/trakt/script.trakt/blob/master/tests/test_utilities.py#L270
