### ISSUE TITLE
Trakt wont download past 2 %

### ISSUE THREAD

**Issue by vidcon911** [razzeee/script.trakt#410]
I have upgraded to Kodi 18, after doing so I have not been able to download Trakt to  utilize library. I am using an Android Devise with Blaze key for video, program apps. I have attempted several times to clear memory and reinstall apps with no change. I have seen Trakt download up to 60%  then drop down to 2%, then give message that tract failed to download. There are other apps that have appeared just before it fails, however shows so briefly that I cant tell which app is being accessed. I have disabled "prevent outside apps" in the kodi program. I have access to any other app. Any assistance would be appreciated. 

    I am also getting "white bars"  at top and bottom of screen while watching movies, and shows. I don't know if  this can help diagnose failure to download Trakt or not. Thanks for any assistance you can provide.

**Comment by razzeee** [comment]
Sounds like a fishy kodi version. If you must run kodi 18 get it from here http://mirrors.kodi.tv/nightlies/android/
