### ISSUE TITLE
Not working with samba profile

### ISSUE THREAD

**Issue by Miloune** [razzeee/script.trakt#411]
Hello,

First of all, thanks for this great plugin!

I have a problem since i updated a major version of kodi? but before i don't know when, that worked like a charm. (I updated a few month ago)

When i use a special profile in advancedsettings.xml to store my settings on a samba server to share the configuration between all of my Kodi, the plugin stop working.

Here is the log plugin

> 21:54:47.414 T:8484   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: unable to open database file
                                            Traceback (most recent call last):
                                              File "C:\Users\fouqu\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py", line 14, in <module>
                                                Main()
                                              File "C:\Users\fouqu\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py", line 11, in Main
                                                script.run()
                                              File "C:\Users\fouqu\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\script.py", line 352, in run
                                                q = sqlitequeue.SqliteQueue()
                                              File "C:\Users\fouqu\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\sqlitequeue.py", line 60, in __init__
                                                with self._get_conn() as conn:
                                              File "C:\Users\fouqu\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\sqlitequeue.py", line 76, in _get_conn
                                                self._connection_cache[id] = sqlite3.Connection(self.path, timeout=60)
                                            OperationalError: unable to open database file
                                            -->End of Python script error report<--
21:55:06.002 T:11436   ERROR: Previous line repeats 1 times.

Here is a part of my advancedsettings.xml

> <pathsubstitution>
                                                <substitute>
                                                  <from>special://profile/Thumbnails/</from>
                                                  <to>smb://samba.mydomain/Kodi/Thumbnails/</to>
                                                </substitute>
                                                <substitute>
                                                  <from>special://profile/profiles.xml</from>
                                                  <to>smb://samba.mydomain/Kodi/profiles.xml</to>
                                                </substitute>
                                                <substitute>
                                                  <from>special://profile/addon_data/</from>
                                                  <to>smb://samba.mydomain/Kodi/addon_data/</to>
                                                </substitute>
                                                <substitute>
                                                  <from>special://profile/sources.xml</from>
                                                  <to>smb://samba.mydomain/Kodi/sources.xml</to>
                                                </substitute>
                                                <substitute>
                                                  <from>special://profile/mediasources.xml</from>
                                                  <to>smb://samba.mydomain/Kodi/mediasources.xml</to>
                                                </substitute>
                                                <substitute>
                                                  <from>special://profile/RssFeeds.xml</from>
                                                  <to>smb://samba.mydomain/Kodi/RssFeeds.xml</to>
                                                </substitute>
                                                <substitute>
                                                  <from>special://profile/favourites.xml</from>
                                                  <to>smb://samba.mydomain/Kodi/favourites.xml</to>
                                                </substitute>
                                              </pathsubstitution>

In case of you ask, Kodi have permission to write on this folder in my samba share.

Thanks,
Miloune

**Comment by razzeee** [comment]
Goto %appdata%\Kodi\userdata\addon_data\script.trakt and delete queue.db then retry

**Comment by Miloune** [comment]
@Razzeee 
There is no file queue.db in my appdata. Since i'm using samba, I find queue.db on it and deleted it. But still not working.

**Comment by razzeee** [comment]
Error log would be important

**Comment by Miloune** [comment]
Sorry i missed one line 

> 22:48:51.368 T:4744   ERROR: No handlers could be found for logger "resources.lib.sqlitequeue"

But i don't have more logs in my kodi.log

**Comment by razzeee** [comment]
Delete queue.db and post a complete log, without anything removed.

**Comment by Miloune** [comment]
Here you get full logs: https://pastebin.com/sPma9wJ7

**Comment by razzeee** [comment]
Did you remove the queue.db before creating that log, as I asked?

**Comment by Miloune** [comment]
Sure I did.

**Comment by razzeee** [comment]
Does the file get recreated? Because it's not logged somehow. Code should write the log due to https://github.com/trakt/script.trakt/blob/01782907b74cea266c26b0bedb6600f6f34d6ad5/resources/lib/sqlitequeue.py#L56

**Comment by Miloune** [comment]
No it didn't recreated the file. I tried to add some log just before the connection method but it never logged something. I dunno why...

**Comment by razzeee** [comment]
Maybe that's not the path it's using after all. Maybe the core method now returns something different then with earlier builds.

**Comment by Miloune** [comment]
Hello @Razzeee,
I come here with some news :)

So, i used `xbmc.log(self.path, xbmc.LOGERROR)` to debug the path and understand the problem.
First one, this logger works perfectly :)
Second, i used this logger just after `        self.path = os.path.join(self.path, 'queue.db')
        xbmc.log(self.path, xbmc.LOGERROR)`
So it logged this: ERROR: C:\Users\fouqu\AppData\Roaming\Kodi\userdata\addon_data\script.trakt\queue.db
Going into my addon_data on my %appdata% and the folder script.trakt doesn't exist. I make a new one and restarted my Kodi. No error from script.trakt and created queue.db successfully

2 things:

- script.trakt load perfectly my settings file from my samba share

- script.trakt is using queue.db on my %appdata% and not on my samba share. I'm pretty sure before something it used my sambashare (cuz i got an old queue.db file on my samba and you asked to delete it)

So, i think, i installed Kodi and configured it on RP and change path to use my SambaShare.
The second Kodi installation (on my computer) use samba share too, but when i installed the script, it already got a settings on my samba, this is probably why it didn't recreate a folder in my %appdata% ?

Anyway, should this queue.db shared between all of my Kodi through Samba? Or it's ok if it use a local folder?

Can give you more details if you want.

**Comment by razzeee** [comment]
Makes sense. It would probably be problematic to share these via the network, so it's fine. But that raises some more questions for me, as I wasn't aware of the option your using in the first place.

**Comment by Miloune** [comment]
In complement, had the same problem on my RP, did the same thing to log the path, and he is looking for "/storage/.kodi/userdata/profiles/TV/addon_data/script.trakt/queue.db"
I didn't know there is an addon_data per profil =/ Kodi Team probably did this change in Krypton release.
The plugin didn't create the folder tho.

**Comment by cat101** [comment]
Hi. I was experiencing the same problem running on XBIAN with Kodi 17.4  (see log bellow). I added logging as shown by Miloune and found that the directory `/home/xbian/.kodi/userdata/addon_data/script.trakt/` was not created. I created it and now things are working.

I hope this helps

Cat 

```
20:16:53.142 260281.843750 T:1924690864    INFO: initializing python engine.
20:16:53.142 260281.843750 T:1924690864   DEBUG: CPythonInvoker(8, /home/xbian/.kodi/addons/script.trakt/defaultscript.py): start processing
20:16:53.784 260282.484375 T:1924690864   DEBUG: -->Python Interpreter Initialized<--
20:16:53.785 260282.484375 T:1924690864   DEBUG: CPythonInvoker(8, /home/xbian/.kodi/addons/script.trakt/defaultscript.py): the source file to load
 is "/home/xbian/.kodi/addons/script.trakt/defaultscript.py"
20:16:53.790 260282.500000 T:1924690864   DEBUG: CPythonInvoker(8, /home/xbian/.kodi/addons/script.trakt/defaultscript.py): setting the Python path
 to /home/xbian/.kodi/addons/script.trakt:/home/xbian/.kodi/addons/script.module.addon.signals/lib:/home/xbian/.kodi/addons/script.module.arrow/lib
:/home/xbian/.kodi/addons/script.module.certifi/lib:/home/xbian/.kodi/addons/script.module.chardet/lib:/home/xbian/.kodi/addons/script.module.dateu
til/lib:/home/xbian/.kodi/addons/script.module.idna/lib:/home/xbian/.kodi/addons/script.module.requests/lib:/home/xbian/.kodi/addons/script.module.
simplejson/lib:/home/xbian/.kodi/addons/script.module.six/lib:/home/xbian/.kodi/addons/script.module.trakt/lib:/home/xbian/.kodi/addons/script.modu
le.urllib3/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2
.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat
20:16:53.790 260282.500000 T:1924690864   DEBUG: CPythonInvoker(8, /home/xbian/.kodi/addons/script.trakt/defaultscript.py): entering source directo
ry /home/xbian/.kodi/addons/script.trakt
20:16:53.791 260282.500000 T:1924690864   DEBUG: CPythonInvoker(8, /home/xbian/.kodi/addons/script.trakt/defaultscript.py): instantiating addon usi
ng automatically obtained id of "script.trakt" dependent on version 2.24.0 of the xbmc.python api
20:16:54.809 260283.515625 T:1924690864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-
-
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: unable to open database file
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/script.trakt/defaultscript.py", line 14, in <module>
                                                Main()
                                              File "/home/xbian/.kodi/addons/script.trakt/defaultscript.py", line 11, in Main
                                                script.run()
                                              File "/home/xbian/.kodi/addons/script.trakt/resources/lib/script.py", line 352, in run
                                                q = sqlitequeue.SqliteQueue()
                                              File "/home/xbian/.kodi/addons/script.trakt/resources/lib/sqlitequeue.py", line 60, in __init__
                                                with self._get_conn() as conn:
                                              File "/home/xbian/.kodi/addons/script.trakt/resources/lib/sqlitequeue.py", line 76, in _get_conn
                                                self._connection_cache[id] = sqlite3.Connection(self.path, timeout=60)
                                            OperationalError: unable to open database file
                                            -->End of Python script error report<--
```

**Comment by razzeee** [comment]
@cat101 
are you also running that advancedsettings.xml config?

**Comment by cat101** [comment]
Yes. I'm using a central MariaDB and I use advanced setting to share resource on a NAS

**Comment by razzeee** [comment]
Interesting part is, it should create the folder if it doesn't exist
https://github.com/trakt/script.trakt/blob/01782907b74cea266c26b0bedb6600f6f34d6ad5/resources/lib/sqlitequeue.py#L55

**Comment by razzeee** [comment]
Were you able to fix this?

**Comment by Miloune** [comment]
Didn't remember, but now I switched to Plex instead of Kodi.
