### ISSUE TITLE
Trakt Kodi add-on and Emby add-on not scrobbling

### ISSUE THREAD

**Issue by PhilipReidy** [razzeee/script.trakt#412]
So far I'm able to scrobble movies fine but I can't get it to scrobble any TV show and I don't know if it's just a problem with the trakt add-on or emby add-on or both so I'm hoping someone can help me with it. 

I'm using Kodi 17.5

https://paste.ubuntu.com/25879590/

**Comment by razzeee** [comment]
Seems to be emby not supplying a episode id

**Comment by PhilipReidy** [comment]
I see and is there anyway to get this to work I really like that I can rate and track the movies I watch, so I would like it to work with TV shows

**Comment by razzeee** [comment]
Not sure which emby addon your using, but they seem to insert the data somehow. They just seem to not do it right or at all for episodes. So if it is indeed working for you with movies, they "just" need to do the similar for episodes. See: https://github.com/trakt/script.trakt/blob/master/resources/lib/scrobbler.py#L184-L188

**Comment by PhilipReidy** [comment]
Okay thank you very much Razzeee I'm using the official Emby add-on not Embycon though, I will let them know the situation and hopefully they can fix it.

**Comment by razzeee** [comment]
Let me know if you need anything

**Comment by tchirou** [comment]
Hi Philip
I have the same issue
Did you report this on Emby forums ?
Thanks

**Comment by tchirou** [comment]
Never mind 
I have found your post over there
Thanks
