### ISSUE TITLE
Trakt Started Supporting Absolute Number/ Scrobbling Absolute Episodes Still Fails

### ISSUE THREAD

**Issue by Eisa01** [razzeee/script.trakt#413]
Hello,

Trakt.tv now supports Absolute Episode Numbering for Anime, however Kodi Trakt Scrobbler still fails to recognize them.
Cannot mark any episode higher than season 1 as watched/ play count does not update/ watching now status does not update.

[Trakt.tv Absolute Order Support Sample](https://i.imgur.com/V5i7IEk.png)

Basically, it is still impossible for Trakt scrobbler to recognize absolute numbering despite the recent changes in Trakt.tv of supporting Absolute Numbering.

Is it still impossible despite the changes?

Thanks.

**Comment by razzeee** [comment]
No, the trakt changes were just on the frontend side of things, afaik. Doesn't change anything.

Also duplicate of #168
