### ISSUE TITLE
Scrobbling starts but does not finish on OSMC

### ISSUE THREAD

**Issue by Matheos96** [razzeee/script.trakt#417]
Hey! I Recently switched from OpenELEC to OSMC and it's all been working fine except for one thing. 
I installed script.trakt and everything seemed fine but the oddest thing is, I see the notification "Scrobbling bla bla" when I start watching a movie or episode but when it finishes there is not "Movie successfully scrobbled" or whatever it's supposed to say, there is nothing at all and nothing is marked as watched on my trakt account. I've checked the trakt settings in the addon countless times and they are as they should be. 

I was thinking that maybe I'd see what is wrong if I enabled debug logging but I did not, just the opposite. When debug logging was enabled trakt started working properly, scrobbling worked and everything was fine, but ofc I don't want that fps and cpu stats on my screen constantly so I turned it off, still worked, problem solved? No. After a reboot having debug logging disabled it once again stopped working... 

Is this a known problem? I installed my OSMC 2 days ago so everything should be the latest version... It's really frustrating. 

Any ideas?

**Comment by razzeee** [comment]
I don't know if it's a known problem, it just feels like OSMC often comes up with problems, somehow.
Other then giving a debug log, no idea.

**Comment by Matheos96** [comment]
Is there any way for me to log trakt's activities? Enabled the logging in system settings in kodi but in the log it does not say anything abotu trakt. And now again, scrobbling worked when logging was on. 

I've also now noticed that if I watch something and finish it (as I said the scrobbling will start and the synced timeline will appear on trakt.tv while I watch), after finishing or stopping, it takes some time until trakt.tv realizes I stopped, after shutting down kodi I can still sometimes see that it thinks I am watching... However, once it dissapears, nothing was marked as watched on trakt...

**Comment by razzeee** [comment]
> Is there any way for me to log trakt's activities? Enabled the logging in system settings in kodi but in the log it does not say anything abotu trakt. And now again, scrobbling worked when logging was on.

https://github.com/trakt/script.trakt#creating-logfiles

> I've also now noticed that if I watch something and finish it (as I said the scrobbling will start and the synced timeline will appear on trakt.tv while I watch), after finishing or stopping, it takes some time until trakt.tv realizes I stopped, after shutting down kodi I can still sometimes see that it thinks I am watching... However, once it dissapears, nothing was marked as watched on trakt...

Sounds like it's not sending a stop message. In that case, it's expected, to keep on watching and not mark it as watched. As scrobbling needs a stop at the end of the show.

**Comment by Matheos96** [comment]
This is a cut out from the log. But as I said, the scrobbling actually ends when I have debug logging on... so no weird things here? As u see I just put on a movie after enabling debug logging, skipped to the end (failing the skipping a few times) and then ones near the end I hit stop. Obviously it worked but if you find any reason from here to why it only works when debug logging is on?
```
`01:13:24.684 T:1735128048   DEBUG: [script.trakt] resources.lib.service: [traktPlayer] onPlayBackStarted() - activePlayers: [{u'playerid': 1, u'type': u'video'}]

01:13:24.684 T:1735128048   DEBUG: [script.trakt] resources.lib.service: [traktPlayer] onPlayBackStarted() - Doing Player.GetItem kodiJsonRequest

01:13:24.694 T:1735128048   DEBUG: GetMovieId (ftp://USERNAME@192.168.0.111:21/Movies/Aliens Special Edition (1986)/Aliens Special Edition 1986.mp4), query = select idMovie from movie where idFile=958

01:13:24.721 T:1735128048   DEBUG: [script.trakt] resources.lib.service: [traktPlayer] onPlayBackStarted() - {u'item': {u'type': u'movie', u'id': 4, u'label': u'Aliens'}}

01:13:24.722 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Queuing for dispatch: {'action': 'started', 'type': u'movie', 'id': 4}

01:13:24.830 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Queued dispatch: {u'action': u'started', u'type': u'movie', u'id': 4}

01:13:24.831 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Dispatch: {u'action': u'started', u'type': u'movie', u'id': 4}

01:13:24.831 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: playbackStarted(data: {u'type': u'movie', u'id': 4})

01:13:24.831 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Watching: movie

01:13:24.937 T:1058006000   DEBUG: CDVDClock::ErrorAdjust - CVideoPlayerAudio::OutputPacket - error:-45455.027125, adjusted:-45455.027125

01:13:25.833 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Warning: Cant find playlist length, assuming that this item is by itself

01:13:25.857 T:1735128048   DEBUG: [script.trakt] resources.lib.kodiUtilities: getMovieDetailsFromKodi(): {u'moviedetails': {u'movieid': 4, u'title': u'Aliens', u'lastplayed': u'2017-11-24 01:10:43', u'label': u'Aliens', u'imdbnumber': u'tt0090605', u'file': u'ftp://kodi@192.168.0.111:21/Movies/Aliens Special Edition (1986)/Aliens Special Edition 1986.mp4', u'year': 1986, u'playcount': 1}}

01:13:25.866 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Movie type, curVideoInfo: {'rating': 0, u'movieid': 4, u'title': u'Aliens', 'ids': {'imdb': u'tt0090605'}, 'watched': 1, 'watched_at': u'2017-11-23 23:10:43+00:00', u'year': 1986, 'collected': 1, 'plays': 1}

01:13:25.867 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: scrobble()

01:13:25.882 T:1735128048   DEBUG: [script.trakt] urllib3.connectionpool: Starting new HTTPS connection (5): api.trakt.tv

01:13:26.607 T:1735128048   DEBUG: [script.trakt] urllib3.connectionpool: https://api.trakt.tv:443 "POST /scrobble/start HTTP/1.1" 201 225

01:13:26.614 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Scrobble response: {u'action': u'start', u'progress': 0.0215280039276752, u'sharing': {u'tumblr': False, u'twitter': False, u'facebook': False}, u'id': 0, u'movie': {u'year': 1986, u'ids': {u'tmdb': 679, u'imdb': u'tt0090605', u'slug': u'aliens-1986', u'trakt': 553}, u'title': u'Aliens'}}

01:13:26.615 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Pre-Fetch result: {u'action': u'start', u'progress': 0.0215280039276752, u'sharing': {u'tumblr': False, u'twitter': False, u'facebook': False}, u'id': 0, u'movie': {u'year': 1986, 'movieid': 4, u'ids': {u'tmdb': 679, u'imdb': u'tt0090605', u'slug': u'aliens-1986', u'trakt': 553}, u'title': u'Aliens'}}; Info: {'rating': 0, u'movieid': 4, u'title': u'Aliens', 'ids': {'imdb': u'tt0090605'}, 'watched': 1, 'watched_at': u'2017-11-23 23:10:43+00:00', u'year': 1986, 'collected': 1, 'plays': 1}

01:13:26.620 T:1959096320   DEBUG: ------ Window Init (DialogNotification.xml) ------

01:13:33.336 T:1735128048   DEBUG: [script.trakt] urllib3.connectionpool: https://api.trakt.tv:443 "POST /scrobble/start HTTP/1.1" 201 None

01:13:33.345 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Scrobble response: {u'action': u'start', u'progress': 95.7926985540089, u'sharing': {u'tumblr': False, u'twitter': False, u'facebook': False}, u'id': 0, u'movie': {u'year': 1986, u'ids': {u'tmdb': 679, u'imdb': u'tt0090605', u'slug': u'aliens-1986', u'trakt': 553}, u'title': u'Aliens'}}

01:13:41.952 T:1735128048   DEBUG: [script.trakt] resources.lib.service: [traktPlayer] onPlayBackSeek(time: 9138000, offset: 252709) - 1

01:13:41.952 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Queuing for dispatch: {'action': 'seek', 'offset': 252709, 'time': 9138000}

01:13:42.423 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Queued dispatch: {u'action': u'seek', u'time': 9138000, u'offset': 252709}

01:13:42.424 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Dispatch: {u'action': u'seek', u'time': 9138000, u'offset': 252709}

01:13:42.424 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: playbackSeek()

01:13:42.424 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: scrobble()

01:13:42.673 T:1735128048   DEBUG: [script.trakt] urllib3.connectionpool: https://api.trakt.tv:443 "POST /scrobble/start HTTP/1.1" 201 None

01:13:42.681 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Scrobble response: {u'action': u'start', u'progress': 98.6089753965685, u'sharing': {u'tumblr': False, u'twitter': False, u'facebook': False}, u'id': 0, u'movie': {u'year': 1986, u'ids': {u'tmdb': 679, u'imdb': u'tt0090605', u'slug': u'aliens-1986', u'trakt': 553}, u'title': u'Aliens'}}

01:13:47.707 T:1735128048   DEBUG: [script.trakt] resources.lib.service: [traktPlayer] onPlayBackStopped() - 0

01:13:47.707 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Queuing for dispatch: {'action': 'stopped'}
.....................................
01:13:49.123 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Queued dispatch: {u'action': u'stopped'}

01:13:49.123 T:1735128048   DEBUG: [script.trakt] resources.lib.service: Dispatch: {u'action': u'stopped'}

01:13:49.123 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: playbackEnded()

01:13:49.123 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: scrobble()

01:13:49.435 T:1735128048   DEBUG: [script.trakt] urllib3.connectionpool: https://api.trakt.tv:443 "POST /scrobble/stop HTTP/1.1" 201 None

01:13:49.443 T:1735128048   DEBUG: [script.trakt] resources.lib.scrobbler: Scrobble response: {u'action': u'scrobble', u'progress': 98.6386611261735, u'sharing': {u'tumblr': False, u'twitter': False, u'facebook': False}, u'id': 3246225484L, u'movie': {u'year': 1986, u'ids': {u'tmdb': 679, u'imdb': u'tt0090605', u'slug': u'aliens-1986', u'trakt': 553}, u'title': u'Aliens'}}

01:13:49.443 T:1735128048   DEBUG: [script.trakt] resources.lib.rating: Rating Check called for 'movie'

01:13:49.444 T:1735128048   DEBUG: [script.trakt] resources.lib.rating: 'movie' is configured to not be rated.`
```

**Comment by razzeee** [comment]
Plse do a log without debug logging then, while it's not as helpful, it might still show the error

**Comment by Matheos96** [comment]
@Razzeee I finally managed to record the error :) It took a while cuz after the last time I had had the debug logging on it decided to work for a couple of days... :P 

> 00:36:36.709 T:1734079472   FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ReadTimeout'>
                                            Error Contents: (ReadTimeoutError("HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)",),)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/service.py", line 44, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 248, in playbackEnded
                                                self.__scrobble('stop')
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 288, in __scrobble
                                                response = self.traktapi.scrobbleEpisode(self.traktShowSummary, self.curVideoInfo, watchedPercent, status)
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/traktapi.py", line 163, in scrobbleEpisode
                                                progress=percent)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 38, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 22, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/scrobble.py", line 448, in stop
                                                **kwargs
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 38, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 22, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/scrobble.py", line 130, in action
                                                'validate_token'
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 154, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 109, in request
                                                return self.send(prepared)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 127, in send
                                                response = self.session.send(request, timeout=timeout)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 618, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 521, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)
                                            -->End of Python script error report<--

**Comment by gregersn** [comment]
I get this exact same error in my logs with Kodi 17.6 on Ubuntu 17.04

**Comment by Matheos96** [comment]
@Razzeee Please would you look at the log please?

**Comment by razzeee** [comment]
Seems to be a normal timeout, can happen with slow connections of if trakt itself is under high connection pressure. Should happen all the time.

**Comment by Matheos96** [comment]
My internet is 100/10... Shld not be a problem right? And it never finishes.But always starts, even after pausing and on pausing it sends pause notification. But never finishes... So weird and annoying having to log everything manually on trakt.tv and also while logging (even if osmc is off) I see on my dashboard that trakt still thinks I am watching :

**Comment by gregersn** [comment]
Well, this is something that has started relatively recent. And anyway, that is an exception then, that should be handled more gracefully. I have used this trakt script for a long time now, and it was always able to submit the end status. But the last few months it only goes through about 1 in a 100 watched things.

**Comment by Matheos96** [comment]
U too huh? Is it a problem with the addon or trakt.tv itself tho?

**Comment by razzeee** [comment]
More and complete logs might help. Timeouts can be pretty random, but should just go away when trying again. So there might be something else at play here.

**Comment by MCs88** [comment]
I've also experienced the same issue since I've been using scrobbling plugin for the last ~2 years. First I saw it with Plex scobbling plugin which uses the same python trakt client as this plugin, and when I switched to Kodi a few weeks ago here it is again.

I made a quick fix in the script.module.trakt lib that seems to solve the problem (at least in my case), @Razzeee please take a look at it, and feel free to merge it back or just use it as a base for a more elegant solution.
https://github.com/MCs88/script.module.trakt/commit/e8dba13f83ff7936e1b2e82a76987000ca25a840

**Comment by Matheos96** [comment]
@MCs88 How do I implement this solution? 
After a month this is still happening to me btw.. Was away for 2 weeks on winter holidays, came back, 3 first movies/episodes scrobbled fine, then it stopped again. What the **** is this? It makes no sense to me how it can work a couple of times after a period of not using it...

**Comment by MCs88** [comment]
@Matheos96 try the following:

1. SSH into your device, locate the addons directory in OSMC (I use LibreElec so I'm not sure where it is in OSMC, but for me it's in ~/.kodi/addons/ )
2. Make a backup of ~/.kodi/addons/script.module.trakt/lib/trakt/core/http.py then replace it with https://github.com/MCs88/script.module.trakt/blob/master/lib/trakt/core/http.py
3. Delete ~/.kodi/addons/script.module.trakt/lib/trakt/core/http.pyo
4. optionally you can modify the retry count by setting the DEFAULT_HTTP_MAX_RETRIES parameter to a higher number (the default is 3) in ~/.kodi/addons/script.module.trakt/lib/trakt/core/configuration.py (if you do don't forget to delete the configuration.pyo file too)
5. Reboot the device 

If something goes wrong or the scrobbling doesn't even start just restore http.py from backup, delete the pyo and reboot.

I'm not sure what the root cause is, but I assume it's something network related around the SSL handshake and SSL connection pooling. It can be ISP or CloudFlare related too, I don't know. My code modification just adds a few new network related error case to the existing retry logic of the Trakt API calls.

**Comment by razzeee** [comment]
@fuzeman this might be interesting for you?

**Comment by Matheos96** [comment]
@MCs88 Seems to be working after applying ur fix! Thx. Hope it keeps working :)

**Comment by MCs88** [comment]
@Matheos96 Great to hear that!

**Comment by Matheos96** [comment]
@MCs88 You know what, scratch that, it worked for two episodes and one movie yesterday but today (the day after applying the fix and also another reboot of my RPi) it is back to not scrobbling... Seems like deleting the pyo + reboot made it work until another reboot was made...

**Comment by MCs88** [comment]
Have you tried to increase the retry count too?

As for increasing this, I might missed one point:
You have to modify it in client.py:
`adapter_kwargs.setdefault('max_retries', 3)` 
Try to increase it to 5 or 10

**Comment by Matheos96** [comment]
@MCs88 Changing the retries did close to nothing... (tried both 5 and 10) I did however realize, that deleting the http.pyo, forcing the plugin to make a new one, works 100% of the time. For a couple of scrobbles, then I have to do it again. What that depends on, I don't know, but I'm pretty sure it would run pretty smothly if the .pyo was deleted after every single shutdown. Haven't had the time to try how many scrobbles it works for without rebooting the system but straight after pyo deletion and reboot it allways works (http.pyo that is)

**Comment by MCs88** [comment]
My last guess is to disable connection reuse:
Change this in http.py:
`def __init__(self, client, adapter_kwargs=None, keep_alive=True):`
to
`def __init__(self, client, adapter_kwargs=None, keep_alive=False):`

Edit: @Matheos96 I'm using it with keep_alive=False in the last 2 days and all of the scrobbling were successful. Give it a try.

**Comment by rgmarques** [comment]
Same issue here, last kodi version on Xbian. MCs88 fix worked like a charm...
Thanks for the effort man!

**Comment by MCs88** [comment]
Happy to hear that! 👍

**Comment by Matheos96** [comment]
Reinstalled OSMC (Latest version) yesterday and I am still having this issue... I know this is a closed issue but I just wanted to leave an update that for some reason this is still haunting me and trakt.script won't work as it should right out of the box for me.... The fix does work though

**Comment by razzeee** [comment]
Well if it should be fixed and if it's the correct fix needs to be decided upstream https://github.com/fuzeman/trakt.py/blob/master/trakt/core/http.py

**Comment by Matheos96** [comment]
> Well if it should be fixed and if it's the correct fix needs to be decided upstream https://github.com/fuzeman/trakt.py/blob/master/trakt/core/http.py

Oh... I did not realize that that was an external library... Well if it is not relevant in all cases, could one not just override the default parameter from the trakt.py library?

**Comment by razzeee** [comment]
> 
> 
> > Well if it should be fixed and if it's the correct fix needs to be decided upstream [fuzeman/trakt.py:trakt/core/http.py@`master`](https://github.com/fuzeman/trakt.py/blob/master/trakt/core/http.py) [](/fuzeman/trakt.py/blob/HEAD@{2019-10-29T07:44:21Z}/trakt/core/http.py)
> 
> Oh... I did not realize that that was an external library... Well if it is not relevant in all cases, could one not just override the default parameter from the trakt.py library?

Overwriting would mean, that we would have to copy/inline the whole library, which is a no go in my book. Sorry.

**Comment by Matheos96** [comment]
> > > Well if it should be fixed and if it's the correct fix needs to be decided upstream [fuzeman/trakt.py:trakt/core/http.py@`master`](https://github.com/fuzeman/trakt.py/blob/master/trakt/core/http.py)
> > 
> > 
> > Oh... I did not realize that that was an external library... Well if it is not relevant in all cases, could one not just override the default parameter from the trakt.py library?
> 
> Overwriting would mean, that we would have to copy/inline the whole library, which is a no go in my book. Sorry.

Yea I did not mean overwriting it in the default library. I haven't looked into how this object is made or when but if it is the trakt.py library that calls/creates it then I guess we are out of luck. In case the initiating is done in script.trakt one could maybe do something abt it tho? But since u say it would have to be done in the original library I guess we can't do much abt it...

**Comment by razzeee** [comment]
Well I guess you should raise an issue over there

Matheos Mattsson <notifications@github.com> schrieb am Mi., 30. Okt. 2019,
18:10:
