### ISSUE TITLE
sync accross multiple devices?

### ISSUE THREAD

**Issue by port-of-forward** [razzeee/script.trakt#419]
I did a search but could not find any info so I hope that its ok to ask the question here.
I use trakt on 2 different fire devices with TerrariumTV. Should the trakt account  be synchonised on my devices? I am signed in to the same trakt account on all devices.
Thank you for any help.

**Comment by razzeee** [comment]
I guess this question can be closed as a quick google what TerrariumTV is, shows that it has been shutdown.
