### ISSUE TITLE
Trakt add-on for Kodi on Xbox one

### ISSUE THREAD

**Issue by khyaniv30** [razzeee/script.trakt#425]
Hi, 
The add-on not working in Xbox.
Kodi shows error right after add-on installation.
In addition add-on not running and can't authorize the account.

**Comment by razzeee** [comment]
If you can generate a logfile I might be able to do something, but I can't guarantee.

**Comment by tdunahoo71** [comment]
Having same issue as well.  How do I generate log file and how do I get it sent to you from Xbox one

**Comment by khyaniv30** [comment]
Log file:
(link: https://paste.ubuntu.com/26298715/) paste.ubuntu.com/26298715/

Thanks.

**Comment by razzeee** [comment]
That's a problem with Kodi itself, needs to be fixed upstream, sorry.

**Comment by razzeee** [comment]
And according to my sources it might be fixed in the current builds. Not sure when they will get updated on the store, but sometimes next week or the week there after.

**Comment by khyaniv30** [comment]
Ok I will wait.
Thanks

**Comment by khyaniv30** [comment]
After Kodi last update works fine.
Thanks.
