### ISSUE TITLE
Sync playback progress between devices

### ISSUE THREAD

**Issue by farfromrefug** [razzeee/script.trakt#427]
I am trying to use trakt to migrate my kodi watched ans playback progress to another device.
It worked just fine for watched but not for playback progress.
I can see what I am watching on trakt website so I guess playback progress are correctly uploaded to trakt.tv
Kodi log does not mention any error on both devices

Should that work? I mean does trakt sync all playback progresses between devices?
If so what should be done to import playback progresses on a new kodi install?

Thanks

**Comment by tronder88** [comment]
Having the same problem, trying to sync between Plex and Kodi. Manual started sync works on "watched" status, but not progress of current movie.
  
similar to this issue: https://github.com/trakt/Plex-Trakt-Scrobbler/issues/476

**Comment by razzeee** [comment]
Well it did work as far as I knew. Would have to investigate.

**Comment by farfromrefug** [comment]
@Razzeee sorry for not responding earlier. For me the problem was actually on Kodi's side. Or maybe the emby kody's addon.
I thought the progress playback was not syncing but it was. The issue is that for some reason the "continue watching" widget was empty. But i went inside my library, the library items were correctly showing their progress.
So for me no real issue on trakt's side.

On question however, do you sync the "date" progress for each item? I ask because i see a weird order after the sync in the "in progress" widget. Still might be on kodi's side.

Thanks and sorry for bothering you

**Comment by razzeee** [comment]
There is no date for "in progress", they just get collected and send whenever. So the timestamp might correspond to whenever and be in a random order of things that get send in that moment.
Feel free to open up a ticket about that.

**Comment by farfromrefug** [comment]
@Razzeee that explains it. Will look at it
