### ISSUE TITLE
Series scraped with TMDB sync with TVDB id

### ISSUE THREAD

**Issue by nrosier** [razzeee/script.trakt#428]
For several reasons I would like to switch from TVDB to TMDB scraping for TV-series.
I've switched 2 series to TMDB scraping but these get scrobbled with the TVDB ID on trakt.

```
{'rating': 0, u'tvshowid': 192, u'title': u'Lucas en co', 'ids': {'tvdb': u'76014'}, u'userrating': 0, u'year': 2017}
{'rating': 0, u'tvshowid': 191, u'title': u'Nachtwacht', 'ids': {'tvdb': u'64089'}, u'userrating': 0, u'year': 2015}
```
MySQL shows following for these series:
```
MariaDB [MyVideos107]> select c00,uniqueid_value,uniqueid_type  from tvshow_view where uniqueid_type = 'tmdb';
+-------------+----------------+---------------+
| c00         | uniqueid_value | uniqueid_type |
+-------------+----------------+---------------+
| Nachtwacht  | 64089          | tmdb          |
| Lucas en co | 76014          | tmdb          |
+-------------+----------------+---------------+
2 rows in set (3.05 sec)
```
As you can see in the DB it is marked as a tmdb series-id but the the addon uses these id's as tvdb.

**Comment by razzeee** [comment]
On which kodi version are you? Can you do a backup and try the master
branch?

**Comment by nrosier** [comment]
Running 17.6 (OSMC)
I've also got a 2nd box with Leia (gmc OSMC builds). I can test it there if needed.

**Comment by razzeee** [comment]
Both would be fine. It might work with the newest version of this addon, but I haven't released it yet as I haven't tested it enoght / want to get some things more in.

**Comment by nrosier** [comment]
Where do I find it. The official github master or your personal?

**Comment by nrosier** [comment]
Moved ~/.kodi/addons/script.trakt out of the way. checked out master branch from trakt/script.trakt and copied it to ~/.kodi/addons/
Restarted Kodi and started a sync. Problem persists. TMDB ID is used as TVDB ID

**Comment by nrosier** [comment]
Did some more testing. For 1 series (Nachtwacht) it seems to work correctly although debug shows the wrong id-type being used. For the other series it syncs with the incorrect tvdb series.
I've tried to spot the difference between the 2 series but so far no luck. Will see if I can "migrate" another series to TMDB and verify trakt sync to the correct ID.

**Comment by razzeee** [comment]
With the new of the old version of the plugin?

**Comment by nrosier** [comment]
Both the stable  version and the master branch version.

**Comment by nrosier** [comment]
I've switched a couple of other series to TMDB. Lucas en co (TMDB 76014) is the only one so far giving problems. Any way I can debug this issue further?

**Comment by nrosier** [comment]
Now scrobbling seems to fail completely; I've captured the logs here: http://paste.debian.net/1009237/

**Comment by razzeee** [comment]
Can you try with kodis default skin, estuary?

**Comment by nrosier** [comment]
Finally had some time to test. 1st test seems to indicate it might be skin related. With estuary I noticed some Nachtwacht episodes got updated from trakt to Kodi when running the script. Will have to test if the other way around also works.

**Comment by nrosier** [comment]
Unfortunatly the problem also happens with Estuary. I had scrobbled some episodes manually and noticed in the logs the script wanted to update these on Kodi. But further analysis shows it still says it is using the id as tvdb id in stead of tmdb id:

```
16:59:53.785 T:2591060736   DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Episodes updated: Nachtwacht [tvdb: 64089] - S01E11, S02E06, S03E02
16:59:53.786 T:2591060736   DEBUG: [script.trakt] resources.lib.syncEpisodes: [traktUpdateEpisodes] Shows to update {'shows': [{'seasons': [{'episodes': [{'rating': 0, 'title': u'1x11. De Spelduivel', 'number': 11, 'ids': {'tmdb': u'1374102'}, 'watched_at': u'2018-02-10 17:51:43+00:00', 'collected_at': u'2018-02-03 18:06:52+00:00', 'runtime': 0}], 'number': 1}, {'episodes': [{'rating': 0, 'title': u'2x06. De Meestervampier', 'number': 6, 'ids': {'tmdb': u'1354092'}, 'watched_at': u'2018-02-10 18:17:47+00:00', 'collected_at': u'2018-01-10 17:35:18+00:00', 'runtime': 0}], 'number': 2}, {'episodes': [{'rating': 0, 'title': u'3x02. De Greystook', 'number': 2, 'ids': {'tmdb': u'1417368'}, 'watched_at': u'2018-02-08 18:22:08+00:00', 'collected_at': u'2018-01-16 18:59:21+00:00', 'runtime': 0}], 'number': 3}], 'year': 2015, 'ids': {'tvdb': u'64089'}, 'title': u'Nachtwacht'}]}
```

**Comment by razzeee** [comment]
Did you try that with master branch of this script?

**Comment by razzeee** [comment]
This should be fixed, as we've been using the new ids system form kodi for some time. Feel free to reopen if not.
