### ISSUE TITLE
rebuild?

### ISSUE THREAD

**Issue by jpf55** [razzeee/script.trakt#430]
I have Trakt setup in the bedroom using Android Kodi and in the living room using Mac Kodi. 
The living room has the hard drives and the bedroom accesses them using SMB. 
I am having problems with the results when running the Kodi Trakt from the Addons. 
I have included a file describing and commenting the progress when I run Trakt. 
By the way, I get similar results whether from the living room or the bedroom. 
So My question is can I rebluid my Trackt database and if so how? 

[Trakt_rebuild_or_repair.txt](https://github.com/trakt/script.trakt/files/1714704/Trakt_rebuild_or_repair.txt)
[kodi.log](https://github.com/trakt/script.trakt/files/1714705/kodi.log)
Thanks for your help

**Comment by razzeee** [comment]
Rebuild your database as in reset everything? Remove every watched, collection and rating?

**Comment by jpf55** [comment]
Thanks for the quick reply but how would I do that?
JP

**Comment by razzeee** [comment]
Check out this project https://github.com/damienhaynes/TraktRater/releases it has a maintenance feature, that will do that.
