### ISSUE TITLE
Movies are not scrobbled on Leia builds

### ISSUE THREAD

**Issue by MCs88** [razzeee/script.trakt#432]
Hi,

Recently I started to play with Kodi Leia builds and I noticed that TV show episodes are scrobbled fine with the plugin, but movies are not. Movie scrobbling is enabled in the settings. In the log files there's no sign that the plugin tried to start scrobbling, it seems that it didn't notice the start event.

Can someone try it with Leia?

**Comment by razzeee** [comment]
Been using Leia for approximatly 1 1/2 years now. Watched a movie today and yesterday, both show up fine in trakt. Using android tv.

**Comment by MCs88** [comment]
I use an Amlogic device with community LibreElec builds (tried on 2 different device in the previous 2 days).
Scrobbling movies works on both with the Krypton builds. 
Every install was a full install from scratch.

**Comment by razzeee** [comment]
Well no log no error :)

**Comment by MCs88** [comment]
See attached:
[new_kodi.log](https://github.com/trakt/script.trakt/files/1821449/new_kodi.log)

Looks like there are items in the movies library which are scrobbled but not all.
The log contains playback of 4 item, 1 TV show and 1 movie scrobbled fine, for the other 2 movie scrobble didn't start and I see no trace in the log.

**Comment by razzeee** [comment]
Interesting, but not very helpful due to missing traces :(

**Comment by MCs88** [comment]
I close this issue and hope it will go away with a newer Kodi/LibreElec build.
