### ISSUE TITLE
Kodi trakt.tv keeps on crashing while TVShow-Scrobble

### ISSUE THREAD

**Issue by l-IN10SE-l** [razzeee/script.trakt#439]
Hey guys,

now I logged into kodi. I was refreshing and downloading the kodi.log:

https://www.dropbox.com/s/vlchxa6dpq0o0pq/kodi.log?dl=0

This was the log like 5 seconds before it crashed.

This is the old kodi log:

https://www.dropbox.com/s/gwd2k5gxjnljyxc/kodi.old.log?dl=0

the old log is including the crash. Can someone please tell me why it crashes? I am using this setup since 3 years without problems.

Now had playstates for around 20 shows. Sometimes it crashes after 1 show scrobbling, now after 20 shows. Next time after 15 shows. But it always keeps on crashing and always rebooting kodi.

Can someone please help me with that? 

Movie scrobble, playcount and ratings syncs always perfectly! Only issues with tvshows. Kodi keeps on freezing all the time, but not always at same position.

**Comment by razzeee** [comment]
I'm not seeing any crash in those logs, not convinced it's an addon. Can you provide a crash log?

**Comment by l-IN10SE-l** [comment]
Hey Razzeee, thank you so much for your time and your effort to answer!

Sadly I am pretty sure it is the trakt plugin or something changed on the trakt.tv homepage. I have the feeling maybe they set a limit for how many information is allowed to process. Or something like that.

I am running in same crashing issue, always during library sync to trakt.tv of TV SHOWS (movies runs perfectly). I have two devices: OSMC Vero4k and RPI3 with OSMC and it happens on both devices at nearly same time (library sync).

So yesterday I stopped the automatic sync of library and ran the trakt.tv plugin by myself. And it happened the same thing. It crashed, freezed and rebooted the Vero4K. But this time I saw that the plugin was freezing (Syncing TV Show Episodes 50 of ...). First I thought it is some of my data, because kept on crashing on same (huge) show. I took it out of library, but same happened.

Yesterday I installed libreelec on my RPI3, just to see, because since three years I never had problems with it. I am scanning my library right now and checking afterwards.

To clarify: My library is huge (2028 movies and 27800 Episodes in 385 TV Shows). I think there is a problem how the data is processed to trakt.tv. But I never had this issue in my 3 years before. Something changed.

I have a sync problem with emby trakt.tv plugin too. It keeps on not syncing the library, only the playstates. But thats another story for another forum.

How do I provide a crash log? Those two logs are exactly between and from the crash from yesterday with all debug enabled (trakt.tv plugin debug mode too). So can you explain me a bit what you need?

**Comment by razzeee** [comment]
There should be another type of log, it it really crashes. That's all I can remember right now, as I'm not at home.

**Comment by l-IN10SE-l** [comment]
Hey Razzeee,

no, I dont find another one. please let me know what exactly you mean and I send it to you. It definetely crashes, it freezes totally and reboots.

I now run it again. It needs for a playstate, so one watched episode, around 2 - 3 minutes. Every two or 3 minutes, NCIS goes one playstate up 22/305, 23/305, 24/305...

I think something really, really slows it down.

**Comment by razzeee** [comment]
This is what it looks like for me 
![image](https://user-images.githubusercontent.com/5943908/41744899-826d7acc-75a5-11e8-8c1d-dc16256049bd.png)

**Comment by razzeee** [comment]
It might be easier to reach out to the trakt.tv guys first

**Comment by razzeee** [comment]
Closing, as there was no response.
