### ISSUE TITLE
Synchronizing in background 

### ISSUE THREAD

**Issue by nour-elghareeb** [razzeee/script.trakt#442]
Hello,

Could you please an option to send the manual synchronization process to the background? Depending on the amount of data being synchronized and the internet speed, it usually takes a long time (usually more than 10 minutes in my case). It leaves kodi unusable while the process is running and it's really frustrating. 

Thank you for the plugin, it's really helpful.

**Comment by glensc** [comment]
i was wondering is it possible to tell to sync via xmlrpc, then could just let it sync during night.

there's this doc:
- https://github.com/trakt/script.trakt/wiki/Action%3A-sync

but not clear how to invoke that over xmlrpc

**Comment by glensc** [comment]
I found answer to my question, it's jsonrpc:
- https://github.com/trakt/script.trakt/issues/192#issuecomment-70359374

**Comment by glensc** [comment]
this is now in readme:
- https://github.com/trakt/script.trakt#invoke-sync-via-jsonrpc

via:
- https://github.com/trakt/script.trakt/pull/462

so @nour-elghareeb or any maintainers can close this issue.
