### ISSUE TITLE
Mark as seen

### ISSUE THREAD

**Issue by luizoti** [razzeee/script.trakt#443]
When I use the option that marks the episodes as "seen" I get this error, can anyone help me?

What are you trying to get the symptoms to be taken care of, whenever there is an error, someone has an idea of ​​what can be?

https://pastebin.com/gGWFj32Y

**Comment by razzeee** [comment]
It fails to get the DBID, so is the item your trying this on added to your local database? As in your movie library or series library.

**Comment by luizoti** [comment]
Yes the content is in the library, so I realized this error happens only when 
I use the "mark as assisted in trakt" option in the context menu.

 If I just watch the episode, he usually does not make a mistake.
