### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by jeffski10** [razzeee/script.trakt#444]
I'm seeing an error installing on 18.0-BETA1 Git:20180812-881a9e69a8). Platform: Windows NT x86 64-bit . 

20:14:54.808 T:3980   ERROR: SQL: [Addons27.db] Abort due to constraint violation
                                            Query: insert into package(id, addonID, filename, hash)values(NULL, 'script.trakt', 'special://home/addons/packages/script.trakt-3.2.1.zip', 'bbd81b51398e560016e1b24c0aee4c5651b124a3470206cdae314ff1dcceed96')
20:14:54.808 T:3980   ERROR: CDatabase::ExecuteQuery - failed to execute query 'insert into package(id, addonID, filename, hash)values(NULL, 'script.trakt', 'special://home/addons/packages/script.trakt-3.2.1.zip', 'bbd81b51398e560016e1b24c0aee4c5651b124a3470206cdae314ff1dcceed96')'

**Comment by razzeee** [comment]
This was a problem with the kodi beta you installed. Please update to a newer nightly and your problem should be solved.
