### ISSUE TITLE
Shows scrobble while they're watched, but don't get added to history when done

### ISSUE THREAD

**Issue by goodevilgenius** [razzeee/script.trakt#445]
When I watch a show on Kodi, it shows up on my Trakt profile as being currently watched, so it's scrobbling correctly. However, when the episode finishes, my profile correctly no longer shows that I'm watching it, but the episode doesn't get added to my watched history.

I've tried this with episodes of two different shows.

**Comment by razzeee** [comment]
Working fine for me. Not sure what your doing differently.

**Comment by nunojsa** [comment]
This seems the same which happens to me. I added a comment on #441. I saw some exception happening on the plugin and added some more comments on this Issue (#441). @Razzeee please give it a look if you have the time. When i have the time i will enable debug both on the plugin and in kodi.

**Comment by zrqx008** [comment]
I have the same problem in kodi 18.1

**Comment by vincewinkel** [comment]
Also have this problem, on Kodi 18.2. How to solve this?

**Comment by razzeee** [comment]
Please create a log as stated in the readme. I'm closing this issue until somebody does that.
