### ISSUE TITLE
VideoPlayer.Year Issue

### ISSUE THREAD

**Issue by ghost** [razzeee/script.trakt#446]
Hi there,

I have a quick question if you could help.

I am making a little addon for my local anime series I have so I can watch them when away and I have found a little issue I cannot work around.

When not playing from library trakt falls back to the year from the player infolabel for year.

I have found that if you set "year" as an InfoLabel trakt uses that year for the tv show.

However, if you set an "aired" info label for an episode trakt gets the year from that infolabel and not the "year" infolabel.

So as an example Yu-Gi-Oh" Duel Monsters first aired in 2000

So on my episodes the "year" info label is set to 2000, the "aired" info label is set to a different year as the show went on for 5 years.

When trakt picks up im watching this the log shows this.

10:53:08.419 T:5280   DEBUG: [script.trakt] resources.lib.scrobbler: playbackStarted(data: {u'episode': 21, u'title': u'Double Trouble Duel (Part 3 of 3)', u'season': 1, u'year': 2002, u'type': u'episode', u'showtitle': u'Yu-Gi-Oh! Duel Monsters'})

As you can see year is 2002, that is the right year of the episode but its a 404 from trakt as the show started airing in 2000.

If i remove the "aired" info label trakt shows me watching the episode and the log shows the year as 2000, but with aired it swaps to 2002 and does not sync to the trakt website.

Any advice please?

**Comment by ghost** [comment]
Example: The infolabels set to the listitem are as follows:

`{'cast': [('Dan Green', ''), ('Hikaru Midorikawa', ''), ('Shigeo Shiraishi', ''), ('Kashiwakura Tsutomu', ''), ('Michiko Neya', ''), ('Ryotaro Okiayu', ''), ('Toshiyuki Morikawa', ''), ('Yumi Kakazu', ''), ('Sumi Shimamoto', ''), ('Ry\xc5\x8d Nait\xc5\x8d', ''), ('Takeshi Aono', ''), ('Tetsuya Iwanaga', ''), ('Ogata Megumi', ''), ('Katsue Miwa', ''), ('Iwanaga Tetsuya', ''), ('Haruhi Nanao', ''), ('Tsutomu Kashiwakura', ''), ('Megumi Ogatai', ''), ('Sasaki Nozomu', ''), ('KONTA', ''), ('Amy B.', '')], 'year': '2000', 'duration': '1500', 'plot': "Bakura's ancient alter ego, the Thief King, arrives at the palace to claim the Millennium Items for himself. The priests engage him in battle, but Bakura's spirit beast Diabound proves too much for them to handle, until the Pharaoh steps in and summons Obelisk the Tormentor. Meanwhile, the spirits of Yugi and the others enter the Millennium Puzzle in search of a doorway into the Pharaoh's memories.", 'votes': '23', 'title': 'The Intruder (1)', 'season': '5', 'status': 'Ended', 'aired': '2005-11-05', 'tvshowtitle': 'Yu-Gi-Oh! Duel Monsters', 'mediatype': 'episode', 'imdbnumber': 'tt0249327', 'studio': 'TV Tokyo', 'genre': 'Animation', 'episode': '18', 'overlay': 6, 'playcount': 0}`

However the VideoPlayer.Year infolabel provides 2005 not 2000, causing the scrobble to produce a 404.

**Comment by razzeee** [comment]
so this is happing without trakt at all?

can you post the jsonRPC queries your using and which kodi versions?

**Comment by ghost** [comment]
This happens when on the little video add-on I made to watch my anime when away. The jsonrpc returns nothing much so as id is not in there it falls back to the non library method. This is where it asks for year from the video player.year infolabel. This then returns the year from aired and not the year sent as year in the infolabels. Does this make sense. I can post the jsonrpc queries tomorrow if you need but I know it falls back to non library gathering as id is not in the dict. 

P.s Kodi 18 Beta 2

**Comment by ghost** [comment]
DEBUG: [script.trakt] resources.lib.kodiUtilities: @@@@Json call result is - {"id":1,"jsonrpc":"2.0","result":{"item":{"label":"S01E07 - Attack From the Deep","type":"unknown"}}}

**Comment by ghost** [comment]
year = xbmc.getInfoLabel('VideoPlayer.Year')

That's the line in service.py of script.trakt.

It returns the year from the aired infolabel and not the year infolabel. Therefore the scrobble uses the year of the episode and not the original year of the shows first air. Which trakts api returns a 404 for.

**Comment by ghost** [comment]
Do you have any update on this?

**Comment by razzeee** [comment]
No, sorry I'm traveling and will not be back for the next 3 weeks.

**Comment by ghost** [comment]
No problem. Thank you for replying.

**Comment by ghost** [comment]
Some further thinking on this issue:

If the issue comes from 

`year = xbmc.getInfoLabel('VideoPlayer.Year')`

Providing the year in ['premiered', 'aired'] instead of the year set via

`item.setInfo(type='Video', infoLabels=meta)`

So meta = {'aired': '2017-05-10', 'year': '2015'}

As xbmc.getInfoLabel('VideoPlayer.Year') is reporting 2017 instead of 2015 I assume this is not an issue for you but more an issue for Kodis core?

**Comment by razzeee** [comment]
So if you can reproduce this on a newly setup kodi instance with the kodi 18 nightly (leia). Please create a ticket at the offical repo.
https://github.com/xbmc/xbmc/issues

**Comment by ghost** [comment]
Thank you @Razzeee 

Closing issue.

**Comment by ghost** [comment]
Hello @Razzeee 

Im re opening as it seems the Kodi core uses this method by design.

I have opened an issue here:

https://github.com/xbmc/xbmc/issues/14754

As you can see here 


It seems to me that the issue is here value["premiered"] = m_premiered.IsValid() ?  m_premiered.GetAsDBDate() : StringUtils::Empty; value["status"] =  m_strStatus; value["productioncode"] = m_strProductionCode;  value["firstaired"] = m_firstAired.IsValid() ?  m_firstAired.GetAsDBDate() : StringUtils::Empty; value["showtitle"] =  m_strShowTitle; value["album"] = m_strAlbum; value["artist"] = m_artist;  value["playcount"] = GetPlayCount(); value["lastplayed"] =  m_lastPlayed.IsValid() ? m_lastPlayed.GetAsDBDateTime() :  StringUtils::Empty; value["top250"] = m_iTop250; value["year"] =  m_premiered.GetYear(); https://github.com/xbmc/xbmc/blob/0978b1dfa3923726841a04b11202eff44552d644/xbmc/video/VideoInfoTag.cpp So the video player reports the year as the year of the episode. However when the kodi trakt addon is sending the info to trakt to  find a show trakt wants the year the show aired not the year the episode  aired. Would it not be better for the video player to attempt to take the  year from the year infolabel or the firstaired infolabel before trying  premiered/aired?
--

It may be that Kodi wants it to be this way however Trakt wants the year the show first aired when you send a search for it.

May I suggest we could fix this in trakt addon by attempting to get the year from videoplayer.firstaired in the first instance, then fall back to videoplayer.year?

**Comment by ghost** [comment]
Actually I see from here: https://kodi.wiki/view/InfoLabels#Video_player

That there is no infolabel that can be used other than Year. As you can see from the kodi core it will always get the year of the episode and that causes issues to show scrobbling as trakt gives a 404 on some shows unless the year is correct (Launch year of the show). I really do not know if there is a way this can fixed.

**Comment by ghost** [comment]
I think the logical answer to all this would be to set the ids = {} for trakt, however the ids fail on yu-gi-oh as tvdb id is wrong. Even if i hack the code to make trakt know the year is 2000 it still fails due to the tvdb id.

If i disable setting ids and allow trakt to get the videoplayer year as 2004 then the scrobble is still 404

If i disable the ids and manually set the year to 2000 trakt does manage to correctly scrobble.

So what I'm saying is that whatever process due to the tvdb and year links to trakt there will always be the odd shows that do not scrobble.

Due to the fact that even if kodi did allow a tv show to set a year infolabel it would still fail with the tvdb id then I dont see a solution to this issue.

I will therefore close the issue and thank you for your time on on this.

**Comment by razzeee** [comment]
Wait, in which sense if the tvdb wrong? Is it wrong local in your database? Is it wrong on trakt? What's happening?

**Comment by ghost** [comment]
Sorry let me clarify.

So Yu-Gi-Oh! Dual Monsters

According to trakt the tvdb and imdb of this show is:

https://trakt.tv/shows/yu-gi-oh-duel-monsters

TVDB: 76894 https://www.thetvdb.com/series/yu-gi-oh-duel-monsters
IMDB:  https://www.imdb.com/title/tt0247902

However according to the TVDB link the IMDB id of the show is https://www.imdb.com/title/tt0249327

Therefore I was setting the ids as 

ids{'imdb': 'tt0249327', 'tvdb': 76894}

So the imdb id is what tvdb says is right, however Trakt uses a different IMDB id with the same TVDB id.

Therefore the scrobble was failing.

This is why I looked deeper and seen that the year was wrong as it was giving the year from the episode, and that would also cause the scrobble to fail. The scrobble would find the right show on trakt if the year was 2000 but not when the year was 2004 for example.

So this looks like a show thats just messed up with the databases across the different sites.

The way around this I have found is for a show to only set the tvdb id in ids and not include any imdb id.

Hope this clears it up a little.

**Comment by razzeee** [comment]
You can report those problems to trakt here https://support.trakt.tv/

**Comment by ghost** [comment]
Thanks @Razzeee 

I think in essence I was wondering to myself through all this if we could maybe have a fallback.

For example: If the show name, season, episode and correct year are sent we get results.
If only tvdb is sent we get correct results.

If the year was allowed to be given for the orignial air date we would have three ways to search.

By IMDB
By TVDB
By show name, season, episode, year

Most of the time trakt returns results even with the wrong year given, I assume the issue arises when trakt has numerous shows that match. I.e Theres quite a few yugioh shows so trakt wants the exact name and year for it.

At present the trakt addon instantly fails with that IMDB not returning instead of maybe falling back to a pure tvdb or string search.
