### ISSUE TITLE
Trakt not working on Android TV

### ISSUE THREAD

**Issue by chicocanada** [razzeee/script.trakt#447]
I have a Kodi v17.5 install on a home theater PC since last year. I installed Trakt v3.2.0 last week and all my watch history appears in my Trakt account on the website. Yesterday purchased an android tv box (Xiaomi Mi Box 3), installed Kodi v17.6 and Trakt v3.2.0, authorized it and it is not showing which files I have watched or not from my home theater pc. On my android tv box when I click run in the Trakt app I get the on-screen pop-up for less than half a second and nothing happens.

Logs attached.
[kodi.log](https://github.com/trakt/script.trakt/files/2504242/kodi.log)
[kodi.old.log](https://github.com/trakt/script.trakt/files/2504243/kodi.old.log)

Ideas?

**Comment by razzeee** [comment]
Your not using this addon, your trying to use `plugin.video.trakt_list_manager`

**Comment by razzeee** [comment]
Your logs don't have any information, please read:
https://github.com/trakt/script.trakt#creating-logfiles

**Comment by chicocanada** [comment]
attached is the log with debug on
________________________________

**Comment by chicocanada** [comment]
My fault. Attached is with debug on both Kodi and Trakt..

Cheers
[kodi.log](https://github.com/trakt/script.trakt/files/2511271/kodi.log)

**Comment by razzeee** [comment]
Did you scan your videos into your movie/show libraries? Doesn't seem to be the case.

**Comment by chicocanada** [comment]
Thank you, that fixed the problem. I had the update set for automatic on startup but I had to do it manually.

Cheers!
On Oct 24, 2018, at 2:20 PM, Razzeee <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you scan your videos into your movie/show libraries? Doesn't seem to be the case.
