### ISSUE TITLE
Trakt Kodi script crashes

### ISSUE THREAD

**Issue by uncovery** [razzeee/script.trakt#449]
Trackt Kodi plugin is crashing

Here is my logfile: http://paste.kodi.tv/ahatiwixan

Some error relating to ImportError: cannot import name tzutc

tried to uninstall and re-install, but does not fix it.

It's the latest versions of Kodi (Stable) and the auto-updated trakt plugin.

Any idea what to do?
thanks!

**Comment by razzeee** [comment]
Sounds like dependency installing failed for you. Can you look if it shows dependencies? Especially the `dateutil` dependency.

**Comment by uncovery** [comment]
Dateutil seems to be installed. RE-installed it from the repo again, now trakt works again. Thanks!

FYI: I don't know how to "Show dependencies", how do I do that?

**Comment by razzeee** [comment]
You can go to the settings page of an addon and show it, I'm not at a pc with kodi installed at the moment.

**Comment by uncovery** [comment]
I cannot find that.

**Comment by razzeee** [comment]
It's under information. So highlight an addon and right click or press `c` to bring up the option menu.

![image](https://user-images.githubusercontent.com/5943908/48164191-148be980-e2e2-11e8-9fb2-dd1a7dd2cb2a.png)

**Comment by uncovery** [comment]
Hmmm that dependencies box is missing here. Otherwise it looks the same. Also I have version 3.2.0 instead of 3.2.1

**Comment by razzeee** [comment]
Might be a new feature in kodi 18 then
