### ISSUE TITLE
TV shows/episodes IDs using TMDB scraper

### ISSUE THREAD

**Issue by axlt2002** [razzeee/script.trakt#450]
Hi Razzeee,

Thanks a lot for this addon; I have discovered it in the last days and gave it a try.

I'm writing here for a question for clarification on TV Shows. Actually, my library contains six TV Shows and I have noticed that the ones that have an italian title are not added to the Trakt collection. In particular:

- Breaking Bad - Reazioni collaterali original title Braking Bad)
- Il Trono di Spade (original title Game of Thrones)
- Westworld - Dove tutto è concesso (original title Westworld)

My guess is that since the title are the italian version of the original ones, they are not correctly identified  (anyway this is not valid for the Movies; even the ones that have part of the title in italian are added to the Trakt collection).
As TV Show scraper I use TMDB that stores the TMDB and TVDB ids; for example, Breaking Bad has:

        <id>1396</id>
        <uniqueid type="tmdb" default="true">1396</uniqueid>
        <uniqueid type="tvdb">81189</uniqueid>

I'm using Kodi 18 (latest nightly) and the last version of your addon installed from the repository.

Thanks in advance for any clarification.

**Comment by axlt2002** [comment]
Me again...I have posted on pastebin my [debug log](https://pastebin.com/Liwv7mGa).

Looking at Breaking Bad, it seems that the tvdb id has the value of the tmdb one, i.e. 1396 instead of 81189, and may be this is the reason of the issue. I guess that the addon, since the id is wrong, makes a try with the title and so it finds the ones the have the original title but it fails with the ones the have the italian one.

Is seems that there is also another issue in adding some concerts. The addon detects that there are three additions to do but one of the three (i.e. Circus Maximus) is already in the collection and the other two (i.e. Dream Theater and Ayreon) are not added. So there is a false detection of a movie that is already in the collection, and an issue in adding the two that are actually missing in the collection.

Hope this can help you.

**Comment by axlt2002** [comment]
Another update...

I made a try setting the TVDB scraper instead of TMBD scraper and...everything works! So it seems that there is an issue when using the TMDB scraper due to the unique id format that Kodi is using. If you look at the example I have reported in my first post, I guess your addon read the **id tag**; you can see that this tag contains the **uniqueid** that has **default = true**. So, according to the scraper that is used, the **id tag** changes accordingly (if TMDB scraper, **id tag** contains the **uniqueid tmdb**, if TVDB scraper, **id tag** contains the **uniqueid tvdb**). I didn't check the code of your addon but may be it would be necessary to read the value of the **uniqueid type="tvdb"** instead of the **id tag**. What do you think?

**Comment by razzeee** [comment]
Yeah, might be the problem here. The change to id types was done at some point where I considered this addon to be done. I thought I added this, but can't really remember.

**Comment by axlt2002** [comment]
Thanks for your prompt answer Razzeee. Are you going to check and eventually add this? I think it would be really useful for the users that use the TMDB scraper as primary scraper.

**Comment by razzeee** [comment]
I don't think I can find any time for this in the near future.

**Comment by axlt2002** [comment]
I see. May be I will try to check the code and see if I can propose a commit...

Thanks for your attention for the time being.

**Comment by razzeee** [comment]
Can you give an update on this?
