### ISSUE TITLE
Trakt Check Marks Disappear

### ISSUE THREAD

**Issue by Baubascat** [razzeee/script.trakt#454]
I'm using Trakt with Kodi 18 on a Shield TV and no matter what video add-on I use with it, it does the same thing. When I first load my TV lists all my check marks of what I have and have not watched are there but when I select a show and watch it or back out to my list, all the check marks disappear. In order to bring them back I have to exit Kodi and restart it. Have you seen or heard of this issue? Do you know what is causing it? I deleted Kodi and did a fresh install but the problem remains. Please help.

**Comment by razzeee** [comment]
Sounds like a problem with the addons or core. This addon just sets those on sync, which is not when you watch.
