### ISSUE TITLE
Problem with trakt remembering watched status

### ISSUE THREAD

**Issue by ladylike1988** [razzeee/script.trakt#457]
Hi. When I'm opening any video app on kodi 18.1 that I have installed on my nvidia shield. I go to my created list (via trakt.tv) called currently watching which gives me an overview of the TV shows I'm watching I see an overview with checkmarks but as soon as I click on any TV show the checkmarks in the overview have disappeared. have tried to re-authenticate trakt. I have installed all kodi or addons, reinstalled kodi and my shield with a clean install but nothing seems to work. It happens in multiple skins and in every video addon so that can't be the problem. It also happens on my laptop which runs on windows.  I'm hoping there is a solution to fix my problem? Greetings Tara

here is my kodi log on the nvidia shield i hope i did everything alright. If im missing something please explain to me what it is i need to do.
https://pastebin.com/dJ6LgNZm
The issue is with trakt. I have the official trakt addon installed and paired as well as i pair trakt in de video addons that i use. This problem doesnt happen with one addon but with every addon. Thats why im quite sure the problem is with the trakt app. If there is anything more you need please ask.

**Comment by razzeee** [comment]
this trakt addon isn't creating any lists, so it can't be this addon.

and there are multiple banned addons in your log https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

**Comment by ladylike1988** [comment]
I'm sure it is. On the trakt website you can create lists. That is what I did, the list I created is called TV shows, this I can now load in the video addons I use. It also happens in the standart lists like the collections and watchlist. I know there are banned addons in my log but the addon causing the problem is trakt which isn't banned. I still hope for a solution to fix my issue

**Comment by razzeee** [comment]
Sorry, but this addon doesn't do anything with trakt lists. So those have to be implemented in one of the other addons. 

This addon doesn't do anything with the watchlist. The only thing we do with the collections is add movies in your library to it. We don't display it in any way, shape or form :)

**Comment by ladylike1988** [comment]
So you are saying that the trakt addon itself doesn't not provide the checkmarks in the video addons? So I can check what I've watched and what not?

**Comment by razzeee** [comment]
No, it does not do that. That's likely the addon or kodi core does.

Only thing that the trakt addon does ON LIBRARY content (not addons) is setting the watched flag via kodi core when you sync or when you finished watching an item.

**Comment by ladylike1988** [comment]
Ok then it must be a kodi core thing since it happens in all video addons. When I open a video from the harddrive that's loaded in the skin via the library the mark stays. Thanks for the explanation.
