### ISSUE TITLE
AttributeError: 'traktAPI' object has no attribute 'authDialog' in Coreelec 9.0.2/Kodi 18.2

### ISSUE THREAD

**Issue by MagicalCrib** [razzeee/script.trakt#467]
Hello,

I've updated my CoreElec from 9.0.1 based on Kodi 18.1 to 9.0.2 based on Kodi 18.2 and trakt.tv plugin stopped to automatically sync watched status. Even when forced it does not always work.
In the kodi log file I've found this:
2019-05-16 00:10:05.664 T:3391091504 WARNING: [script.trakt] trakt.core.emitter: [expired] Exception raised in: traktAPI.on_expired - 'traktAPI' object has no attribute 'authDialog'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.trakt/lib/trakt/core/emitter.py", line 178, in __call_sync
                                                callback(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.trakt/resources/lib/traktapi.py", line 111, in on_expired
                                                self.authDialog.close()
                                            AttributeError: 'traktAPI' object has no attribute 'authDialog'

I'm not sure how to collect logs, I've seen the instructions here but didn't really understood them.
I've run the bash script and it results this:
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 38
Content-Type: application/json
Cache-Control: private, max-age=0, no-cache
Accept-Ranges: none
Date: Wed, 15 May 2019 23:14:36 GMT

{"id":1,"jsonrpc":"2.0","result":"OK"}

Is someone having the same issue?

**Comment by MagicalCrib** [comment]
I'm running plugin version 3.2.4, which seems to be 4 days old according to this commit:
https://github.com/trakt/script.trakt/commit/87a7cb9882ab9756959146dda72357599d735435
It matches more or less with the time I started to have issues.
Is there a way to revert to the previous version to test?

**Comment by MagicalCrib** [comment]
There's definitely some issue. I've reverted back to the version 3.2.1 available here on github and it works again.
I think I finally understood how to collect the logs, here's the log I collected with version 3.2.4:
https://paste.kodi.tv/lixorifoju.kodi

**Comment by razzeee** [comment]
I'm not seeing a problem in that log, which is weird.

**Comment by MagicalCrib** [comment]
Weird indeed. I had Guardians of the Galaxy vol2 marked watched in Trakt.tv website and unwatched on kodi, and usually the plugin syncs this status. But it did not in v3.2.4 but did work as expected in v3.2.1.
I'll try to collect a new log file later today.

**Comment by MagicalCrib** [comment]
New tests
I have 2 movies to sync:
Homem-Aranha: Regresso a Casa (Spider-Man: Homecoming) - watched in trakt.tv, to be marked as watched in kodi
O Filme LEGO 2 (The Lego Movie 2) - watched in Kodi, to be marked as watched in trakt.tv

Tested on Coreelec 9.0.2 based on Kodi 18.2, and none got synced with the version 3.2.4 of the plugin. Here's the log:
https://paste.kodi.tv/anebagagoh.kodi

Android version of Kodi 18.1, version 3.2.4 of the plugin, none of the movies got synced as well. Log:
https://paste.kodi.tv/vesulesabe.kodi

Upgraded Android Kodi to 18.2 and retested. Once again no sync was seen. Log:
https://paste.kodi.tv/yuxivixeyo.kodi

Finally the last test. Back in Coreelec 9.0.2 (Kodi 18.2), reverted the plugin back to v3.2.1 and both movies were successfully synced both ways. I've also collected a log, for comparison if possible:
https://paste.kodi.tv/yeyedesofa.kodi

**Comment by razzeee** [comment]
Last log (the one that seemed to work) does not have anything about any movie being updated.

While all other say they did it.

The android one has an error, but related to scrobbling not sync. But that's related to bad data which means it only got an imdb id. Not sure why you don't have themoviedatabase ids.

**Comment by MagicalCrib** [comment]
Then I don't understand what's happening. 
Isn't anyone else facing the same issue? 

I've disabled the plugin automatic updates for now.

**Comment by razzeee** [comment]
I don't have more reports like yours. The new version is still pretty new but already was dowloaded about 427850 times.
Not sure if that problem might be core elec related

**Comment by MonSoon1212** [comment]
I think I have a similar issue. Not getting synced.

Watched a few shows on various installations (Android & Windows). They are marked correctly on Trakt. However not getting synced across all devices. 

All have auto update on so they are all updated to 3.2.4
All using Kodi 18.2

Tried reauthorising the Trakt account too while on 3.2.4 (Windows)

Reverted back to 3.2.1 and it works

Logs
...

**Comment by razzeee** [comment]
Unfortunatly those logfiles aren't showing any useable logs. See https://github.com/trakt/script.trakt#creating-logfiles on how to create logs.

**Comment by MonSoon1212** [comment]
I see, I will get some logs tomorrow.

Regards,

**Comment by MonSoon1212** [comment]
Okay, hopefully I got this right this time.

In order:
#1 - Windows, Kodi 18.2, upgraded Trakt back to 3.2.4
Added Movie - Bad Teacher (Watched on Trakt) - Syncs Movie!
Added Series - Moonlight (Watched All on Trakt) - Fails to sync TV Show.
Log: -

#2 - Windows, Kodi 18.2, Trakt 3.2.4 - Run 2
Added Movie - Antitrust (Watched on Trakt) - Syncs Movie!
Log: -

#3 Windows, Kodi 18.2, downgraded back to Trakt 3.2.1 (Deleted 3.2.4, extracted, copy & pasted in 3.2.1)
Removed & Readded - Series - Moonlight (Watched All on Trakt) - Syncs TV Show!
Log: -

So it appears 3.2.4, work with Movies but not TV Shows for me.

**Comment by MagicalCrib** [comment]
Then I don't understand what's happening. 
Isn't anyone else facing the same issue? 

I've disabled the plugin automatic updates for now.

> 
> 
> I don't have more reports like yours. The new version is still pretty new but already was dowloaded about 427850 times.
> Not sure if that problem might be core elec related

Well, latest version does not work on Coreelec with Kodi 18.2, Android with Kodi 18.1 and Android with Kodi 18.2 (didn't test on windows)
It does work with version 3.2.1 with Coreelec with Kodi 18.2. Does not seem Coreelec related otherwise the latest version would work in Android.

**Comment by razzeee** [comment]
Are you using nfo files?

**Comment by MagicalCrib** [comment]
Yes, I feed Kodi database with nfo files instead of letting Kodi to retrieve whatever it wants.
I also have the database running on a MySQL database to centralize all the clients.

**Comment by razzeee** [comment]
then the source is likely, that your nfo is missing the new kodi id format, as kodi now can hold multiple ids.

```
<uniqueid type="imdb" default="true">tt0212720</uniqueid>
<uniqueid type="tmdb">644</uniqueid>
```

would be valid for a movie for e.g.

**Comment by MonSoon1212** [comment]
Yes I'm also using NFO files generated by Media Companion. 

Am I missing something in terms of TV Shows?

Also are those Logs useful?

**Comment by MagicalCrib** [comment]
But is it mandatory? 
Is it something that needs to be fixed in the plugin?

**Comment by razzeee** [comment]
@MonSoon1212 yes, those logs help

TV Shows should in fact also have those new ids on tvshow and episode level.
best place to fix this would probably be Media Companion (even if I don't know that tool)

if you export you nfos from kodi it will include these ids, if you scaped them before.

**Comment by MonSoon1212** [comment]
@Razzeee Okay thanks. I will try have a look what is missing from the tv shows in terms of the new IDs you mentioned. And compared to Media Companion.

Do find it odd that using the same NFO with 3.2.1 works but the same NFO with 3.2.4 doesn't. Is it just how 3.2.4 searches for IDs to compare to Trakt?

**Comment by razzeee** [comment]
No, it's not odd, while I did not think of it, it makes perfect sense. It's basically the new future proof way to do this, as kodi leia has a new default tv scaper. With the old system this was just guessing and hoping you got the correct id. Now it should always work, when you run it with a scraper that the tratk website recognizes.

**Comment by MagicalCrib** [comment]
I just looked at my .nfo files, they have the ID of both the IMDB and TMDB. Here's an example:
```
    <id>tt0168786</id>
    <tmdbid>13435</tmdbid>
```
Not exactly the same as your example above but the IDs are there.

**Comment by MagicalCrib** [comment]
Just did a new test. Cleaned up the database and re-added all the movies with TMDB scrapping (can't do this test with TV Shows). Updated the plugin to 3.2.4 and forced the synchronization.
After the sync I've got 4 movies watched, 59 un-watched (63 in total). 
I should have got 11 un-watched, 52 watched. And this is exactly what I get from v3.2.1.

**Comment by razzeee** [comment]
If you "Not exactly" have the nfo, as my example is, it won't work.

Did you test with nfo?

**Comment by MagicalCrib** [comment]
I don't really understand what you mean... I tested with and without nfo.

**Comment by razzeee** [comment]
Nfo like you said above or adjusted to look like the example I posted?

**Comment by MagicalCrib** [comment]
I didn't touch the NFO files, I just created a new library using Kodi's TMDB scrapper instead of reading the NFO files I had previously. Maybe this does not have the behavior I expect...

Can't an option be added to the plugin to choose between the old and new sync methods?

**Comment by razzeee** [comment]
Sure, if your willing to code and maintain it. Just send a PR.

I think if you create a new library with your files, you need to make sure to remove/move the nfo's that are next to your files first, otherwise the scraper will just access them.

**Comment by MagicalCrib** [comment]
So all have the NFO files, but it does not explain how 4 of them got synced.
I'll test without the NFO files when I get back home.

**Comment by MonSoon1212** [comment]
@Razzeee Thanks for your assistance. It appears others came across the same issue and now Media Companion will be updating/fixing the unique IDs in their next release.

**Comment by razzeee** [comment]
@MonSoon1212 neat, can you link me to that information?

**Comment by MonSoon1212** [comment]
@Razzeee Here the author mentions the unique tags
https://forum.kodi.tv/showthread.php?tid=129134&pid=2855825#pid2855825

**Comment by MagicalCrib** [comment]
So I did the test without NFO files.
Added 36 movies to a new kodi library but only 32 were added (need to understand why).
Upgraded trakt.tv plugin to the latest release and executed it.
I've got 9 unwatched and 23 watched. This matches what it was supposed to be.
It is indeed an issue with the NFO file. It does not contain the uniqueid tag, neither I want to edit all files manually to add it.
