### ISSUE TITLE
Not all my TV Shows are imported to my Kodi library.

### ISSUE THREAD

**Issue by cg00001** [razzeee/script.trakt#470]
I have over 120 TV shows and using Kodi 18.2, when I'm importing them and sync only 53 are imported.

Is there a solution?

Thank you.

**Comment by razzeee** [comment]
are you using nfo files?

**Comment by cg00001** [comment]
> are you using nfo files?

No. All my shows are "green" on trakt.tv. 100% collected.

**Comment by razzeee** [comment]
Not sure I'm following.

> to my Kodi library

Collection only works from kodi to trakt, as everything else would not make much sense. What do you think should actually happen?

**Comment by cg00001** [comment]
> Not sure I'm following.
> 
> > to my Kodi library
> 
> Collection only works from kodi to trakt, as everything else would not make much sense. What do you think should actually happen?

I'm sorry you thought this could not be done.

My issue remains, not all my tv shows appear in my Kodi library after syncing.
I'm open to suggestions.

**Comment by razzeee** [comment]
This is not going to download any tvshows for you. This only marks them as collected on the website if you already own them.

**Comment by cg00001** [comment]
I never said they were downloaded.
My library simply shows them TV Shows after syncing.
If you are responsible for Trakt issues and don't know what I'm writing about, maybe you should get someone that does next time before closing the issue.

**Comment by razzeee** [comment]
Please take some time to write down:
- What is happening.
- What you expect to happen.
- Why you expect that to happen.

Thanks

**Comment by cg00001** [comment]
> Please take some time to write down:
> 
>     * What is happening.
> 
>     * What you expect to happen.
> 
>     * Why you expect that to happen.
> 
> 
> Thanks

Sorry to waste your time, I don't think you can help me.

**Comment by DaVukovic** [comment]
I'm pretty sure that he could have helped you if you would have bothered to answer his questions or give him the info he needed to help you. 

If you don t share the requested info, then noone is able to help you.

**Comment by cg00001** [comment]
> I'm pretty sure that he could have helped you if you would have bothered to answer his questions or give him the info he needed to help you.
> 
> If you don t share the requested info, then noone is able to help you.

I already did above.

* What is happening.
I usually add my TV Shows to my library using Tools / Import TV Show Collection from an addon.

* What you expect to happen.
I tried and not all of my shows where added.
That is the issue.

* Why you expect that to happen.
Because it always worked in the past.

**Comment by razzeee** [comment]
So you added tv shows to your library via something like the netflix addon? Then you would expect these tv shows to be added to your library (as in being shown as collected) on the trakt.tv website?

If it stopped working recently, it might be that those addons are not correctly providing the `uniqueid` field, that has become standard in kodi 18. I know that emby had that problem and has/or is working on a fix.

**Comment by cg00001** [comment]
> So you added tv shows to your library via something like the netflix addon? Then you would expect these tv shows to be added to your library (as in being shown as collected) on the trakt.tv website?
> 
> If it stopped working recently, it might be that those addons are not correctly providing the `uniqueid` field, that has become standard in kodi 18. I know that emby had that problem and has/or is working on a fix.

Thanks for the reply, sorry If I wasn't clear enough to be understood before.

So, there's nothing I could do but an update might help?

**Comment by razzeee** [comment]
Well you could check your database, if you know how to do that and check if there are values set for tvshows, episodes and movies in the uniqueid field. Containing a json.

**Comment by cg00001** [comment]
> Well you could check your database, if you know how to do that and check if there are values set for tvshows, episodes and movies in the uniqueid field. Containing a json.

Thank you, I will.
