### ISSUE TITLE
ValueError: year=1

### ISSUE THREAD

**Issue by Worldgate** [razzeee/script.trakt#472]
I have tried using kodi 19 and 18.3, same issue regardless the syncing gets stuck and does nothing for hours.  I've left it going for 2 days and still nothing.

https://pastebin.com/vKE5Qkgw

Not sure whats going on, been at this two weeks now trying everything.  Do i have to pay now to sync the complete file or what?

**Comment by razzeee** [comment]
It seems like you somehow set a `last_watched_at` date, for an episode, that is invalid. Likely saying that you watched it in the year 1.

**Comment by Worldgate** [comment]
Hmm, i'll see if i can find the culprit.

**Comment by Worldgate** [comment]
On trakt it had two episodes set to december 31, 0000.  Thanks for the help.
