### ISSUE TITLE
Intermittent random scrobbling of tv shows collected/watched

### ISSUE THREAD

**Issue by nogoer** [razzeee/script.trakt#474]
Im having an issue where some episodes of shows are either not scrobbling as collected, watched, or both. It's very random and sporadic even within the same series. Some episodes might show as collected but then never update as watched or none of the episodes show as collected but then randomly some episodes will scrobble as watched. Ive turned on scrobble notifications and it always shows as successful. I mostly see this on my OSMC Pi device running leia, but its also happened in osmc 17 and also happens on my HTPC although not as frequently so i dont think its device related. Maybe its the fact i have multiple devices on the same account?

Ive attached the log from the OSMC Pi device. Last night i watched an episode of season 4 episode 4 of The Last Ship. None of the episodes for this show and season are getting updated as collected and only episode 2 got marked as watched even though ive watched 1-4 and the scrobble notification shows success for all. Another show on this device having issues is Expedition Unknown season 7. It's marked episodes 1-4 as collected but not 5 and 6. Its marked 1-6 as watched though.

Thanks

[kodi.log](https://github.com/trakt/script.trakt/files/3621698/kodi.log)

**Comment by nogoer** [comment]
I was looking over the log file myself and theres an exception thrown for connection reset by peer during the playbackended call when the episode i mentioned finished. This probably means trakt themselves killed the connection before the plugin could successfully mark the episode as watched. If so ill go back to the trakt guy and bring this up with him. I can already see from the log as well that trakt responded that this episode was collected even though the website doesnt show it as collected. So im wondering if this is actually an issue on thier end and not with the plugin. Although the plugin is reporting successful scrobbles even when it's bombing.

**Comment by razzeee** [comment]
How did you check that it's not collected? The page of the show or your https://trakt.tv/users/me/collection page? The problem with the collection page might be, that it might not have been added with a recent date. As we're asking kodi, which might choose the file date under some circumstances.

I'm not sure if reset by peer really means it's on trakts side, it might also be your network. But that would be very weird, as it only seems to fail on certain calls.

**Comment by nogoer** [comment]
> How did you check that it's not collected? The page of the show or your https://trakt.tv/users/me/collection page? The problem with the collection page might be, that it might not have been added with a recent date. As we're asking kodi, which might choose the file date under some circumstances.
> 
> I'm not sure if reset by peer really means it's on trakts side, it might also be your network. But that would be very weird, as it only seems to fail on certain calls.

I check on the progress page where it shows what episodes have been collected and then watched as you progress through the season.

**Comment by nogoer** [comment]
Nothing on this at all? My issue is getting worse. I watched 3 episodes of Titans over the weekend and none of them scrobbled as watched. I watched a few episodes of many other shows and again intermittent scrobbling of watched status as well as everything new i got were marked collected until i did a manual sync. The sync appears to be the only part that consistently works, but the addon still continues to give me a scrobble success notification for everything i watch. I iwsh the addon would log better without having to put everything into debug mode. Since this issue involves watching shows its kind of annoying to have the debug info constantly on top of what im watching.

**Comment by nogoer** [comment]
Ive been doing some more troubleshooting and i think i may know the issue. I think it has to do with the % of the show watched when im stopping and it possibly being not enough for the scrobbler to mark the show as watched on trakt. For example i have an episode that is 52:30 long, at approx. 50:51 the credits start and by 51 mins ive stopped the show because im done watching. Kodi has marked it watched long before at about 48 mins but its not until 51:09 ish that the scrobbler will mark it watched. There seems to be a discrepancy between what kodi deems as watched vs what the scrobbler deems as watched and i dont have any advanced settings set to use a custom value. This would also explain why a normal sync works fine because that is using kodi's watched status rather than the current time position of the playing episode.

The addon doesnt appear to have a setting for when to mark as watched but i dont know if the addon is what triggers watched or simply scrobbling to trakt will do it based on a time value passed. Ive gone back and forth on 2 different episodes resetting watched status and seeing when credits start and i would normally stop the show and im pretty sure this is whats going on and explains why its so random. Maybe the addon when a stop playback is done it should check the kodi watched state and use that rather than any time based test for watched?

**Comment by nogoer** [comment]
One step further, and i apologize for the posting spam i tried to get kodi to push up to be more inline with trakt by using advanced settings and while kodi is totally ignoring all the watched related settings trakt seemed to fall back inline with kodi once i set the ignore percent at end to 0 or below kodis watched percent mark. Trakt now appears to mark as watched at the same time as kodi does.

**Comment by razzeee** [comment]
So you basically found a fix for you now?

**Comment by nogoer** [comment]
Yeah for the most part so ill close the issue. Once it started marking watched at the same time while debugging all of a sudden i couldnt go back to before to replicate it not marking at the same time. I also have been getting in the habit of ffwing to the end of the file rather than stopping at the credits as an extra measure as well as i turned on sync during library updates so everything is collected at that point rather than the watched point. This past week everything on all my kodi devices has been fully in sync and watched properly so it appears maybe most of this was just personal behavior.
