### ISSUE TITLE
ModuleNotFoundError: No module named 'dummy_thread' in sqlitequeue.py, line 11

### ISSUE THREAD

**Issue by nSpecter** [razzeee/script.trakt#478]
OS: Lubuntu 18.04.3 LTS (kernel: Linux 4.15.0-66-generic)
Kodi: 19.0-ALPHA1 
Git: 20191022-b1e3946b20

I _think_ I first noticed the Trakt script begin erroring out, oh, about 3 or so Kodi (or Lubuntu) updates ago. It had been running fine for many months prior to that.

At Kodi load-time it produces the on-screen message, "Trakt error. Check the log for more information".

The log file records the following error: http://bit.ly/2qDYryT

I've tried uninstalling and re-installing the script.
I've tried uninstalling and removing the configuration and then re-installing the script.
All to no avail.

Any suggestions?

**Comment by razzeee** [comment]
Hey, kodi alpha changed to be python 3 now, I haven't yet been able to update this addon for that case.

**Comment by nSpecter** [comment]
Not to be argumentative, but are you sure that's it? I've been running v19 Matrix for about a year and this broke only just last week or so. Though I do understand it could have been a recent change in Kodi or a dependency that borked it.

Regardless, thanks for all you do. I'll kick back and wait for an update. :D

**Comment by razzeee** [comment]
https://github.com/xbmc/xbmc/pull/16116
Merged on the 13th of october, not sure if that matches up with your problem.

**Comment by nSpecter** [comment]
Thanks. I'll check it out.

**Comment by MasterCATZ** [comment]
I guess that is my issue as well , what needs to be done to make this python 3 compatible ? 


https://github.com/MasterCATZ/script.trakt/blob/master/resources/lib/service.py

changing a few things around but I believe its that file 

and the changes needed seem to be along the lines of this 
https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error

for files 
defaultscript.py
script.py
sqlitequeue.py

unsure if its a kodi bug or not now 

In certain cases Kodi API returns text in encodings other than UTF-8 which causes UnicodeDecodeError when converting this C++ std::string to Python 3 str that represents Unicode text.

*edit*

I gave up tried 3x different conversion types 
The dummy_thread module has been renamed to _dummy_thread in Python 3
but still failed 
https://docs.python.org/2/library/dummy_thread.html

**Comment by nSpecter** [comment]
I still haven't had time to deep-dive into this issue, but I did want to note that I've discovered two other scripts appear to have gone kaputskie at the same time as this one:

Up Next and Open Weather Map Extended

OpenWeatherMap is also producing a "ModuleNotFoundError" but on URLLIB2

**Comment by MasterCATZ** [comment]
starting next year its going to be really bad , really is a shame when backward compatibility is lost 

lol yeh was wondering why my weather forecasts stopped :P

**Comment by korayal** [comment]
in `sqlitequeue.py` `dummy_threading` is deprecated since Python 3.7, so I've switched it to `threading`.

and the `decode` function call may not be necessary since in Python 3 it should be unicode by default (unless it's encoded before, but I don't think `translatePath` has something else)

So these two changes do prevent the initial error messages I'm getting. But this addon seems to require a lot more work to support Python 3.

**Comment by razzeee** [comment]
I started to work on https://github.com/trakt/script.trakt/pull/483 but it's still early. I successfully tested startup, scrobbling and rating movies and episodes. Nothing else has been tested. And some strings have been broken.

**Comment by razzeee** [comment]
Closing this, as I have pushed a version for matrix.
