### ISSUE TITLE
Make Trakt compatible again with kodi17.6

### ISSUE THREAD

**Issue by bugatsinho** [razzeee/script.trakt#484]
Is there any possibility to rollback xbmc.python version to 2.25 and make the add-on compatible with previous Kodi version or is something that i'm missing and add-on works only on Kodi18?
For example script.module.trakt has 2.14 xbmc python version!
Thank you!

**Comment by razzeee** [comment]
You should not get the addon from here but the kodi repo, which will install the correct version. Or are you looking for a recently introduced feature?

**Comment by bugatsinho** [comment]
I didn't realize that kodi repo has two different versions for trakt! 
thank you!

**Comment by razzeee** [comment]
It's actually more then two. Just for reference.
