### ISSUE TITLE
Question - updated shows question

### ISSUE THREAD

**Issue by jonathanantoine** [razzeee/script.trakt#493]
Hello,

I am wondering when a show is included in this endpoint ? https://trakt.docs.apiary.io/#reference/shows/watched/get-recently-updated-shows

When any of it's info change ? Also when any of it's episode info is changed ?

Regards

**Comment by razzeee** [comment]
You probably wanted to ask this here https://github.com/trakt/api-help/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by jonathanantoine** [comment]
Oups, sorry @Razzeee
