### ISSUE TITLE
Sync multiple Kodi installs using different scrapers

### ISSUE THREAD

**Issue by Rippert** [razzeee/script.trakt#495]
I have one older kodi install that uses the tvdb scraper. This install has created most of my thousands of TV show episodes recorded on mythtv. I am now trying to transition to a new computer with a newer version of Kodi where the default scrapper is themoviedb. I have imported the old library into the new install, but I need to refresh each folder to get the themoviedb scrapper to work on new episodes. Using the trackt script, I can sync these and recover the watched state of the episodes after the refresh. 

Why the watched state is lost when I switch scrappers seems like a bug in Kodi, but not the issue here.

While I have been able to use the trackt sync to recover the watched state after refreshing on the new machine, when I go back to the old machine and try to sync to get the watched state updated for what was watched on the new machine, it fails. The synch works, but it does not add watched status to episodes I watched on the old machine.

So, the real issue: What is the dependence of the trakt watched status on the scrapper used?

**Comment by razzeee** [comment]
There should be no dependence unless the ids your using are wrong for whatever reason on one of the sides.

**Comment by Rippert** [comment]
Thanks Razzeee. I did try refreshing the problematic folders on the old Kodi install, and now trakt is updating them properly. This even though everything was scraped properly already and I've never changed scrapers. Seems like a Kodi bug/inconvenience, not a trakt script one.
