### ISSUE TITLE
rating window won't pop up

### ISSUE THREAD

**Issue by Rootzpower** [razzeee/script.trakt#498]
When I finish watching a tv show/movie the rating window won't pop up.

If I replay the episode and fast forward to the end, the rating window does pop.

**Comment by razzeee** [comment]
Did you check if you also hit this problem? https://github.com/trakt/script.trakt/issues/496

**Comment by Rootzpower** [comment]
> 
> 
> Did you check if you also hit this problem? #496

Don't apply for me.
I'm using NFS access to my media for ever (10 years) and only last week I've this trouble.
Just test kodi on PC access directly to my media and got the same problem.
Ratting window don't popup at the end

**Comment by razzeee** [comment]
So any log? https://github.com/trakt/script.trakt#creating-logfiles

**Comment by Rootzpower** [comment]
"To create a logfile, enable the debug setting in Kodi AND script.trakt, otherwise the logfile won't show any data from script.trakt. Check the Kodi documentation if you don't know where your logfile can be found."

I dont understant how debug script.trakt can you help?

**Comment by Rootzpower** [comment]
[01_KODI.log](https://github.com/trakt/script.trakt/files/4440842/01_KODI.log)

**Comment by Rootzpower** [comment]
I don't know what happened but rating popup works again 😳

**Comment by razzeee** [comment]
I guess I can close this then :)
