### ISSUE TITLE
Setup release pipeline

### ISSUE THREAD

**Issue by razzeee** [razzeee/script.trakt#505]
Hey @rectifyer 

can you please go to the repo settings and setup these two?

![image](https://user-images.githubusercontent.com/5943908/86903797-1db10780-c110-11ea-9363-0eaa69af4f67.png)

So that we can use the addon-submitter https://github.com/xbmc/action-kodi-addon-submitter

You will need to create a token in your personal settings, if I remember right

**Comment by rectifyer** [comment]
Yeah, can you email the values I need for each one?
