### ISSUE TITLE
Krypton- cannot get movie sync (Trakt to Kodi) happening

### ISSUE THREAD

**Issue by nicholashead** [razzeee/script.trakt#506]
Hello,

New install of Krypton 17.6, and TV sync is working however movie sync appears not to. Watching the status window it seems to skip movie syncing almost. But TV sync is working. I am using The Movie DB movie source.

I can try and post logs shortly.

Thanks!

**Comment by razzeee** [comment]
Can you also use v18?

**Comment by nicholashead** [comment]
I wish :-/ but I am forced to use v17 because of the custom builds that implement DSPlayer support. It seems no one has made a v18 version of that as far as I can tell.

**Comment by Andy2244** [comment]
Just noticed this too with the fresh [v17 2020](https://forum.kodi.tv/showthread.php?tid=351534) install.
Trakt version is the old from the repo 3.2.0, btw can we install the matrix versions in krypton too?

**Comment by razzeee** [comment]
Would be surprised if that worked without problems

**Comment by burekas7** [comment]
According to my issue, it seems to be a problem regarding to Kodi 17.6 or something.
The questions are:
1) Is if the newer version will fix this issue?
2) The newer version which is not supported by Kodi v17 is working with pyhon v2 or only with v3?
3) What is the last version that you advice to install to test it?

**Comment by nicholashead** [comment]
I turned on debug logging and it seems that the plugin is generating a URL too long for Trakt:

GET /sync/ratings/movies/ (with a long querystring of all my movies)

Is returning a 414 HTTP status.  Then the logging says:

[script.trakt] resources.lib.syncMovies: [Movies Sync] Error getting Trakt.tv movie list, aborting movie Sync.

**Comment by nicholashead** [comment]
What's weird is my "sync ratings" is turned off in the Trakt plugin settings, so I don't know why it would even bother?

**Comment by nicholashead** [comment]
Checking the Trakt API docs it doesn't seem like that's valid anyway? Unless I'm missing something it should just query the movie category and get all the ratings?

**Comment by burekas7** [comment]
@nicholashead 
Please use this version I made.
This is the last version for Kodi v18 (3.2.5) that fixed to be working with v17.
This version is working.
(The download link is in this comment)
https://github.com/trakt/script.trakt/issues/508#issuecomment-700251359

**Comment by nicholashead** [comment]
@burekas7 thanks, that worked.
