### ISSUE TITLE
Trakt rating dialog not coming after watching a movie

### ISSUE THREAD

**Issue by onlytanmoy** [razzeee/script.trakt#507]
Hiya @Razzeee the rating pop-up not coming after done watching a movie.
Its only showing up for episodes alone which is odd as I thought the pop-up is handled similarly for movies and tv episodes or not?
I am using Kodi 18.8 on Nvidia Shield Pro 2019.
Unfortunately there is no other add-on AFAIK that can show this Trakt rating pop-up at the end of movie/episode, therefore coming to you to get this fixed. Please look into the matter.

**Comment by razzeee** [comment]
I can't replicate the problem, all working fine for me. Does it work for
you if you pause the movie or do you only get it without pausing and
skipping?

**Comment by onlytanmoy** [comment]
I don't get it at all, so the movie finishes playing but rating pop-up dialog never shows up. It does get marked as watched in my Trakt history though.
Strange thing is for TV show episodes, the rating pop-up shows up instantly once done watching it. so failing to understand what's wrong for movies? How come it works only for TV episodes?

**Comment by razzeee** [comment]
Might be a problem with your scraper. I guess a log might help

**Comment by onlytanmoy** [comment]
ok sure, I am currently out of home, will share a log with you...in fact two logs- one successful one for TV episode and another unsuccessful one for movies. Will be great to have this back working again for me as really no other kodi add-on I know of that can handle trakt rating.

**Comment by onlytanmoy** [comment]
@Razzeee here you go mate, replicated the issue with movie not showing Trakt rating pop-up. Let me know if not able to view the log file. I will now grab another log with the case for TV episode where rating pop-up is shown as expected.
[kodi.log](https://github.com/trakt/script.trakt/files/5081355/kodi.log)

**Comment by razzeee** [comment]
That's weird, there are only three log lines from trakt. Can you check if you followed https://github.com/trakt/script.trakt#creating-logfiles ?

**Comment by onlytanmoy** [comment]
Oh ok, I only enabled debug mode in Kodi. Have enabled debug in script.trakt as well now. Will share the log file shortly.

**Comment by onlytanmoy** [comment]
@Razzeee please see log file attached for movie case, unsuccessful one that is. I will get the log for TV episode now, successful case.
[kodi.log](https://github.com/trakt/script.trakt/files/5081427/kodi.log)

**Comment by onlytanmoy** [comment]
And here is the log file for a TV episode scenario which displayed the rating pop-up immediately after show end.
[kodi.log](https://github.com/trakt/script.trakt/files/5081440/kodi.log)

**Comment by razzeee** [comment]
however your watching this, we only get the year, not the name. So I'm guessing your using an online source, which either doesn't set it or sets it wrong.

It seems to set the title as `showtitle` (this is not a show but a movie), so the problem might be there.

Best would be if that addon could provide the actual ids, or at least the correct titles.
The docs on how to do it correctly are here https://github.com/trakt/script.trakt/wiki/Providing-id%27s-to-facilitate-scrobbling

**Comment by onlytanmoy** [comment]
Ok, so you suggesting me to log a issue on this with the add-on as the add-on is not sending the right info. I used Fen in this example so will report an issue there with cross reference to this post. Thanks for checking for me.
