### ISSUE TITLE
Wrong Show is Scrobbled

### ISSUE THREAD

**Issue by greatvc** [razzeee/script.trakt#513]
Hi, I have Kodi 18.7 and trakt addon v.2.3.5. I have the "The Missing" show on my Desktop, from Kodi i select the file from file manager and click on play. 

The wrong tv Show that gets scrobbled is: https://trakt.tv/shows/the-missing-2016
instead of the correct one: https://trakt.tv/shows/the-missing

I tried with .nfo files from "Tiny Media Manager" to identify the correct show but again nothing.
The filenames i tried:
The Missing 1x01
The Missing 1x01 (2014)

If you are a VIP member you can see my post in Trakt here: https://forums.trakt.tv/t/wrong-show-is-scrobbled/2983/9 

How can i make the Scrobble to select the correct show ?

Many thanks.
Vassilis

**Comment by greatvc** [comment]
Does anyone has any comment on this ?

**Comment by razzeee** [comment]
Haven't had time to test this.

**Comment by razzeee** [comment]
Please post a log https://github.com/trakt/script.trakt#creating-logfiles

**Comment by greatvc** [comment]
it is ok, i found another way
thanks
