### ISSUE TITLE
Trakt addon doesn't sync episode progress even though I get the scrobble notification

### ISSUE THREAD

**Issue by unkn0wn234** [razzeee/script.trakt#518]
I watch part way of an episode I back out, the resume point gets saved, but upon doing a Trakt Sync it resets it to the beginning. I can't go to another Kodi build and resume bc this doesn't work. I swear it used to before I fresh installed not sure whats going on. Let me know if you need a log.

EDIT: Issue was caused by Runtime for episodes being 0 in Kodi DB, you can fix it by editing the DB manually or generating NFOs for your episodes.

**Comment by razzeee** [comment]
What are your settings?

**Comment by unkn0wn234** [comment]
https://imgur.com/a/7pFWAcr

**Comment by razzeee** [comment]
no dice without a good log

**Comment by unkn0wn234** [comment]
Ill get to posting it tonight, thank you.

**Comment by unkn0wn234** [comment]
[kodi.log](https://github.com/trakt/script.trakt/files/5648076/kodi.log)
[kodi.old.log](https://github.com/trakt/script.trakt/files/5648077/kodi.old.log)

https://imgur.com/a/t4VAWLZ

**Comment by unkn0wn234** [comment]
https://imgur.com/a/foe7icj

also this is a screencap of github progress manager, the seinfeld episode was there too but i removed it to set my eps back to normal, all the movies aside from justice have their progress and dont get reset. the other episodes dont update in my library at all

**Comment by razzeee** [comment]
You might want to update kodi, your some versions behind.

The logfiles are not very useable, chech https://github.com/trakt/script.trakt#creating-logfiles

**Comment by unkn0wn234** [comment]
[kodi.log](https://github.com/trakt/script.trakt/files/5649640/kodi.log)
[kodi.old.log](https://github.com/trakt/script.trakt/files/5649641/kodi.old.log)


for the time being id like to stay on my version as i heard people who updated broke alot of their home widget setups and stuff, if i need to to fix it then i will. Here are 2 debug logs, I notcied after the sync the progress was still there but it turned out it was just a visual bug with the skin I use bc I clicked into the show and the progress was lost again. Bit of false hope :L , anyways here are the debug logs.

**Comment by razzeee** [comment]
Both logs don't seem like you actually ran the sync, there is no log from the sync or something crashing.

**Comment by unkn0wn234** [comment]
I have the option run sync upon library update or cleaning so I use that to force a sync I know it’s happening too because I have the notifications where it shows both movies and episode sync started, then completed like in those images in the imgur link I sent earlier. Or by sync are u referring to something else such as my episode progress being synced with trakt so it doesn’t get overridden upon a library update?? In which case I also have the scrobble notification enabled to make sure it’s updating and I see it being scribbled.

**Comment by unkn0wn234** [comment]
It’s not crashing to me because the sync completes, and then my episode progress gets overridden being sent back to 0, if I mark the next few episodes as watched on trakt before the update it will update to that episode so I can tell it’s working on an episode basis just not with mid episode progress, even tho I get a scrobble notification

**Comment by razzeee** [comment]
When you start an episode and it says scrobbling, do you see that on trakt.tv on your profile too? As currently watching?

**Comment by unkn0wn234** [comment]
I will go and check, if it does not what does that mean? Something on my end, a bug with trakt addon, etc. I will update in a few minutes

**Comment by unkn0wn234** [comment]
Also again if y can check that GitHub image I sent it shows progress for episodes such as archer, kill la kill, and family guy which do not get updated.

**Comment by unkn0wn234** [comment]
Yes it does, sorry for a late respone here is an image
![Capture](https://user-images.githubusercontent.com/52363082/101297672-265d5500-37f8-11eb-8f8e-10f55e7f655f.PNG)

**Comment by razzeee** [comment]
Interesting, so your saying your not able to see that episode via the trakt progress viewer?

**Comment by unkn0wn234** [comment]
> Interesting, so your saying your not able to see that episode via the trakt progress viewer?

if you’re talking about the GitHub trakt viewer I do, I deleted the Seinfeld episode from it tho cause I wasn’t actually on that episode anyway I just did it to test and it showed 3x4 from me testing 

Also I deleted it after the trakt sync so i didn’t make it not update

**Comment by razzeee** [comment]
So it showed the wrong episode or did you test with 3x4 this time?

**Comment by unkn0wn234** [comment]
No just ignore that 3x4, bc i tested this numerous times, the time I went to 3x4, and the image above are separate occasions. When I had progress in 3x4 it would show 3x4 after the sync but the playback progress is removed, same with 3x1.

What always happens is, the correct episode is shown but any playback progress is wiped after a trakt sync

**Comment by razzeee** [comment]
Just tried with matrix on my android setup and demon slayers, the progress wasn't wiped for me.

We only ever set progress via scrobble, in fact we only have a get call for your progress data. So no idea, how they can go missing. Maybe it's server side, only the trakt guys might know @rectifyer

**Comment by unkn0wn234** [comment]
Can you show me your trakt addon settings and version?

**Comment by razzeee** [comment]
Version is https://github.com/trakt/script.trakt/releases/tag/v3.3.2

Here's a settings diff:
- Show scrobble notification is off
- Rate after tvshow/movie end on

- Show sync notifications is off
- Hide notifications during playback off
- Sync ratings on
- I'll ignore movies for now
- Add new TV episodes to Trakt collection is on

**Comment by unkn0wn234** [comment]
I checked Add new TV Episodes to Trakt collection as that would be the only thing I dont have on, no change. I just tested with Seinfeld 3x2, went about 10 min in, Trakt Github viewer showed I was watching it as well as the Trakt Site, I went and clicked Run on the Trakt addon went back to the episode, my episode progress vanished. I checked on Github viewer the 44% of 3x2 progress is still there. 

I realized I made a mistake earlier I had enabled debug logging but not in the Trakt addon too let me delete 3x2 from the progress, and re-try. I also just re-installed the addon but my Trakt info was already logged in even tho i pressed delete all data.

**Comment by unkn0wn234** [comment]
Oh by the way, the library folders i used is shared among another Kodi Build, do u think that could be the problem?

**Comment by unkn0wn234** [comment]
Here is the debug log with debug in Trakt enabled. I will explain what I did a bit, I played Seinfeld S3E2, skipped halfway, checked on  Trakt PLayback Progress Manager (github) progress was there. Though It didnt say I was playing it live this time, anyways I backed out checked progress it was still there, I played it again to confirm my library resume point was there and on the second play it went to the point I was it as you can see in the log. This time I checked again on Trakt Github Manager, and the Trakt site, both said I was currently watching this episode. I back out, run the Trakt addon to sync, go back and the progress is lost, just to be safe I play the episode, but as you can see it does not resume.

[kodi.log](https://github.com/trakt/script.trakt/files/5655904/kodi.log)

**Comment by unkn0wn234** [comment]
Did a complete fresh install, and now my movies in progress wont even populate anymore, only completely watched episodes and movies are marked but none of the in progress are marked correctly in Kodi. :'/ (Also i just updated to Kodi 18.9 as well)

EDIT:I forgot to enable sync playback progress for both movies and episodes, doing so brought my in progress movies back, however not my in progress episodes.

I had progress in 21 Bridges, I marked it as unwatched, ran a Trakt sync and it came back, so i have no idea why this is not working with episodes at the moment. I will post another debug log.

**Comment by unkn0wn234** [comment]
In this debug log I marked the 2 movies in my in-progress (21 bridges, and Da 5 Bloods) as unwatched, then watched partway into Seinfeld 3x3, I backed out to confirm it saved the resume point and also checked on the Trakt github viewer it showed both when i was watching it live, and the progress after I quit. I played 3x3 again to confirm it would resume and it did, then I ran the Trakt sync, Episode progress again is lost, but the 2 movies in progress returned again.

So this is a problem only with episodes in progress, movies and episodes watched status' sync fine, movies playback progress syncs up, however episode playback progress is the only thing that gets wiped everytime i run a trakt sync, and does not get synced to my library from trakt, bc as u can see on my trakt github the episodes have progress.

[kodi.log](https://github.com/trakt/script.trakt/files/5656978/kodi.log)

**Comment by razzeee** [comment]
would you be able to edit `syncEpisodes.py` and add more logging? then redo the test? especially in the later parts of `__addEpisodeProgressToKodi`

**Comment by unkn0wn234** [comment]
> would you be able to edit `syncEpisodes.py` and add more logging? then redo the test? especially in the later parts of `__addEpisodeProgressToKodi`

I am very nooby but if u tell me what to edit exactly I can follow instructions

**Comment by unkn0wn234** [comment]
> would you be able to edit `syncEpisodes.py` and add more logging? then redo the test? especially in the later parts of `__addEpisodeProgressToKodi`

Just following up

**Comment by razzeee** [comment]
try `logger.debug("[Episodes Sync] Episode progress chunk: %s" % json.dumps(chunk))` right before `kodiUtilities.kodiJsonRequest(chunk)`. You will also need to do `import json` at the top of the file.

Please keep it indented like the lines next to them.

**Comment by unkn0wn234** [comment]
> try `logger.debug("[Episodes Sync] Episode progress chunk: %s" % json.dumps(chunk))` right before `kodiUtilities.kodiJsonRequest(chunk)`. You will also need to do `import json` at the top of the file.
> 
> Please keep it indented like the lines next to them.

I can try but sorry to ask, if it’s not much hassle could u just send me the edited.py?

**Comment by razzeee** [comment]
I think this should work
[syncEpisodes.zip](https://github.com/trakt/script.trakt/files/5683980/syncEpisodes.zip)

**Comment by unkn0wn234** [comment]
theres a .pyo as well but just replacing the .py is fine? do i also have to re enable Trakt debug, and Kodi debug?

**Comment by unkn0wn234** [comment]
[kodi.log](https://github.com/trakt/script.trakt/files/5684016/kodi.log)

**Comment by razzeee** [comment]
Sorry, seems like I made a mistake while patching, can you try this?

[syncEpisodes.zip](https://github.com/trakt/script.trakt/files/5692290/syncEpisodes.zip)

**Comment by unkn0wn234** [comment]
> Sorry, seems like I made a mistake while patching, can you try this?
> 
> [syncEpisodes.zip](https://github.com/trakt/script.trakt/files/5692290/syncEpisodes.zip)

I didnt see this sorry testing now

**Comment by unkn0wn234** [comment]
![Untitled](https://user-images.githubusercontent.com/52363082/102838415-1a62bd00-43cc-11eb-954d-f7fa82100b6b.png)

Trakt website, and github progress manager both show in progress while watching. After exiting progress is shown/saved on the github progress manager as well. Running trakt sync wipes episode progress again however here is the log for it. Debug enabled on Kodi and in Trakt addon.

[kodi.log](https://github.com/trakt/script.trakt/files/5727275/kodi.log)

**Comment by unkn0wn234** [comment]
> Sorry, seems like I made a mistake while patching, can you try this?
> 
> [syncEpisodes.zip](https://github.com/trakt/script.trakt/files/5692290/syncEpisodes.zip)

Following up, was this new log able to tell you anything?

**Comment by razzeee** [comment]
Seems like it reset these for you:
2020-12-21 20:34:43.863 T:9624   DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Episodes updated: The Promised Neverland [tvdb: 348002] - S01E05
2020-12-21 20:34:43.864 T:9624   DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Episodes updated: Family Guy [tvdb: 75978] - S19E01
2020-12-21 20:34:43.864 T:9624   DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Episodes updated: Demon Slayer: Kimetsu no Yaiba [tvdb: 348545] - S01E12

it seems to think the total length of the episode is 0 minutes, so that might be the cause for this.

**Comment by unkn0wn234** [comment]
> Seems like it reset these for you:
> 2020-12-21 20:34:43.863 T:9624 DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Episodes updated: The Promised Neverland [tvdb: 348002] - S01E05
> 2020-12-21 20:34:43.864 T:9624 DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Episodes updated: Family Guy [tvdb: 75978] - S19E01
> 2020-12-21 20:34:43.864 T:9624 DEBUG: [script.trakt] resources.lib.syncEpisodes: [Episodes Sync] Episodes updated: Demon Slayer: Kimetsu no Yaiba [tvdb: 348545] - S01E12
> 
> it seems to think the total length of the episode is 0 minutes, so that might be the cause for this.

Where does the trakt addon get the runtimes for episodes? My library uses .strms from the official TMDBHelper addon I would think this might be the reason as a strm Might default to 0 min, but my movies progress again work completely fine. 

Is the 0 minutes something I can hope to see fixed or is there still more unknowns to try and figure out?

also thank you for taking the time to help. Me out these past however many day’s. I really appreciate it

**Comment by razzeee** [comment]
Do use nfo files? Which scraper are you using? Can you check if the episodes have a runtime in kodi/the database/the api? It's the "runtime" field on the episode.

**Comment by unkn0wn234** [comment]
> Do use nfo files? Which scraper are you using? Can you check if the episodes have a runtime in kodi/the database/the api? It's the "runtime" field on the episode.

I use the tmdb scraper for shows and sometimes tvdb I think tmdb makes nfos but only for the show as a whole not for episodes. Can you explain what u mean by in the database/api? I think I can just go check in my Kodi library I’ll go boot up my laptop

**Comment by razzeee** [comment]
Nfo files only get generated, if you want that (by kodi) but there are people who like to place them next to every file, to be able to control everything. Depending on where the database is, you can open it up and look at the tables and the data in there.

**Comment by unkn0wn234** [comment]
> Nfo files only get generated, if you want that (by kodi) but there are people who like to place them next to every file, to be able to control everything. Depending on where the database is, you can open it up and look at the tables and the data in there.

Uhh so what is the file named I can just search it up and open it? As of now my shows only have a .nfo in the root folder of the show for tmdb scraper shows not for all episodes I don’t think I want one for each file/episode unless u think I need to to fix this.

**Comment by razzeee** [comment]
filename should be the same as the episode name, but with `.nfo` an filetype. You can however check if the shows here have the top level nfo and if removing/moving, rescanning and retesting changes something.

**Comment by unkn0wn234** [comment]
I think I found the database folder in Kodi but the files are all .db I don’t know how to open them, I think I checked an nfo and all it has is just the url to the tmdb but I could be wrong I just dtagvdropped it into chrome. Could u tell me how to make Kodi make nfos for each episode None of the information provider addons in Kodi I have have the option

**Comment by unkn0wn234** [comment]
I think we may have got it, I’ll update in a few minutes to make sure it works with other shows too

**Comment by unkn0wn234** [comment]
Nvm I didn’t even have sync episode playback on let me test now lol. I had it turned off CAuse it kept messin my stuff up

**Comment by unkn0wn234** [comment]
Deleting an nfo from the show itself didn’t help to solve this unfortunately

**Comment by razzeee** [comment]
You can open the database with https://sqlitebrowser.org/dl/

**Comment by unkn0wn234** [comment]
![Capture](https://user-images.githubusercontent.com/52363082/103182165-4d4afc00-4877-11eb-8b74-4a75cb663502.PNG)

So upon checking the wiki for where the runtime is stored it is "c09" in my database in "c09" they are all 0. Except for the show DBZ which I have physically in my library that showed a 4 digit number. Aside from that all of them said 0. What are the next steps I can take? Also I will test with an episode of DBZ and get back to u if it works or not since i have the whole show marked as watched ill mark one of them as unwatched and see if my progress doesnt get wiped

**Comment by unkn0wn234** [comment]
It wiped the progrss for my DBZ episode too, it showed up in Progress manager after playing, and when i was playing it live. This episode also has runtime in the DB. Still gets wiped after a Trakt sync. EDIT: Testing a second time saved the progress, let me do it again a few times and on other episodes

**Comment by unkn0wn234** [comment]
Okay so watching an episode part way, backing out, then running a Trakt sync seems to wipe the episode progress. The last thing I did in the log was watch episode 1x2 of DBZ partway, back out, run a trakt sync, episode progress gets wiped.

After Closing Kodi, reopening, then running the Trakt sync again returns the progress! So it somewhat works on physical media, or network drive media that is not a .strm, I assume it comes down to one of two things. 1- There is probalby a certain time for it to refresh or load to trakt servers or something like that so maybe if I just wait long enough and run the Sync, it would keep the progress without me needing to close Kodi and reopen (i believe closing and reopening kodi forces a reconnection/refresh with trakt), or 2- Whatever the bug or reason is for not working, running the trakt sync once and then again after closing/reopening (or maybe even just a 2nd time without closing) will make the playback progress return.

All in all its a small price to pay at least the playback progress is there and here to stay! The main 2 differences between DBZ and my .strm library is one is physical media, and/or the runtime being in the SQL database as u said. I do think we are getting close. I noticed i could manually edit the runtime in the database but with the ridiculous amount of episodes I have doing it one by one would be crazy

Lost Progress Log
[kodi.log](https://github.com/trakt/script.trakt/files/5745499/kodi.log)

Progress Return Log
[kodi.log](https://github.com/trakt/script.trakt/files/5745507/kodi.log)

**Comment by razzeee** [comment]
I think strm files should also get a proper runtime, if the scraper works correctly. So that should be the first thing we report/fix.

**Comment by unkn0wn234** [comment]
> I think strm files should also get a proper runtime, if the scraper works correctly. So that should be the first thing we report/fix.

After some more testing, adding the runtime manually (through SQL) to the shows i had progress for and running Trakt sync added the progress so we are FIXED! But again i faced the smaller issue above where the first sync didnt really restore it (this time it did visually, but when i played it it didnt resume) I ran a second sync, closed the app and opened it and finally when the widget refreshed, my progress actually came back. So as you said my main error is the runtime.

Can you help me figure out how to get the runtime in my shows nfos? I use the default TMDB TV show scraper and it does not add the run time to the nfos. Im not sure if i have anythign set up wrong it seems to be working fine. The NFO only has the tmdb or tvdb url in it and I assume the scraper, or kodi gets all the info from there. 

My options are either fix (im not even sure if theres somethign to fix) the scraper or mass generate nfos (if i can figure out how) for my shows again. 

Or manually add the runtimes in show by show in the DB using SQL(which I did for some shows already and confirmed trakt now syncs the resume points).

Thank you so much for helping me solve this! I really cannot express how grateful I am for your patience and helpfulness.

**Comment by razzeee** [comment]
You might be able to use ember media manager or tinymediamanager to write the nfo files? I'm not really an expert in that regard, I'm only really using physical media. But I think you will need to add it to the episodes, not just the show. 
I guess you might also be able to try the tvdb python scraper if your switching to matrix at some point https://github.com/xbmc/metadata.tvdb.com.python

**Comment by unkn0wn234** [comment]
> You might be able to use ember media manager or tinymediamanager to write the nfo files? I'm not really an expert in that regard, I'm only really using physical media. But I think you will need to add it to the episodes, not just the show.
> I guess you might also be able to try the tvdb python scraper if your switching to matrix at some point https://github.com/xbmc/metadata.tvdb.com.python

For the time being, I am not planning on switching to Matrix. Also I heard TVDB is going to become paid soon anyway no?

Anyways, I tried EmberMediaManager and it wouldnt detect any of my shows or movies, I tried TinyMediaManager and it worked. Though I need to pay for it bc it only generates like 10-15 NFOs before hitting the free limit, and it also generates poster images, clearlogos, and a lot of other metadata images. Which if I did for each show the size of my folder would increase a LOT. But I did confirm adding the NFOs without needin to edit the DB, fixed it for me as I tested with Fire Force. 

Again thank you a lot for all the help. My next steps will probably be figuring out how to make TMM only add NFOs, and also ignore any of my custom images (poster, clearlogo, etc) in my folders. and then I should be set.

**Comment by unkn0wn234** [comment]
Hi, I added all the NFOs to all my episodes and now the progress is not being saved for new episodes, the previous episodes I had are atleast not being wiped anymore but any new episodes i watch, leave progress, run a sync gets wiped again. The one in question is Stranger Things

[kodi.log](https://github.com/trakt/script.trakt/files/5750162/kodi.log)

**Comment by unkn0wn234** [comment]
eH sorry I think i know whats happening, the NFOs have not been updated into the Kodi database? if I delete the file will it force kodi to refresh or will it break it?

**Comment by razzeee** [comment]
Unfortunatly I don't know how NFOs work very well, I'm not really using them.

**Comment by unkn0wn234** [comment]
> Unfortunatly I don't know how NFOs work very well, I'm not really using them.

Setting content to none, then back to tv shows and forcing a complete rescan fixed it for me. Thanks
