### ISSUE TITLE
Sync stopped working 1hr after fresh install (openelec)

### ISSUE THREAD

**Issue by YippeeKaiay** [Razzeee/script.trakt#52]
happened on 2 openelec devices. starts sync but does not complete

http://xbmclogs.com/show.php?id=407979

**Comment by magnumpci** [comment]
Not sure if the dev and master are in sync (Razzeee merged them earlier today I believe)  but you are using the dev build it would seem:

23:45:49 T:140327033661184   DEBUG: CPythonInvoker(6, /storage/.kodi/addons/script.trakt-dev/script.py): start processing

https://github.com/Razzeee/script.trakt/pull/47#event-226782282

Even when I had it happen, closing \ opening resolved the issue most often.

**Comment by YippeeKaiay** [comment]
ok I will try the master see if it fixes my issue. Where do I find it?

**Comment by YippeeKaiay** [comment]
Ok I think I have found the issue. After multiple fresh install's to norrow down the bug it is caused by having a tv show folder in an excluded flash drivests content set to tv shows /local information only!! When I unset the content it finishes sync again :)

**Comment by Razzeee** [comment]
@YippeeKaiay meaning nfo's?

**Comment by YippeeKaiay** [comment]
Yea but after playing around more it also stopped if I added tvdb?? It could be the folder as I have a movies folder from the same drive added in tvdb and it works fine. Either way sync is working properly. Just have the VPN issue left now a then ill be laughing

**Comment by Razzeee** [comment]
@YippeeKaiay 
so I can close this?

**Comment by YippeeKaiay** [comment]
Yea. Guess it's just a bug on my usb drive. Thanks
