### ISSUE TITLE
Trakt Stuck at Synchronize 1% Kodi Matrix

### ISSUE THREAD

**Issue by gboystance** [razzeee/script.trakt#522]
Hi, trying to sync my library with trakt and I'm unable to proceed beyond 1% and have to force close. 
However, when I watch something - it scrobbled fine, just unable to sync my collection or sync historical watch status. Please help

**Comment by razzeee** [comment]
You probably have some show/movie, that's missing data from the scraper or in your nfo files. If you have nfo files, I recommend to regenerate them.

**Comment by Lentzeris** [comment]
I don't think it is as simple as that. I have the same problem since I installed Matrix version, and I was hoping it was something you had identified and were working on.

Here is my log file (addon starting manually after line 523): [https://pastebin.pl/view/8d601e43](https://pastebin.pl/view/8d601e43)

There is probably some python script error.

**Comment by razzeee** [comment]
You also see to be running in the uniqueId error, that I mentioned above.
The log is basically saying, that one of your shows is missing it.

You might be able to find help in these other issues https://github.com/trakt/script.trakt/issues?q=is%3Aissue+sort%3Aupdated-desc+uniqueid+is%3Aclosed

**Comment by Lentzeris** [comment]
All my shows and movies contain .nfo files with just a link for imdb or thetvdb and nothing else. My scrapers are "Universal Movie Scraper" and "Thetvdb".
Kodi versions up to 18 were working normally, and the problem occurs only with version 19. So it must be some code change in python, since it is a new version for Matrix build.
I had never set a uniqueid before, so why should it be a problem now, all of a sudden? The previous versions probably ignored the uiniqueid error and continued the sync progress.
I even checked my video database manually, and one of my movies was missing a uniqueid too. But the trakt sync finished the movie sync progress and just hanged in TV Show sync progress.

**Comment by razzeee** [comment]
Well the change to uniqueId is two years old by now and was also pushed to leia https://github.com/trakt/script.trakt/commit/87a7cb9882ab9756959146dda72357599d735435 starting with version 3.2.4 as you can see there.

**Comment by Lentzeris** [comment]
I'm not sure I understand...
The change in the code was pushed two years ago, but the problem only appeared with Kodi Matrix builds in the last few months. I tried a new installation with a Leia build and the sync errors disappeared. Then I reinstalled the Matrix build and the errors appeared again. There was no alteration in the database during this time.

**Comment by razzeee** [comment]
Which scrapers are you using in both cases? Python ones or the legacy ones? Might be kodi having a bug when reading such NFO files or just the scrapers erroring.

**Comment by Lentzeris** [comment]
I'm using "Universal Movie Scraper" (version 5.4.6) for movies and "Thetvdb" (version 3.2.8) for TV Shows, both from the official Kodi repository.
As I mentioned before, the sync for movies ends successfully, but the tv show sync hangs with the error on the log posted earlier.

**Comment by razzeee** [comment]
https://github.com/trakt/script.trakt#creating-logfiles
Might help to find the offending show but might not be enough

**Comment by kchen13** [comment]
[kodi.log](https://github.com/trakt/script.trakt/files/5969861/kodi.log)
Relevant log info is at the end. I think I'm having the same issue but op's pastebin is no longer available for me to compare. 

I read about the multiple posts and solutions on the uniqueId error and while it does show up in the log as the last error there's a bunch before that. Before posting here I scraped all the nfo files multiple times different ways but problems still persisted. The nfo files all have id and uniqueid, like below. I had them scraped from TVDB, then I switched to TMDB and even tried IMDB, same freeze.
```
<id>6786303</id>
<uniqueid default="true" type="tvdb">6786303</uniqueid>
```
My nfo files for tv shows was created by tinymediamanager and they worked fine on Kodi v18.*. I'm now trying v19 RC1 out and everything is fine except this. Scanned my local library in using only local information. Has something changed with Kodi v19 and tv show nfo and how trakt identifies the shows?

Movies sync'd up fine but stalls immediately on TV episodes, progress bar has a hair of progress, nothing gets synced and cancelling seems to just freeze the system up needing to force quit. Using Kodi v19 RC1 on a Fire TV 2nd  Gen.

**Comment by fun4stuff** [comment]
I have been having the same problem. Trakt add-on hangs on TV synchronization and I have close out Kodi. I'm on the Nvidia shield. Occured after update to matrix.

**Comment by psonnosp** [comment]
Yes, same here, everything was working great the other day but after updating to Matrix the sync stops at 2% of Synchronize TV Episodes and the only thing to do is to force an exit of Kodi since the Cancel button doesn't respond.
Will be back with a log.

**Comment by psonnosp** [comment]
https://paste.kodi.tv/rabumewicu.kodi
I don't know much about reading the logs but I can't find if there's a show that's the issue but the 
```
2021-02-26 15:11:39.779 T:4760    ERROR <general>: KeyError
2021-02-26 15:11:39.779 T:4760    ERROR <general>: : 
2021-02-26 15:11:39.779 T:4760    ERROR <general>: 'ids'
```
part seem to point at an ID issue, but all my shows are updated with the < uniqueid > so I'm more confused than usual.

**Comment by fun4stuff** [comment]
Trakt plugin seems broken with the new matrix Kodi. Have to revert to Leia.

**Comment by razzeee** [comment]
Works fine over here, have been using it for more then a year at this point

**Comment by Lentzeris** [comment]
Ok, just a quick kind question, @Razzeee...
Are you the developer of the addon, or just a user?
There are a few people sharing their logs mentioning a specific problem, and your answer is usually a generic one, and lastly "works fine for me". What developer says "I don't know about you, but it works for me"? You should be asking for more information and logs, trying to find the actual problem.
You can just say that you are not the person responsible for the development and maintenance of this addon/package. No-one would blame you.

**Comment by razzeee** [comment]
This is probably mixing multiple problems at this stage. The non 'ids' problem should be fixed with the version from today.

**Comment by psonnosp** [comment]
Nope, updated to 3.3.5 and it still stops at the same "Synchronize TV episodes - 2%"

**Comment by razzeee** [comment]
As stated above, the other error then the "ids" error should be fixed now. Wording was a bit weird.

**Comment by Arthur1967** [comment]
Do I just hit update to update to 3.25 script I’m still using 18.9

**Comment by Arthur1967** [comment]
My bad I have 3.26

**Comment by razzeee** [comment]
It doesn't seem like you used https://github.com/trakt/script.trakt#creating-logfiles when creating that log. Doing it like that, might make a log actionable or at least point you to the offending show. In that case, it might be interesting to share your NFO file.

**Comment by psonnosp** [comment]
I thought I did.
I turned on debug both in kodi and the script, what else is there?

**Comment by razzeee** [comment]
Hrm, that should be enough. Normally you end up with a bunch of logs that start with `[script.trakt]`, you only have that once in your logfile.

Maybe a kodi 19 change, that I somehow missed? There has been component logs for some time, maybe they block our logs too.

**Comment by razzeee** [comment]
Seems to still work on 19 see https://github.com/trakt/script.trakt/issues/531 as an example

**Comment by psonnosp** [comment]
Not to be disrespectful or rude but if it work or not for someone else is of no interest to me, because that doesn't make it work on my machine anyway.
I just want help with what I can do to help you help me to get it to work for all of us with 19 where it doesn't work.

So now we are at the point where the logs didn't show anything. What's the next step?

**Comment by razzeee** [comment]
No idea how to proceed without a log. It's basically a black box like this.

**Comment by psonnosp** [comment]
So then that's the next step, fix so a proper log is created.
Since the solution provided in your link seem not to work is it anything else I can do to get this going?

**Comment by razzeee** [comment]
Please give https://github.com/trakt/script.trakt/pull/532 a spin

**Comment by psonnosp** [comment]
Sorry for the late response but no difference with latest update, still stops at 2% for no obvious reason.
