### ISSUE TITLE
Is PR allowed ?

### ISSUE THREAD

**Issue by HydrelioxGitHub** [razzeee/script.trakt#523]
Hello,
I'm a new to Kodi add-on developper. I would like to add to this add-on a feature that can sync trakt list with tag in Kodi. Currently, I'm doing this by mannually for my Kodi installation and it's quite boring. Is P.R. allowed on this repo ? Do you think this feature could be useful for other users ?

As I'm not very experimented, I would like to do it step by step and maybe get some advices with the WIP.

**Comment by razzeee** [comment]
Hey, I started this somewhere in 2016 but never finished it, the code is here https://github.com/Razzeee/script.trakt/commit/a9275d6b072717241785d2dbd8281d2257b4760d but it's likely out of date/needs a serious revamping/never worked.

**Comment by HydrelioxGitHub** [comment]
Thanks for pointing this code at me. I will look at it, keep in mind some ideas, and remind which files have been modified to start in a good way. But maybe rewrite it from scratch could avoid some issues.

My first goal is to implement a two way sync between list names on trackt and tags on Kodi. I think it could be good to prefix tag in Kodi like `trakt_{name of the list}` to easily know if a tag is a sync with trakt or if it's a regular tag. 

If I manage to make this works properly, in a second time, I will populate lists/tags with movies.

**Comment by kingkearney** [comment]
A lot of people would make use of this feature but just a heads up, some skins display tags on video info screen and library view's. People aren't going to want to see 'trakt_' included in their tag names.

I personally use my 200+ trakt lists as Netflix 'multi genres', the addon i used for auto tagging died a while back so having to do it manually. I'm hoping TMM (tinymediamanager) will be able to bring this feature in (its on their todo list but not a priority) so I can tag the nfo's.

If you manage to get this working then I can at least auto-tag in kodi again and use the 'Metadata Editor' addon to auto update my nfo's.

Dont forget you can also get access to the watchlist and recommended list as well, they make great tags in kodi. 

The things we do for that perfect media library 😁

**Comment by HydrelioxGitHub** [comment]
Your comment @kingkearney  is very interesting because I didn't think that people could get so many list in their trakt account. 

As I said above I would like to go easy and make simple things works at the first step. In my opinion, begin with tags labelled with trakt keyword is not the best but the simple solution. As @Razzeee starts in his previous work, the list sync must be enabled in settings so people won't get annoyed with unsightly tags in the UI.

In my mind, the best system is to display in the UI the name of Trakt lists and allow user to select which one he wants to sync or not. And store these names somewhere. But it's to complicated for me to start with this.

**Comment by razzeee** [comment]
Closing as question is answered.
