### ISSUE TITLE
Trakt addon crashes when trying to sync (Kodi 19 RC1)

### ISSUE THREAD

**Issue by guenniguenzelsen** [razzeee/script.trakt#527]
I've noticed an issue with Trakt addon version 3.3.2.
By starting the addon, it tries to load my Kodi movie-selection for synchronization and freezes in that task.
This issue is present on severeal systems, after switching from Kodi Leia to Kodi 19 RC1 (Win 10 PC, Libreelec PC, FireTV 4k).
1: Using local information scraper in Kodi only.
All Movies and TV-Shows are scraped with Ember Media Manager.

2: Deleted whole Database and used Phyton movie scraper in Kodi

Trakt freezes when it tries to load my kodi movie selection. No matter of scraped in one or another way.

Trakt is working with Kodi 18.x as expected.
kodi.log attached
[kodi.log](https://github.com/trakt/script.trakt/files/5860045/kodi.log)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 3.3.2
* Kodi version used: 19 RC1
* Operating System and version: 1: Windows 10 / 2: Libreelec 9.80 nightly / 3: FireOS

**Comment by razzeee** [comment]
Your nfo files need to have a `uniqueId` now. You should be able to get these via scraping or a media manager of your choosing.

**Comment by guenniguenzelsen** [comment]
I don't need this ID for Kodi.
Everything in the library is working as expected. Excactly like before.
Not clear to me, why I shall change my nfo. Trakt was able to work with these nfo's in Kodi Leia. Kodi is still working with them in Matrix.

**Comment by ijefferies** [comment]
With version 3.3.2, Kodi 19 RC1 and Libreelec 9.80 nightly.

I'm having exactly the same problem, everything works fine on Kodi 18, no issues at all on Linux/Kodi, Libreelec x86-64 and on RPI4. 

My .nfo files do not contain a unique ID as have never needed one before. If that is the issue then it would be helpful for an error message to appear, the sync operation abandoned and Kodi to continue running as normal (without freezing). 

Preferred solution though is that the addon can be fixed to run without a unique ID and everything continues to function as before on Kodi 18.

**Comment by guenniguenzelsen** [comment]
For my understanding the sync routine shall be:
Unique ID = Sync
No unique ID = Skip w/o sync

Example: My library has 98% movie's and show's with unique ID.
2% of my library have not - they are simply not relevant for online databases (e.g.: private concert recording, or any other material that was never launched officially).

**Comment by razzeee** [comment]
Can you post a log with the latest version? As I think it should skip the previous error now. But might fail later.

**Comment by ijefferies** [comment]
Just done some quick checks with the latest version, seems to be working fine now, status on Kodi reflecting correctly on trakt.tv when episodes set as watched.

Thanks for the great work and quick turnaround, have attached Kodi log in case it helps.

[kodi.old.log](https://github.com/trakt/script.trakt/files/6011863/kodi.old.log)

**Comment by razzeee** [comment]
Log looks good, at least there's no exception. But you didn't turn on detailed logging.
