### ISSUE TITLE
[Bug] Trakt context menu & TMDB scraper for TV Shows library

### ISSUE THREAD

**Issue by burekas7** [razzeee/script.trakt#530]
Hi,

When I set my TV Shows using the tmdb tv show scraper
http://mirrors.kodi.tv/addons/leia/metadata.tvshows.themoviedb.org/metadata.tvshows.themoviedb.org-3.5.12.zip

The trakt context menu doesn't work well.
For example if I open the context menu for an episode, and open the "trakt options" it takes the id which is now of tmdb id and make a search using tvdb instead, which is incorrect.
Therefore when I choose to rate the episode for exmaple, it show the episode name of other tv show that the tmdb id is in TVDB.

What can I do in order to fix that?

Thanks.

**Comment by razzeee** [comment]
Tested on which kodi version?

**Comment by Arthur1967** [comment]
What is the repository for the latest trakt version for kodi 18.9 Thank you

**Comment by razzeee** [comment]
Official kodi repo

**Comment by burekas7** [comment]
> Tested on which kodi version?
@Razzeee 

I tested it on both version of 18.9 and 17.6, the same behavior.
It makes the serach only by TVDB.
So if I'm using TMDB scraper for TV Shows it use the TMDB ID for looking it in TVDB which is wrong.

How can I solve this?

**Comment by angelitto2005** [comment]
@burekas7, why don't you use TVDB scraper for TV Shows and TMDB scraper for Movies. Maybe this way, your problem will be solved. I say this because i had problems with OpenInfo when i use TMDB scraper for TV Shows. But after i changed in settings the TVDB scraper for TV Shows, everything is ok again. Just a thought.

**Comment by Arthur1967** [comment]
Because they want to start charging people each month for the use of their
service mean well they get their directories from the users so they’re
charging us for using our information so a lot of people have switched to
the movie database

**Comment by angelitto2005** [comment]
I checked again and i was talking about this: 
![Captură de ecran 2021-03-02 150111](https://user-images.githubusercontent.com/29383306/109652222-2c00d780-7b68-11eb-90cf-3ce6313f49bc.jpg)

**Comment by burekas7** [comment]
> @burekas7, why don't you use TVDB scraper for TV Shows and TMDB scraper for Movies. Maybe this way, your problem will be solved. I say this because i had problems with OpenInfo when i use TMDB scraper for TV Shows. But after i changed in settings the TVDB scraper for TV Shows, everything is ok again. Just a thought.

All the years until today I was using only TVDB for TV Shows.

My reason of changing it to TMDB is because it is more updated and they have more translated content in my language.
In addition, it is more convenient to update content in their site, rather then TVDB which is annoying platform for updating content.

**Comment by razzeee** [comment]
> > Tested on which kodi version?
> > @Razzeee
> 
> I tested it on both version of 18.9 and 17.6, the same behavior.
> It makes the serach only by TVDB.
> So if I'm using TMDB scraper for TV Shows it use the TMDB ID for looking it in TVDB which is wrong.
> 
> How can I solve this?

Why do you think this is the case? I just tested a setup with the tmdb scraper, setting the bulk of the show `3%` to watched and then syncing it as watched. It did work without problems.

**Comment by burekas7** [comment]
@Razzeee 

Hi,

Read again the main post.
The sync is correct, I'm not talking about that.
I mentioned that the problem is with the **context menu**:
I tested that with: **context.trakt.contextmenu-1.0.3**

It takes the tmdb id and use it as tvdb id and search it in TVDB site, so it actually returns a wrong tv show.
It should knows (or add a setting) if the scraper is by tmdb. so the searching should be with tmdb and not in tvdb.
The same if the scraper is by TVDB, the searching should be with tvdb.

In order to test it:
Select an episode,
Open the context menu and select "Trakt Options"
Select "Rate the episode"
You can see the episode title that is wrong. It returns a tvdb tv show which suit to the tmdb id.

**Comment by razzeee** [comment]
Can you test https://github.com/trakt/script.trakt/pull/534

It seems to fix the problems on my test setup
