### ISSUE TITLE
Notifications don't show at all

### ISSUE THREAD

**Issue by D4anielCB** [razzeee/script.trakt#533]
## Expected Behavior
Notifications  showing for scrobling and when synchronizingthe library

## Current Behavior
When scrobbling or when synchronizing the notifications that used to show on kodi 18.9 and below are not showing in kodi 19
the addon is working for both situations mentioned, only the notification that is missing

## Steps to Reproduce (for bugs)
1. Enable notifications in the settings and sync collection on library update/cleaning
2. Try to watch any tv show/movie
3. Try to update the library

## Context
Even this is not compromising its functionality I find the notifcations very useful, so i decided to report

## Your Environment
* Version used: 3.3.5
* Kodi version used: 19.0
* Operating System and version: Windows 10

Thanks for the great addon!

**Comment by bromix** [comment]
Same with me...noticed it today. I'm looking at the debug.log right now.

**Comment by bromix** [comment]
So, I updated my library and see in the log that the scan process is starting
```
2021-03-07 19:11:59.036 T:12396    INFO <general>: VideoInfoScanner: Starting scan ..
```
But after that, no trakt information at all. If I start trakt manually via the addon section...
```
2021-03-07 19:15:39.326 T:9680    DEBUG <general>: CPythonInvoker(4, C:\Users\<USERNAME>\AppData\Roaming\Kodi\addons\script.trakt\defaultscript.py): start processing
```

**Comment by razzeee** [comment]
Please see the readme on how to get log output by the script

**Comment by bromix** [comment]
I added my log so far.
```
2021-03-07 22:41:27.049 T:20836   DEBUG <general>: [script.trakt] resources.lib.service: [traktMonitor] onScanFinished(database: video)
```
[kodi.log](https://github.com/trakt/script.trakt/files/6098028/kodi.log)
