### ISSUE TITLE
Add webhook for translations

### ISSUE THREAD

**Issue by razzeee** [razzeee/script.trakt#537]
@rectifyer Please add a webhook to https://kodi.weblate.cloud/hooks/github as described on https://kodi.weblate.cloud/

**Comment by gade01** [comment]
I can see the webhooks are not yet added.
Please add webhooks for correct sync.  

![](https://inlinestudio.dk/xtra/kodi/weblate/webhook.png)

**Comment by razzeee** [comment]
Ping @rectifyer

**Comment by rectifyer** [comment]
Just added the webhook, let me know if that works.

**Comment by gade01** [comment]
Sounds great, thanks.
