### ISSUE TITLE
Watchlist resetting on Trakt

### ISSUE THREAD

**Issue by magnumpci** [Razzeee/script.trakt#54]
Seemingly, at some point in the SALTS update, and as a subsequent the library update and Trakt sync called when it is done, the watchlist flag at Trakt.tv is doing something funky for TV shows.  Not all, just the majority.  If I had to theorize on why some are not affected, they would be the shows where I have watched no episodes (with one show, having shown watched one episode in Trakt.tv, being the lone exception), .

Funkiness:

Trakt.tv watchlist for shows only shows a fraction of the usually flagged shows.  If I go to a show that is missing, it reads that is it watchlisted.  When I try to test remove \ re-adding on the show page, it errors out.

http://screencast.com/t/acP6AY9Cb6XH

So to from the history page:

http://screencast.com/t/uOZ36ofO

If I go into the Salts TV subscriptions, it shows what the Trakt TV watchlist link shows (the incomplete one).  

What I also cant determine is if it's a problem with SALTS (or a setting I have for it, pruning ended shows being enabled perhaps?), the new Kodi Trakt plugin (in its current ver 3 state) or Trakt.tv itself (possibly timing out as it has lately).  As one can see from the error when I try to remove \ re-add, I cant do any further remove \ re-add tests.

Posted here as I know tknorris is watching this project as well.

Posting a log should it provide any insight:

http://xbmclogs.com/show.php?id=408225

If you can see from the log that the issues is not with the Trakt plugin, Ill try to figure something else out.

One other thing, it would appear episodes are adding multiple times it seems:

http://screencast.com/t/MBvjqkgwVzx

Thanks.

**Comment by tknorris** [comment]
FYI, I posted this response here: http://forums.tvaddons.ag/threads/29574-Trakt-watchlist-anomalies?p=250648&viewfull=1#post250648

**Comment by Razzeee** [comment]
@magnumpci @tknorris 
script.trakt doesn't work with your watchlist, so it can't be this plugin
