### ISSUE TITLE
not able to install on Windows 10 on Kodi 19.1

### ISSUE THREAD

**Issue by nickoo0** [razzeee/script.trakt#554]
I upgraded from 18.9 Kodi to 19.1 and noticed that the Trackt addon was disabled, I have tried to install the latest from the official addon repo and it says "The add-on is not compatible with this version of Kodi"

## Expected Behavior
Should install the addon

## Current Behavior
error message shown

## Steps to Reproduce (for bugs)
Just install the addon on Kodi 19.1

## Your Environment
* Version used: 3.4.1
* Kodi version used: 19.1
* Operating System and version: 
Windows 10 Pro
Version	20H2
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0
![Capture](https://user-images.githubusercontent.com/62260155/123134858-20a02780-d449-11eb-9e08-f1b75d530bbe.PNG)

**Comment by razzeee** [comment]
Can you update your repo, that's not the latest version your trying to install

**Comment by nickoo0** [comment]
I have tried 3.4.2 but I get the following errors
I also changed Kodi from 19.1 to 19 to see if it made a difference but it did not.

![Capture](https://user-images.githubusercontent.com/62260155/123227567-9d281a00-d4cc-11eb-9ed4-c197245cef14.PNG)

**Comment by razzeee** [comment]
do you have any third party repos installed? did you install trakt from the kodi repo?

**Comment by nickoo0** [comment]
straight from the official repo but I also downloaded it from Git and uploaded it and that also fails

**Comment by razzeee** [comment]
Something is fishy with your kodi version, had other windows 10 user test it, after you posted this and it worked for them. You might want to uninstall kodi, cleanup the data paths and use an installer from the official kodi website.

**Comment by nickoo0** [comment]
Thanks that got it working
