### ISSUE TITLE
Some episodes not being marked watched/Sync stops at 12%

### ISSUE THREAD

**Issue by shedrock** [razzeee/script.trakt#564]
Some of the episodes are not being marked off as watched after scrobbling. Even if I run a manual update of the add-on, the process gets stuck at 12%.

<-->

## Your Environment

* Version used: 3.2.6 
* Kodi version used: 9.0.2
* Operating System and version: LibreELEC

**Comment by razzeee** [comment]
Please post a log https://github.com/trakt/script.trakt#creating-logfiles , I'm also pretty sure the kodi version is wrong.

**Comment by shedrock** [comment]
Kodi version is definitely: **_9.0.2_** on LibreELEC
Here is a link to my logfile: https://paste.kodi.tv/ugiqodunag.kodi

Thank you

**Comment by razzeee** [comment]
You seem to be getting a 504 which means, that there is a problem on the side of trakt. Which is kinda weird.
https://trakt.docs.apiary.io/#introduction/status-codes

**Comment by shedrock** [comment]
Well, this was my response from trakt a few days ago. So they definitely don't think it's on their end. They also recommended that I should try revoking and reauthorizing the add-on, but that didn't work.

> Kate Admin
July 27

Here are the two sites I have related to that add-on. Please contact them for support.
https://github.com/trakt/script.trakt/issues

trakt.tv movie and TV show scrobbler for Kodi. Contribute to trakt/script.trakt development by creating an account on GitHub.

https://forum.kodi.tv/showthread.php?tid=220547

**Comment by shedrock** [comment]
Here is my latest response from Justin over at trakt.

> A 504 should be a temporary issue, if the Trakt api is getting overloaded for example. When that happens, it automatically adds in more servers and the problem should go away.

**Comment by razzeee** [comment]
Yeah, that's what I would expect too

shedrock ***@***.***> schrieb am Do., 29. Juli 2021, 18:31:

**Comment by shedrock** [comment]
If you wish, you can look at the thread I started over at trakt. No one seems to be able to help me over there.

Link: https://forums.trakt.tv/t/trakt-for-kodi-sync-issues/7644/8

**Comment by razzeee** [comment]
Maybe that was a fluke and your getting different errors on different runs? 

You could also try to disable ratings sync for episodes and check if it's only that endpoint, that blocks you.

**Comment by shedrock** [comment]
I tried disabling the ratings, but that didn't help. I also uninstalled the add-on, as well as the addon_data folder and reinstalled the add-on, but it's still stuck at 12% **"Retrieving Episodes From Trakt"**.

**Comment by razzeee** [comment]
A logfile with those changed settings might show something or not...

**Comment by shedrock** [comment]
Here is an updated log file: https://paste.kodi.tv/helupoguqe.kodi

**Comment by razzeee** [comment]
Hrm, it's still trying to get the ratings, not sure if we always need them no matter what.

**Comment by rectifyer** [comment]
This looks to be related to having a high amount of ratings (16,000+) and that API method is timing out basically. Even the website is having trouble loading your ratings page and it's very slow. I actually have a task already to look into optimizing ratings and hopefully I can find a way to bump up performance. It's tough to have any API method return that many items in a single response though.

**Comment by shedrock** [comment]
Why would my ratings have such a sharp increase as oppose to last weeks ratings? I only added a few more TV shows to my library with approximately 30 episodes. Unless I am misunderstanding something. 😃

**Comment by shedrock** [comment]
Any updates on this issue?

**Comment by razzeee** [comment]
If those watches are not correct, you usually need to reach out to the trakt support to have them removed. Or you could try a tool, but you might not have as good control that way.

**Comment by shedrock** [comment]
Thanks, I quoted this message to the trakt support team. Hopefully someone can help me out wit this issue.

**Comment by Zipster79** [comment]
I have the exact same problem, always getting the 504 error, I just checked my ratings and I have 23k+!! I do have 'Sync Ratings' turned off but as already pointed out this seems to make no difference, I don't need ratings syncing between trakt & kodi.

**Comment by razzeee** [comment]
Can anybody try https://github.com/trakt/script.trakt/pull/565 I'm not sure if that might have nasty side effects.

**Comment by Zipster79** [comment]
> Can anybody try #565 I'm not sure if that might have nasty side effects.

Brilliant, that has fixed the problem for me! Thank you very much!

**Comment by shedrock** [comment]
Awesome, this works great for me now with ratings set to off.

Thank you,

Shedrock

**Comment by razzeee** [comment]
I would suggest to still get your ratings sorted by the trakt support.
