### ISSUE TITLE
Nothing seems to work

### ISSUE THREAD

**Issue by UnclePsymon** [razzeee/script.trakt#569]
Hi there! I installed the addon and the context buttons. Unfortunately nothing works. I can not scrobble or rate anything. Everything gives me an error: Trakt error, see log for more information. 

I am on Linux (Pop OS) and i use Kodi Matrix 19.1, Flatpak

[kodi.log](https://github.com/trakt/script.trakt/files/6992308/kodi.log)

Thx!

**Comment by razzeee** [comment]
The log suggests, that your using an incompatible skin, can you try to use the default skin?

**Comment by UnclePsymon** [comment]
I will try it and give you feedback. Thx!

**Comment by UnclePsymon** [comment]
So, I have tried some other skins, but the problems persist. I used Esturay (the default one), Arctic, Bello and Metropolis.

**Comment by razzeee** [comment]
Interesting, it should work with estuary, if I remember right from https://github.com/trakt/script.trakt/issues/395

Then again, are you testing this on local files?

**Comment by UnclePsymon** [comment]
If you mean local films, no. I use Kodi for streaming (Netflix & Co.).

**Comment by razzeee** [comment]
Seems like their not setting a `ListItem.DBID` then, might not be able too.

But scrobbling should work fine via https://github.com/trakt/script.trakt/wiki/Providing-id%27s-to-facilitate-scrobbling if they implemented it.

**Comment by UnclePsymon** [comment]
Alright, I will dig into it a little bit. Thanks :)

**Comment by UnclePsymon** [comment]
So, I found the solution: Trakt > Config > Scrobbling > Attempt secondary show title search. That was all. Now everything works just fine. Thanks again!
