### ISSUE TITLE
Not syncing: "overflowerror: timestamp out of range"

### ISSUE THREAD

**Issue by wokkieman** [razzeee/script.trakt#572]
## Expected Behavior
When I run the add-on, I expect to sync watched status with my trakt account.

## Current Behavior
Tried restarts and logout and re-authentica with Plex, but no difference in behavior. Also reinstalled the add on + clean Kodi cache in android tv.

When running add on the progress pop up stops at 7% and nothing else happens. Can't cancel either (so it freezes). I need to exit and force stop and restart Kodi to continue using Kodi.

Debug log indicated that there is an overflow error: timestamp out of range for platform time_t

## Your Environment
* Version used: 3.5 (latest?)
* Kodi version used: 19.1 matrix
* Operating System and version: Chromecast with android TV

It always worked fine, but I don't when it changed. I noticed it when I re-added my libraries and wanted to sync watch status.

Anything I'm doing wrong or is it a bug?

Pastebin: https://pastebin.com/1PfK7BAy

**Comment by Arthur1967** [comment]
I'm using 19.1 with Trakt script 3.50 and it's working fine for me so I'm not sure I know that doesn't help but hopefully you can still be your issue￼

**Comment by Arthur1967** [comment]
I'm using 19.1 3.50 track script on an android box and it's working fine so it must be something with Script for your system probably a bug￼￼

**Comment by razzeee** [comment]
probably one of your files, a logfile might help to track it down https://github.com/trakt/script.trakt#creating-logfiles

you can upload it with the logfile addon

**Comment by wokkieman** [comment]
I reviewed the Kodi database and there were indeed a few tv shows with crappy data (nfo related). Removed all nfo's, rebuild the library and re-run the scan. All works fine now. Thanks!
