### ISSUE TITLE
Sync - Server is over capacity

### ISSUE THREAD

**Issue by Ben91** [Razzeee/script.trakt#58]
Impossible to sync my XBMC/Kodi Collection via the official trakt.tv script (2.3.1 - xbmc repository) and even with this new one now.

Always get "server is over capacity" errors... (since yesterday) in the Kodi logs. Tried to copy/paste urls in a browser/HTTP, get the same answers.

[trakt] [traktAPI] traktRequest(): Starting retry loop, maximum 5 retries.
...
[trakt] [traktAPI] traktRequest(): (0) Other problem (500 Internal Server Error)
....
[trakt] [traktAPI] traktRequest(): (1) Server Busy ({"status":"failure","error":"server is over capacity"})

Tried starting manual syncs and updating the library. Same thing.

Using Kodi 14.0 (stable).

Cheers.

**Comment by Ben91** [comment]
@traktapi says "Some calls for v1 are not enabled. There is a beta xbmc plugin updated to the new api."

But happens with this one too.

**Comment by Razzeee** [comment]
@Ben91 
probably just on episodes?

**Comment by Ben91** [comment]
Tested for movies.

Tried with the cleaning collection enabled. Doesn't work at all.
New movies not added to trakt, deleted ones from XBMC not deleted on trakt.

Here you are some logs : http://pastebin.com/QuGaDTpR

**Comment by Razzeee** [comment]
@Ben91 
your using the old version or an unclean install.

Should be:
NOTICE: [trakt] Loading 'script.trakt' version '3.0.0'

Your log has:
[trakt] Loading 'script.trakt' version '2.3.2'

**Comment by Ben91** [comment]
My bad !

I used the link from the "Installation" part : (or download it here). :D

Should I use the "Download ZIP" button ?

**Comment by Razzeee** [comment]
Yes but be sure you are in dev and it's not advised to use it with your main trakt account. As it's still rough around the edges and probably destroys some of your data.

**Comment by Ben91** [comment]
Ok. Thank you very much.

**Comment by Ben91** [comment]
It works with the correct 3.0.0 version ! Nice work. ;)

Had issues on tv eps now, posted on the corresponding issue (39).

Cheers.
