### ISSUE TITLE
Keeps rebuilding

### ISSUE THREAD

**Issue by Arthur1967** [Razzeee/script.trakt#597]
Every time I open up kodi Seren says rebuilding database is it a trakt issue or this version or is trakt down it's been doing it for about three days it allows me to use So I'm not sure what it is thank you

**Comment by razzeee** [comment]
I have no idea what seren is or how that is connected with trakt. Therefor I would suggest to report that on their repos.

**Comment by Arthur1967** [comment]
OK thank you I will
