### ISSUE TITLE
Trakt rating pop-up not appearing

### ISSUE THREAD

**Issue by onlytanmoy** [Razzeee/script.trakt#606]
Hi @razzeee hope you are doing well. As you might be aware of the recent Trakt outage, ever since that got resolved somehow the Trakt rating pop-up do not show up at the end of a movie. It is getting marked as watched in the Trakt site all fine but I am no longer getting the rating option. Any idea?

**Comment by razzeee** [comment]
Can you try re-authorizing? I've just tested it and it seems to work for me (but that was a fresh authorization)

**Comment by onlytanmoy** [comment]
Sure, will do that once I return home next week from vacation. Happy new year ✨️ 😊

**Comment by onlytanmoy** [comment]
Working all good now after the re-auth :) thanks mate.
