### ISSUE TITLE
Authentication not work --Solved

### ISSUE THREAD

**Issue by bich30** [Razzeee/script.trakt#607]
When starting the kodi, the Trakt.tv authentication screen appears, I activate it from the web trakt.tv/activate and the authentication screen stays fixed in the Kodi.
It cannot be closed with the "X" nor in the buttons to remember later or "No, thanks"

Attached log.

My Environment

* Version used:  script.trakt v3.5.0
* Kodi version used: 19.5.0
* Operating System and version: Ubuntu 22.04

[trakt.log](https://github.com/trakt/script.trakt/files/10324598/trakt.log)

**Comment by razzeee** [comment]
I just tested this with a test account and it seems to work. Your log also doesn't show anything, so if anything fails, it's probably on the trakt.tv side of things, so you will have to reach out to them.

**Comment by bich30** [comment]
When I start Kodi, the Trakt authentication screen appears and I can't close it in any way.
To close it I must kill the kodi, run it again and disable the trakt addons to prevent the trakt screen from appearing again and thus be able to start using the kodi, otherwise I cannot use it.

Attach the screenshot.

In libreelec and AndroidTV it works perfectly for me, so I don't think it's a problem with my account or Trakt.tv.

Any way to show a longer log ?
![takt](https://user-images.githubusercontent.com/10535855/210135657-077ed837-3355-4862-868c-4827eadea666.png)

**Comment by razzeee** [comment]
Creating a log is described here https://github.com/trakt/script.trakt#creating-logfiles

Is the problem the 
1. No gracias button not working
2. Activate not working 
3. Or both?

**Comment by bich30** [comment]
The problem was that neither of the 2 buttons nor the "X" to close the window worked.

I have uninstalled and deleted Kodi, upgraded ubuntu from 22.04 to 22.10 and installed Kodi 19.5 again.

Everything works perfectly.

Thanks!!

**Comment by razzeee** [comment]
Weird, thanks for letting me know.
