### ISSUE TITLE
[BUG] watched status for one show won't synced, also the show doesnt show up in the collection

### ISSUE THREAD

**Issue by webepg** [Razzeee/script.trakt#628]
I'm watching a show (heute-show, https://trakt.tv/shows/heute-show) which won't get synced with trakt status. I can't even see it in my collection on the website. At first I thought this might be a problem with my tv information addon so I tried the movie database, tmdb, tvdb shows, xem, tvmaze with none of them the sync works. The status won't sync on any side, I manually set the watched status on the  website and won't get synced back. Is there any way to make this work?

The scraper recogizes the show correctly

All other shows and movies do work perfectly

thats the content of the tvshow.nfo:

https://www.themoviedb.org/tv/46056

## Expected Behavior

The trakt watched status should be synced and the show should be in my collection.

## Steps to Reproduce (for bugs)

Add the tv show you your library, then do a sync the status won't get synced and the show won't show up in the collection on the trakt website

## Your Environment

* Version used: 3.5.0
* Kodi version used: 20.2 on Mac, 21 Beta 1 on Shield
* Operating System and version: Mac OS Sonoma, Android TV 11

**Comment by mechalv** [comment]
Hi. This is also happening to me with different TV Shows. It will mark as watched from Trakt but what is watched in Kodi will not be marked in Trakt. I have tried with version 3.6.0 but still the same result. The pop-up windows will say at the end “X show(s) had missing watched status” but it seems to do nothing about it. Anything that I can try to help with this issue? Thanks.
I’m using CoreELEC 20.3

**Comment by razzeee** [comment]
Look at the log

**Comment by mechalv** [comment]
> Look at the log

The log shows nothing, only “start trakt with arguments: {‘action’: sync}”. I’ve also enabled debug mode but I see nothing more detailed.
Still having the same problems with the latest version of the addon(3.6.8 but then it’s 3.6.1 which i find odd). From Trakt it will sync to Kodi, but with certain TV Shows, it won’t sync from Kodi to Trakt.

**Comment by mechalv** [comment]
I don’t know why is this closed. Still does not sync correctly. From time to time it works, but it’s completely random.
