### ISSUE TITLE
Latest release pointing to version that is 2 1/2 years old

### ISSUE THREAD

**Issue by brentsmith721** [Razzeee/script.trakt#639]
## Expected Behavior
Latest release should probably point this this tag: https://github.com/trakt/script.trakt/releases/tag/v3.6.0

## Current Behavior
Latest release and official Kodi repository are pointing to a v3.5.0 which is now 2 1/2 years old and missing important fixes.

## Possible Solution
Create a new release based on https://github.com/trakt/script.trakt/releases/tag/v3.6.0 or newer

## Your Environment

* Version used: 3.5.0
* Kodi version used: 20.3
* Operating System and version: CoreELEC 20.3

**Comment by tundrablasen** [comment]
hey. i just did a fresh install, and agree. the latest release via the Kodi Repository is 3.5.0 which is outdated. should be 3.6.0 as stated above

**Comment by razzeee** [comment]
Blocked by https://github.com/trakt/script.trakt/issues/627

**Comment by tundrablasen** [comment]
> Blocked by #627

would you recommend to manually install the 3.6.0 .zip file or wait for the token fix and stay on 3.5.0?

**Comment by razzeee** [comment]
If your not running into anything mentioned in the changelog, just stay on the old version https://github.com/trakt/script.trakt/blob/main/changelog.txt

**Comment by razzeee** [comment]
https://github.com/xbmc/repo-scripts/pull/2593 needs to be merged
