### ISSUE TITLE
Bug: Rating bar doesn't gets sync

### ISSUE THREAD

**Issue by rsp2308** [Razzeee/script.trakt#660]
If we rate any movie after watching it and if want to rate it again it doesn't get updated on rating scale that's too much confusing that is it saved or not according to user perspective.

![image](https://github.com/user-attachments/assets/563cb9a6-f941-4e32-b12e-424d4a59e929)

Description

When a user rates a movie and attempts to rate it again, the rating scale does not reflect the updated value. This creates confusion for users as it is unclear whether the rating has been saved or not.
Expected Behavior

    The updated rating should be saved and reflected immediately on the rating scale.
    A visual confirmation (e.g., highlighting the heart or a brief notification) should inform the user that the rating has been successfully updated.

Current Behavior

    The rating scale does not show the updated value when the user re-rates a movie.
    There is no visual feedback to confirm the new rating is saved.

Possible Solution

    Ensure the rating scale refreshes to display the latest rating.
    Add a visual cue like a heart highlight or a toast message saying, "Rating updated successfully."

Steps to Reproduce

    Select a movie and rate it.
    Attempt to update the rating for the same movie.
    Observe that the rating scale does not reflect the updated value.
    Note the lack of visual confirmation for the updated rating.

Context

This issue causes confusion for users and affects their trust in the rating system. It diminishes the overall user experience by making the feature feel unreliable.
Your Environment

    App/Version Used: N/A...24/12/24
    Operating System:windows
    Browser/Device: Firefox/laptop

**Comment by razzeee** [comment]
Are you actually refering to the kodi plugin or the website? As you're including your browser and a screenshot from that.

**Comment by rsp2308** [comment]
trakt's website

**Comment by razzeee** [comment]
You are in the wrong issue tracker then
