### ISSUE TITLE
episodes not watched marked as watched on trakt

### ISSUE THREAD

**Issue by chx0003** [Razzeee/script.trakt#69]
Some TV show episodes are still being sent as watched even when the fields "playCount" and "lastPlayed" in the table "files" of Kodi DB are null.

In those cases the 'watched at' parameter is sent with no date, so trakt.tv takes it as if the episode was watched the moment you informed it.

![trakt-sample](https://cloud.githubusercontent.com/assets/966226/5994231/fa013662-aa49-11e4-9ebd-bb5790320c14.png)

The 'watched at' parameter should not be sent at all when the playCount is null or "0".

**Comment by chx0003** [comment]
Sorry to report that this issue it's not completely solved yet (after commit fd6e842c0cb6160f274715e33f731b9ec6a6eb7f).
For TV shows with more than one season, all the episodes for the following unwatched seasons after a season with any watched episodes end up marked as watched.

**Comment by Razzeee** [comment]
Have to try to reproduce that tomorrow. Anything special about your setup? Nfos etc?

**Comment by chx0003** [comment]
Centralized MySQL DB.
For movies it is working great.
Thank you for your efforts!

**Comment by chx0003** [comment]
I believe that the problem is that the addon is sending the 'watched at' parameter, even for unwatched episodes. It sends it with no date ('watched_at': u'') and probably trakt.tv is understanding it as it was informed as watched at the time it is informed.

**Comment by Razzeee** [comment]
@chx0003 
it should not send these objects at all, they should be filtered out way before. thats te problem I have to look at. probably something in compareEpisodes.

**Comment by Jobespierre** [comment]
I can report similar issue, did a sync with a clean TRAKT account and it marked al the unwatched episodes in KODI as watched on TRAKT with the sync date/time as the watched date time. 

It also added a lot of watched marks on some other dates:

![screen shot 2015-02-02 at 17 15 45](https://cloud.githubusercontent.com/assets/10722166/6003861/37763d20-aaff-11e4-8091-a83262feba6b.png)

A second sync resulted in all these episodes being marked as watched in KODI as well.

**Comment by Razzeee** [comment]
Should hopefully work as of https://github.com/Razzeee/script.trakt/commit/c05186d9e5642627d162e0d65624bf8fbc5c9edc
But be careful!

**Comment by chx0003** [comment]
No luck, my friend... 

The last version is still sending the 'watched_at': u'' parameter without date for unwatched episodes.
For example:
{'title': u'4x11. Krieg Nicht Lieb', 'ids': {'tvdb': u'5034576'}, 'number': 11, 'watched_at': u'', 'collected_at': u'2014-12-15 07:12:13+00:00'}

![02_02_2015 09_58_12 pm](https://cloud.githubusercontent.com/assets/966226/6012550/31f47aa0-ab28-11e4-9f9f-1839b22820e9.png)

**Comment by Razzeee** [comment]
Please be absolutely sure your using the dev version. 
And delete all traces of the script before you try again. Including the settings.

**Comment by chx0003** [comment]
I'm completely sure that I'm using the latest dev version (now 7bdb844928da6795b19b7e5c53694318c33de248)

Before each new test, I delete addons subfolder script.trakt and reclone it from github, I also delete script.trakt in addon_data and also my trakt.tv test account and recreate it again to start blank with each new test.

Within the addon settings, in "Synchronize" I selected only "TV Episodes --> Add new TV episodes to trakt collection" and "Add watched TV episodes to trakt history"

**Comment by chx0003** [comment]
Just in case, here are my full settings:

```XML
<settings>
    <setting id="ExcludeHTTP" value="true" />
    <setting id="ExcludeLiveTV" value="true" />
    <setting id="ExcludePath" value="" />
    <setting id="ExcludePath2" value="" />
    <setting id="ExcludePath3" value="" />
    <setting id="ExcludePathOption" value="false" />
    <setting id="ExcludePathOption2" value="false" />
    <setting id="ExcludePathOption3" value="false" />
    <setting id="add_episodes_to_trakt" value="true" />
    <setting id="add_movies_to_trakt" value="false" />
    <setting id="clean_trakt_episodes" value="false" />
    <setting id="clean_trakt_movies" value="false" />
    <setting id="debug" value="true" />
    <setting id="hide_notifications_playback" value="true" />
    <setting id="kodi_episode_playcount" value="false" />
    <setting id="kodi_movie_playcount" value="false" />
    <setting id="password" value="***" />
    <setting id="rate_each_playlist_item" value="true" />
    <setting id="rate_episode" value="true" />
    <setting id="rate_min_view_time" value="75.000000" />
    <setting id="rate_movie" value="true" />
    <setting id="rate_rerate" value="false" />
    <setting id="rating_default_advanced" value="6" />
    <setting id="retries" value="3" />
    <setting id="scrobble_episode" value="true" />
    <setting id="scrobble_movie" value="true" />
    <setting id="scrobble_notification" value="false" />
    <setting id="show_marked_notification" value="true" />
    <setting id="show_sync_notifications" value="true" />
    <setting id="startup_delay" value="0" />
    <setting id="sync_on_update" value="false" />
    <setting id="trakt_episode_playcount" value="true" />
    <setting id="trakt_movie_playcount" value="false" />
    <setting id="username" value="***" />
    <setting id="watching_call_on_resume" value="false" />
    <setting id="watching_call_on_seek" value="false" />
</settings>
```

**Comment by Razzeee** [comment]
Can you comment in these two lines: (remove the #)
https://github.com/Razzeee/script.trakt/blob/dev/sync.py#L289

Same here:
https://github.com/Razzeee/script.trakt/blob/dev/sync.py#L635

If you don't want to post it here send it to me via pm

**Comment by chx0003** [comment]
Full log is here: https://raw.githubusercontent.com/chx0003/testing/master/kodi.log

**Comment by chx0003** [comment]
You succesfully solved this issue in commit https://github.com/Razzeee/script.trakt/commit/8ab447fcb402f40b23624b015090df22d5c65388
Thanks a bunch!

**Comment by Razzeee** [comment]
Be careful I'm experiencing double history additions with the latest, will have a look at that later today.
