### ISSUE TITLE
AssertionError in trakt/core/configuration.py

### ISSUE THREAD

**Issue by anaconda** [Razzeee/script.trakt#72]
I'm not really sure how to reproduce, I'd say that this happens randomly.

It seems to only happen when deleted episodes are to be removed from the trakt collection ("Clean episodes from collection" enabled). However, most of the times it works just fine. Rarely it hits this assertion, for some reason I wasn't able to determine exactly.
Noticed the same with multiple shows, I'm using the TVDB scraper and no NFOs.

Before the part I'm pasting here, the log output is the same as when it works:
```
05:47:41 179242.515625 T:2661147712  NOTICE: [trakt] [Episodes Sync] 1 show(s) will have episodes removed from trakt.tv collection.
05:47:41 179242.515625 T:2661147712  NOTICE: [trakt] [Episodes Sync] Episodes removed: Suits [tvdb: 247808] - S03E02
05:47:41 179242.515625 T:2661147712  NOTICE: [trakt] [trakt][traktRemoveEpisodes] Shows to remove {'shows': [{'seasons': [{'episodes': [{'ids': {}, 'number': 2, 'collected_at': 'None'}], 'number': 3}], 'year': 2011, 'ids': {'tvdb': '247808'}, 'title': u'Suits'}]}
05:47:41 179242.531250 T:2661147712   ERROR: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): api.trakt.tv
05:47:41 179242.531250 T:2661147712  NOTICE: .
05:47:43 179243.718750 T:2661147712   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
                                                self.run()
                                              File "/home/xbian/.kodi/addons/script.trakt/service.py", line 290, in run
                                                sync.sync()
                                              File "/home/xbian/.kodi/addons/script.trakt/sync.py", line 703, in sync
                                                self.__syncEpisodes()
                                              File "/home/xbian/.kodi/addons/script.trakt/sync.py", line 381, in __syncEpisodes
                                                self.__traktRemoveEpisodes(traktShowsRemove)
                                              File "/home/xbian/.kodi/addons/script.trakt/sync.py", line 133, in __traktRemoveEpisodes
                                                result = self.traktapi.removeFromCollection(shows)
                                              File "/home/xbian/.kodi/addons/script.trakt/traktapi.py", line 161, in removeFromCollection
                                                result = Trakt['sync/collection'].remove(mediaObject)
                                              File "/home/xbian/.kodi/addons/script.trakt/trakt/core/configuration.py", line 91, in __exit__
                                                assert item == self
                                            AssertionError
```

~~I've noticed it opens a second connection to trakt (`Starting new HTTPS connection (2)`) - I'll try to investigate this further, but I haven't noticed the same when it works just fine. If I have to guess, it seems that it doesn't handle multiple connections correctly.~~ No, seems unrelated. It has sync'ed fine couple minutes ago with 2 connections.

**Comment by Razzeee** [comment]
@fuzeman
you might have an idea where this is comming from

**Comment by fuzeman** [comment]
I've spotted this issue in https://github.com/trakt/Plex-Trakt-Scrobbler as well, looking into it today.

**Comment by anaconda** [comment]
```python
try:
    self.manager.stack.remove(self)
except ValueError:
    raise ThisReallyShouldNotHappenException
```
might fix the assertion failure.

**Comment by fuzeman** [comment]
The ```assert``` check is to ensure the configuration isn't corrupted due to a thread synchronization issue.

It appears that there is a chance configuration will break if ```with Trakt.configuration[...]:``` is called in multiple threads at once. Still working on a fix :smiley:

**Comment by fuzeman** [comment]
Should be fixed with https://github.com/fuzeman/trakt.py/commit/6d37222d9d43888736191861cea52731e36adf91

**Comment by Razzeee** [comment]
Updated our version, so @anaconda can you try again and let us know?

**Comment by anaconda** [comment]
As I have said it's pretty hard to reproduce, however I have updated to current dev branch. Let's see how it goes.

**Comment by Razzeee** [comment]
Closed until further infos ;)
