### ISSUE TITLE
Store watched_at date from trakt in kodi

### ISSUE THREAD

**Issue by Razzeee** [Razzeee/script.trakt#80]
It would be nice to have an option to pull the last_watched_at date from trakt and add it to the kodi item if we have it.

**Comment by Jean85** [comment]
:+1:

**Comment by Razzeee** [comment]
Should now be possible to tackle this https://plus.google.com/115955471780682194443/posts/S9deiWDYene

**Comment by chris400** [comment]
Your Link is not working.

**Comment by Razzeee** [comment]
@chris400 
it is, you need to be in the trakt api group to see it.
