### ISSUE TITLE
Episodes already in trakt history are sent again to trakt as watched at the same date and time

### ISSUE THREAD

**Issue by chx0003** [Razzeee/script.trakt#84]
Each time the addon is executed it reports all the watched episodes again to trakt.tv

Check the function __compareShows in sync.py
Something is wrong between lines 319 to 367, cause it is not matching the episodes already in trakt history with the ones marked as watched in Kodi DB.

![06_02_2015 12_32_49 am](https://cloud.githubusercontent.com/assets/966226/6074190/e0601db2-ad97-11e4-977a-6dec7a23a080.png)

**Comment by chx0003** [comment]
Nevermind, it seems to be working correctly now.

**Comment by Razzeee** [comment]
Had to grab some sleep, will have a look later today. Pretty sure it's still there.

**Comment by Razzeee** [comment]
This could also be done by the retry feature. I fixed the last bit in the latest commit
