### ISSUE TITLE
New feature suggestion: Clear Trakt.TV History

### ISSUE THREAD

**Issue by chx0003** [Razzeee/script.trakt#85]
Similar to the features "Remove deleted movies from trakt collection" and "Remove deleted TV episodes from trakt collection" I suggest to add a new feature "Clean trakt history" that removes from Trakt.TV History the movies and/or TV episodes that are marked as not watched in Kodi DB, and also update the watched date and time if it is different from the one stored in Kodi DB.

**Comment by Razzeee** [comment]
Pretty sure the trakt api doesn't handle the update part yet. We would have to delete the old and create one with the new timestamp. Might be pretty messy.

**Comment by chx0003** [comment]
The API has a function "Remove items from history" (http://docs.trakt.apiary.io/#reference/sync/remove-from-history/remove-items-from-history) so it should be posible to clean the history in a similar manner as the addon cleans the collection.

**Comment by Razzeee** [comment]
Yes, I was talking about updating the timestamps.

**Comment by chx0003** [comment]
Yes, you're right.

**Comment by chx0003** [comment]
We could delete all trakt history and recreate it in full.
Probably a long process, but very usefull when your trakt history is corrupted.

**Comment by chx0003** [comment]
I just tried deleting all my watched history in trakt (119 TV Shiows) and it didn't take too long

**Comment by Razzeee** [comment]
That's not a problem, just wanted to let you know, but it might problematic. As trakts history can have multiple watches. As far as I know, we only have last viewed date and number of plays. So we won't be able to recreate these.

**Comment by chx0003** [comment]
You're right, Kodi only has the last played timestamp.
For me that's good enough, but some people may like to have multiple watched timestamps for each media piece.

**Comment by Razzeee** [comment]
If you want to delete all please use https://github.com/damienhaynes/TraktRater
This probably won't go into the kodi trakt addon
