### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by fuzeman** [Razzeee/script.trakt#86]
Just received some emails from a kodi translation coordinator:

```
Hi Dean,

I am a Kodi translation coordinator.

script-trakt just got pushed into Transifex.

"Logging" is it " Logging in" or "The log is being written"?

"trakt - Failed making as watched" should read "trakt - Failed marking as watched"

Best regards,

Alain-Olivier
```

```
Also Dean, is there any way to recode to use the plural feature in Transifex?

In many languages you have agreement on the adjectives and the verbs, thus making the translated strings very heavy (e.g. "
%i episode(s) were added to your trakt collection")

Best,

Alain-Olivier
```

-----------------------

**Note:** kodi moved away from the old ```strings.xml``` format (http://kodi.wiki/view/Translation_System):
> In the development cycle from Eden (V11) to Frodo (V12) the translation system has been revised.
>
> The former strings.xml file has been superseeded by the appropriate strings.po files. Due to that the way how translations are handled has been changed, too. 

PO files have a plural format described here:
 - https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms
 - https://www.gnu.org/software/gettext/manual/gettext.html#Translating-plural-forms

Not sure how this can be used in Kodi addons though..

**Comment by Razzeee** [comment]
I know about the plurals and have searched for infos on plurals. The threads by the team seemed like its still in dev. http://forum.kodi.tv/showthread.php?tid=142736 http://forum.kodi.tv/showthread.php?tid=187109

I know about the xml but as I had to send it's path in order to get the translations up and running, I'm not so sure it won't break if I delete it.

Fixed the typo and maybe "Activate Logging" would be better than "Logging". Not sure.

**Comment by fuzeman** [comment]
Not sure what the "plural feature" he is referring to then (if gettext plural forms isn't supported yet)...

------------

Just wanted to make you saw these emails, no idea why I was contacted on this issue..

**Comment by Razzeee** [comment]
I can imagine that it works, but seems like there is no documentation at all. Will search in github for some examples, might have some luck.

**Comment by Razzeee** [comment]
I'll cose this as it doesn't seem to lead anywhere.

**Comment by Razzeee** [comment]
Plurals are indeed not working so far.
http://forum.kodi.tv/showthread.php?tid=218405
