### ISSUE TITLE
Marking unseen TV Shows seasons watched on trakt

### ISSUE THREAD

**Issue by Ben91** [Razzeee/script.trakt#89]
Hi.

Just had a big problem yesterday.

I manually lauched an "Update library" in Kodi. (Trakt is set to sync with lib update.)

Then I got 2-3 pages of new episodes set as watched in my trakt history. There had some episodes that I don't even have in my Kodi collection nor in my trakt collection. (If I remember well, like the entire season 0 -specials of The Walking Dead of 36 episodes. I only have the e02 in my collection...).

For shows I have in my Kodi collection but as unwatched, If I remember well I had unseen episodes of American Horror Story, Lost.... and more. And always complete seasons marked as watched. Had to remove them manually by unseeing seasons on trakt.

Here is my Kodi logs (sorry couldn't paste it, it's 1.2 MB) : http://www38.zippyshare.com/v/3XHrOXdh/file.html or http://www.multiup.org/en/download/aadce8bb8c49ff9a0ea52bfe256e0e21/kodi.log

Cheers.

**Comment by chx0003** [comment]
This issue was already reported and solved some time ago.
Are you using the latest dev version of the addon?

**Comment by Ben91** [comment]
Thanks, I missed this closed ticket.

Must be the same problem. I use a version older than the date of your ticket. Will update and report back if I have problems. Thanks.

**Comment by chx0003** [comment]
I'm glad I could help
Best regards
