### ISSUE TITLE
Add resolution, auto, 3d etc to collection items

### ISSUE THREAD

**Issue by bigmong** [Razzeee/script.trakt#99]
If this is already included I have missed the post about it.
This is more of a Feature.

Can this plugin add the Media Object Data eg. "media_type", "resolution", "audio", "audio_channels", "3d".
Maybe as a task after the Movie and TV Show syncs
http://docs.trakt.apiary.io/#reference/sync/add-to-collection

Awesome work on getting this plugin updated to V2 been using the dev builds and loving it :)

**Comment by Razzeee** [comment]
That would be an enhancement of the collection part of the script. Have to look up where the fields are and the compare would become more difficult. As we have to check if the quality or anything else has changed.

**Comment by freeman212** [comment]
I'd better keep it simple for now. once the updated version is mostly bug-free and on the Kodi repository we can think about enhancements like this.

**Comment by Razzeee** [comment]
This may also cause a lot of discussion, piracy wise etc. 
So this has to be configurable.

**Comment by Razzeee** [comment]
For some reason most of my collection is even missing this data in kodi
http://i.imgur.com/w9kbi3z.png

Even if we have it, it will be a pretty rough to match the kodi types to trakt types

**Comment by spegg** [comment]
your data are ok, iStreamType 0 only contains videostream data,1 audiostream data, 2 subtitle data. Check the same idFile.

**Comment by Razzeee** [comment]
Yes, I know but there are movies in my collection which doesn't have streamdetails filled.

**Comment by spegg** [comment]
Ah, that might be because they were not scanned yet, they need to available when data are accessed in library. Just make all episodes playlist, open it once and it should run the task on background for all available files. Should work for Movies - Title view by default.

**Comment by Razzeee** [comment]
This will help when I get to this feature:

https://github.com/Technicolour/Trakt-for-Mediaportal/blob/master/TraktPlugin/TraktHandlers/MovingPictures.cs#L1076

https://github.com/Technicolour/Trakt-for-Mediaportal/blob/master/TraktPlugin/TraktHandlers/TVSeries.cs#L1590

**Comment by RavRob** [comment]
If/When you implement this feature I will be happy to test for you.

**Comment by vonH** [comment]
Now signed in on this PC. I'm against the idea, as said in the forum. There's no need to complicate an add-on. Trakt, in my opinion, should offer: rating for episodes and films, syncing of watched status/library. That's about it.

**Comment by s7eele** [comment]
its really neat stuff but it feels 'out of scope' for this add-on, its not something i see myself taking advantage of and it seems like it could get REALLY complicated (especially if im understanding the piracy aspect, that could affect where its hosted)

**Comment by vonH** [comment]
I think s7eele and I are in agreement. Adding these options might be worth your time, but creating an additional add-on would be a better choice. More of a modular approach - like the trakt list manager add-on. This keeps the core add-on as clean as possible with less chance of issues.

**Comment by Razzeee** [comment]
Well this is not that complicated (if I'm wrong correct me)

If it's deactivate we do:
1. Compare collected local to collected on trakt
2. Send the missing items

If its activated:
1. Compare collected local (with resolution etc attached, this should even be okay for the deactivated part) to collected on trakt
2. Parse the Kodi Resolution etc to something trakt will understand, append it to the missing items
2. Send the missing items

**Comment by RavRob** [comment]
Sorry guys.  My day is just starting here.  It will be at least 10 hours before I can get to testing as requested.  I am on my way to work now and won't be back for a while.
